### ISSUE TITLE
nodeJS profiling docs do not mention profilesSampler

### ISSUE THREAD

**Issue by ndmanvar** [getsentry/sentry-docs#10010]
### Core or SDK?

Platform/SDK

### Which part? Which one?

Profiling in NodeJS

### Description

It looks like nodeJS profiling docs don’t mention `profilesSampler`.
docs -> https://docs.sentry.io/platforms/javascript/guides/node/profiling/#enabling-profiling
src code -> https://github.com/getsentry/sentry-javascript/blob/13904020da1e0a988a44ff83ef3dfebab922227b/packages/node/src/types.ts#L31-L43

### Suggested Solution

Add `profilesSampler` docs/example

**Comment by mydea** [comment]
Hey, thanks for raising this. We'll add docs for this!
