### ISSUE TITLE
Restore the image of User Feedback custom modal in JS Docs

### ISSUE THREAD

**Issue by thinkocapo** [getsentry/sentry-docs#10021]
### Core or SDK?

Core Sentry product

### Which part? Which one?

javascript and angular

### Description

https://docs.sentry.io/platforms/javascript/user-feedback/configuration/#bring-your-own-widget
https://docs.sentry.io/platforms/javascript/user-feedback/configuration/#css-customization
https://docs.sentry.io/platforms/javascript/guides/angular/user-feedback/#user-feedback-widget

It's missing from this screenshot's URL but in the 'Suggested Solution' it's shown, I had it earlier today. Maybe I'm missing something
![image](https://github.com/getsentry/sentry-docs/assets/8920574/d5ac0291-025d-4cbe-aba8-9e50e2803a39)

### Suggested Solution

![image](https://github.com/getsentry/sentry-docs/assets/8920574/8e2e096b-fe15-477e-bd14-062065b22f39)

**Comment by lizokm** [comment]
@thinkocapo did you still want to leave this open based on the comments from @c298lee or should we close it?

**Comment by c298lee** [comment]
We're adding an updated image back with https://github.com/getsentry/sentry-docs/pull/10022

**Comment by c298lee** [comment]
@mydea we can close this since the image has been updated
