### ISSUE TITLE
Incorrect solution for Laravel closure serialization issue

### ISSUE THREAD

**Issue by matfish2** [getsentry/sentry-docs#10086]
### Core or SDK?

Platform/SDK

### Which part? Which one?

Laravel

### Description

https://docs.sentry.io/platforms/php/guides/laravel/configuration/laravel-options/#closures-and-config-caching

```php
'traces_sampler' => [App\Exceptions\Sentry::class, 'tracesSampler'],
```

running `php artisan config:cache' in Laravel 10 results in:

> Symfony\Component\OptionsResolver\Exception\InvalidOptionsException  
 > The option "traces_sampler" with value array is expected to be of type "null" or "callable", but is of type "array".

### Suggested Solution

I don't know

**Comment by stayallive** [comment]
Ensure the `tracesSampler` is actually a `static` method. This has been tested and works on Laravel 9, 10 and 11 (just tested).
