### ISSUE TITLE
Suggestion: show default values for integrations parameters

### ISSUE THREAD

**Issue by ldorigo** [getsentry/sentry-docs#10088]
### Problem Statement

The documentation for integrations (I'm looking at next.js but I assume others too) describes the parameters, but doesn't say what the default values are. It would be helpful to know that information

### Solution Brainstorm

Show the default value next to the parameter name :-)

**Comment by AbhiPrasad** [comment]
The integration docs now have been revamped to display a table if they are auto-enabled (so part of the default integrations): https://docs.sentry.io/platforms/javascript/guides/nextjs/configuration/integrations/

**Comment by lforst** [comment]
@ldorigo can you confirm that your request is about showing the default values for the options of specific integrations? For example here https://docs.sentry.io/platforms/javascript/guides/nextjs/configuration/integrations/extraerrordata/, where we don't do it, and here https://docs.sentry.io/platforms/javascript/guides/nextjs/configuration/integrations/requestdata/, where we do it?
