### ISSUE TITLE
Reduce max. line length for code formatting

### ISSUE THREAD

**Issue by mydea** [getsentry/sentry-docs#10102]
### Problem Statement

Currently, code is formatted in code blocks to a certain max. line length which exceeds the space we actually have:

![Screenshot 2024-05-22 at 12 44 40](https://github.com/getsentry/sentry-docs/assets/2411343/b299a85e-17d4-4d4d-890b-4236d1c30df8)

We should format it so that the max. line length fits into the max. content width we can have.

### Solution Brainstorm

Reduce max line length to fit into code block.

**Comment by a-hariti** [comment]
Where does the screenshot you attached happen?

**Comment by mydea** [comment]
You can see it for example here: https://docs.sentry.io/platforms/javascript/configuration/integrations/#lazy-loading-integrations

**Comment by a-hariti** [comment]
looks like the magic number is 74, but 80 is the sweet spot
