### ISSUE TITLE
Laravel Docs

### ISSUE THREAD

**Issue by pevensentry** [getsentry/sentry-docs#10116]
### Core or SDK?

Platform/SDK

### Which part? Which one?

Laravel and PHP

### Description

We are entering into a partnership with Laravel where users of their Forge platform can signup for Sentry through Forge. As part of the contract, we agreed to highlight the integration on the docs pages below with a screenshot and CTA to Forge. 

https://docs.sentry.io/platforms/php/guides/laravel/
https://docs.sentry.io/platforms/php/

Note the contract goes into effect June 3rd. Please plan to publish the updates then.

### Suggested Solution

At the bottom of the docs pages linked below, please add the following copy and screenshot. 

https://docs.sentry.io/platforms/php/guides/laravel/
https://docs.sentry.io/platforms/php/

**Set up Sentry through Forge**
If you're using Laravel's Forge platform to provision and deploy your PHP application, you can create a Sentry organization [through Forge](https://forge.laravel.com/docs/integrations/sentry.html).

Screenshot: https://drive.google.com/file/d/1CZ9Lxt6TTXnfqVJ1iouZWgvFXNu9SGUb/view?usp=sharing

**Comment by rahulchhabria** [comment]
@lizokm i'll take this one.

**Comment by rahulchhabria** [comment]
PR: https://github.com/getsentry/sentry-docs/pull/10202

**Comment by pevensentry** [comment]
@rahulchhabria higher resolution image attached. 
![forge + sentry](https://github.com/getsentry/sentry-docs/assets/101372341/696892ff-5d3b-467e-b676-2b46613c4a9a)

**Comment by pevensentry** [comment]
Higher resolution image attached

<img width="1645" alt="image" src="https://github.com/getsentry/sentry-docs/assets/101372341/ee83c22a-a92a-461c-b67c-38843ab7ea02">

**Comment by rahulchhabria** [comment]
@pevensentry wanna give me a quick review. then you can merge whenever you're ready.
