### ISSUE TITLE
🔗 404 Error for cache instrumentation for perf monitoring for JavaScript SDK

### ISSUE THREAD

**Issue by jeff-held-aiven** [getsentry/sentry-docs#10140]
### URL

https://docs.sentry.io/platforms/javascript/performance/instrumentation/custom-instrumentation/caches-module/

### Additional Info

Attempted to navigate there from https://docs.sentry.io/product/performance/caches/#custom-instrumentation, and then from the JavaScript SDK

**Comment by a-hariti** [comment]
Should we hide platforms with no cache specific instrumentation @lizokm @stephanie-anderson ?

**Comment by stephanie-anderson** [comment]
Yes, that would be great! @a-hariti
