### ISSUE TITLE
CaptureConsole (and other integrations) specify an incorrect import name

### ISSUE THREAD

**Issue by kumar303** [getsentry/sentry-docs#1015]
The [`CaptureConsole` integration documentation](https://docs.sentry.io/platforms/javascript/?platform=browsernpm#captureconsole) specifies an "import name" of `Sentry.Integration.CaptureConsole`. I'm not sure what this even means but there's no way it can be correct. My best guess at what it meant was this:

```ts
import * as Sentry from '@sentry/browser';

Sentry.init({
  dsn: '...',
  integrations: [
    new Sentry.Integration.CaptureConsole({ levels: ['error'] })
  ],
});
``` 
This results in the following TypeScript error:

```
src/configureApplication.tsx:32:33 - error TS2339: Property 'Integration' does not exist on type 'typeof import("/Users/kumar/dev/addons-code-manager/node_modules/@sentry/browser/dist/index")'.

32       integrations: [new Sentry.Integration.CaptureConsole({ levels: ['error'] })],
                                   ~~~~~~~~~~~
```

The proper way to import and configure it is:

```ts
import * as Sentry from '@sentry/browser';
import { CaptureConsole } from '@sentry/integrations';

Sentry.init({
  dsn: '...',
  integrations: [new CaptureConsole({ levels: ['error'] })],
});
```

All other integrations seem to be documented with "import names" in this manner.

**Comment by ajl100b** [comment]
> 32       integrations: [new Sentry.Integration.CaptureConsole({ levels: ['error'] })],


should be Sentry.Integration**s**.CaptureConsole **note the s in integrations**

**Comment by GaramNick** [comment]
In Angular 6 I'm getting a signature mismatch error on integrations.

```
import * as Sentry from '@sentry/browser';
import { CaptureConsole } from '@sentry/integrations';
```

```
Sentry.init({
	environment: 'xxx'
	release: '1.0',
	dsn: 'xxx',
	integrations: [new CaptureConsole({levels: ['error'],})],
});
```
```
Type 'CaptureConsole[]' is not assignable to type 'Integration[] | ((integrations: Integration[]) => Integration[])'.
  Type 'CaptureConsole[]' is not assignable to type 'Integration[]'.
    Type 'CaptureConsole' is not assignable to type 'Integration'.
      Types of property 'setupOnce' are incompatible.
        Type '(_: (callback: EventProcessor) => void, getCurrentHub: () => Hub) => void' is not assignable to type '(addGlobalEventProcessor: (callback: EventProcessor) => void, getCurrentHub: () => Hub) => void'.
          Types of parameters '_' and 'addGlobalEventProcessor' are incompatible.
            Types of parameters 'callback' and 'callback' are incompatible.
              Type 'import("CODE/node_modules/@sentry/integrations/node_modules/@sentry/types/dist/eventprocessor").EventProcessor' is not assignable to type 'import("CODE/node_modules/@sentry/types/dist/eventprocessor").EventProcessor'.
                Types of parameters 'event' and 'event' are incompatible.
                  Type 'import("CODE/node_modules/@sentry/types/dist/event").Event' is not assignable to type 'import("CODE/node_modules/@sentry/integrations/node_modules/@sentry/types/dist/event").Event'.
                    Types of property 'type' are incompatible.
                      Type '"none"' is not assignable to type '"transaction"'.ts(2322)
options.d.ts(33, 5): The expected type comes from property 'integrations' which is declared here on type 'BrowserOptions'
```

**Comment by AngularDevMrs** [comment]
Still facing the same issue in Angular 8

**Comment by fr1sk** [comment]
same issue in NestJS, any solution?

**Comment by ykshatroff** [comment]
Same thing for me, the documentation was very confusing.
Actually there seems to be no `integrations` module installed if you just install `@sentry/node`, so I had to `npm install @sentry/integrations` as well to make it work.
Then both 
```
const { CaptureConsole } = require("@sentry/integrations");
```
and 
```
Sentry.Integrations.CaptureConsole
```
appeared.

**Comment by manjeetyadv** [comment]
This will surely work in the case of Nodejs or anything:-

`const CaptureConsole = require('@sentry/integrations').CaptureConsole;
`
`Sentry.init({
    dsn: "...",
    integrations: [new CaptureConsole({
        levels: ['error']
    })],
});`

**Comment by blyszcz** [comment]
Sentry team, why don't you update the docs? They are old and people have to look into GitHub issues to integrate such a primary thing

**Comment by kjellski** [comment]
I think the problem here is that you've got a version mismatch between the `@sentry` package and the `@sentry/integrations`. 
Once I've installed `@sentry/integrations` I got the same error, but upgrading the other `@sentry` packages to the same version fixed it :)
