### ISSUE TITLE
Allow negative check for `<OnboardingOption>`

### ISSUE THREAD

**Issue by mydea** [getsentry/sentry-docs#10159]
You can use something like this to show a block only when an option is enabled:

```jsx
<OnboardingOption optionId="profiling">
  show when profiling is enabled
</OnboardingOption>
```

However, this does not allow to do some kind of "else" logic. For example, I want to be able to show either this snippet:

```bash
npm install --save @sentry/node
```

Or, if profiling is enabled, show this snippet:

```bash
npm install --save @sentry/node @sentry/profiling-node
```

I don't think this is doable today? (or if it is, happy for pointers).

## How we could do this

We could allow to pass `hideForOptionsId='profiling'`, which we could use to build else blocks manually?

**Comment by a-hariti** [comment]
What about:

```bash {"onboardingOptions": {"performance": "1"}}
npm install --save @sentry/node \
  @sentry/profiling-node
```
but this comes with the issue of the trailing `\`

@mydea

**Comment by mydea** [comment]
This is not working, it is removing everything for me 😅 and even so I wouldn't want to have a line break in there either way!

**Comment by a-hariti** [comment]
I'm thinking:

```jsx
<OnboardingOption optionId="profiling" hideForThisOption>
  hide when profiling is enabled
</OnboardingOption>
```
wyt @mydea ?
should this be hidden by default in the DOM?

**Comment by mydea** [comment]
I _think_ considering how this works for other things we have, I'd prefer an inverse option (e.g. think we have `<PlatformSection notSupported=....`, but no strong feelings.

I think hiding it by default makes sense!
