### ISSUE TITLE
OnboardingOptionButtons jump when scrolling

### ISSUE THREAD

**Issue by stephanie-anderson** [getsentry/sentry-docs#10231]
### Steps to Reproduce

[screen-capture.webm](https://github.com/getsentry/sentry-docs/assets/7096858/9a04b233-80eb-4e9e-a746-5d99750763fb)

### Expected Result

* the horizontal position should not change when scrolling
* the box should not have rounded borders, so changing background colors (due to codeblocks) don't irritate visually

### Actual Result

* when scrolling, the buttons shift to the right
* the box with buttons has rounded corners, which allow codeblocks (or other background colors) to shine through

**Comment by a-hariti** [comment]
This was intentional to give the semi transparent background behind the buttons some padding when they are sticking

should I remove this @stephanie-anderson ?

**Comment by mydea** [comment]
This is even more of a problem with all 4 categories 😅 

https://github.com/getsentry/sentry-docs/assets/2411343/9e4bd6a2-1758-49df-8a5e-c230d5612db3
