### ISSUE TITLE
New layout on Troubleshooting doesn't include anchors

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-docs#10243]
We can’t now link to a specific heading on this page: https://docs.sentry.io/platforms/javascript/guides/angular/session-replay/troubleshooting/

It does look a lot nicer though, is there a way we can get the anchors back though?

**Comment by bruno-garcia** [comment]
To clarify: Opening a link with an anchor, e.g: https://docs.sentry.io/platforms/javascript/troubleshooting/#dealing-with-ad-blockers

Doesn't expand the item the anchor leads to.

# Expected



![Image](https://github.com/user-attachments/assets/720db1a7-2a64-468f-b114-148fef6bddbd)



# Actual


![Image](https://github.com/user-attachments/assets/0adcce88-54f4-4f87-859f-eeb5e820c7fa)

**Comment by stephanie-anderson** [comment]
This has been done by @a-hariti via another issue, will close this one. Please make sure to use the `Type: Platform` label in the future, otherwise we won't have issues on our radar 🙏
