### ISSUE TITLE
Add link to insights module in product to the manual instrumentation docs for that module

### ISSUE THREAD

**Issue by antonpirker** [getsentry/sentry-docs#10256]
### Core or SDK?

Platform/SDK

### Which part? Which one?

Python SDK manual insights module docs

### Description

Add a link to the insights modules in the product in the following pages:
- https://docs.sentry.io/platforms/python/performance/instrumentation/custom-instrumentation/caches-module/
- https://docs.sentry.io/platforms/python/performance/instrumentation/custom-instrumentation/requests-module/
- https://docs.sentry.io/platforms/python/performance/instrumentation/custom-instrumentation/queues-module/

### Suggested Solution

Add a link like this `[cache-monitoring dashboard](https://sentry.io/orgredirect/organizations/:orgslug/insights/caches/)`

### Note:

Set the target branch to `launch`!

**Comment by szokeasaurusrex** [comment]
Should be fixed by [#10263](https://github.com/getsentry/sentry-docs/pull/10263)
