### ISSUE TITLE
[Docs] Move 'detection logic' for Rage Click issues from replay Troubleshooting page to https://docs.sentry.io/product/issues/issue-details/replay-issues/

### ISSUE THREAD

**Issue by ryan953** [getsentry/sentry-docs#10277]
We've got the section "How does Rage Click detection work?" here: https://docs.sentry.io/platforms/javascript/session-replay/troubleshooting/

Problem: That page is phrased more like an FAQ, and it's not a trouble-shooting thing, per-se... it's more of like How it Works.

1. We should put that "detection" section into https://docs.sentry.io/product/issues/issue-details/replay-issues/. This is similar to what pages like N+1 Queries have (https://docs.sentry.io/product/issues/issue-details/performance-issues/n-one-queries/) 

2. The troubleshooting section for rage clicks could be phrased a little differently. Make it say something to get these points across:
> Why am I seeing too-many or too-few rage clicks?
> Rage clicks are only detected on button & input & a tags, 7 second timer, 3 clicks in a row. There might be fewer if the user did wait long enough, and just went off to do something else. This is why rage click instances you do see can be so valuable, because the user really did wait!
> You might also see more than expected from Print and Download buttons on your site. Buttons that don't trigger dom mutations. You can fix this by setting `slowClickIgnoreSelectors` to exclude those buttons.

**Comment by drguthals** [comment]
So I was looking at this some more @ryan953 and I noticed a few things:

1. The [docs on Rage Clicks](https://docs.sentry.io/product/issues/issue-details/replay-issues/) are under:
`Product` -> `Issues` -> `Issue Details` -> `Rage Click Issues`

2. The [Set up Session Replay docs](https://docs.sentry.io/platforms/javascript/session-replay/), where we have the "Troubleshooting" is found here under:
`JavaScript` -> `Set up Session Replay` -> `Troubleshooting`

3. But then we *also* have [Set up Session Replay](https://docs.sentry.io/product/session-replay/) under:
`Product` -> `Session Replay`

When you search of "Sentry rage clicks", the page that seems to pup up to the top is **1** from above (`Product` -> `Issues` -> `Issue Details` -> `Rage Click Issues`). 

I would propose:
1. Add to `Product` -> `Issues` -> `Issue Details` -> `Rage Click Issues` -> [here](https://docs.sentry.io/product/issues/issue-details/replay-issues/)
3. Remove from `JavaScript` -> `Set up Session Replay` -> `Troubleshooting` -> [here](https://docs.sentry.io/platforms/javascript/session-replay/troubleshooting/)
4. Add to `JavaScript` -> `Set up Session Replay` -> `Understanding Sessions` -> [here](https://docs.sentry.io/platforms/javascript/session-replay/understanding-sessions/)

Then, I think we should add a new page: 
5. Add to `Product` -> `Session Replay` -> ` Rage and Dead Clicks` 

Thoughts?
