### ISSUE TITLE
🔗 404 Page Not found

### ISSUE THREAD

**Issue by vinhltaz** [getsentry/sentry-docs#10279]
### URL

URL: https://docs.sentry.io/platforms/javascript/guides/react/configuration/integrations/browserprofiling/

![Screenshot 2024-06-05 082731](https://github.com/getsentry/sentry-docs/assets/57315839/811e6cf7-f24d-471e-b654-00a5ee84f494)

**Comment by a-hariti** [comment]
Thank you for reporting @vinhltaz!
