### ISSUE TITLE
Setting the text highlight colour to transparent breaks accessibility

### ISSUE THREAD

**Issue by whitep4nth3r** [getsentry/sentry-docs#10320]
### Steps to Reproduce

1. Attempt to highlight some text (copy text, not code samples) on the docs page
2. Observe that you can't see what text you have highlighted
3. This is due to the webkit-tap-highlight colour being set to transparent

### Expected Result

I should be able to see what text I have highlighted if I have done so.

### Actual Result

<img width="804" alt="image" src="https://github.com/getsentry/sentry-docs/assets/52798353/ba74cfc6-e22c-4504-b859-562702b3ccb7">

**Comment by a-hariti** [comment]
Does this happen on iOS @whitep4nth3r ?

**Comment by whitep4nth3r** [comment]
This is happening for me on MacOS in Arc browser.

I can highlight correctly on iOS.

**Comment by a-hariti** [comment]
I'm not sure I understand / can repro the issue @whitep4nth3r 
screenshot with Arc on Mac os (both in desktop and mobile mode)

![image](https://github.com/getsentry/sentry-docs/assets/17055517/4efd855b-d1a0-48d5-9084-184984de7ae9)

**Comment by whitep4nth3r** [comment]
That's strange. I've turned off all my browser extensions and I still can't highlight text.

I've tried in Safari and I can highlight in that browser, so it's not to do with my system settings.

I'm on Arc Version 1.46.0 (50665).

**Comment by a-hariti** [comment]
I'm on the exact same version

**Comment by danielcompton** [comment]
I can reproduce this on https://docs.sentry.io/platforms/javascript/guides/express/ on the `instrument.js` sample, only when logged in.

**Comment by whitep4nth3r** [comment]
I'm now on the following version of Arc on desktop:

```
Version 1.48.2 (51225)
Chromium Engine Version 126.0.6478.115
```

And I can highlight text _when logged in_ and _when logged out_.

I'm not sure what's happening here!

However, regarding logged in/logged out behaviour and I think I found a different bug.

Should the nav bar item for "sign in" change to something else when you _are_ signed in?

**Comment by stephanie-anderson** [comment]
![Image](https://github.com/user-attachments/assets/3360c843-4bb2-4666-b80e-51a8355bc2f6)

**Comment by whitep4nth3r** [comment]
@stephanie-anderson you've cracked the case. This is exactly why I was experiencing this 🫠
