### ISSUE TITLE
🔗 404 Error

### ISSUE THREAD

**Issue by marcosox** [getsentry/sentry-docs#10322]
### URL

https://docs.sentry.io/platform-redirect/?next=%2Fdata-management%2Fevent-grouping%2Fserver-side-fingerprinting%2F

### Additional Info

Found clicking this link in the "issue grouping" settings page.

There seems to be no place where I can read the app version

![image](https://github.com/getsentry/sentry-docs/assets/13382107/f6cf4c0f-852e-4620-ae66-3f2335fcd925)

**Comment by vivianyentran** [comment]
I think this was just a wrong link used in the product and has since been fixed to go to the correct page here: https://docs.sentry.io/concepts/data-management/event-grouping/fingerprint-rules/
