### ISSUE TITLE
For Sentry Tunnel (/tunnel endpoint) implementation example, binary data should not be parsed as string(=UTF8), for like Sentry Replay

### ISSUE THREAD

**Issue by LumaKernel** [getsentry/sentry-docs#10348]
### Core or SDK?

Core Sentry product

### Which part? Which one?

Sentry Tunnel

### Description

In the doc, the following example can be found.
page: https://docs.sentry.io/platforms/javascript/troubleshooting/ Section **Using the `tunnel` Option**

```ts
const SENTRY_HOST = "oXXXXXX.ingest.sentry.io";
const SENTRY_PROJECT_IDS = ["123456"];

export const postAction = async ({ request }) => {
  try {
    const envelope = await request.text();
    const piece = envelope.split("\n")[0];
    const header = JSON.parse(piece);
    const dsn = new URL(header["dsn"]);
    const project_id = dsn.pathname?.replace("/", "");

    if (dsn.hostname !== SENTRY_HOST) {
      throw new Error(`Invalid sentry hostname: ${dsn.hostname}`);
    }

    if (!project_id || !SENTRY_PROJECT_IDS.includes(project_id)) {
      throw new Error(`Invalid sentry project id: ${project_id}`);
    }

    const upstream_sentry_url = `https://${SENTRY_HOST}/api/${project_id}/envelope/`;
    await fetch(upstream_sentry_url, { method: "POST", body: envelope });

    return json({}, { status: 200 });
  } catch (e) {
    console.error("error tunneling to sentry", e);
    return json({ error: "error tunneling to sentry" }, { status: 500 });
  }
};
```

See these points:

```ts
const envelope = await request.text();
// ...
await fetch(upstream_sentry_url, { method: "POST", body: envelope });
```

The body is parsed as UTF8, and we can understand the envelope has JSON metadata on first bytes till byte 0A.
But if the envelope has binary that is not compatible with UTF8, the data would be broken, and Sentry envelope endpoint fails.
Specifically, if the vendor has the Sentry Replay endpoint, it always goes to 500 error.

### Suggested Solution

I can guess the example is written for express users, so it seeems we can use `.raw()` instead of `.text()`.
API doc: https://expressjs.com/en/4x/api.html#express.raw
NOTE: Not sure. We don't test as it is. We're using another web framework.

```ts
const SENTRY_HOST = "oXXXXXX.ingest.sentry.io";
const SENTRY_PROJECT_IDS = ["123456"];

export const postAction = async ({ request }) => {
  try {
    const envelope = await request.raw();
    const piece = envelope.toString().split("\n")[0];
    const header = JSON.parse(piece);
    const dsn = new URL(header["dsn"]);
    const project_id = dsn.pathname?.replace("/", "");

    if (dsn.hostname !== SENTRY_HOST) {
      throw new Error(`Invalid sentry hostname: ${dsn.hostname}`);
    }

    if (!project_id || !SENTRY_PROJECT_IDS.includes(project_id)) {
      throw new Error(`Invalid sentry project id: ${project_id}`);
    }

    const upstream_sentry_url = `https://${SENTRY_HOST}/api/${project_id}/envelope/`;
    await fetch(upstream_sentry_url, { method: "POST", body: envelope });

    return json({}, { status: 200 });
  } catch (e) {
    console.error("error tunneling to sentry", e);
    return json({ error: "error tunneling to sentry" }, { status: 500 });
  }
};
```

Off-Topic: I prefer following to get JSON segment. (But this doesn't affect the behaviour. No worry)

```diff
-    const piece = envelope.toString().split("\n")[0];
+    const piece = envelope.slice(0, envelop.indexOf(/* CR */ 0x0a)).toString();
```

**Comment by LumaKernel** [comment]
Credits: I found this while working in https://github.com/Optimind-llc and found this problem with the team member @lbk-yuuki-nakamura.

**Comment by mydea** [comment]
Hey, the tunnel examples are all a bit WIP and need updating. I am going to put this into the backlog, we are pretty swamped with work right now - PRs are welcome!

**Comment by AbhiPrasad** [comment]
We're tracking improvements toward tunneling docs and setup here: https://github.com/getsentry/projects/issues/385

Going to close this issue in favour of that.
