### ISSUE TITLE
🔗 404 Error

### ISSUE THREAD

**Issue by wojtekmaj** [getsentry/sentry-docs#10368]
### URL
https://docs.sentry.io/product/accounts/choose-your-data-center
(which redirected me to:)
https://docs.sentry.io/account/choose-your-data-center/

### Additional Info

> United States of America (US) 🇺🇸
> Your organization's data storage location. [Learn More](https://docs.sentry.io/product/accounts/choose-your-data-center)

**Comment by vivianyentran** [comment]
fixed in #10440
