### ISSUE TITLE
Document JS TRPC middleware

### ISSUE THREAD

**Issue by mydea** [getsentry/sentry-docs#10372]
We have a TRPC middleware (https://github.com/getsentry/sentry-javascript/blob/develop/packages/core/src/trpc.ts)

Which we test here: https://github.com/getsentry/sentry-javascript/blob/develop/dev-packages/e2e-tests/test-applications/node-express/src/app.ts#L108

But we haven't added any docs for it (yet).

**Comment by mydea** [comment]
@lforst when you're back from PTO, we can take a look at this!

**Comment by lforst** [comment]
we def have/had this documented previously

**Comment by lforst** [comment]
![Screenshot 2024-06-17 at 09 27 12](https://github.com/getsentry/sentry-docs/assets/8118419/8f4e1891-7049-4cf0-9507-9e18855cd773)

It used to be in pluggable integrations but I am too lazy to find the commit that removed it. I'll just add it back.
