### ISSUE TITLE
🔗 404 Error

### ISSUE THREAD

**Issue by timvandam** [getsentry/sentry-docs#10377]
### URL

https://docs.sentry.io/platforms/javascript/guides/react/configuration/integrations/trycatch/

this page is indexed by google

**Comment by a-hariti** [comment]
Thanks for reporting @timvandam!

any idea what's the current equivalent of this @stephanie-anderson?

**Comment by vivianyentran** [comment]
I think this should now go to [browserApiErrors](https://docs.sentry.io/platforms/javascript/configuration/integrations/browserapierrors/) . See https://github.com/getsentry/sentry-javascript/pull/10755
