### ISSUE TITLE
Anchor link must be clicked twice to change URL address in URL bar

### ISSUE THREAD

**Issue by cstavitsky** [getsentry/sentry-docs#10376]
### Steps to Reproduce

1. Visit https://docs.sentry.io/platforms/android/configuration/options/
2. Click the anchor link for `httpProxy` once
3. page jumps to correct location, but URL bar does not update to show correct address with anchor link
4. Click anchor link for `httpProxy` a second time
5. now URL bar updates to show correct address with anchor link

not sure how widespread this problem may be.

### Expected Result

The URL address should update in the URL bar after clicking the anchor link for the first time.

### Actual Result

https://github.com/getsentry/sentry-docs/assets/12092849/31f79a7b-3a17-40a0-b56c-a4a39db47f71

**Comment by a-hariti** [comment]
I couldn't repro this on different browsers @cstavitsky 

Can you repro it in a browser with not extensions?

**Comment by cstavitsky** [comment]
@a-hariti I can't reproduce it myself anymore when I try now 🙃 If you're not seeing it, and I'm no longer seeing it, I suggest we close it. If I encounter it again on a browser with no extensions enabled, I'll come back and reopen with more context
