### ISSUE TITLE
Changelog doesn't render markdown

### ISSUE THREAD

**Issue by smeubank** [getsentry/sentry-docs#10428]
### Core or SDK?

Core Sentry product

### Which part? Which one?

changlog

### Description

The changelog doesn't display markdown correctly. Seen here with a link that displays a regular text

You can see this [here](https://docs.sentry.io/changelog/), only when viewing the summary of a changelog post.

Create an example here -> https://docs.sentry.io/changelog/_admin/

![image](https://github.com/getsentry/sentry-docs/assets/47563310/483dee75-ebc5-4569-8041-fe3c7d54602a)

### Suggested Solution

Links and stuff should work good

summary portion here

<img width="489" alt="image" src="https://github.com/getsentry/sentry-docs/assets/47563310/770faa7f-710f-4ecf-a3fe-01b2b8035d9e">

**Comment by chargome** [comment]
fixed here: https://github.com/getsentry/sentry-docs/pull/10612
