### ISSUE TITLE
🔗 404 Error

### ISSUE THREAD

**Issue by gttomvenema** [getsentry/sentry-docs#10432]
### URL

https://docs.sentry.io/_not-found/

### Additional Info

Via my organisation settings

**Comment by a-hariti** [comment]
Thanks for reporting @gttomvenema,

can you please tell us which link took you here?

**Comment by gttomvenema** [comment]
@a-hariti , I think it was via https://*.sentry.io/settings/organization/, and then clicking on Your organization's data storage location. [Learn More](https://docs.sentry.io/product/accounts/choose-your-data-center)

It appears to be resolved
