### ISSUE TITLE
DjangoIntegration example disables LoggingIntegration

### ISSUE THREAD

**Issue by horida** [getsentry/sentry-docs#1044]
Conncerning the documentation of the django integration (maybe others as well): https://docs.sentry.io/platforms/python/django/

The example to integrate django is
```python
sentry_sdk.init(
    dsn="https://c0aea1807448476b838f70c2edf9cf8a@sentry.io/122455",
    integrations=[DjangoIntegration()]
)
```

And in the [behaviour description](https://docs.sentry.io/platforms/python/django/#behavior) you say that 

> Logging with any logger will create breadcrumbs when the Logging integration is enabled (done by default).

However, this is not true, since integrations is only set to DjangoIntegrations in the example.

Am I missing something?

**Comment by untitaker** [comment]
The logging integration is enabled by default. The example at https://docs.sentry.io/platforms/python/logging/ shows the used parameters.

If you want to disable default integrations you need to pass `default_integrations=False`. If you want to change settings on the integration, pass an explicit instance (which overwrites the implicit one)
