### ISSUE TITLE
🔗 404 Error

### ISSUE THREAD

**Issue by MisterKubs** [getsentry/sentry-docs#10466]
### URL

https://docs.sentry.io/product/tracing/getting-started/?platform=react

### Additional Info

While reading the docs for getting started with [React Router](https://docs.sentry.io/platforms/javascript/guides/react/features/react-router/) I stumbled upon a broken link to the "Getting started with React Performance" page was broken.
![image](https://github.com/getsentry/sentry-docs/assets/19376848/a037db20-53ad-4785-b9d8-e261bab01a49)

However, the "same" link on the [Tanstack Router](https://docs.sentry.io/platforms/javascript/guides/react/features/tanstack-router/) integration page works and points at what i assume is the correct path: [Set Up Tracing](https://docs.sentry.io/platforms/javascript/guides/react/tracing/#enable-tracing)

Keep up the good work, great docs! 🥇

**Comment by AbhiPrasad** [comment]
Fixed with https://github.com/getsentry/sentry-docs/pull/10486
