### ISSUE TITLE
Search input breaks on mobile

### ISSUE THREAD

**Issue by stephanie-anderson** [getsentry/sentry-docs#10471]
[Feedback from Slack]

The search input completely breaks on mobile.
Why are we hijacking keypresses?
I type s and it selects sandbox rather than letting me enter a query

**Comment by a-hariti** [comment]
I couldn't repro this @stephanie-anderson

**Comment by stephanie-anderson** [comment]
Just tried to repro as well - this is how I was able to:
1. navigate to the Next.js docs
2. open the menu modal
3. type in "s" .. other characters I've tried don't trigger the same behaviour

**Comment by a-hariti** [comment]
oh, I think the menu items have focus by default and s selects the first item that starts with an s, c selects "changelog" too btw

**Comment by stephanie-anderson** [comment]
Oh!
