### ISSUE TITLE
Broken link to Python's Auto Instrumentation

### ISSUE THREAD

**Issue by kpujjigit** [getsentry/sentry-docs#10477]
### URL

https://docs.sentry.io/platform-redirect/?next=%2Fperformance%2Finstrumentation%2Fautomatic-instrumentation

### Additional Info

Found on the Queues Page under 'Prerequisites and Limitations': https://docs.sentry.io/product/insights/queue-monitoring/#prerequisites-and-limitations

**Comment by a-hariti** [comment]
fixed in #10502
