### ISSUE TITLE
🔗 404 Error

### ISSUE THREAD

**Issue by vindi-r** [getsentry/sentry-docs#10478]
### URL

https://docs.sentry.io/product/tracing/getting-started/?platform=react

### Additional Info

From: https://docs.sentry.io/platforms/javascript/guides/react/features/react-router/

> The React Router integration is designed to work with Sentry Tracing. Please see [Getting Started with React Performance](https://docs.sentry.io/product/tracing/getting-started/?platform=react) for more details on how to set up and install the SDK.

**Comment by AbhiPrasad** [comment]
created a PR here to fix this! https://github.com/getsentry/sentry-docs/pull/10486
