### ISSUE TITLE
Toggles displayed over search results

### ISSUE THREAD

**Issue by sentrivana** [getsentry/sentry-docs#10488]
### Steps to Reproduce

1. Go to https://docs.sentry.io/platforms/python/
2. Make sure the onboarding toggles (Error Monitoring, Tracing, Profiling) are visible on the page
3. Use the search input to search for something, for example `before_send`
4. Observe search results

### Expected Result

Search results should display over toggles.

### Actual Result

Toggles are displayed over search results:

![Screenshot 2024-06-25 at 10 49 26](https://github.com/getsentry/sentry-docs/assets/131587164/5d0c0f96-e560-42cd-9152-30fa1671bf89)

### Additional Info

Observed on Firefox 127.0.1

**Comment by a-hariti** [comment]
This was fixed in #10529
