### ISSUE TITLE
🔗 404 Error

### ISSUE THREAD

**Issue by evans-jz** [getsentry/sentry-docs#10492]
### URL

https://docs.sentry.io/platform-redirect/

### Additional Info

Redirecting from [insights queue-monitoring](https://docs.sentry.io/product/insights/queue-monitoring/) -> [auto instrumentation](https://docs.sentry.io/platform-redirect/?next=%2Fperformance%2Finstrumentation%2Fautomatic-instrumentation)

**Comment by evans-jz** [comment]
Enterprise customer: https://evisort.sentry.io/

**Comment by a-hariti** [comment]
Thanks for reporting @evans-jz 

fixed in #10502
