### ISSUE TITLE
Platform redirect page could be more specific about where you're heading next

### ISSUE THREAD

**Issue by cstavitsky** [getsentry/sentry-docs#10517]
### Problem Statement

Platform redirect page ([example for sampling](https://docs.sentry.io/platform-redirect/?next=/configuration/sampling/)) shows generic text at top:
> ## Platform Specific Content
> ...list of SDK-specific links

If I land on this page, it's not clear that the redirect page will lead me to docs about Sampling.

### Solution Brainstorm

Instead, I would like it to read something like this, so I know where I'm about to head after the redirect.

> # Platform Specific Content
> ### Sampling
> #### Learn how to configure the volume of error and transaction events sent to Sentry.
> ...list of SDK-specific links

**Comment by realkosty** [comment]
@stephanie-anderson
> Unfortunately, there is no guarantee that all pages across platforms will have the same title and/or description:
IMO that's fine. We can pick the most common title, a concatenation of all titles, or even just the first one - would be way better than nothing. The titles should be fairly similar anyway, right?

I personally lean towards putting it in the big header instead. As a Sentry user not very familiar with our docs platform I would be confused by huge "Platform Specific Content" and assume I opened the wrong link or looking at the wrong tab. But your proposed solution would be definitely a big improvement too. Or what Chris suggested above.

**Comment by realkosty** [comment]
@lizokm what do you think?

**Comment by cstavitsky** [comment]
> As a Sentry user not very familiar with our docs platform I would be confused by huge "Platform Specific Content" and assume I opened the wrong link or looking at the wrong tab.

How about replacing `Platform Specific Content` with something that feels more actionable? For example `Continue To Docs For Your Platform:`

> I think what we could do is show a preview of title and description of all platforms that have that content. Unfortunately, there is no guarantee that all pages across platforms will have the same title and/or description

> IMO that's fine. We can pick the most common title, a concatenation of all titles, or even just the first one - would be way better than nothing. The titles should be fairly similar anyway, right?

Yes, either of these would help. Anything that will give the user an expectation of what exactly they're about to navigate to!

**Comment by lizokm** [comment]
I think it would be best to put the information in the header/ and maybe elaborate a little more in the text just under the header. Then we could put the "The page you are looking for is customized...." text in a <Note></Note> so that it stands out :)

**Comment by lizokm** [comment]
@chargome this is what we were talking about in our meeting on Monday. I'd love to make this happen.
