### ISSUE TITLE
🔗 404 Error on /pricing/am2-pricing/

### ISSUE THREAD

**Issue by aewshyae** [getsentry/sentry-docs#10554]
### URL

https://docs.sentry.io/pricing/am2-pricing/

### Additional Info

I could see this page on 2024/6/27 but when I accessed on 6/28 it's gone somewhere.
There was a pricing before 11 June 2024.

Though I can search the page(of cource this is the same URL and it's gone)
![screenshot-2024-06-29-16 33 27](https://github.com/getsentry/sentry-docs/assets/1528058/27efb5a6-81e0-4424-872f-f53b2c1612ec)

**Comment by vivianyentran** [comment]
Hi, thanks for filing an issue for this! The page you're looking for now lives at https://docs.sentry.io/pricing/legacy-pricing/. We also added a redirect so the old link should no longer give you a 404. Hope this solves your issue!

**Comment by aewshyae** [comment]
I've confirmed the URL is redirected to legacy-pricing page.
Thanks!
