### ISSUE TITLE
Deprecated function still shown in latest Node documentation

### ISSUE THREAD

**Issue by cstavitsky** [getsentry/sentry-docs#10563]
### Core or SDK?

Platform/SDK

### Which part? Which one?

Node.js

### Description

Opening this issue as feedback from a trialing customer:

> https://docs.sentry.io/platforms/javascript/guides/node/enriching-events/transaction-name/
> 
> In that transaction name article it mentions using setTransactionName like so:
> `Sentry.getCurrentScope().setTransactionName("UserListView");`
> 
> But our engineer was getting undefined errors. Then they found the deprecations list and that function is included.
> https://docs.sentry.io/platforms/javascript/guides/gatsby/migration/v7-to-v8/v7-deprecations/#deprecate-scopesettransactionname
> So we weren't sure if this was just documentation needed an update or what but figured we would pass it along in case others ran into it

### Suggested Solution

This code snippet should be updated to use a non-deprecated function from the v8 SDK

**Comment by AbhiPrasad** [comment]
Hmm `setTransactionName` should not be deprecated any longer, were you able to reproduce `setTransactionName` not working in `7.x`? The docs are wrong, we will fix!

**Comment by AbhiPrasad** [comment]
I'm gonna go ahead and close this because we fixed the docs, but please reach out if that is not expected.
