### ISSUE TITLE
Can't Find SENTRY_FEATURES documentation

### ISSUE THREAD

**Issue by milonti** [getsentry/sentry-docs#1056]
Hello

While trying to enable an SSO provider for my On-Premise installation, I came across the SENTRY_FEATURES flag in the sentry.conf.py file. The documentation says to use it to enable advanced SSO features, but does not list ANYWHERE what those features are. 

So far as I can tell, there is no information on what SENTRY_FEATURES is or what it does or what options it can actually enable/disable. 

Can someone point me at an API or resource that describes them rather than me trying to comb through the source code on my own? The Sentry.IO documentation is incredibly vague about most On-Premise things...

**Comment by masad-frost** [comment]
Not docs, but commented code https://github.com/getsentry/sentry/blob/d1e9afc17f72075e43ac60c24bdae4602066fdd1/src/sentry/conf/server.py#L811-L897

You can probably submit a PR to sentry-docs using those.
