### ISSUE TITLE
iOS Guide link is wrong

### ISSUE THREAD

**Issue by jaesungline** [getsentry/sentry-docs#10568]
### Core or SDK?

Platform/SDK

### Which part? Which one?

platforms/apple/guides/ios/

### Description

https://docs.sentry.io/platforms/apple/guides/ios/#install
install section,  below text here.
```
This will patch your project and configure the SDK. You'll only need to patch the project once, then you'll be able to add the patched files to your version control system. If you prefer, you can also [set up the SDK manually](https://docs.sentry.io/platforms/react-native/manual-setup/manual-setup/) or follow the instructions below to adapt the [configuration](https://docs.sentry.io/platforms/apple/guides/ios/#configure).
```

[set up the SDK manually] link refers to react-native document link

### Suggested Solution

[set up the SDK manually] should be 
https://docs.sentry.io/platforms/apple/guides/ios/manual-setup/

**Comment by JLuse** [comment]
Thanks for letting us know @jaesungline. The link has been fixed.
