### ISSUE TITLE
API Documentation Error: /api/events/get-group-events/

### ISSUE THREAD

**Issue by boblail** [getsentry/sentry-docs#1057]
The response I get from this API does not match the documentation.

When I request `https://sentry.io/api/0/issues/#{issue_id}/events/`, this is the list of keys I get for each event:

```
eventID
tags
projectID
dateCreated
user
message
id
culprit
title
platform
location
crashFile
event.type
groupID
```

The example in the documentation includes a `vars` section with an `'extra'` key. The issue I was pulling events for _has_ extra values but they're not in the API response.

**Comment by markstory** [comment]
The `vars.extra` keys in that example are nested under the `frames` interface. From what you've provided you don't have frames, and have a crashFile instead.

**Comment by boblail** [comment]
Oh, thanks @markstory. Maybe I was interpreting the key name `extra` wrong there. Is _this_ information available through the API?

<img width="797" alt="Screen Shot 2019-06-11 at 10 18 41 AM" src="https://user-images.githubusercontent.com/151907/59284728-6149f100-8c32-11e9-8e52-43e84bb055d8.png">

**Comment by markstory** [comment]
>  Is this information available through the API?

Yes, but not from the event list endpoint. You need to use the GET event-details endpoint e.g `/api/0/issues/:issue_id/events/:event_id/`.

**Comment by boblail** [comment]
Gotcha. Thanks!
