### ISSUE TITLE
Allow changing indentation with onboardingOptions

### ISSUE THREAD

**Issue by andreiborza** [getsentry/sentry-docs#10572]
### Problem Statement

Currently, we can use `onboardingOptions` to show/hide certain lines of code in a code snippet, but there's no way to change indentation of other lines. This leads to snippets that aren't quite right.

e.g.

```javascript {"onboardingOptions": {"performance": "1-4, 12"}}
Sentry.startSpan({
  op: "test",
  name: "My First Test Span",
}, () => {
  setTimeout(() => {
    try {
      foo();
    } catch (e) {
      Sentry.captureException(e);
    }
  }, 99);
});
```

when toggling off performance, the resulting code snippet looks like
```javascript {"onboardingOptions": {"performance": "1-4, 12"}}
  setTimeout(() => {
    try {
      foo();
    } catch (e) {
      Sentry.captureException(e);
    }
  }, 99);
```

instead of what it should look like 

```javascript {"onboardingOptions": {"performance": "1-4, 12"}}
setTimeout(() => {
  try {
    foo();
  } catch (e) {
    Sentry.captureException(e);
  }
}, 99);
```

### Solution Brainstorm

A workaround is to duplicate the code in the code snippet but complexity grows quickly when having several options. It would be nice if we could supply some kind of indentation delta of sorts for the other lines.

**Comment by a-hariti** [comment]
I think duplicating lines is still less complex than adding this feature (it will be more brittle with less control from authors as compared to duplication) @andreiborza

**Comment by andreiborza** [comment]
Yea fair enough. It's just that complexity grows quickly, i.e. for 3 toggles we have 8 duplicated scripts to keep in sync, very easy to make mistakes there.

**Comment by stephanie-anderson** [comment]
I agree that for now, it seems less brittle to just make a separate code block for that. Will close the issue for now 🙏
