### ISSUE TITLE
Add docs for `@sentry/vercel-edge`

### ISSUE THREAD

**Issue by AbhiPrasad** [getsentry/sentry-docs#10587]
### Core or SDK?

Platform/SDK

### Which part? Which one?

`@sentry/vercel-edge` package

### Description

We should document `@sentry/vercel-edge` as a platform and note it's differences from using `@sentry/node`

### Suggested Solution

New platform!

We should also remove the alpha flag from https://github.com/getsentry/sentry-javascript/blob/develop/packages/vercel-edge/README.md

**Comment by mydea** [comment]
Hmm, I am not 100% sure how to proceed here. We have this marked as a more internal thing for now - cc @lforst I think you have stronger opinions about this. When in doubt I'd close this issue for now, we can always revisit.

**Comment by smeubank** [comment]
we can close, i think this came up around re-using with other SDKs like remix, we generally should still figure that story out. And I don;t think it is a docs solution. I also discussed with @s1gr1d that we should have a daci to outline how we could tackle this the different UX options.
