### ISSUE TITLE
UI Bug: ^ and $ symbols not visible

### ISSUE THREAD

**Issue by roger-sato** [getsentry/sentry-docs#10583]
### Steps to Reproduce

1. Navigate to the documentation page
https://docs.sentry.io/platforms/javascript/configuration/filtering/#using-
2. Notice that the regex /Exact Match Message/ is displayed without the ^ and $ anchors
3. Copy the code snippet and paste it into a text editor
4. Verify that the pasted code actually includes the ^ and $ anchors

### Expected Result

The regex in the documentation should visually display the ^ and $ anchors: /^Exact Match Message$/

### Actual Result

The regex is displayed without the visible ^ and $ anchors: /Exact Match Message/

**Comment by chargome** [comment]
@roger-sato Thanks for reaching out! This issue is most likely related to #10468, we'll look into it.
