### ISSUE TITLE
Search delivers results in unexpected order

### ISSUE THREAD

**Issue by stephanie-anderson** [getsentry/sentry-docs#10592]
This was reported via [Slack Message](https://sentry.slack.com/archives/C8H0BQRDJ/p1720165203423089?thread_ts=1720165203.423089&cid=C8H0BQRDJ):

> We should _really_ fix the search in the docs... :sweat_smile: e.g. being in the node docs and searching for `startNewTrace` it only shows the result in the electron docs? that makes no sense at all, the same content exists in the node docs too :see_no_evil:

Let's make sure search results are context sensitive, e.g.
* when in user docs deliver results from user docs (don't return any from develop)
* when in develop docs deliver results from develop docs (don't return any from user-facing docs)
* when on a guide site, return results, that match this guide
* when on a platform site, return results, that match this platform, but not their guides, or other platforms or guides of those

On that note, we should also restrict access to modifying the indices

**Comment by mydea** [comment]
More examples, if needed - e.g. search like this:

![Image](https://github.com/user-attachments/assets/54dd5d2e-1046-46dd-bbb3-54dd86888a14)

Gives me not a single result that I would expect/want based on the place I am searching from.

**Comment by chargome** [comment]
note: modifying the indices should not be an issue, they will be overwritten with each new algolia workflow run

**Comment by chargome** [comment]
Closing this as we now have context sensitive search activated. Let's create separate issues for any other search-related improvements.
