### ISSUE TITLE
Section links are broken

### ISSUE THREAD

**Issue by cleptric** [getsentry/sentry-docs#10613]
![image](https://github.com/getsentry/sentry-docs/assets/6617432/276318b8-8d38-4e86-b839-1e0cb5fe8993)

e.g. https://docs.sentry.io/platforms/go/configuration/filtering/#using-, the fragment is cut off.

**Comment by chargome** [comment]
Just had a quick look at this and saw that only sections links with `<PlatformIdentifier />` are affected. The problem is that `remark-slug` does not extract the id correctly from the nested components.
