### ISSUE TITLE
Unclear V8 Migration instruction vs Manual Setup

### ISSUE THREAD

**Issue by thomasverleye** [getsentry/sentry-docs#10615]
### Core or SDK?

Platform/SDK

### Which part? Which one?

Remix

### Description

The [Sentry Remix v7 to v8 migration documentation](https://docs.sentry.io/platforms/javascript/guides/remix/migration/v7-to-v8/) **OR** the [Sentry Remix Manual Setup documentation](https://docs.sentry.io/platforms/javascript/guides/remix/manual-setup/) are unclear.

## The problem with the server side setup
In the **migration documentation** there is mentioned that the `Sentry.init` call for the server side must be moved at the top of the `entry.server.tsx`.

In the **manual setup documentation** there is no mention of `entry.server.tsx` at all and instead you need to add a `instrument.server.mjs` file which you manually should add in the node script.  
**Sidetracking:** the express import is not working when using Vite.

## The problem with the client side setup
In the **migration documentation** there is mentioned that the `Sentry.init` call for the client side must be moved at the top of the `entry.client.tsx`.  
**Sidetracking:** the routing instrumentation uses a `router` variable that is not imported anywhere and does not make sense from a Remix perspective here.

In the **manual setup documentation** there is no mention of setting up `Sentry.init` at the top before all imports.

### Suggested Solution

I have no clear solution here as I am not 100% sure which part of the documentation is right or outdated.

**Comment by mydea** [comment]
Hey there,

you can follow the migration guide, that should all work just fine!
During the v8 cycle, we did some further work on the remix SDK, including a new way to set this up. This has some benefits in improved instrumentation etc. However the way that is documented in the migration guide is also just fine and can be used without problems!

The migration guide is really a snapshot of steps to migrate from v7 to v8, it does not show the very recent stuff necessarily, which should be fine!

> Sidetracking: the express import is not working when using Vite.

Do you mind opening an issue here: https://github.com/getsentry/sentry-javascript with details on that problem? We'll look into it!

> Sidetracking: the routing instrumentation uses a router variable that is not imported anywhere and does not make sense from a Remix perspective here.

Great point, that's actually incorrect - we'll fix this!

**Comment by mydea** [comment]
I opened a PR to fix/clarify some things there: https://github.com/getsentry/sentry-docs/pull/10619
