### ISSUE TITLE
🔗 404 Error

### ISSUE THREAD

**Issue by ionelmc** [getsentry/sentry-docs#10652]
### URL

https://docs.sentry.io/platforms/python/performance/

### Additional Info

https://docs.sentry.io/product/performance/getting-started/

**Comment by gggritso** [comment]
@ionelmc thanks for raising this! We're working on fixing the URLs. Out of curiosity, where did you see these bad URLs?

**Comment by gggritso** [comment]
Maybe fixed by https://github.com/getsentry/sentry-docs/pull/10684

**Comment by ionelmc** [comment]
Here: https://docs.sentry.io/product/performance/getting-started/

**Comment by mjq** [comment]
This was fixed in #10678. Thanks for reporting!
