### ISSUE TITLE
🔗 404 Error

### ISSUE THREAD

**Issue by Angelodaniel** [getsentry/sentry-docs#10654]
### URL

https://docs.sentry.io/_not-found/ from the https://docs.sentry.io/platforms/javascript/tracing/instrumentation/automatic-instrumentation/#what-our-instrumentation-provides when I click on traces, transactions and spans
<img width="704" alt="Screenshot 2024-07-11 at 16 50 02" src="https://github.com/getsentry/sentry-docs/assets/25929053/6bdb9248-29e7-4c5d-bff3-ab823ff5d3cf">

**Comment by chargome** [comment]
@Angelodaniel thank you, has been fixed!
