### ISSUE TITLE
🔗 404 Error

### ISSUE THREAD

**Issue by ecrtmn** [getsentry/sentry-docs#10670]
### URL

https://docs.sentry.io/product/integrations/integration-platform/ui-components/

### Additional Info

The issue occurs when I try to look at the documentation at UI schema.
<img width="952" alt="image" src="https://github.com/user-attachments/assets/a38f3564-f22b-4f2b-a1f8-637ad50eedf0">

**Comment by stephanie-anderson** [comment]
Thank you for reporting! Redirects have been fixed :)
