### ISSUE TITLE
Disabling Integrations (breadcrumbs) Is not So clear

### ISSUE THREAD

**Issue by smeubank** [getsentry/sentry-docs#10671]
### Core or SDK?

Platform/SDK

### Which part? Which one?

Node

### Description

There has been feedback that disabling breadcrumbs and all the extra auto-integrations is not so easy or clear how to do in the Node SDK

### Suggested Solution

There are a number of suggestions, the docs links from this issue do not really exist anymore. Can we confirm if this suggestion is the best and if it still works, then amend the docs

https://github.com/getsentry/sentry-javascript/issues/1706#issuecomment-434631497

**Comment by mydea** [comment]
IMHO we have documented this reasonably here: https://docs.sentry.io/platforms/javascript/configuration/integrations/#removing-a-default-integration
