### ISSUE TITLE
setLevel example does not work

### ISSUE THREAD

**Issue by turbolego** [getsentry/sentry-docs#1068]
In the section for ["Setting the level"](https://docs.sentry.io/enriching-error-data/context/?platform=browser#setting-the-level) in the documentation the example is:

`Sentry.configureScope((scope) => {
  scope.setLevel('warning');
});`

This gives me this error:

> Argument of type '"warning"' is not assignable to parameter of type 'Severity'.ts(2345)

If i instead do this:
`Sentry.configureScope((scope) => {
  scope.setLevel(Sentry.Severity.Warning);
});`

It works! 😄 (Thanks @gregwym for [the solution](https://github.com/getsentry/sentry-javascript/issues/1592)).

Please update the documentation.

**Comment by dashed** [comment]
@turbolego glad you found a workaround. Mind sending a pull-request for this?
