### ISSUE TITLE
🔗 404 Error - CLI Installation

### ISSUE THREAD

**Issue by nathcakes** [getsentry/sentry-docs#10692]
### URL

https://docs.sentry.io/product/cli/installation/

### Additional Info

Following the link from 1. Download sentry-cli  
Lead to this 404 Page from the Upload Debug Symbols page on iOS. https://docs.sentry.io/platforms/apple/guides/ios/dsym/

**Comment by stephanie-anderson** [comment]
Thank you for reporting! Redirects have been fixed :)
