### ISSUE TITLE
Stale preview deployments

### ISSUE THREAD

**Issue by chargome** [getsentry/sentry-docs#10695]
### Problem Statement

We are running into issues of bandwidth usage by stale preview deployments.

### Solution Brainstorm

~~We should provide our own deployment pipeline by using [the vercel CLI via gh actions](https://vercel.com/guides/how-can-i-use-github-actions-with-vercel).~~

We will probably solve this by periodically running a script to remove old preview deployments.

**Comment by stephanie-anderson** [comment]
Let's make sure that Vercel respects no-index on all these previews
