### ISSUE TITLE
Broken link in docs

### ISSUE THREAD

**Issue by Chris-Gillis** [getsentry/sentry-docs#10706]
### URL

https://docs.sentry.io/platforms/php/guides/laravel/configuration/environments/

### Additional Info

![image](https://github.com/user-attachments/assets/e7972017-9cf0-4f97-97f1-794be2c060b8)

The link pictured here leads to a 404 page.

**Comment by stephanie-anderson** [comment]
Thank you for reporting! Redirects have been fixed :)
