### ISSUE TITLE
Syntax highlight doesn't work when open on new tab

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-docs#10719]
### Steps to Reproduce

If I open links on another tab, syntax highlight doesn't work:

![image](https://github.com/user-attachments/assets/7fe6bbb9-1359-4843-9f4a-8fe6ccc9b450)

If I just navigate away (or if I refresh the new tab with broken highlight), it works:

![image](https://github.com/user-attachments/assets/f82ec60b-565b-4081-b52e-8c63d418feb7)

### Expected Result

highlighting

### Actual Result

no highlighting

**Comment by a-hariti** [comment]
I have noticed this happens "sometimes", can you repro consistently @bruno-garcia ?

**Comment by chargome** [comment]
couldn't reproduce this with the latest changes, feel free to re-open!
