### ISSUE TITLE
🔗 404 Error when selecting - A root transaction is missing.

### ISSUE THREAD

**Issue by Prithvirajkumar** [getsentry/sentry-docs#10715]
### URL

`A root transaction is missing. Transactions linked by a dashed line have been orphaned and cannot be directly linked to the root.`

Selecting the link i.e https://docs.sentry.io/product/sentry-basics/concepts/tracing/trace-view/#orphan-traces-and-broken-subtraces takes me to https://docs.sentry.io/_not-found/

It should instead be - https://docs.sentry.io/concepts/key-terms/tracing/trace-view/#orphan-traces-and-broken-subtraces

**Comment by mjq** [comment]
We should add a redirect for this in docs, but in the meantime we can also fix the links inside Sentry (which is where the link itself lives) - will link a PR in a moment.

**Comment by chargome** [comment]
@mjq @Prithvirajkumar Thanks! On docs side this was fixed with #10757.
