### ISSUE TITLE
🔗 404 Error - Links to documentation from the Issue Grouping page of Project's Settings.

### ISSUE THREAD

**Issue by saul-gardens-dev** [getsentry/sentry-docs#10725]
### URL

https://docs.sentry.io/product/data-management-settings/event-grouping/fingerprint-rules/

### Additional Info

Looks like it should be https://docs.sentry.io/concepts/data-management/event-grouping/fingerprint-rules/.
It seems like other doc-related links on this page, which is the Issue Grouping page for a Project's Settings, also use a URL whose path starts with `/product/`, but it seems like the correct path is `/concepts`/?

![image](https://github.com/user-attachments/assets/b0bf24b7-d00d-436f-b0aa-db35bcf0d54c)

**Comment by stephanie-anderson** [comment]
Thank you for reporting! Redirects have been fixed :)
