### ISSUE TITLE
Single colon not being interpreted in dev docs mdx files

### ISSUE THREAD

**Issue by chargome** [getsentry/sentry-docs#10738]
### Steps to Reproduce

https://develop.sentry.dev/sdk/event-payloads/contexts/#device-context -> colons in front of Required/Optional

We should search the dev-docs for occurrences and remove this syntax. 

### Expected Result

no ":" visible

### Actual Result

":" is visible

**Comment by stephanie-anderson** [comment]
related to https://github.com/getsentry/sentry-docs/issues/8994
