### ISSUE TITLE
Misleading docs around OpenTelemetry support for `@sentry/browser`

### ISSUE THREAD

**Issue by HeroicEric** [getsentry/sentry-docs#10750]
### Problem Statement

The sidebar in the docs for `@sentry/browser` include a migration guide for migrating from 7.x to 8.x. One section of the migration guide is about [OpenTelemetry support](https://docs.sentry.io/platforms/javascript/migration/v7-to-v8/v8-opentelemetry/).

After spending some time trying to figure out how to get it working I realized that these docs are actually only relevant if you're using `@sentry/node` or one of the libraries built on top of it.

I believe this discussion is the latest on `@sentry/browser` support for OpenTelemetry: https://github.com/getsentry/sentry-javascript/discussions/7364

### Solution Brainstorm

I think it would be helpful to either not show these docs or add explanation to the OpenTelemetry guide to make it clear that these features are not available for `@sentry/browser` and other packages built on top of it like `@sentry/react` and `@sentry/ember`.

Also would be happy to hear that those features are available for `@sentry/browser` and I was just doing it wrong :)

**Comment by AbhiPrasad** [comment]
Opened https://github.com/getsentry/sentry-docs/pull/10752 to fix!
