### ISSUE TITLE
User Feedback Form - Manual injection NextJS SDK not working

### ISSUE THREAD

**Issue by mendezona** [getsentry/sentry-docs#10791]
### Core or SDK?

Platform/SDK

### Which part? Which one?

User Feedback Form - NextJS SDK

### Description

Hello, I tried using the manual injection of the NextJS User Feedback Form, but it is not working. I get an error in my browser saying 

`Unhandled Promise Rejection: TypeError: undefined is not an object (evaluating 'feedback.createWidget')`

I am using the following package versions:

```
"@sentry/nextjs": "^8.19.0",
"next": "^14.2.5",
```

```
"use client";

import * as Sentry from "@sentry/nextjs";
import { useEffect, useState } from "react";

export function SentryFeedbackWidget() {
  const [feedback, setFeedback] = useState();
  // Read `getFeedback` on the client only, to avoid hydration errors when server rendering
  useEffect(() => {
    setFeedback(Sentry.getFeedback());
  }, []);

  const [widget, setWidget] = useState();
  return (
    <button
      type="button"
      onClick={async () => {
        if (widget) {
          widget.removeFromDom();
          setWidget(null);
        } else {
          setWidget(feedback.createWidget());
        }
      }}
    >
      {widget ? "Remove Widget" : "Create Widget"}
    </button>
  );
}

```

### Suggested Solution

Update documentation or update NextJS SDK

**Comment by mydea** [comment]
Hey, we did a few changes/improvement in this regard - is this still not working with the latest SDK & the latest docs: https://docs.sentry.io/platforms/javascript/guides/nextjs/user-feedback/configuration/ for you?
