### ISSUE TITLE
Incorrect Docs for captureConsoleIntegration

### ISSUE THREAD

**Issue by johnmantios** [getsentry/sentry-docs#10860]
### Core or SDK?

Core Sentry product

### Which part? Which one?

Sentry Integrations

### Description

In the https://docs.sentry.io/platforms/javascript/configuration/integrations/captureconsole/ page, in order to use the captureConsoleIntegration it is written that you should do the following import: 

`import * as Sentry from "@sentry/browser";`

but in reality what worked for me at least was this:

`import * as Sentry from "@sentry/integrations";`

### Suggested Solution

Change `import * as Sentry from "@sentry/browser";` with `import * as Sentry from "@sentry/integrations";`

**Comment by chargome** [comment]
Hey @johnmantios thanks for reaching out. `@sentry/integrations` is no longer published. You can instead import these pluggable integrations directly from your SDK package (e.g. `@sentry/browser` or `@sentry/react`) when using the latest version of our Sentry SDKs.

**Comment by mydea** [comment]
This is like this since v8 - no more need for `@sentry/integrations`.
