### ISSUE TITLE
Inject package metadata from registry for older versions

### ISSUE THREAD

**Issue by s1gr1d** [getsentry/sentry-docs#10874]
### Problem Statement

`@inject packages.checksum` or `@inject packages.version` only return data for the latest version. But on some pages (like pluggable integrations [here](https://docs.sentry.io/platforms/javascript/configuration/integrations/captureconsole/)), we want to show the setup with v7.

This is not super urgent as we can hardcode this right now as the latest version of v7 is not changing often. 

Also see this PR: https://github.com/getsentry/sentry-docs/issues/10874

### Solution Brainstorm

Adding an optional `version` parameter for the checksum and the version (to get a specific, and not the latest version)

**Comment by chargome** [comment]
partly related to [#3881](https://github.com/getsentry/sentry-docs/issues/3881)

**Comment by stephanie-anderson** [comment]
Decided not to implement something for this, as it seems this is not required all too often. Please reopen, if hardcoding that information does not work for you
