### ISSUE TITLE
`<PageGrid>` should reflect `sidebar_order`

### ISSUE THREAD

**Issue by mydea** [getsentry/sentry-docs#10887]
### Problem Statement

Although the naming is a bit misleading, I think it would make sense for the `<PageGrid>` component to reflect the order of `sidebar_order`. Otherwise, the order there does not match the sidebar order.

### Solution Brainstorm

Use the same ordering method for `<PageGrid>` as for the sidebar.

**Comment by a-hariti** [comment]
Can you include a concrete example @mydea?

**Comment by mydea** [comment]
If you look at this PR: https://github.com/getsentry/sentry-docs/pull/10872 it adds a new OpenTelemetry section in node docs (https://sentry-docs-git-fn-node-otel-docs.sentry.dev/platforms/javascript/guides/nestjs/opentelemetry/). There, I defined an order for the sidebar that is not reflected on the "landing page".

**Comment by a-hariti** [comment]
the `sidebar_order: 7000` is set on the index file (`docs/platforms/javascript/common/opentelemetry/index.mdx`), which will not affect its children

**Comment by a-hariti** [comment]
it has an order of `0`, which is getting compared with other items with `0` or none at all

did you try using bigger numbers?

**Comment by mydea** [comment]
hmm, but that did change the order in the sidebar to it being the first entry 😅 can it be we use different heuristics in these two places? What I want to achieve is have this one entry be the first, the other ones can have default (alphabetical, I guess?) ordering :) and it should be the same for the sidebar and the "grid"!
