### ISSUE TITLE
Main page for Python SDK integrations uses generic icon for Starlite integration

### ISSUE THREAD

**Issue by KellyWalker** [getsentry/sentry-docs#10933]
### Core or SDK?

Platform/SDK

### Which part? Which one?

python

### Description

The main page for the Sentry Python SDK lists available integrations:
https://docs.sentry.io/platforms/python/integrations/

One of those integrations is [Starlite](https://pypi.org/project/starlite/). There is a [PR](https://github.com/getsentry/sentry-python/pull/3358) to add an integration for [Litestar](https://pypi.org/project/litestar/) soon, as well as a [draft PR](https://github.com/getsentry/sentry-docs/pull/10880) to add Litestar to the list of integrations on that page.

The icon for the Starlite integration is the generic Python icon rather than an icon specific to Starlite. Starlite has been renamed Litestar. Various pages related to Litestar have icons that might be used:
- https://litestar.dev/
- https://docs.litestar.dev/latest/

It might be possible to reach out to the Litestar team on their [Discord](https://discord.gg/X3FJqy8d2j) or elsewhere to get an icon to use.

### Suggested Solution

Replace the generic Python icon used for the Starlite integration with an icon specific to Starlite. That icon can likely also be used for the upcoming Litestar integration docs.

**Comment by KellyWalker** [comment]
I reached out to the Litestar team on Discord. They pointed me to https://github.com/litestar-org/branding/ and suggested the attached SVG would probably be appropriate.

![Image](https://github.com/user-attachments/assets/c202251f-0c94-4603-8914-fc044001a00d)

**Comment by KellyWalker** [comment]
It seems 20x20 and 80x80 icons will need to be selected and added to https://github.com/getsentry/platformicons.

**Comment by antonpirker** [comment]
We have a PR in the `platformicons` project: https://github.com/getsentry/platformicons/issues/177
