### ISSUE TITLE
Incorrect usage of backtick emphasize entire paragraph in Breadcrumbs docs page

### ISSUE THREAD

**Issue by NoNameProvided** [getsentry/sentry-docs#10945]
### Steps to Reproduce

1. Open https://docs.sentry.io/platforms/javascript/guides/angular/configuration/integrations/breadcrumbs/
2. Go to the _"By default, the Sentry SDK wraps..."_ section
3. See that backticks are incorrectly used and result in an unexpected look

### Expected Result

Backticks are correctly used and only emphasize the correct words.

### Actual Result

Backticks are accidentally not closed and the entire section is emphasized.

**Comment by mydea** [comment]
This seems fixed to me now - I am closing this, thanks for reporting!
