### ISSUE TITLE
Filler DSN on docs

### ISSUE THREAD

**Issue by drguthals** [getsentry/sentry-docs#10952]
### Problem Statement

I *love* the fact that docs auto-fills the DSN and allows me to choose projects for ease of copy and paste. 

_However_ when I'm making a video, blog post, or live streaming and wanting to share the docs, I would like to be able to just put "YOUR_DSN" without having to edit after the fact.

### Solution Brainstorm

Would it be possible to add to the drop down "YOUR_DSN" as one of the options?

Happy to do this if someone can point me to where this is being auto-filled :)

**Comment by chargome** [comment]
Hey @drguthals, I think this handled in https://github.com/getsentry/sentry-docs/blob/master/src/components/codeContext.tsx :)

**Comment by drguthals** [comment]
OK - I was looking into this. If I'm not logged into Sentry I can just get "examplePublicKey":
![Image](https://github.com/user-attachments/assets/966a48fb-9aea-4e86-bdbe-1972fd855445)

Which basically solves for my use case. However, I feel like maybe the default should be "click to choose project" or something?

**Comment by chargome** [comment]
Yeah good point, I'll bring it up today!

**Comment by chargome** [comment]
We'll leave this as is since we already have the sign in note on top of every codeblock that uses this feature.
