### ISSUE TITLE
confusion about available javascript config options

### ISSUE THREAD

**Issue by raffomania** [getsentry/sentry-docs#1100]
the [js configuration docs](https://docs.sentry.io/error-reporting/configuration/?platform=javascript) say that `whitelistUrls` is not available for the js platform. Your [blogpost on reducing noise in js exceptions](https://blog.sentry.io/2017/03/27/tips-for-reducing-javascript-error-noise) recommends to use this option. Can I use it or not?

**Comment by dashed** [comment]
@raffomania the `whitelistUrls` config option as referenced in the blog post (written in 2017) refers to a legacy client called Raven: https://docs.sentry.io/clients/javascript/config/

The current JS SDK unfortunately doesn't support this option.

Hopefully this clarifies things.

**Comment by untitaker** [comment]
@dashed @raffomania the new SDK also supports this option. The issue is that "JavaScript" was selected in the docs page instead of "Browser JavaScript"

**Comment by dashed** [comment]
@untitaker Thanks for clarifying 😄
