### ISSUE TITLE
ExpressJS not catching errors

### ISSUE THREAD

**Issue by KyleAsaff** [getsentry/sentry-docs#1102]
I am copying the exact documentation (https://docs.sentry.io/platforms/node/express/):

```
const express = require('express');
const app = express();
const Sentry = require('@sentry/node');

Sentry.init({ dsn: 'REDACTED' });

// The request handler must be the first middleware on the app
app.use(Sentry.Handlers.requestHandler());

// All controllers should live here
app.get('/', function rootHandler(req, res) {
  res.end('Hello world!');
});

app.get('/debug-sentry', function mainHandler(req, res) {
  throw new Error('My first Sentry error!');
});

// The error handler must be before any other error middleware and after all controllers
app.use(Sentry.Handlers.errorHandler());


app.listen(3000);
```

and pointing my browser to http://localhost:3000/debug-sentry and sentry is not capturing my error. I can throw an error outside the route and it will capture it but it will not capture it if I throw an error inside the route.

**Comment by KyleAsaff** [comment]
Fixed it.

`Filter out events coming from localhost`

was turned on in the project.

**Comment by dashed** [comment]
@KyleAsaff glad you're able to resolve it! 👏 

Totally optional, but would you be open to send a pull-request to add a note about this? It may help other folks in the future for their local Sentry setups 👍

**Comment by KyleAsaff** [comment]
@dashed done

https://github.com/getsentry/sentry-docs/pull/1103
