### ISSUE TITLE
Circular Link on DT docs

### ISSUE THREAD

**Issue by drguthals** [getsentry/sentry-docs#11037]
### Core or SDK?

Platform/SDK

### Which part? Which one?

Distributed Tracing on Python 

### Description

The link on this page: https://github.com/getsentry/sentry-docs/blob/master/platform-includes/distributed-tracing/how-to-use/python.mdx

Links back to that page.

Live it's here: https://docs.sentry.io/platforms/python/tracing/trace-propagation/#how-to-use-distributed-tracing

### Suggested Solution

I'm not sure where this should be linked to, but maybe https://docs.sentry.io/platforms/python/tracing/

I'm happy to do that if there is agreement that is where we should link to

**Comment by antonpirker** [comment]
As this link points to the page currently on and the suggested link to "tracing" is right below that list of frameworks, I just removed the link in the linked github issue.
