### ISSUE TITLE
API Documentation Error: /api/releases/delete-organization-release-details/

### ISSUE THREAD

**Issue by z3us94** [getsentry/sentry-docs#1105]
I am not able to delete a release, im setting content type header, and authorization as well. But the request returns only 404. what is the reason for this ? 

full url as below,
https://sentry.io/api/0/organizations/{organization_slug}/releases/{version}

**Comment by dashed** [comment]
@z3us94 are you trying to delete a release on sentry.io?

**Comment by z3us94** [comment]
> @z3us94 are you trying to delete a release on sentry.io?

@dashed yeah. My situation is there can be situations where there will multiple builds from the same version. In that i case i want to be able to delete artifacts or the whole release.

**Comment by z3us94** [comment]
@dashed Any updates ?

**Comment by PeloWriter** [comment]
This link to archiving a release may be helpful - https://docs.sentry.io/product/releases/usage/archive-release/

Closing. Please use the forum to ask product questions, keeping the issues here focused on Sentry docs. Thanks very much.
