### ISSUE TITLE
Document de.sentry.io domain for EU organisations.

### ISSUE THREAD

**Issue by rodolfoBee** [getsentry/sentry-docs#11058]
### Core or SDK?

Core Sentry product

### Which part? Which one?

https://docs.sentry.io/api/

### Description

The current API docs make no mention to the de.sentry.io domain that needs to be used to work with organisations hosted in the EU. 

### Suggested Solution

Document the usage of de.sentry.io for EU hosted organisations.

**Comment by sentaur-athena** [comment]
Adding a page to api docs introducing de makes sense to me. Maybe actually the first page? https://docs.sentry.io/api/
