### ISSUE TITLE
Laravel documentation unclear about config/sentry.php full capabilities

### ISSUE THREAD

**Issue by mfn** [getsentry/sentry-docs#1109]
Hi,

I just had an epiphany I wanted to share and gauge feedback.

I learned that the PHP sentry SDK received a the feature for more flexible serialization ( https://github.com/getsentry/sentry-php/issues/316 ).

I'm using https://github.com/getsentry/sentry-laravel and went to https://github.com/getsentry/sentry-docs/blob/master/src/collections/_documentation/platforms/php/laravel.md to learn how to use this feature, but nothing was found.

Then I came to understand that in `\Sentry\Laravel\ServiceProvider::configureAndRegisterClient` the following code means that _everything_ in Laravels `config/sentry.php` actually goes to configuring the client:
```php
            $userConfig = $this->getUserConfig();

            // We do not want this setting to hit our main client because it's Laravel specific
            unset(
                $userConfig['breadcrumbs'],
                // this is kept for backwards compatibilty and can be dropped in a breaking release
                $userConfig['breadcrumbs.sql_bindings']
            );

            $options = \array_merge(
                [
                    'environment' => $this->app->environment(),
                    'prefixes' => [$basePath],
                    'project_root' => $basePath,
                    'in_app_exclude' => [$basePath . '/vendor'],
                ],
                $userConfig,
                [
                    'integrations' => $this->getIntegrations(),
                ]
            );

            $clientBuilder = ClientBuilder::create($options);
```
That's a pretty big deal (to me at least :smile:) but when I head over to https://github.com/getsentry/sentry-docs/blob/master/src/collections/_documentation/platforms/php/laravel.md , this fact isn't really mentioned.

But I think it's _really_ useful that people are aware of it. Or it's written somewhere in big letters and I just missed it.

The Laravel dosc already cover a wide range so I didn't wanted to create a PR out of the blue but first wanted to ask, because maybe I missed it?

Thanks!
```

**Comment by stayallive** [comment]
This would probably be a good addition indeed to add as a note somewhere... not sure where or how since I guess this also would be the same for Symfony for example.

**Comment by mfn** [comment]
Ah! Not using Symfony so wasn't ware of this, but definitely makes sense.

Where would a common place make sense? And so that if you're just reading the Laravel/Symfony docs, one would be aware of it?

OTOH, if it's just a small stanza it might not hurt being a dupe:
> Note: the whole configuration is passed to the Sentry ClientBuilder and therefore accepts all regularly documented configuration options.

🤔

**Comment by stayallive** [comment]
Hey @mfn bit late but I just noticed this issue, a few weeks ago I published some changes to the Laravel docs that should make this more apparent that all options from the base SDK are supported in the Laravel `sentry.php` config file.

> https://docs.sentry.io/platforms/php/laravel/#configuration

**Comment by mfn** [comment]
Nice, LGTM, thanks!
