### ISSUE TITLE
Change Default Privacy Configuration so it is more explicit

### ISSUE THREAD

**Issue by sdzhong** [getsentry/sentry-docs#11116]
### Core or SDK?

Core Sentry product

### Which part? Which one?

https://docs.sentry.io/platforms/javascript/guides/react/session-replay/privacy/#privacy-configuration

### Description

The readability of this docs page https://docs.sentry.io/platforms/javascript/guides/react/session-replay/privacy/#privacy-configuration is confusing at a glance. 

The header is "Privacy Configuration" while the first code block reflects _changing_ the default configuration. 

![Image](https://github.com/user-attachments/assets/490c3d00-4cbd-472e-8098-cf5b3fc956d4)

### Suggested Solution

Recommend changing the header to `Changing Default Privacy Configuration`.

**Comment by mydea** [comment]
Hmm, can you clarify your problem? IMHO it makes sense for the example below "Privacy Configuration" to show how to configure privacy? No need to configure anything if you want the defaults, configuring something implies that it will change the defaults? 😅
