### ISSUE TITLE
Missing documentation about the SENTRY_PROFILER_BINARY_DIR and SENTRY_PROFILER_BINARY_PATH env variable

### ISSUE THREAD

**Issue by Jimmy89** [getsentry/sentry-docs#11128]
### Core or SDK?

Platform/SDK

### Which part? Which one?

@sentry/profiling-node

### Description

I was debugging errors from my webpack output (packing node_modules as well) for our lambda, as I received a missing `SENTRY_FILE.node` error.

After some debugging, I found out that the @sentry/profiling-node package dynamically lookup a compiled .node file, where the path can be set with SENTRY_PROFILER_BINARY_DIR or SENTRY_PROFILER_BINARY_PATH. However, I did not find any documentation within Sentry that these env variables exist.

### Suggested Solution

Document these two variables.

**Comment by JonasBa** [comment]
@Jimmy89 We intentionally did not document this as we do not really want to encourage the usage - in most cases this should never be used. Is this something that you need in your project?

**Comment by Jimmy89** [comment]
@JonasBa yes, as we used webpack to minimize our build (a copy of our node_modules and code exceeded the 50mb zip file limit), we used webpack to minimize our build (including the node_modules artifacts). We got errors from the sentry package which stated that the binaries could not be found within the build path location (running within the lambda environment). Therefore, I started digging into the code to find a way to patch the lookup path for the binary. Resulting into finding these env variables, including the `sentry-prune-profiler-binaries`. By using both (env and pruner) I managed to create a very minimal and working package in our lambda, without monkey-patching any code.

We used the [lambda layer](https://docs.sentry.io/platforms/javascript/guides/aws-lambda/install/), which should also have the binaries, but with the latest major version (v8) of Sentry EcmaScript code (which we use) are assigned to the NPM modules. In combination with a webpack build you must use those Sentry env variables. Therefore, I think it's good to document these, as it will help others.

**Comment by andreiborza** [comment]
Hi @Jimmy89, we have https://github.com/getsentry/sentry-javascript/issues/13049 in our backlog aiming to create a dedicated layer for Lambda, but didn't get to it yet.

This might still be nice to document tho @JonasBa wdyt?

**Comment by JonasBa** [comment]
@andreiborza yes, I'm adding the doc today. I planned on adding it yesterday, but ended up prioritizing other work.

**Comment by JonasBa** [comment]
Added the documentation in https://github.com/getsentry/sentry-docs/pull/11382
