### ISSUE TITLE
DDM docs - specify which plans have access to the feature

### ISSUE THREAD

**Issue by InterstellarStella** [getsentry/sentry-docs#11126]
### Core or SDK?

Core Sentry product

### Which part? Which one?

Metrics (DDM)

### Description

In the DDM docs, we do not specify which SaaS plans have access to Metrics. The Metrics beta is currently only available to customers on self-serve plans, not yet to customers on our Enterprise tier or sponsored accounts.

### Suggested Solution

Mention that customers on an Enterprise or Sponsored plan do not have access to this feature yet.

**Comment by stephanie-anderson** [comment]
Beta will be discontinued, will close this issue
