### ISSUE TITLE
Remove the requestHandler Express middleware from documentation

### ISSUE THREAD

**Issue by QuentinGprd** [getsentry/sentry-docs#11149]
### Core or SDK?

Platform/SDK

### Which part? Which one?

Express

### Description

The `Sentry.Handlers.requestHandler()` has been removed, but is still present in the documentation: [https://docs.sentry.io/platforms/javascript/guides/express/configuration/releases/#sessions](https://docs.sentry.io/platforms/javascript/guides/express/configuration/releases/#sessions)

### Suggested Solution

Remove or update the documentation regarding the _requestHandler_ Express middleware.

**Comment by mydea** [comment]
Hey, thank you for reporting this! We'll remove this.
