### ISSUE TITLE
robots.txt points to wrong sitemap

### ISSUE THREAD

**Issue by stephanie-anderson** [getsentry/sentry-docs#11164]
### Steps to Reproduce

A `robots.txt` should always contain a link to the page's sitemap. For our develop docs, the URL of the user facing docs is being used

See: 
https://develop.sentry.dev/robots.txt

### Expected Result

```
Sitemap: https://develop.sentry.dev/sitemap.xml
User-agent: *
```

### Actual Result

```
Sitemap: https://docs.sentry.io/sitemap.xml
User-agent: *
Disallow: /development-api/
```

**Comment by a-hariti** [comment]
I think we don't even need that `Disallow: /development-api/` rule @stephanie-anderson

**Comment by stephanie-anderson** [comment]
Yeah I also don't think it's necessary for any of the two sites :)
