### ISSUE TITLE
SDK Onboarding Feature Bar

### ISSUE THREAD

**Issue by stephanie-anderson** [getsentry/sentry-docs#11174]
Could use an adjusted background in dark mode:

![Image](https://github.com/user-attachments/assets/288cba52-1a4f-4922-9e8c-1ec024549729)

**Comment by a-hariti** [comment]
do you have something in mind?

I think it should remain semi transparent @stephanie-anderson

**Comment by stephanie-anderson** [comment]
Dark transparent background, instead of white transparent?
