### ISSUE TITLE
Transparent Image background

### ISSUE THREAD

**Issue by stephanie-anderson** [getsentry/sentry-docs#11175]
Home page hero image should be on transparent background, so it also works with dark mode:

![Image](https://github.com/user-attachments/assets/f6b03e1d-e837-481e-bd8d-cf95101334ec)

Same is true for some of the icons further below:

![Image](https://github.com/user-attachments/assets/41574f6d-ead8-4b11-b5f1-690626bac863)

**Comment by lizokm** [comment]
![Image](https://github.com/user-attachments/assets/f1ff287a-ea0f-481a-94a0-9826209ae2d6)



![Image](https://github.com/user-attachments/assets/2fda29cf-c2da-493d-b54d-1928e1dfe8fc)



![Image](https://github.com/user-attachments/assets/15abcbb5-3033-4c90-a88f-472ce3aa95f9)



![Image](https://github.com/user-attachments/assets/9e2962df-6bdb-466f-bd15-590034ce07c0)

**Comment by stephanie-anderson** [comment]
Amazing, thank you @lizokm!
