### ISSUE TITLE
Expandable component style issues in dark mode

### ISSUE THREAD

**Issue by stephanie-anderson** [getsentry/sentry-docs#11208]
Looks like the text color for the troubleshooting accordion titles needs a little adjustment in dark mode:

[Slack Message](https://sentry.slack.com/archives/C8H0BQRDJ/p1725353962666349?thread_ts=1725353962.666349&cid=C8H0BQRDJ)

**Comment by stephanie-anderson** [comment]
Lukas also wrote:

> ok so it seems to be only a problem on some pages with the Expandable component. It looks fine in the main JS [Troubleshooting](https://docs.sentry.io/platforms/javascript/troubleshooting/) page but is broken on the [Replay Troubleshooting](https://docs.sentry.io/platforms/javascript/session-replay/troubleshooting/) page.

**Comment by a-hariti** [comment]
can you check  #11199 ?
