### ISSUE TITLE
(CSS Bug) Italic Text is bold

### ISSUE THREAD

**Issue by lforst** [getsentry/sentry-docs#11203]
### Steps to Reproduce

Doing `_foo_` in the MDX makes the font bold which looks a bit odd.

![Image](https://github.com/user-attachments/assets/d02329a1-586d-4e9f-a625-caee558ce294)

### Expected Result

No bold font.

### Actual Result

Bold font. (500 weight)

**Comment by lforst** [comment]
Probably related to this change https://github.com/getsentry/sentry-docs/commit/b6e1a71f75ade8b68536550923310b21b6a2dcd3

**Comment by a-hariti** [comment]
it was introduced before that change @lforst , fixed now!
