### ISSUE TITLE
Page titles use the wrong variable

### ISSUE THREAD

**Issue by stephanie-anderson** [getsentry/sentry-docs#11219]
### Steps to Reproduce

I notices our platform docs must use the wrong frontmatter information when it comes to generating a pages' title.

### Expected Result

Should be "PHP"
![Image](https://github.com/user-attachments/assets/751aff31-10cc-491a-86c9-f05940fa14f0)

Should be ".NET"
![Image](https://github.com/user-attachments/assets/13d2508a-bb29-497e-ba42-3fddf90fabc8)

Should be "React Native"
![Image](https://github.com/user-attachments/assets/289d0a88-ef32-432a-8e2d-6c86b9669dfb)

**Comment by a-hariti** [comment]
is this related to the change you made to platform capitalisation @chargome ?

**Comment by chargome** [comment]
Shouldn't be, might be, I'll check

**Comment by chargome** [comment]
@stephanie-anderson  Ok this has been this way ever since, we want to get rid of the "Sentry for ..."?

**Comment by stephanie-anderson** [comment]
I don't think that's related - see React Native. I think it's simply using the wrong data from frontmatter (should use the `title`)

![Image](https://github.com/user-attachments/assets/ca283002-9f34-4fdb-8e56-0d1e49a9bbd0)

**Comment by stephanie-anderson** [comment]
@chargome no, this should stay as it is

`<title>.NET | Sentry for Dotnet</title>`

should become

`<title>.NET | Sentry for .NET</title>`

**Comment by stephanie-anderson** [comment]
I had a look at the PR @chargome - I think a sustainable solution would be changing what we pass into this function:
https://github.com/getsentry/sentry-docs/blob/a61c058a5d94860eecd98825d6fddfeedb16f5d3/app/%5B%5B...path%5D%5D/page.tsx#L145

where it shouldn't be the `name` but the `title`.

Otherwise we will have to put all platforms in those conditions, which does not make sense since we have the correct information available anyways :)

**Comment by chargome** [comment]
Oh lol you are right I didn't think about that, I'll refactor it

**Comment by stephanie-anderson** [comment]
Thank you! :D
