### ISSUE TITLE
applicationKey in next.js section is incorrect

### ISSUE THREAD

**Issue by saiichihashimoto** [getsentry/sentry-docs#11213]
### Steps to Reproduce

1. [The docs](https://docs.sentry.io/platforms/javascript/guides/nextjs/configuration/filtering/#using-thirdpartyerrorfilterintegration) show how to include `applicationKey` into `sentryWebpackPlugin`, but Sentry is setup in Next.js with `withSentryConfig`.
2. `withSentryConfig` is supposed to allow the webpack builder's options directly, but typescript is upset with me including `applicationKey` into the build config.

### Expected Result

1. [The docs](https://docs.sentry.io/platforms/javascript/guides/nextjs/configuration/filtering/#using-thirdpartyerrorfilterintegration) should show where one includes `applicationKey` into `withSentryConfig` for it to work when using `Sentry.thirdPartyErrorFilterIntegration` in the `sentry.client.config.ts`.
2. If it is indeed directly into `SentryBuildOptions`, then it's typings need to be corrected to allow for it.

### Actual Result

1. [The docs](https://docs.sentry.io/platforms/javascript/guides/nextjs/configuration/filtering/#using-thirdpartyerrorfilterintegration) show how to include `applicationKey` into `sentryWebpackPlugin`, but Sentry is setup in Next.js with `withSentryConfig`.
2. `withSentryConfig` is supposed to allow the webpack builder's options directly, but typescript is upset with me including `applicationKey` into the build config.

**Comment by saiichihashimoto** [comment]
Got it, that makes sense. So... How would I do this as it currently stands? Including it in the unstable config?

**Comment by lforst** [comment]
Yes, simply use `unstable_sentryWebpackPluginOptions.applicationKey`. It should have TS definitions even.
