### ISSUE TITLE
Missing documentation for `Sentry.metrics.timing`

### ISSUE THREAD

**Issue by jake** [getsentry/sentry-docs#11229]
### Core or SDK?

Platform/SDK

### Which part? Which one?

nodejs, javascript, aws-lambda, etc

### Description

The javascript SDK has support for the `Sentry.metrics.timing` methods but it isn't mentioned in the docs for any of the javascript SDKs. 

### Suggested Solution

add documentation for the `Sentry.metrics.timing` method to the relevant SDK docs that support it.

**Comment by mydea** [comment]
Hey,

Metrics are being discontinued, so all of the docs for it will go away in the near future. You can read more about this here: https://sentry.zendesk.com/hc/en-us/articles/26369339769883-Metrics-Beta-Coming-to-an-End
