### ISSUE TITLE
Mention that sentry needs to be initialised before adding context for sentry native

### ISSUE THREAD

**Issue by moritzsur** [getsentry/sentry-docs#11242]
### Core or SDK?

Platform/SDK

### Which part? Which one?

Sentry Native

### Description

Not yet mentioned in the native docs

### Suggested Solution

Change the code example from

```
#include <sentry.h>

sentry_value_t character = sentry_value_new_object();
sentry_value_set_by_key(character, "name", sentry_value_new_string("Mighty Fighter"));
sentry_value_set_by_key(character, "age", sentry_value_new_int32(19));
sentry_value_set_by_key(character, "attack_type", sentry_value_new_string("melee"));
sentry_set_context("character", character);
```

to

```
#include <sentry.h>

//...
//sentry_init(options);

sentry_value_t character = sentry_value_new_object();
sentry_value_set_by_key(character, "name", sentry_value_new_string("Mighty Fighter"));
sentry_value_set_by_key(character, "age", sentry_value_new_int32(19));
sentry_value_set_by_key(character, "attack_type", sentry_value_new_string("melee"));
sentry_set_context("character", character);
```

**Comment by JoshuaMoelans** [comment]
Hi, thanks for raising this issue. On our [page about configuring the native SDK](https://docs.sentry.io/platforms/native/#configure) we mention that this configuration should happen as early as possible within your application. So, by the time you add context, `sentry_init(options)` should have been called already.

I can see how this is easy to overlook, but to avoid clutter in our other docs pages we don't show this initialization on every code snippet.
