### ISSUE TITLE
Changelog out of date

### ISSUE THREAD

**Issue by govert-co-co** [getsentry/sentry-docs#1129]
The changelog mentions that Sentry 9.1 is still unreleased.

**Comment by splattael** [comment]
Maybe, https://docs.sentry.io/server/changelog/ could also link to https://github.com/getsentry/sentry/blob/master/CHANGES :thinking:

**Comment by BYK** [comment]
Yup, we have neglected that page sorry. Will fix soon! :)

**Comment by BYK** [comment]
We no longer have this page and https://github.com/getsentry/sentry/blob/master/CHANGES, which is the replacement (or the original changelog) is at least up-to-date regarding versions.
