### ISSUE TITLE
Platform redirect is broken

### ISSUE THREAD

**Issue by rodolfoBee** [getsentry/sentry-docs#11342]
### Steps to Reproduce

1. Go to this page: https://docs.sentry.io/concepts/data-management/event-grouping/
2. Click on the link for SDK fingerprinting

### Expected Result

See the list of SDK that support that feature and be able to select one of them to see the specific docs. 

### Actual Result

Get the follow error:
Application error: a client-side exception has occurred (see the browser console for more information).

In the console: 
Error: An error occurred in the Server Components render. The specific message is omitted in production builds to avoid leaking sensitive details. A digest property is included on this error instance which may provide additional details about the nature of the error.

**Comment by chargome** [comment]
Can't reproduce, has probably been fixed!
