### ISSUE TITLE
Search leads to 404

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-docs#11391]
### Steps to Reproduce

Searching for `searchable` on: https://develop.sentry.dev/getting-started/ 

Shows `https://develop.sentry.dev/concepts/search/searchable-properties/` as a result, which leads to 404:

![Image](https://github.com/user-attachments/assets/8ad2277f-1f9c-48b0-b0c2-e80fc1de2f5f)
![Image](https://github.com/user-attachments/assets/649ff353-85f7-4a9e-819e-68e1dbedd728)

### Expected Result

no 404

### Actual Result

404

**Comment by chargome** [comment]
That is strange since this should point to a docs.sentry.io page – thanks for raising that!
