### ISSUE TITLE
DSN Selection is unreadable when using dark mode

### ISSUE THREAD

**Issue by malwilley** [getsentry/sentry-docs#11419]
### Steps to Reproduce

1. Use dark mode
2. Click a DSN selector (I did so on this page: https://docs.sentry.io/platforms/native/guides/minidumps/)

### Expected Result

Dropdown should be readable

### Actual Result

Colors are off:

![Image](https://github.com/user-attachments/assets/a108ad1e-6437-427b-8fc2-ccac11a83e37)

**Comment by chargome** [comment]
@malwilley we currently can't reproduce this, do you have any active browser extension – or maybe a cached stylesheet?

**Comment by malwilley** [comment]
Strange! I've tried again in incognito and in a different browser I never use (Safari) and it looks the same for me everywhere. Looking at the applied styles, I only see emotion classes.

**Comment by timfish** [comment]
I can see this for the org selector:
https://docs.sentry.io/platforms/javascript/guides/astro/#add-readable-stack-traces-to-errors

![Image](https://github.com/user-attachments/assets/995c0c67-b56a-4739-9457-cb58e18d0060)
