### ISSUE TITLE
Conditional changelog deployments

### ISSUE THREAD

**Issue by chargome** [getsentry/sentry-docs#11437]
### Problem Statement

Currently changelog is build on every push to the repo.

### Solution Brainstorm

Maybe use skip-build.sh for detecting changelog diffs and only deploy it conditionally

**Comment by a-hariti** [comment]
its output depends on outside input (posts in database), so not visible to the script

on the other hand, it builds fast, so not sure if we should bother?

**Comment by chargome** [comment]
Yeah the other day this blocked all docs deployments bc there was some issue in the changelog. I think we can safely just build the changelog whenever there is a change in apps/changelog
