### ISSUE TITLE
Update custom instrumentation docs wrt new trace-/span-id validation

### ISSUE THREAD

**Issue by supervacuus** [getsentry/sentry-docs#11504]
### SDK

Native SDK

### Description

page to update: https://docs.sentry.io/platforms/native/tracing/trace-propagation/custom-instrumentation/
related PR: https://github.com/getsentry/sentry-native/pull/1046

**Comment by JoshuaMoelans** [comment]
closed in https://github.com/getsentry/sentry-docs/pull/11511
