### ISSUE TITLE
Show links to `previous` and `next` pages

### ISSUE THREAD

**Issue by stephanie-anderson** [getsentry/sentry-docs#11572]
### Description

Add buttons for easier navigation through docs at the bottom of each page (for `previous` and `next` pages), similar to this one here:

![Image](https://github.com/user-attachments/assets/57455de9-821b-4055-b623-d7a5d5736abe)

Source: https://docusaurus.io/docs/static-assets

### Requirements

1. General:

- Despite the screenshot below, wording should be `Previous` and `Next`
- Buttons should render the page's title

2. Automatically generate `previous` and `next` buttons:
- The docs index page (`/`) does neither have `previous` nor `next` buttons
- The first child of a parent node should render the parent as its `previous` page
- The last child of a parent node should render the next sibling of its parent as `next` page
- If that parent does not have a next sibling, no `next` page link should be rendered

![Image](https://github.com/user-attachments/assets/1c526870-a62c-4e55-989b-fb7e61b963c9)

- If the page is a direct child of the index page (`/`), previous should point to the index page (`/`)

![Image](https://github.com/user-attachments/assets/f587b894-c32b-444c-9e0d-535fe5a23e10)

3. It should be possible to manually overwrite what `previous` and `next` should be for a given page. For example, for some JavaScript SDKs we have 3 different ways for users to install the SDK. We don't want to guide users from one install method to the others, but instead might guide them next to some configuration pages.

**Comment by chargome** [comment]
@stephanie-anderson do we want this on dev docs?
