### ISSUE TITLE
"First Input Display" should be "First Input Delay"

### ISSUE THREAD

**Issue by JohnMealy23** [getsentry/sentry-docs#11601]
### SDK

JavaScript SDK

### Description

[This section](https://docs.sentry.io/product/insights/web-vitals/web-vitals-concepts/#interaction-to-next-paint-inp) notes a new metric, "First Input Display (FID)".  I believe "display" is a typo here, as numerous other entries on the page are for "First Input **Delay**"

### Suggested Solution

Change "Display" to "Delay" here, and review the remaining docs for a similar typo.

Thank you.

**Comment by coolguyzone** [comment]
Thanks for catching this @JohnMealy23 , we have a PR in to fix: https://github.com/getsentry/sentry-docs/pull/11706
