### ISSUE TITLE
API Documentation Error: /api/projects/

### ISSUE THREAD

**Issue by keradus** [getsentry/sentry-docs#1161]
Hi !
Docs for experimental API is great, but I found an endpoint that is not documented:
`api/0/projects/{organisation}/{example_project}/rules/{rule}/`

Can we add docs for it, please?

**Comment by keradus** [comment]
such a great discussion! ;) not all at once, easy ;)

**Comment by ingvarch** [comment]
Hi there! +1 
Could you add information about RULEs in documentation ?

**Comment by untitaker** [comment]
you have my acknowledgement :) please just 👍 the issue so we can prioritize things

API docs will always be incomplete, only the most interesting endpoints are documented in docs.sentry.io
