### ISSUE TITLE
Org selection dropdown for auth token in dark mode

### ISSUE THREAD

**Issue by timfish** [getsentry/sentry-docs#11630]
### Steps to Reproduce

Go here in dark mode:
https://docs.sentry.io/platforms/javascript/guides/astro/#add-readable-stack-traces-to-errors

### Expected Result

Should use correct theme

### Actual Result

![Image](https://github.com/user-attachments/assets/f7deb49f-c27a-4c8a-8eee-e85b67811cbc)

**Comment by stephanie-anderson** [comment]
@timfish, I think this has [been fixed](https://github.com/getsentry/sentry-docs/issues/11419), could you confirm real quick? cc @a-hariti

**Comment by timfish** [comment]
No, this still displays like the top post for me today. 

It looks like the issue **was** fixed in the DSN selector but this UI component is for auth token generation.

**Comment by a-hariti** [comment]
any idea on how to repro this @timfish ?

**Comment by timfish** [comment]
I can reproduce this by: 
- Being logged in and a member of 3 orgs
- Go [here](https://docs.sentry.io/platforms/javascript/guides/astro/#add-readable-stack-traces-to-errors) and click `Click to generate token`
- Light mode dropdown appears

Let me know if there's anything else I can do to help or debug. 

Before opening this issue I pulled this repo and ran in dev mode and could reproduce this issue there too.
