### ISSUE TITLE
Duplicate titles on Arcade embeds

### ISSUE THREAD

**Issue by a-hariti** [getsentry/sentry-docs#11714]
### Problem Statement

some (all?) iframes from arcade.software have duplicate `title` attributes and that results in a lot of noise on build logs like this:

```
▲ [WARNING] Duplicate key "title" in object literal [duplicate-object-key]

    _mdx_bundler_entry_point-65616264-ad49-45a8-9f26-185df5a53898.mdx:126:8:
      126 │         title: "Trace View - Tabbing"
          ╵         ~~~~~

  The original key "title" is here:

    _mdx_bundler_entry_point-65616264-ad49-45a8-9f26-185df5a53898.mdx:111:8:
      111 │         title: "Sentry",
          ╵         ~~~~~
```

### Solution Brainstorm

dedupe titles

is there a heuristic to know which one to keep? (first or second) or do we have to decide on a case by case basis?

cc @stephanie-anderson

**Comment by stephanie-anderson** [comment]
I would remove all the title attributes of iframes, on the [trace view](https://docs.sentry.io/concepts/key-terms/tracing/trace-view/) page are three iframes, those titles are irrelevant

**Comment by stephanie-anderson** [comment]
I think we should also create a component for those embeddings - but we can do that in a separate PR

**Comment by a-hariti** [comment]
yeah, will remove lots of redundancy 👍
