### ISSUE TITLE
Profiling is incorrectly set to browser profiling for several JS SDKs

### ISSUE THREAD

**Issue by wif70068** [getsentry/sentry-docs#11785]
### SDK

JavaScript SDK

### Description

The documentation (https://docs.sentry.io/platforms/javascript/guides/capacitor/profiling/) isn't about Sentry Capacitor but about Sentry Browser with a few "sentry/browser" replaced with "sentry/capacitor".

Does profiling actually work with Sentry Capacitor?

**Comment by chargome** [comment]
Hey @wif70068 thanks for pointing that out, we'll fix that.
