### ISSUE TITLE
🔗 404 Error

### ISSUE THREAD

**Issue by nealio82** [getsentry/sentry-docs#11814]
### URL

docs.sentry.io/pricing/quotas/org-stats/

### Additional Info

I clicked the link for 'Org Stats' on this page, https://grafana.com/grafana/plugins/grafana-sentry-datasource/, under the 'Known Limitations' header.

I should have been sent to https://docs.sentry.io/product/accounts/quotas/org-stats/, but my request seems to have been redirected to docs.sentry.io/pricing/quotas/org-stats/ instead, and I received a 404

:'(

**Comment by a-hariti** [comment]
Thank you for reporting @nealio82
