### ISSUE TITLE
Fix Typo in Angular SDK Docs

### ISSUE THREAD

**Issue by JayDarjiAubergine** [getsentry/sentry-docs#11856]
### SDK

JavaScript SDK

### Description

https://docs.sentry.io/platforms/javascript/guides/angular/migration/v7-to-v8/#conflicting-dependency-versions-with-bundler-plugins

In this section of [Conflicting Dependency Versions with Bundler Plugins](https://docs.sentry.io/platforms/javascript/guides/angular/migration/v7-to-v8/#conflicting-dependency-versions-with-bundler-plugins), we have one line saying

> The Sentry JavaScript Bundler Plugins (@sentry/webpack-plugin, @sentry/vite-plugin, @sentry/esbuild-plugin, @sentry/rollup-plugin) used to depend on certain Sentry SDK packages on version 7 **wich** may clash with version 8 of the SDK.

Where we can recognise the type of **wich**, that can be corrected to **which**.

### Suggested Solution

> The Sentry JavaScript Bundler Plugins (@sentry/webpack-plugin, @sentry/vite-plugin, @sentry/esbuild-plugin, @sentry/rollup-plugin) used to depend on certain Sentry SDK packages on version 7 **which** may clash with version 8 of the SDK.

Hope this is helpful!

**Comment by a-hariti** [comment]
Thanks for reporting @JayDarjiAubergine
