### ISSUE TITLE
Described API URLs do not match auto-generated schema

### ISSUE THREAD

**Issue by whitep4nth3r** [getsentry/sentry-docs#11854]
### SDK

Other

### Description

Relevant Discord thread: https://discord.com/channels/621778831602221064/1301836198355931220/1301836198355931220

## Affected pages:

API URLs described at the top of API pages including (but not limited to):

- https://docs.sentry.io/api/events/retrieve-an-issue/
- https://docs.sentry.io/api/events/remove-an-issue/

## The issue

URLs, e.g. `GET /api/0/issues/{issue_id}/` are used as an example of a URL to call.

Further down on the page, the docs state that each URL requires an `organization_id_or_slug`.

This is not represented in the URL.

---

I understand that the API docs are auto-generated from the annotations on API endpoint definitions inside the Sentry repo i.e. [here](https://github.com/getsentry/sentry/blob/1685d003f37d0103429fd74f903b7e9728fa6e70/api-docs/paths/events/issue-details.json#L321-L344).

**Comment by a-hariti** [comment]
I think this has to do with auto generated API docs more than authors

**Comment by Christinarlong** [comment]
Yeah, the API docs for retrieving an issue were not up to date. They are updated now to use `organization_id_or_slug`
