### ISSUE TITLE
🔗 404 Error

### ISSUE THREAD

**Issue by AlwinXue** [getsentry/sentry-docs#11881]
### URL

docs.sentry.io/server/installation/

**Comment by a-hariti** [comment]
Thanks for reporting @AlwinXue 

Can you provide some context where you found this link?

**Comment by AlwinXue** [comment]
From a document?, I was trying to upgrade Sentry from Version9 to 23, do
you have any idea how I can achieve that, or is there any document
containing the command I need to use?

**Comment by AlwinXue** [comment]
yes

**Comment by a-hariti** [comment]
@chargome 👀

**Comment by chargome** [comment]
The link now works, this was part of https://github.com/getsentry/sentry-docs/issues/11870
