### ISSUE TITLE
Throttles and Rate Limiting docs could be more verbose

### ISSUE THREAD

**Issue by loisaidasam** [getsentry/sentry-docs#1193]
Docs are a little light here:

https://docs.sentry.io/server/throttling/

Resources:

- https://forum.sentry.io/t/quotas-and-rate-limiting-projects-on-premise/220
- https://twitter.com/LoisaidaSam/status/1168979415507902464

**Comment by dashed** [comment]
Should be resolved in https://github.com/getsentry/sentry-docs/pull/1194
