### ISSUE TITLE
sentry upgrade gives error.

### ISSUE THREAD

**Issue by pkd809** [getsentry/sentry-docs#1196]
Sentry upgrade gives the following error ---

!! Configuration error: AttributeError: 'module' object has no attribute 'dir'

Done installation with python.

**Comment by pkd809** [comment]
Sentry webui not opening on port 9000 with an ec2 instance.

**Comment by untitaker** [comment]
This is not a useful bug report, and the correct repo would be sentry instead of sentry-docs.

**Comment by pkd809** [comment]
Sentry gives following error on its web UI.
![sentryerror](https://user-images.githubusercontent.com/43242987/64500237-0039c400-d2da-11e9-8a0f-e88d675f0a9c.png)
