### ISSUE TITLE
Platform mismatch when clicking on browser back-button

### ISSUE THREAD

**Issue by chargome** [getsentry/sentry-docs#11973]
### Steps to Reproduce

- go to https://docs.sentry.io/platforms/javascript/guides/node/opentelemetry/custom-setup/
- Select Angular in top left dropdown
- Browserback

### Expected Result

Node should be the selected platform in the sidebar (matching the url)

### Actual Result

Angular is still selected

**Comment by a-hariti** [comment]
it only happens on prod for some reason 🤔
