### ISSUE TITLE
Fix action field description in metric alert rule endpoint

### ISSUE THREAD

**Issue by rodolfoBee** [getsentry/sentry-docs#11985]
### Which part? Which one?

https://docs.sentry.io/api/alerts/create-a-metric-alert-rule-for-an-organization/

### Description

The docs say:
> actions: A list of actions that take place when the threshold is met. Set as an empty list if no actions are to take place.

But this is required. If not set, the user will get the error: Each trigger must have an associated action for the alert to trigger. 

### Suggested Solution

Explain it is required for each trigger.

**Comment by rodolfoBee** [comment]
https://github.com/getsentry/sentry/pull/81415

**Comment by ceorourke** [comment]
Thanks for the PRs, I just approved them. We recently made this change as rules with no actions are pointless

**Comment by rodolfoBee** [comment]
PRs merged
