### ISSUE TITLE
Add Issue Tracking Documentation

### ISSUE THREAD

**Issue by dcramer** [getsentry/sentry-docs#12]

**Comment by richardweiu** [comment]
I get an error when I invite member。
why I got this error??
the error is[Errno 111] Connection refused

**Comment by dcramer** [comment]
@richardweiu this issue has nothing to do with your question. Frankly, I'm starting to get annoyed with directing you to the appropriate places to get support.

**Comment by richardweiu** [comment]
I’m so sorry
I have put this question at Google group,but no one here,I’manxious
I don’t know what’s the problem,I can sent email yesterday,but fail today

原始邮件
发件人:David Cramernotifications@github.com
收件人:getsentry/sentry-docssentry-docs@noreply.github.com
抄送:richardweiuRichard934935@gmail.com
发送时间:2015年11月25日(周三) 15:20
主题:Re: [sentry-docs] Add Issue Tracking Documentation (#12)


@richardweiu this issue has nothing to do with your question. Frankly, I'm starting to get annoyed with directing you to the appropriate places to get support.
