### ISSUE TITLE
send_default_pii: what do the docs really recommend?

### ISSUE THREAD

**Issue by faassen** [getsentry/sentry-docs#1240]
In the Python docs:

```Sending users to Sentry will unlock many features,```

I want to unlock those features! I want to do this for Django, so I go there and read:

```
If you use django.contrib.auth and have set send_default_pii=True in your call to init, user data (current user id, email address, username) is attached to the event.
```

Awesome, all I have to do is turn on `send_default_pii` to True and I'm good to go. But:

```Sentry also excludes personally identifiable information (such as user ids, usernames, cookies, authorization headers, IP addresses) unless you set send_default_pii to True.```

Wait. I don't want to send authorization headers and cookies!

I go on and find this in the configuration section:

https://docs.sentry.io/error-reporting/configuration/?platform=python#send-default-pii

```
send_default_pii

If this flag is enabled, certain personally identifiable information is added by active integrations. Without this flag they are never added to the event, to begin with. If possible, it’s recommended to turn on this feature and use the server side PII stripping to remove the values instead.
```

Okay, what's server side PII stripping? I assume it the same as server-side PII *scrubbing* - I recommend you use that term consistently in the docs and link to it.

https://docs.sentry.io/data-management/sensitive-data/

```
We recommend filtering or scrubbing sensitive data within the SDK, so that data is not sent with the event, and also configuring server-side scrubbing to ensure the data is not stored.
```

This seems wise; better not send the information in the first place. But wait? The SDK documentation just told me to send this data... And I want to unlock features?

So are you recommending we turn *on* `send_default_pii` or are you recommending we turn it *off* to ensure data is not sent?

I think that would be best is to *only* send the minimum information (which user) to unlock the Django features, but *not* to send any other authorization headers like password tokens along. I guess I'm off on my own for that, but it would be helpful if the documentation clearly told me so.

**Comment by faassen** [comment]
After going through the Python SDK (wsgi shared, wsgi, Django) I suspect what I really want to do is turn `send_default_pii` on, but do application-specific scrubbing in `before_send`. If that's correct, the documentation may want to mention that in the right places.

**Comment by untitaker** [comment]
@faassen 

Think of it this way:

* The default `send_default_pii=False` is as safe as it gets (also for us from a legal perspective), but it omits a lot of stuff that is useful
* `send_default_pii=True` "opens the floodgates" (first decision) and requires you to think about what data you really want to send to Sentry (second decision)
* We cannot give you advice on either decision as we do not know your privacy policy (it would also be way too close to being legal advice)

I believe the docs do need some love here, but ultimatively we cannot give a simple answer to "which option do I want", otherwise there would be no configuration option.

**Comment by faassen** [comment]
I realize you can't answer what option anyone in particular would want, but my goal here really was to improve your documentation by giving feedback. :)

I left a few comments on the PR itself.

**Comment by untitaker** [comment]
I recognize the feedback, and believe that we can better link the separate pages into one "narrative". I'll make some changes to the Sensitive Data page too.
