### ISSUE TITLE
Rails documentation for config.action_dispatch.show_exceptions

### ISSUE THREAD

**Issue by rossta** [getsentry/sentry-docs#126]
Opening for discussion. I found the docs for Rails configuration a bit confusing. https://docs.sentry.io/clients/ruby/integrations/rails/#configuration

A new Rails app in recent versions (I tested 4.2.8 and 5.1), the default settings for `config.config.action_dispatch.show_exceptions` are set to `true`, so I don't understand the comment in the code snippet from the docs:

> `config.action_dispatch.show_exceptions = false # this is the default setting in production`

I could be mistaken but I believe, unless developers have control over their web server configuration settings, a consequence of setting this value to `false` could be that pretty error pages are no longer served in production environments. This would happen for vanilla Rails apps on Heroku, [for example](http://stackoverflow.com/questions/25468529/rails-app-on-heroku-status-500-error-blank-white-page/25540243). This may not be common knowledge, so perhaps a note or even a sample web server configuration would be helpful.

I'm also not sure whether this config change is even necessary depending on the version of the sentry and rails gems being used.

Or... am I missing something?

cc @nateberkopec

**Comment by nateberkopec** [comment]
Give me your GORUCO speaker slot and I'll answer!

You're absolutely right, this documentation is out of date (and wasn't ever correct, I think, about that setting being false in prod). What we actually do no is just patch ShowExceptions or DebugExceptions, so you don't have to remove those middlewares: https://github.com/getsentry/raven-ruby/blob/master/lib/raven/integrations/rails.rb#L50

**Comment by nateberkopec** [comment]
Closing with https://github.com/getsentry/raven-ruby/commit/4d9f00a5242009eb995f51bfdde4e99cb7320632

**Comment by rossta** [comment]
Ha! Trade you for RailsConf? 

Module prepending as inheritance... nice bit of ruby magic in there!
