### ISSUE TITLE
API Documentation: Create Deploy Not Working

### ISSUE THREAD

**Issue by kelsonm** [getsentry/sentry-docs#1273]
I'm making a `POST` request to Sentry, using the API endpoint: `/api/0/organizations/{organization_slug}/releases/{version}/deploys/`

In order to let Sentry know, once a release as being published (deployed). Where the `{organization_slug}` and `{version}` are my organisation and release number respectively. For the request body, I'm simple passing the environment name, exactly as it appears on Sentry.

I'm using powershell to achieve this, since I'm simple adding a step to my company CD (Octopus).

However, this doesn't seem to be working, even though the request response returns success every time.

Can someone help me with this? Is there something not right with the current documentation or is there something I might be missing on my request?

**Comment by PeloWriter** [comment]
Note that the forum is the best spot to ask questions about implementation. Closing this, but please reach out in the forum if you're still experiencing issues.
