### ISSUE TITLE
Missing example in `SDK Fingerprinting`

### ISSUE THREAD

**Issue by stayallive** [getsentry/sentry-docs#1289]
> https://docs.sentry.io/data-management/event-grouping/sdk-fingerprinting/#group-errors-more-aggressively

The text indicates there should be an example but I don't see one 😄 

![image](https://user-images.githubusercontent.com/1090754/67501121-02869080-f684-11e9-888f-0497fb66c6db.png)

**Comment by untitaker** [comment]
thanks, opened pr
