### ISSUE TITLE
clarifying of 'release' and 'dist' in react native docs

### ISSUE THREAD

**Issue by schumannd** [getsentry/sentry-docs#1349]
the example [there](https://docs.sentry.io/platforms/react-native/) is the following:

```
Sentry.setRelease('release');
Sentry.setDist('dist');

```

I think this could be improved by displaying actual values for "release" or "dist".

**Comment by SrMouraSilva** [comment]
A commentary about it https://github.com/getsentry/sentry-react-native/issues/516

**Comment by PeloWriter** [comment]
Closing as this has been resolved in the linked issue.
