### ISSUE TITLE
Clarify desired behaviour on unified API Scope::remove* methods

### ISSUE THREAD

**Issue by brunowowk** [getsentry/sentry-docs#1407]
On [the unified API docs about the Scope](https://github.com/getsentry/sentry-docs/blob/89a05812f02a66b31c12c0a2910e26dca9a17dbb/src/collections/_documentation/development/sdk-dev/unified-api.md#scope) the text regarding methods to remove context data is not 100% clear on whether those methods should clear all the data from the respective context or if they should clear only specified keys.

For instance:

> - `scope.set_user(user)`: Shallow merges user configuration (`email`, `username`, …).  Removing user data is SDK-defined, either with a `remove_user` function or by passing nothing as data.

Should it be `remove_user(key)` or just `remove_user()`

>- `scope.set_extra(key, value)`: Sets the extra key to an arbitrary value, overwriting a potential previous value. Removing a key is SDK-defined, either with a `remove_extra` function or by passing nothing as data.

Same thing. Should it be `remove_extra(key)` or `remove_extra()`?

As this makes for some discussion on SDK repos, I think it would be best to clarify the spec. ✌

IMHO it would make sense to have `clear*` methods clearing the whole context to be consistent with `scope.clear()` and `scope.clear_breadcrumbs()`, and then `remove*` methods would serve to unset specific keys. WDYT?

**Comment by HazAT** [comment]
So if the language allows it, we prefer `setUser(undefined)` over `removeUser()`, for the sole reason the not have another public function.
Same of extra and everything else.

Breadcrumbs are the exception because you can never access all the "collection" of breadcrumbs and just add them, so you need to be able to clear them.

Hope that makes sense.

**Comment by ste93cry** [comment]
I don't like the fact that `setUser` (or `setTag` or whatever else) must accept `null`/`undefined` to unset an item from a context as it's not clear enough what will happen behind the scene (being a setter the first thing I would think as an user is that I'm going to set that property to `null`, not that I'm gonna unset it). I also had a look at some other SDK (Go and Python) and they both have the `removeXXX` method for nearly all context types, so to me it seems that the way to go is adding that method and normalize this API for all contexts

**Comment by brunowowk** [comment]
I agree with @ste93cry...passing null/undefined/empty array to `setUser` is kinda cryptic. I don't think it's worth it having it behave like that just to keep from having the symmetric `remove` public method.

Also, having a mixed type on the props leads to code that's harder to maintain. It may be ok to mix types on dynamically-typed languages like javascript, but not so much on strict-typed languages, so we would be better off ecosystem-wise with well-defined parameter types on that API.
