### ISSUE TITLE
Sentry.showReportDialog() gives 403 forbidden.

### ISSUE THREAD

**Issue by hiteshchaudhari-tudip** [getsentry/sentry-docs#1440]
I'm using the '@sentry/browser' with ReactJS. And have added a link on click of which 'Sentry.showReportDialog()' function is called. But the 'https://sentry.io/api/embed/error-page/?dsn=https://{key}@sentry.io/{code}&name={name}&email={email}&eventId={eventId}' provides 403 error.

Any help would be appreciated.

**Comment by BYK** [comment]
Hi @hiteshchaudhari-tudip - have you tried contacting our support?
