### ISSUE TITLE
Xcode 11 / Ionic 3 / Sentry - Archive: Ipa processing failed  

### ISSUE THREAD

**Issue by sarias980** [getsentry/sentry-docs#1472]
I found a problem if you update the xcode 10 to the 11, If you do this is not possible generate a ipa whit the proyect. I searched in internet and I saw the porblem are realeted with the freamwork and 
in how it is included in the ios project, so in my case I only have a Sentry, any idea about how I can solved this problem ?
\
![Captura de pantalla 2020-01-30 a las 15 51 46](https://user-images.githubusercontent.com/32466364/73460284-88e3fa00-4378-11ea-806d-442a79ec3bd7.png)

![j826M](https://user-images.githubusercontent.com/32466364/73460362-a5803200-4378-11ea-9a8e-ce2cd638520f.png)

**Comment by bhandaribhumin** [comment]
any progress?

**Comment by bhandaribhumin** [comment]
@sarias980  any solution bro?

**Comment by InSantoshMahto** [comment]
### I able to resolve the issue using following steps:-
LINK:- [DOCS](https://docs.sentry.io/platforms/javascript/guides/cordova/)

1. Open project into Xcode
2. Select on target [APP_NAME] -> Build Phase
3. Click on + (PLUS ICON) -> SELECT New Run Script Phase and pass the code 
[code 1st block](https://docs.sentry.io/platforms/javascript/guides/cordova/#run-script-phase)

4. Again Click on + (PLUS ICON) -> SELECT New Run Script Phase and pass the code
[code 2st block](https://docs.sentry.io/platforms/javascript/guides/cordova/#run-script-phase)

screenshots:-

![Screenshot 2021-01-04 at 6 26 06 PM](https://user-images.githubusercontent.com/29502453/103539602-6169ab80-4ebe-11eb-88e4-863cd3e6d5ca.png)

![Screenshot 2021-01-04 at 6 28 47 PM](https://user-images.githubusercontent.com/29502453/103539755-9aa21b80-4ebe-11eb-9244-e37d1615e14d.png)
