### ISSUE TITLE
Java SDK Read Timeout option should be added in Timeout paragraph

### ISSUE THREAD

**Issue by mznet** [getsentry/sentry-docs#1506]
In [Java SDK Timeout](https://github.com/getsentry/sentry-docs/blob/master/src/collections/_documentation/clients/java/config.md#timeout-advanced) paragraph, it just only introduces `timeout` which means **connection timeout**, but `readtimeout` option isn't introduced in the paragraph. This option is very important to configure SDK and should be added in this paragraph.

**Comment by marandaneto** [comment]
@maciejwalkowiak maybe still worth it? SentryOptions contains both indeed
