### ISSUE TITLE
Document the /api/<projectId>/store endpoint

### ISSUE THREAD

**Issue by OssiPesonen** [getsentry/sentry-docs#1542]
Is the `/api/<projectId>/store` endpoint documented at all?

I went through the PHP SDK code to figure out what endpoint it uses to send an issue to. I did this because we have an enterprise level application that we're implementing Sentry to and we want operational stability. If Sentry has any latency, or it is down, this will reflect on any requests being made by the clients. It's unacceptable. We need to be able to deliver errors to Sentry without it affecting client performance meaning we have to store them on a disk and deliver them through a separate pipeline.

Anyway, I couldn't find any documentation regarding `/api/<projectId>/store`. It would be really helpful if it were documented as `Create an issue` inside the documentation explaining what kind of payload the endpoint can receive. Now we propably have to do some digging through the source code to figure this out.

**Comment by rhcarvalho** [comment]
The documentation includes this type of information for (SDK) developers.

The `/store` endpoint: https://docs.sentry.io/development/sdk-dev/overview/#parsing-the-dsn.

This endpoint takes events as documented in https://docs.sentry.io/development/sdk-dev/event-payloads/.

If you have specific questions that are not addressed in the existing docs, please to file a new issue and we can fill in the gaps.

Given that we already have documentation covering the original ask, I'm marking this as closed.

**Comment by OssiPesonen** [comment]
Thank you! Would be helpful to reference the 'Event payload' inside the API docs portion, but this will do for us.

**Comment by rhcarvalho** [comment]
> Would be helpful to reference the 'Event payload' inside the API docs portion

Believe it or not, it is in the first paragraph of the [page](https://docs.sentry.io/api/)!

![image](https://user-images.githubusercontent.com/88819/76980192-2f8c5600-6939-11ea-8929-ad4f880951c7.png)

The events payload is part of the [SDK Development](https://docs.sentry.io/development/sdk-dev/) documentation.

@OssiPesonen would you have any suggestions on how to make it more visible?

---

@MimiDumpling tagging you here for visibility; perhaps you would also have some suggestion on how we could better guide users to the correct documentation section next time?

**Comment by MimiDumpling** [comment]
> > Would be helpful to reference the 'Event payload' inside the API docs portion
> 
> Believe it or not, it is in the first paragraph of the [page](https://docs.sentry.io/api/)!
> 
> ![image](https://user-images.githubusercontent.com/88819/76980192-2f8c5600-6939-11ea-8929-ad4f880951c7.png)
> 
> The events payload is part of the [SDK Development](https://docs.sentry.io/development/sdk-dev/) documentation.
> 
> @OssiPesonen would you have any suggestions on how to make it more visible?
> 
> @MimiDumpling tagging you here for visibility; perhaps you would also have some suggestion on how we could better guide users to the correct documentation section next time?

Thanks for the heads up, @rhcarvalho! 😸 @PeloWriter and I will discuss ways to improve this issue.
