### ISSUE TITLE
Document valid exception mechanism types

### ISSUE THREAD

**Issue by rhcarvalho** [getsentry/sentry-docs#1584]
https://docs.sentry.io/development/sdk-dev/event-payloads/exception/#exception-mechanism says that `type` is required and says to use `generic` when the type cannot be determined, but doesn't list what are valid `types` that SDKs can send.

**Comment by rhcarvalho** [comment]
cc @getsentry/client-infra (ingestion team should know the answer)

**Comment by untitaker** [comment]
The type can be any string. In python its the integration name

**Comment by marandaneto** [comment]
> The type can be any string. In python its the integration name

same for Android

**Comment by jan-auer** [comment]
Yes, exception mechanism is an opaque string and can have any value. Beyond the type, ingestion does not impose restrictions on this field. Note that the type is only required when a mechanism is declared (which can be omitted completely). 

There is only one special case for minidumps, in all other cases exception mechanism has no semantics.

**Comment by rhcarvalho** [comment]
Quoting the docs (emphasis mine):

> Required unique identifier of this mechanism **determining rendering and processing** of the mechanism **data**.

How can the type be an arbitrary string and still determine **rendering** and **processing** of `data` (assuming this refers to the `data` field?)?

**Comment by marandaneto** [comment]
> Quoting the docs (emphasis mine):
> 
> > Required unique identifier of this mechanism **determining rendering and processing** of the mechanism **data**.
> 
> How can the type be an arbitrary string and still determine **rendering** and **processing** of `data` (assuming this refers to the `data` field?)?

I'll just make a guess here.
eg `type` for breadcrumbs., it renders differently for `error` and `http` but it takes a raw String as a `type` too, I believe this a common pattern in the protocol.

**Comment by untitaker** [comment]
@rhcarvalho there are sentinel values with special meaning as @marandaneto said. This makes it hard to "claim" new sentinel values without breaking random people's code, but that's where we're at

**Comment by jan-auer** [comment]
@rhcarvalho thanks for pointing that out. The point with determining rendering of the mechanism's data was never followed-up upon and can be disregarded. I will double check, but we now treat mechanism data more or less as opaque. This doc description will be fixed when doing the next pass over the attributes.
