### ISSUE TITLE
Are there examples for monitor and trace context interface?

### ISSUE THREAD

**Issue by kok202** [getsentry/sentry-docs#1588]
Hi. I made a new issue for asking about context interface. I think the official document has not  been synchronized with the real sentry code yet.
If you look at the official document, the context type could have device, app, runtime, OS, gpu, browser. 
https://docs.sentry.io/development/sdk-dev/event-payloads/contexts/

However, it seems that monitor and trace contexts have been added to the recently update.
https://github.com/getsentry/sentry/blob/cdc9e1b29e1e1471e1a9d3e3f2247278a597ef2f/src/sentry/interfaces/contexts.py

As I looked it up, I think the context is the form below. Could you give me some feedback?
Or can I know when the document will be updated?
```
{
	"trace": {
		"type": "trace",
		"trace_id": "a0fa8803753e40fd8124b21eeb2986b5",
		"span_id": "8c931f4740435fb8",
		"start_timestamp": 1586255412.255,
		"timestamp": 1586255412.255,
		"op": "http",
		"description": "GET http://example.com",
		"data": {
			"status_code": 200,
			"reason": "OK"
		},
		"tags": {
			"service": "example",
			"sentry:user": "id:1"
		}
	}
}
```
```
{
	"monitor": {
		"id": string,
		"status": string, // active, disabled, pending_deletion, deletion_in_progress, ok, error
		"type": string, // unknown, health_check, heartbeat, cron_job
		"name": string,
		"config": config, // config[schedule_type]: string // unknown, internal, cron_job
		"lastCheckIn": double,
		"nextCheckIn": double,
		"dateCreated": double,
		"project": object
	}
}
```

It is a little questionable that there is a type field in monitor context. To find related code, type seems to have `unkown`, `health_check`, `heartbeat`, and `cron_job`. But as you know, the type of context should be one of device, app, runtime, OS, gpu, browser, trace, monitor.
I would appreciate it if you could share the example code.

**Comment by rhcarvalho** [comment]
@untitaker or @jan-auer could you please help me triaging this?

**Comment by markstory** [comment]
The `monitor` context isn't ready to be documented yet as that feature isn't complete or ready for public consumption.

**Comment by jan-auer** [comment]
Same for the `trace` context, it is still evolving and until we're going live with the functionality, it is suspect to change. We will add public documentation ahead of the release.

**Comment by kok202** [comment]
Thank you for your reply. The answer was helpful, and I will close this issue. It's very interesting how new features will be added and used!
