### ISSUE TITLE
SDK Dev docs: clarify requirements for Runtime Context

### ISSUE THREAD

**Issue by rhcarvalho** [getsentry/sentry-docs#1590]
In https://docs.sentry.io/development/sdk-dev/event-payloads/contexts/#runtime-context we say that `name` is required, but then `raw_description` is optional and can be used to set both `name` and `version` in some unspecified cases.

![image](https://user-images.githubusercontent.com/88819/78669401-7dfb9780-78dc-11ea-89da-860c49d2b126.png)

If `raw_description` can be used by itself, then `name` is **not required**.

**Comment by rhcarvalho** [comment]
cc @jan-auer, maybe we can tackle this when you do a pass over the SDK dev docs.

**Comment by jan-auer** [comment]
This still needs to happen.
