### ISSUE TITLE
Use code owners for docs segments

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-docs#1623]
What about using [code owners](https://help.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners) to auto mark people for review?

Could be, for example that at the root level `*` we have @MimiDumpling and @PeloWriter.
At `/src/collections/_documentation/platforms/android/` @marandaneto would be the owner.

Each SDK has at least 1 owner so under `/platform` there would be at least one person from the SDK team as an owner.

**Comment by marandaneto** [comment]
if it's possible to set a code owner not only for the whole repo, that's awesome.

**Comment by PeloWriter** [comment]
I like this very much. Thanks for thinking of this - how would it affect areas of the doc that don't have clear owners; would we simply tag reviewers and the two root level reviewers would be added automatically?

**Comment by MimiDumpling** [comment]
Hi! Yes, I like this, too. Here's what I'm thinking:

- SDKs are assigned to individual maintainers
- anything else without a clear individual maintainer, we can assign the whole team. For example, the app team has a group handle we use to tag for review

**Comment by bruno-garcia** [comment]
@MimiDumpling @PeloWriter could you suggest some parts of the documentation tree and their appropriate owners?
We thought of a script to sync owners from the repository (using the repo's `CODEOWNERS`) but  it'd just be simpler if we could create GitHub teams for things, if that works.

**Comment by MimiDumpling** [comment]
I can get started on a tree. Thanks, Bruno!

**Comment by bruno-garcia** [comment]
It's done
