### ISSUE TITLE
Align SDK dev docs and user-facing docs on effects of empty DSN

### ISSUE THREAD

**Issue by rhcarvalho** [getsentry/sentry-docs#1635]
At the moment they are not incompatible, but inconsistent. User-facing docs don't mention the effects of "disabling the SDK":

~https://docs.sentry.io/error-reporting/configuration/#dsn~ => https://docs.sentry.io/product/sentry-basics/dsn-explainer/#what-the-dsn-does

![image](https://user-images.githubusercontent.com/88819/79986421-51cf4180-84ac-11ea-86c2-cacc72d26d49.png)

~https://docs.sentry.io/development/sdk-dev/overview/~ => https://develop.sentry.dev/sdk/overview/#usage-for-end-users

![image](https://user-images.githubusercontent.com/88819/79986338-2f3d2880-84ac-11ea-9477-31d0900baf09.png)

**Comment by rhcarvalho** [comment]
cc @Swatinem who's clarifying the SDK dev docs in #1621.

**Comment by rhcarvalho** [comment]
Here's one example where users got confused because they were led to believe that the only implication of empty DSN is that "the SDK will just not send any events".

https://github.com/getsentry/sentry-javascript/issues/2369#issuecomment-617658048

**Comment by Swatinem** [comment]
That is an interesting usecase. So we actually need to setup integrations even when the SDK is "disabled", so that integrations can create any globals that users depend on.

**Comment by rhcarvalho** [comment]
The meaning of "disabled SDK" is not very consistent today, and has different implications in different SDKs.

If the only observable behavior was to not send events, there is a lot of instrumentation going on in vain. So, IMHO, it does make sense to avoid as much work as possible when events won't be sent / "disabled SDK".

@Swatinem as you are documenting, other consequences are some callbacks are not called, among other things to avoid unnecessary work. I am not sure whether "we actually need to setup integrations". That is questionable, since again (like for max_breadcrumbs we talked in the docs PR) an integration might be missing information when there is no DSN.

**Comment by rhcarvalho** [comment]
Will bring this up with other SDK devs on Discord / SDK evolution call.

**Comment by HazAT** [comment]
We decided in the meeting:

Decision: If you pass an empty string, the events shouldn't be sent to Sentry.
^ this is the important part.

For SDK developers we decided depending on the ecosystem and platforms if for example global handlers are still instrumented or not is an implementation detail. The core is, events should not hit the Sentry server.

**Comment by Swatinem** [comment]
> is an implementation detail

admittedly, an observable implementation detail (like `configure_scope` or `before_send` hooks being called)
