### ISSUE TITLE
Node.js: misplaced note about serverless

### ISSUE THREAD

**Issue by rhcarvalho** [getsentry/sentry-docs#1645]
https://docs.sentry.io/platforms/node/ has a note on `AWS Lambda` usage:

![image](https://user-images.githubusercontent.com/88819/80427139-67e36480-88e7-11ea-9468-1ad1d88ced56.png)

Users searching and landing directly on https://docs.sentry.io/platforms/node/serverless/ have no such note.

---

When replacing the note, consider that the advice could be better -- instead of "The only way to send events to Sentry is to manually use Sentry.captureException() or Sentry.captureMessage()." be more specific and show a pattern of wrapping the whole Lambda entry point with a try...catch (the wrapper pattern from the existing example).

**Comment by rhcarvalho** [comment]
@ajjindal FYI

**Comment by silent1mezzo** [comment]
No longer relevant with the changes to the docs
