### ISSUE TITLE
JS beforeSend callback "event" object not documented

### ISSUE THREAD

**Issue by alex-jitbit** [getsentry/sentry-docs#1651]
The docs suggest using `beforeSend` as a way to filter some errors, but I can't find any description of the `event` object whatsoever. Here's docs I'm referring to https://docs.sentry.io/error-reporting/configuration/filtering/?platform=browser#before-send

**Comment by alex-jitbit** [comment]
sdfgsdftgewdrgsdthgsdftyh

**Comment by rhcarvalho** [comment]
The `Event` type is defined in `@sentry/types`: https://getsentry.github.io/sentry-javascript/interfaces/types.event-1.html

**Comment by PeloWriter** [comment]
In addition, we have this [content](https://docs.sentry.io/platforms/javascript/configuration/filtering/#using-beforesend) that may be helpful. Every SDK will have its own definition of `event`, and this is something we plan to incorporate into our developer docs in the long term.
