### ISSUE TITLE
Navigating to the docs for on premise installation gives a 404 error

### ISSUE THREAD

**Issue by c-dart** [getsentry/sentry-docs#1657]
URL - https://docs.sentry.io/server/ (Link present in https://github.com/getsentry/onpremise)

![sentry_on_premise](https://user-images.githubusercontent.com/46990382/80803240-5b088e80-8bcf-11ea-81db-4c6d0c75d7e4.png)

**Comment by arvindamirtaa** [comment]
The urls now redirect to the sentry on-premise github page. 
Was the removal of documentation for on-premise installations intentional?
