### ISSUE TITLE
Ionic Cordova Build Android

### ISSUE THREAD

**Issue by marcogrieco** [getsentry/sentry-docs#1676]
Hi, i'm receiving this error if i try to build android build.

Using "requireCordovaModule" to load non-cordova module "fs" is not supported. Instead, add this module to your dependencies and use regular "require" to load it.

What does it mean? These are my ionic info

Ionic:

   ionic (Ionic CLI)             : 4.12.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 5.1.0
   @angular-devkit/build-angular : 0.803.26
   @angular-devkit/schematics    : 8.3.26
   @angular/cli                  : 8.3.26
   @ionic/angular-toolkit        : 2.2.0

Cordova:

   cordova (Cordova CLI) : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms     : android 8.1.0
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.2.1, (and 14 other plugins)

System:

   NodeJS : v12.6.0 (/usr/local/bin/node)
   npm    : 6.9.0
   OS     : macOS

Thanks in advance.

**Comment by monikaja** [comment]
I have the same problem. Any way to fix it?

**Comment by monikaja** [comment]
Ok, justo in case you still hace this error, I've changed:
**const fs = ctx.requireCordovaModule('fs');** in file "plugins/sentry-cordova/scripts/plugin_add_rm.js for **const fs = require('fs');**

And

  **const path = ctx.requireCordovaModule('path');
  const fs = ctx.requireCordovaModule('fs');**

for 

  **const path = require('path');
  const fs = require('fs');**

in file "plugins/sentry-cordova/scripts/before_compile.js and now the compilation has worked!
