### ISSUE TITLE
Review sampling rate advice

### ISSUE THREAD

**Issue by rhcarvalho** [getsentry/sentry-docs#1678]
While updating the docs in https://github.com/getsentry/sentry-docs/pull/1667#discussion_r422064998, a conversation started about what advice we give for setting the sampling rate of different components, specially in the light of different load patterns.

The updated docs with the advice reads:

> If you enable tracing in services with multiple entry points, we recommend choosing similar sampling rates, to avoid biasing your data. [...]

And the discussion is that even setting all sampling rates to the same value may not help with sample bias.

<details>

This is a screenshot of the advice prior to the update (red underline to emphasize the advice):

https://docs.sentry.io/performance/distributed-tracing/#sampling-transactions

![image](https://user-images.githubusercontent.com/88819/81578821-a2e79c80-93ab-11ea-9a81-36296aba56d3.png)

</details>

**Comment by rhcarvalho** [comment]
The advice, despite a few edits, is still there at https://docs.sentry.io/product/performance/distributed-tracing/#consistency-between-traces.

@trillville I'd appreciate your help if you could have a look at that advice in the docs? My understanding is that, in that case, distribution bias is orthogonal to the choice of sample rates.

**Comment by trillville** [comment]
> The advice, despite a few edits, is still there at https://docs.sentry.io/product/performance/distributed-tracing/#consistency-between-traces.
> 
> @trillville I'd appreciate your help if you could have a look at that advice in the docs? My understanding is that, in that case, distribution bias is orthogonal to the choice of sample rates.

I agree. Just to make it concrete with an example:

- 10k web app frontend transactions
- 10k backend transactions (from web app)
- 100k backend API transactions

If frontend sampling rate is 10% and backend is 10%, we end up with:
- 1k web app frontend transactions
- 1k backend transactions (from web app)
- 10k backend API transactions

If frontend sampling rate is 10% and backend is 50%:
- 1k web app frontend
- 500 web app (backend)
- 5k backend API transactions

In both cases, the ratio of backend transactions attributable to the web app to backend transactions attributable to the API is the same.

**Comment by trillville** [comment]
Let me know if I'm misunderstanding something! But if I'm not, definitely agree that different sampling rates wouldn't affect bias here.

**Comment by PeloWriter** [comment]
@lobsterkatie or @wmak - can either of you take a look and update the content here?
