### ISSUE TITLE
Outdated React Native client docs

### ISSUE THREAD

**Issue by sseppola** [getsentry/sentry-docs#1744]
Hi, I just integrated Sentry into my React Native app. I stumbled a lot when I attempted this yesterday (worked today), and came across two different instructions for setting it up:

https://docs.sentry.io/clients/react-native/ (outdated)
vs.
https://docs.sentry.io/platforms/react-native/ (latest)

**Comment by HazAT** [comment]
Thanks for the heads up
the page on top of https://docs.sentry.io/clients/react-native/ 
should show something like this:

![image](https://user-images.githubusercontent.com/363802/86623481-fb10d880-bfc1-11ea-81b6-7d131b1766a2.png)

We will deal with it.

**Comment by sseppola** [comment]
Yes, that would solve the problem.
