### ISSUE TITLE
Clarify SSO docs

### ISSUE THREAD

**Issue by DominicWatson** [getsentry/sentry-docs#18]
Further to a conversation on IRC. As SSO is not publicly supported (i.e. commercial), the documentation on SSO should make that clear to avoid people fruitlessly following the instructions.

**Comment by dcramer** [comment]
This is resolved with v8 of Sentry as those docs no longer exist and are replaced with this repo + docs.getsentry.com

**Comment by DominicWatson** [comment]
I personally don't think that removing the docs for the next version goes far enough. The difficulty is that an online search will intimate to curious minds that built in SSO is possible (historic records, etc.). Removing the docs on SSO will do nothing to deny that and leave unfortunate souls with the impression that "the new docs are lacking". This is what happened to me, and I found bits of information that suggested it should work but none to say that it absolutely isn't possible (in an out of box kind of way).

Instead, create a page in the documentation for Single Sign On that has:

1. The fact that there is no out of box SSO solution for On-Premise solutions
2. The fact that SSO options are available in the hosted version (if that's true)
3. The fact that the authentication API lets you roll your own with links to developer docs
4. The fact that you can support customers needs commercially
5. The fact that third party authentication plugins may/do exist






I think a notice in the documentation about the non-availability of SSO (and promoting hosted / B2B contact for custom solutions) would be preferable to removing it as it has already been publicly intimated that it is available leading to a false trail of hope for some (with no public material to negate that).

Anyways, leave it as closed if you will, but
