### ISSUE TITLE
Outdated docs in enriching-error-data/additional-data/?platform=browser

### ISSUE THREAD

**Issue by rix1** [getsentry/sentry-docs#1824]
I was reading through your [docs about setting additional data/context](https://docs.sentry.io/enriching-error-data/additional-data/?platform=browser#context) and was confused about the example. It promotes using `setExtra()` in the example, only to say on the line below that it's deprecated 🤔 

<img src="https://user-images.githubusercontent.com/2470775/86222977-402ea800-bb87-11ea-9782-f5c2e1036308.png" width="450" />

---

I would have loved to open a PR fixing this, but I couldn't figure out where to find `{% include components/platform_content.html content_dir='set-extra' %}` in your [docs' source code](https://github.com/getsentry/sentry-docs/blob/master/src/collections/_documentation/enriching-error-data/additional-data.md).

**Comment by silent1mezzo** [comment]
Thanks, this has been updated in the [latest docs](https://docs.sentry.io/platforms/javascript/enriching-events/context/).

**Comment by rix1** [comment]
@silent1mezzo You seem to have a bug in your routing 🤔 You linked to `https://docs.sentry.io/platforms/javascript/enriching-events/context/` but it's redirected to  `https://docs.sentry.io/platforms/(.*)/enriching-events/context/`

?

**Comment by silent1mezzo** [comment]
@rix1 hm, thanks for pointing that out. Looks like we broke something today. The team's working on a fix.

**Comment by silent1mezzo** [comment]
@rix1 the redirect is now fixed. Thanks for letting us know about it.
