### ISSUE TITLE
【src/collections/_documentation/enriching-error-data/environments.md】doc mistake

### ISSUE THREAD

**Issue by hanshou101** [getsentry/sentry-docs#1842]
In [Creating Environments] section, there is no multi-language usage document

<br/>
<br/>
<br/>
<br/>

![image](https://user-images.githubusercontent.com/19248935/86455891-dadbe200-bd53-11ea-92ec-3268394a38af.png)

**Comment by PeloWriter** [comment]
Thanks for raising this issue; it has been fixed.
