### ISSUE TITLE
Document sentry_sdk.last_event_id in Python SDK docs

### ISSUE THREAD

**Issue by ExplodingCabbage** [getsentry/sentry-docs#1850]
Currently, there's an example of its usage in the Tryton docs at https://docs.sentry.io/platforms/python/tryton/, but otherwise it appears to go unmentioned in the docs. Yet it's not Tryton-specific at all, so ought to be documented somewhere more general.

**Comment by untitaker** [comment]
it is documented as part of user feedback for which this API exists: https://docs.sentry.io/enriching-error-data/user-feedback/?platform=django

**Comment by ExplodingCabbage** [comment]
@untitaker there's still no generic Python section there, only a Django section.

**Comment by untitaker** [comment]
If you're not interested in examples (and I believe for a realistic one you need to have some kind of web endpoint) I think you may be looking for API docs: https://getsentry.github.io/sentry-python/api.html#sentry_sdk.last_event_id

that one is linked in the readme of the sdk

**Comment by ExplodingCabbage** [comment]
Huh. That's pretty well buried - I'm not sure I'd ever have found it without you pointing it out.

That aside, the description there is a little lacking. I note that the "last" event is - usefully, and importantly! - defined not as the most recently-emitted one for the process, but as the most recently-emitted one within your current request handler (or perhaps within whatever other context may make sense based on the framework you're in). That seems worth noting there.

**Comment by untitaker** [comment]
Fair enough, I'll add that. I just feel like API docs are probably what we want here. We can do a better job linking them from docs.sentry.io
