### ISSUE TITLE
Documentation release link bug

### ISSUE THREAD

**Issue by nath1as** [getsentry/sentry-docs#1873]
This part of documentation:

```Release names are just strings but some formats are detected by Sentry and might be rendered differently. For more information have a look at the releases documentation.```
goes to a dead link:

https://docs.sentry.io/enriching-error-data/environments/%5Bhttps://docs.sentry.io/workflow/releases/%5D(https://docs.sentry.io/workflow/releases/)

**Comment by PeloWriter** [comment]
Thanks for raising this, the broken link has been fixed.
