### ISSUE TITLE
Document the behavior of Merge and Similar Issues

### ISSUE THREAD

**Issue by ehfeng** [getsentry/sentry-docs#195]
Document the behavior of Merge and Similar Issues.

1. Why should I merge issues?
2. What happens when issues are merged (which issue "remains"? what happens to future events?)
3. Can I undo merges?
4. What are "Similar Issues"? Are they merged?
5. How are Similar Issues determined? How do these categories (Exception Message, Application Code, Stacktrace Frames, Log Message) play into similarity?
![image](https://user-images.githubusercontent.com/279398/34173341-01dbb5ae-e4aa-11e7-9057-034f8f2f90ac.png)
6. How does merging affect Similar Issues?

**Comment by sdwvit** [comment]
@ehfeng any update on this?

**Comment by sdwvit** [comment]
bump, still relevant

**Comment by PeloWriter** [comment]
We have this covered now in our [content](https://docs.sentry.io/product/sentry-basics/guides/grouping-and-fingerprints/).
