### ISSUE TITLE
Webhook anchors are off in webhook integrations page

### ISSUE THREAD

**Issue by alexmv** [getsentry/sentry-docs#1988]
There's a weird error happening in the rendering as currently seen on https://docs.sentry.io/product/integrations/integration-platform/webhooks/ (and perhaps other places, I've not looked extensively).  But I can't reproduce it in a local clone of the repo at 0a36b492b6eb40bee42fd1799c431f510bc7e539.

On https://docs.sentry.io/product/integrations/integration-platform/webhooks/, `#uninstallation` looks to be the `id` and linked anchor for both the `[Un]installation` _and_ the `Webhook Alerts` headings -- which means the latter doesn't work as expected at all.  The anchor and id on the `Issues` heading, in turn, is `#webhook-alerts`, which works, but is misleading in URLs.  The anchor and id on `Errors` is correct, as `#errors`.

Since I can't replicate locally, and there's nothing obviously amiss with the `.mdx` file, I don't know of a fix to suggest.

**Comment by MimiDumpling** [comment]
Hi @alexmv, thank you for the feedback. We've resolved the issue. Please feel free to let us know if any other inconsistencies appear. Thanks, again!
