### ISSUE TITLE
Add deprecation notes about Raven clients

### ISSUE THREAD

**Issue by nip3o** [getsentry/sentry-docs#1995]
Googling "sentry javascript" gives me these pages as top hits: https://docs.sentry.io/clients/javascript/ and https://docs.sentry.io/platforms/javascript/. The first page is about the legacy Raven JS, the other page about the new Javascript SDK, but without knowing that Raven is the old client it's impossible to know which one is preferred. The old clients should have a clear statement on top of the page linking to the newer version of the SDK.

This probably applies to more docs about the old clients.

**Comment by AbhiPrasad** [comment]
Thank you for reporting, I have raised a PR to address this.
