### ISSUE TITLE
Decide on Documented Protocol

### ISSUE THREAD

**Issue by mitsuhiko** [getsentry/sentry-docs#2]
Sentry supports a ton of functionality and now that we do a pass over the docs we need to decide what is the minimum set we want to document, and then make sure all libraries support that and the protocol docs match.

This might cover:
- tags
- releases
- extra
- stacks
- user
- interfaces
- level
- checksum

**Comment by akleiber** [comment]
kind of old - any progress here?

the docs need some ❤️  - the log levels for example are out of sync for all the clients - may be that is intended but that would be awkward

example: [JavaScript](https://docs.sentry.io/clients/javascript/usage/#passing-additional-data) vs. [NodeJS](https://docs.sentry.io/clients/node/usage/#additional-data)

**Comment by cameronmcefee** [comment]
Closing as stale and new docs are on the way
