### ISSUE TITLE
Enhance search experience on Doc

### ISSUE THREAD

**Issue by s-pace** [getsentry/sentry-docs#204]
👋  Sentry,

Your tool is so great. I was using your documentation and I felt like the search experience could be way much better:

![DocSearch playground](https://cl.ly/2G2U31312x2W/Screen%20Recording%202018-02-06%20at%2011.08%20AM.gif)

I am working on [DocSearch, The easiest way to add search to your documentation](https://community.algolia.com/docsearch/). I couldn't help providing you such free and nice tool:

Congratulations, your search is now ready!

I've successfully configured the underlying crawler and it will now run every 24h.

You're now a few steps away from having it working on your website:
- Copy the following CSS/JS snippets and add them to your page
```html
<!-- at the end of the HEAD -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.css" />
<!-- at the end of the BODY -->
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.js"></script>
<script type="text/javascript"> docsearch({
  apiKey: 'afa63b18ba7e71185819b923f51bbbec',
  indexName: 'sentry',
  inputSelector: '### REPLACE ME ####',
  debug: false // Set debug to true if you want to inspect the dropdown
});
</script>
```
- Add a search input in your page if you don't have any yet. Then update the inputSelector value in JS snippet to a CSS selector that targets your search input field.

- Replace $CLIENT with the client you want to search on. The list of possible client is hardcode in the config.
   So as of today you have: `cocoa`, `cordova`, `csharp`, `elixir`, `go`, `java`, `javascript`, `node`, `perl`, `php`, `python`, `react-native`, `ruby`

 *For example if you want to refine the search to the client "cocoa" just specify: 'facetFilters': ["client:cocoa"]*

- Optionally customize the look and feel by following the DocSearch documentation (https://community.algolia.com/docsearch/documentation/)
- You can also check your configuration in our github repo (https://github.com/algolia/docsearch-configs/blob/master/configs/sentry.json).

Please open a pull request if want to leverage your configuration!

Feel free to get back to us if you have any issues or questions regarding the integration.

We'd also be happy to get your feedback and thoughts about DocSearch - so we can continue to improve it.

Have a nice day :)

**Comment by s-pace** [comment]
👋 @jan-auer @adhiraj ,
I have bootstrap a quick playground in 2 sec.
http://sentry-docsearch.surge.sh/

Please let us know what do you think about that.

Cheers

**Comment by s-pace** [comment]
@jan-auer @adhiraj Do you need any help in order to test it?

Happy to help.

**Comment by s-pace** [comment]
👋 ,

Hope you are doing great.

Do you need some help in order to integrate DocSearch? I would be happy to help and note any of your feedback.

By the way, we do provide the algolia analytics for free for your DocSearch index. Please send me the email addresses of the people you want to grant access to.

Have a nice day,

**Comment by dcramer** [comment]
Appreciate the interest, but we'll decide on our own if we ultimately want to outsource search.

**Comment by s-pace** [comment]
Make sense, thank you. Feel free to ping.
