### ISSUE TITLE
Add Cordova SDK to sidebar

### ISSUE THREAD

**Issue by saragilford** [getsentry/sentry-docs#205]
The Cordova docs are live, but we should make sure it's surfaced in the sidebar.

<img width="410" alt="screen shot 2018-02-07 at 3 50 10 pm" src="https://user-images.githubusercontent.com/10121420/35947876-c6318b22-0c1e-11e8-838d-b1bf065db0b1.png">

**Comment by cameronmcefee** [comment]
This should be resolved
