### ISSUE TITLE
[req] Add the endpoints /csp-report (and soon /security-report)

### ISSUE THREAD

**Issue by dekimsey** [getsentry/sentry-docs#207]
I recently wanted to add environment and release data to my csp reports.

I found by experimentation and a little [IRC help](https://botbot.me/freenode/sentry/2018-02-22/?msg=97095808&page=1), `/csp-report?sentry_release=...` is supported but `/csp-report?sentry_environment=...` is not (yet).

Long story short, please document the security report endpoints, indicating what meta parameters are supported and how.

Thanks!

**Comment by PeloWriter** [comment]
Closing. The docs have been fully refreshed.
