### ISSUE TITLE
Implement Wizards

### ISSUE THREAD

**Issue by mitsuhiko** [getsentry/sentry-docs#21]
This is a quick overview issue about the wizard functionality:
## What are Wizards?

Wizards are a basic overview of how to configure a client or integration for a sentry project.  Just the bare minimums for copy/paste.
## Where are Wizards configured?

Wizards are configured in a `sentry-doc-config.json` file.  There can be multiple wizards per such a file and those files can appear in any folder in the documentation tree.  The contents are as follows:

``` javascript
{
  // all wizards go here
  "wizards": {
    // the key is the id of the wizard which is how sentry can identify it.
    "python": {
      // the human readable name for this wizard.  This should be the name
      // of the programming language of framework.
      "name": "Python",
      // the most appropriate name of the client lib used
      "client_lib": "raven-python",
      // this is true if the wizard refers to a framework or app rather than a raw client.
      "is_framework": false,
      // the name of the document (can be relative) the documentation should
      // link to.
      "doc_link": "installation",
      // a list of selectors that should be included in the wizard.  This just
      // points to `rst_file#headline_anchor`.
      "snippets": [
        "installation#installation",
        "usage#capture-an-error",
        "usage#reporting-an-event"
      ]
    }
}
```
## How are Wizards build?

The docs build them out automatically.  They are then placed in a `_wizards` folder as JSON file.  The server can either load that directly from the docs or we can ship it.

**Comment by cameronmcefee** [comment]
I presume this is an early draft of what became `_platforms`
