### ISSUE TITLE
Documentation for Performance (@sentry/tracing) in Node/Express

### ISSUE THREAD

**Issue by doginthehat** [getsentry/sentry-docs#2104]
Looking at the documentation for @sentry/tracing (https://docs.sentry.io/product/performance/getting-started/), it seems that Node should be supported.

<img width="801" alt="Screen Shot" src="https://user-images.githubusercontent.com/843366/91399687-c282d200-e881-11ea-920f-1875a04c218e.png">

However, there is no documentation for it available (that I can find).

Poking around the @sentry/tracing code, there seems to be an Express integration available.

Based on the integration source code, it looks like it should be instantiated liked this:

```
const express = require('express');

const app = express();

const Sentry = require('@sentry/node');
const { Integrations } = require( "@sentry/tracing");

Sentry.init({ 
	dsn: __MY_SENTRY_DSN__,
	integrations: [
		new Integrations.Express({app}),
	]
});
```

I've tried implementing it like this but i'm not getting any trace data in Sentry.

And because there's no official documentation, i'm not very confident in using it (could change any time).

**Comment by doginthehat** [comment]
For reference if anyone comes here looking for answers, there's a Stackoverflow question with some answers

https://stackoverflow.com/q/63613384/192705

**Comment by doginthehat** [comment]
Key points are:

- `Sentry.Handlers.tracingHandler` in `@sentry/node` is undocumented 
- `Integrations.Express` in @sentry/tracing` is undocumented

**Comment by AbhiPrasad** [comment]
Hey thanks for opening an issue. If you select the node dropdown on the getting started page (https://docs.sentry.io/product/performance/getting-started/), we have a section on `Automatic Instrumentation` that covers setting up the Express integration and tracing handlers.

![image](https://user-images.githubusercontent.com/18689448/91469959-17165500-e862-11ea-828a-acc53229cba7.png)

I agree this could be much better though, thank you for your feedback. We will be addressing this to make the page more intuitive and add some more info.

**Comment by doginthehat** [comment]
Ohhhhhhhh, woah I did not see that button at all 🙄

Ok yeah, that answers that then, my bad.

**Comment by AbhiPrasad** [comment]
Cool, feel free to open up another issue if you come across something else. 

Thanks!
