### ISSUE TITLE
Add auth token scope permissions information

### ISSUE THREAD

**Issue by MeredithAnya** [getsentry/sentry-docs#213]
Add info on what permissions (i.e `project:read` , `project:write`, etc)  are needed for what actions.

**Comment by mrnagydavid** [comment]
It is quite surprising that this needs to be issued a ticket. It would be nice to see what permissions mean and from an opposite logical direction: what permissions are needed for specific actions, like creating a new release.

This poor guy asked 1 year ago the same:
https://forum.sentry.io/t/how-to-get-a-valid-api-key-for-creating-releases/977
And got no response at all.

**Comment by RobinDaugherty** [comment]
And now this gets no response as well. I guess they want us to grant all permissions to all auth tokens.

**Comment by mkj28** [comment]
> I created an auth token for CI only for creating a new release and it seems that `projects:releases` is not sufficient for executing `sentry-cli releases set-commits --auto $VERSION`

You would think... right? Same issue. Plz document the scopes/actions in API docs.

**Comment by rszalski** [comment]
Turns out you also need `org:read` permission to associate commits. So the final, minimal set of permission scopes to associate commits with release is: `org:read`, `project:read`, `project:releases`.

Source: https://forum.sentry.io/t/403-error-adding-commits-to-release/4708/2

**Comment by rivajunior** [comment]
@rszalski where I can set those permissions?

**Comment by rszalski** [comment]
@rivajunior you can select them when creating a new Auth Token by going to 
https://sentry.io/settings/account/api/auth-tokens/

![ebe1d8e1-8c54-4f6b-950e-58dc0763ddaf](https://user-images.githubusercontent.com/184806/53262898-200bf080-36d8-11e9-92ae-feb32d282797.jpeg)
