### ISSUE TITLE
Wrong links in side bar when custom anchors are used

### ISSUE THREAD

**Issue by rhcarvalho** [getsentry/sentry-docs#2130]
Side bar links to https://docs.sentry.io/platforms/ruby/#installation-install

![image](https://user-images.githubusercontent.com/88819/91695019-cf4b4280-eb6d-11ea-876a-5a7cedaf3dcf.png)

Actual anchor is `#install`: https://docs.sentry.io/platforms/ruby/#install

https://github.com/getsentry/sentry-docs/blob/05f6be681238bbbaed676f7348e34723d2399fff/src/platforms/ruby/index.mdx#L15

---

Need to fix side bar link generation.

**Comment by rhcarvalho** [comment]
cc @getsentry/docs

**Comment by dcramer** [comment]
I believe this only affects MDX, though its not obvious to me how we're going to fix it.

**Comment by dcramer** [comment]
Hard to grep the internet for this, but I'm guessing theres "no known fix". We'd need to find a way to parse the tree and generate our own tableOfContents entry.

I also noticed that the markdown and MDX tableOfContents queries return two different entities. Markdown returns a string, MDX returns a list.
