### ISSUE TITLE
Data Scrubbing documentation is unclear

### ISSUE THREAD

**Issue by marfire** [getsentry/sentry-docs#214]
There are a few ways that the [Data Scrubbing section of the documentation](https://github.com/getsentry/sentry-docs/blob/eec07b4d2539810646580db80ab2c2201357a9c0/docs/learn/sensitive-data.rst#server-side-filtering) is unclear: 

1. It's imprecise about the terms *key*, *value*, and *field*. For example, it says that Sentry will scrub "*values* that look like they contain credit cards" and "*keys* that contain any of the following values". [What's actually happening](https://github.com/getsentry/sentry/blob/6e0daaa6237c118614142cfd27da7899beb2a3d9/src/sentry/utils/data_scrubber.py#L132) in the second case is that Sentry is scrubbing values (always values) when either the key or the value contains one of the sensitive strings as a substring.

    Similarly with "fields", which is used here as well as in the Sentry interface itself. What is a field? In **Additional Sensitive Fields** it refers to strings that are checked as substrings of either keys or values, as above. But in **Safe Fields**, the next section, the fields in question refer [only to keys](https://github.com/getsentry/sentry/blob/6e0daaa6237c118614142cfd27da7899beb2a3d9/src/sentry/utils/data_scrubber.py#L114) and must match exactly.

2. It doesn't mention some other important scrubbed values, like [social security numbers and cryptographic keys](https://github.com/getsentry/sentry/blob/6e0daaa6237c118614142cfd27da7899beb2a3d9/src/sentry/utils/data_scrubber.py#L50).

3. It lists `"auth_token"` as a sensitive value even though the [actual string](https://github.com/getsentry/sentry/blob/6e0daaa6237c118614142cfd27da7899beb2a3d9/src/sentry/constants.py#L159) is `"auth"`. As far as I can tell `"auth_token"` was never a sensitive value, and `"auth"` [was added](https://github.com/getsentry/sentry/commit/1dbd1d80f3e8533f4a88259347f10eee0eeacdf8#diff-e62c2bcbcd2547971e395019c679a61a) a year and a half ago.

    I'm not that familiar with reST, but couldn't these values be automatically extracted from `constants.py` to avoid this problem in the future?

**Comment by DanielGibbsNZ** [comment]
I'm also getting some unexpected behaviour when using custom breadcrumbs. When I add a breadcrumb containing the string `auth` (e.g. `Reauthenticating`) it shows up as `[Filtered]` in Sentry.

```
Sentry.addBreadcrumb({
  category: 'auth',
  message: 'Reauthenticating',
  level: Sentry.Severity.Info
})
```

**Comment by DanielGibbsNZ** [comment]
Sentry support have confirmed that the above can be fixed by adding `message` to the list of non-scrubbed fields.

**Comment by untitaker** [comment]
fwiw most of this should now be fixed with https://github.com/getsentry/sentry-docs/pull/2880
