### ISSUE TITLE
Documentation page stuck in infinite refresh loop

### ISSUE THREAD

**Issue by TravisBumgarner** [getsentry/sentry-docs#2212]
I've verified this on my MacBook Pro on Firefox and Chrome. Had a coworker verify it as well.

https://docs.sentry.io/platforms/node/typescript/

**Comment by joergi** [comment]
came to post the same error....
I can verify it, on my Linux Firefox and Chrome

**Comment by untitaker** [comment]
We recently fixed this I believe, can you verify again? I can't see the issue now

**Comment by 4264746** [comment]
Ребята почему так лагают автики? у  меня щас 402 пишет

**Comment by untitaker** [comment]
Can you write in english? I put your comment through Google Translate and couldn't understand it.

**Comment by TravisBumgarner** [comment]
Looks good!

**Comment by joergi** [comment]
works!
