### ISSUE TITLE
Links to headers via document fragment (#) don't show header

### ISSUE THREAD

**Issue by benvinegar** [getsentry/sentry-docs#23]
e.g. https://docs.getsentry.com/hosted/clients/javascript/sourcemaps/#uploading-source-maps-to-sentry

This is what you see (header "Uploading Source Maps to Sentry" is missing):

https://www.dropbox.com/s/8s4u6c0ipe92tkh/Screenshot%202015-10-31%2017.02.38.png?dl
![image](https://cloud.githubusercontent.com/assets/2153/10866564/36ba1826-7ff1-11e5-9a14-e35dcaf3a37f.png)

Should be:

![image](https://cloud.githubusercontent.com/assets/2153/10866565/46eb2bfe-7ff1-11e5-933a-075294b68cdf.png)

**Comment by mitsuhiko** [comment]
I wonder what a good solution for this is.  The anchors unfortunately I cannot move to another element because this is deep inside sphinx.  Maybe the solution is some hackery with margins?

**Comment by benvinegar** [comment]
It's a CSS issue.

**Comment by ckj** [comment]
Yeah, this is an issue that was introduced with the sticky stuff. Working on a fix now.
