### ISSUE TITLE
Missing documentation for setting environment (and other configuration pages) for Dart/Flutter

### ISSUE THREAD

**Issue by jkcdarunday** [getsentry/sentry-docs#2309]
Currently, Sentry uses the Dart library for the [Flutter guide](https://docs.sentry.io/platforms/flutter/). However, other than the getting started page, the pages for configuration (I specifically noticed the environment page as I was trying to figure out how to set it) are missing.

Looking at the library's [code](https://github.com/getsentry/sentry-dart) and [unit tests](https://github.com/getsentry/sentry-dart/blob/16880d084aab59cb223a789494606f11a7dd95f2/test/test_utils.dart#L70-L81), I see that `environment` can be set using the `environmentAttributes` parameter.

Given that they are available, these pages should show them instead of showing the ff. message.
![Screenshot_20200921_190130](https://user-images.githubusercontent.com/4564810/93759509-e1844200-fc3c-11ea-879c-8cac76cdfb13.png)

**Comment by jkcdarunday** [comment]
I'm trying to figure out where I can add an example for this so I can make a pull requests by looking up how it is done for Javascript but I see two places where the example code can be found:
- `src/includes/set-environment/javascript.mdx`
- `src/docs/clients/javascript/config.mdx`

Is it correct that I just create a flutter folder/file same as the above?

**Comment by dcramer** [comment]
@jkcdarunday its all in the includes - yeah. We are improving contribution docs yet, but theres some information here: https://docs.sentry.io/contributing/pages/components/#platformcontent

**Comment by bruno-garcia** [comment]
Worth noting that the Dart/Flutter SDK still doesn't have `init` so you'd need to provide these while creating an instance of `SentryClient`:

```dart
final sentry = SentryClient(
    dsn: options.dsn,
    environmentAttributes:
        Event(release: 'io.sentry@1.3.4', environment: 'production'));
```

Please note we're working in improving Dart and Flutter and these will change significantly in the upcoming weeks.
