### ISSUE TITLE
Add some basic frontmatter for previews on external services (e.g. Twitter)

### ISSUE THREAD

**Issue by benvinegar** [getsentry/sentry-docs#2311]
This is how links to docs appear embedded [in a tweet](https://twitter.com/bentlegen/status/1308101045533335552): 

![image](https://user-images.githubusercontent.com/2153/93802412-48cbd300-fbf8-11ea-99df-3b10790467b4.png)

It would be nice if we got a basic Sentry logo/header in here.

**Comment by PeloWriter** [comment]
Thanks, Ben. We've got this as an ongoing, background project.

**Comment by PeloWriter** [comment]
this has been completed.
