### ISSUE TITLE
No Sentry Documentation For Spring

### ISSUE THREAD

**Issue by nilesh16** [getsentry/sentry-docs#2357]
For Spring Sentry Documentation is not present. Usages, different types of capturing etc nothing is present for java frameworks. Pls update the documentation if possible.

Thanks and Regards,
Nilesh Mittal
nileshmittal16@gmail.com

**Comment by bruno-garcia** [comment]
We're working a [new Spring integration (as part of a new Java SDK, version 3.0.0)](https://github.com/getsentry/sentry-java).

There's a [draft PR for the docs](https://github.com/getsentry/sentry-docs/pull/2239) already which you can browser here: https://sentry-docs-git-fork-maciejwalkowiak-sentry-java-30.sentry.dev/platforms/java/

Please note these bits are not published GA yet. They are an alpha available on [bintray](https://bintray.com/beta/#/getsentry/sentry-android?tab=packages).
We plan to release it all next week, including `jcenter` and `maven central`.

**Comment by nilesh16** [comment]
Thanks a lot for the reply. Waiting for the documentation to release
