### ISSUE TITLE
before-send callback in Ruby SDK

### ISSUE THREAD

**Issue by ijdickinson** [getsentry/sentry-docs#2440]
The [filtering events](https://docs.sentry.io/platforms/ruby/configuration/filtering/) page in the Ruby SDK says:

```plain
The platform or SDK you've selected either does not support this functionality, 
or it is missing from documentation.

If you think this is an error, feel free to let us know on GitHub
```

I'm very much hoping that it is an error!

**Comment by birdwell** [comment]
@ijdickinson did you ever figure out if filtering is supported?

**Comment by ijdickinson** [comment]
@birdwell Sadly not. Nor a response from the folks at Sentry so far.

**Comment by PeloWriter** [comment]
Looking into this. Thanks for flagging it.

@HazAT - we need to populate the samples for Ruby.

**Comment by PeloWriter** [comment]
@st0012 - might you take a look at this?

**Comment by st0012** [comment]
we do have a sample for `before-send` now. I added it for the new SDK around December. you can find it [in the filtering page](https://docs.sentry.io/platforms/ruby/configuration/filtering/) or the [basic options page](https://docs.sentry.io/platforms/ruby/configuration/options/).

**Comment by ijdickinson** [comment]
Confirm I can see the examples now. Thanks @st0012 and @PeloWriter !
