### ISSUE TITLE
Docs on grouping/correlation say that java doesn't support it

### ISSUE THREAD

**Issue by Daenyth** [getsentry/sentry-docs#2484]
The `SentryClient` api does expose a `setFingerprint` method, so it seems strange for the docs to say it's not supported.

https://docs.sentry.io/platforms/java/data-management/event-grouping/sdk-fingerprinting/

I feel like it used to be present in the docs but the site layout changed? I'm not sure

**Comment by bruno-garcia** [comment]
The documentation reflects our latest release, `sentry` 3.0.0.

It has a public `setFingerprint`:

https://github.com/getsentry/sentry-java/blob/main/sentry/src/main/java/io/sentry/SentryEvent.java#L219-L221

**Comment by bruno-garcia** [comment]
Closing this hoping it clarified.
Feel free to reopen otherwise.

**Comment by Daenyth** [comment]
That doc page (docs.sentry.io/platforms/java/data-management/event-grouping/sdk-fingerprinting) url now appears to contain code samples instead of the "doesn't support this" message, so whatever you changed seems to have fixed it
