### ISSUE TITLE
How to track user ip or user information to sentry

### ISSUE THREAD

**Issue by hkmsadek** [getsentry/sentry-docs#2507]
I am trying to get user information from flutter application. Is it possible with sentry?

**Comment by marandaneto** [comment]
See this thread #2655

Sentry v4 exposes a `setUser` method and sends this info along with the captured event.

You need to set this info manually though.

**Comment by marandaneto** [comment]
https://docs.sentry.io/platforms/flutter/enriching-events/identify-user/
