### ISSUE TITLE
Mention in Sentry Logback Docs that MDC is managed per Thread

### ISSUE THREAD

**Issue by SethiPandi** [getsentry/sentry-docs#2513]
This is regarding the documentation here:  
https://github.com/getsentry/sentry-docs/blob/master/src/platforms/java/guides/logback/index.mdx

_In my opinion,_ it would be nice to pull into the documentation the fact that MDC is on a per-thread basis.

This may be redundant, as it is mentioned in the Logback docs already. However, Sentry's documentation is self-contained and usable without clicking through to the Logback docs. Some users might rush through it and wonder why the MDC tab isn't appearing in Sentry, like myself.

I think it's noteworthy that MDC works in a per-thread basis only, as opposed to a global/runtime basis. 

For example, the following could be added, either under "Additional Data", or at the bottom in a new heading for technical information for users.

> Note that MDC manages data on a per-thread basis, and that a child thread does not automatically inherit MDC properties from its parent.

If this is added, it may also be worth noting that `Sentry#setExtra` is a friendly global solution which will affect all logs, as opposed to MDC.

**Comment by bruno-garcia** [comment]
By default all the `Sentry` static class method use a ThreadLocal instance. You'd need to change the Hub mode in order to change that, which is what we do on Android.

The calls you do on the main thread will mutate the main Hub which then gets cloned as you spawn new threads. Maybe that's the confusion?

**Comment by SethiPandi** [comment]
This issue is regarding the documentation in the Logback page which encourages the use of `MDC#put`, ie the methods if slf4j, not the `Sentry#` static methods.

```java
void logWithExtras() {
    // MDC extras
    MDC.put("Environment", "Development");
    MDC.put("OS", "Linux");

    // This sends an event where the Environment and OS MDC values are set as MDC entries
    logger.error("This is a test");
}
```

I'm very sorry, but I'm unfamiliar with a "Hub" or "Hub mode".
