### ISSUE TITLE
Please provide a better example for Performance monitoring and AWS Nodejs Lambda

### ISSUE THREAD

**Issue by teebu** [getsentry/sentry-docs#2540]
Page: https://docs.sentry.io/platforms/node/guides/aws-lambda/performance/
Can you include an actual AWS lambda sample, with transaction, as an addition to the sample provided on this page https://docs.sentry.io/platforms/node/guides/aws-lambda/

```
const Sentry = require("@sentry/serverless");

Sentry.AWSLambda.init({
  dsn: 'https://examplePublicKey@o0.ingest.sentry.io/0',
  tracesSampleRate: 1.0,
});

exports.handler = Sentry.AWSLambda.wrapHandler(async (event, context) => {
  // Your handler code
});
```

Where would the sample transaction go? In the root or inside the wrapped lambda function?

```
const transaction = Sentry.startTransaction({
  op: "transaction",
  name: "My Transaction",
});

// Note that we set the transaction as the span on the scope.
// This step makes sure that if an error happens during the lifetime of the transaction
// the transaction context will be attached to the error event
Sentry.configureScope(scope => {
  scope.setSpan(transaction);
});
```

**Comment by ajjindal** [comment]
@teebu Sentry will automatically pick all transactions with `traceSampleRate` greater than 0. However, if you are trying to manually capture additional transactions, you can do so by starting and ending a transaction from within the handler. We will include an example on our docs soon.
