### ISSUE TITLE
Confusing restriction for release names

### ISSUE THREAD

**Issue by juhana** [getsentry/sentry-docs#2570]
The chapter on release names at https://docs.sentry.io/platforms/javascript/configuration/releases/#bind-the-version says:

>The release name cannot:
> [..]
> * use a forward slash ("/"), back slash ("\"), period ("."), or double period ("..")

But that doesn't make sense: if you can't use one period, it's obvious that you can't use two periods either. Furthermore the immediately following example uses periods in the id: "my-project-name@2.3.12"

Should it say instead that you can't start or end the id with a period, or something else?

**Comment by juhana** [comment]
Issue still exists

**Comment by PeloWriter** [comment]
Fixed in PR 2856. Thanks.
