### ISSUE TITLE
Meta Information and Attributes have the same url

### ISSUE THREAD

**Issue by lucas-zimerman** [getsentry/sentry-docs#2601]
![image](https://user-images.githubusercontent.com/8229322/97336229-878b2380-185d-11eb-8226-8db6aa115d6d.png)

source: https://develop.sentry.dev/sdk/event-payloads/exception

**Comment by silent1mezzo** [comment]
Thanks for reporting @lucas-zimerman seems like it was a gatsby build issue since I can't replicate.
