### ISSUE TITLE
Documentation showcases usage of depreciated sentry fastlane action

### ISSUE THREAD

**Issue by andon** [getsentry/sentry-docs#261]
The documentation page for [Uploading Debug Symbols](https://docs.sentry.io/clients/cocoa/dsym/) is showing fastlane integration via the deprecated fastlane action: [upload_symbols_to_sentry](https://docs.fastlane.tools/actions/upload_symbols_to_sentry/).

I think it should be updated to use the following [sentry-fastlane-plugin](https://github.com/getsentry/sentry-fastlane-plugin).

**Comment by christhegrand** [comment]
I just opened a similar issue with Fastlane: https://github.com/fastlane/fastlane/issues/14608

**Comment by christhegrand** [comment]
This has still not been fixed.

**Comment by hojatdelfan** [comment]
This action (upload_symbols_to_sentry) is deprecated
Please use the `sentry` plugin instead.
Install using `fastlane add_plugin sentry`.
Replace `upload_symbols_to_sentry(...)` with `sentry_upload_dsym(...)`.
----------------------------------------------------------------------
In fact, its fields were changed below:
url, auth_token, api_key, org_slug, project_slug, dsym_path, dsym_paths, symbol_maps, info_plist

Finally:
sentry_upload_dsym(
      url: "https://app.getsentry.com/api/0",
      auth_token: "...",
      org_slug: "...",
      project_slug: "...",
      dsym_path: "./App.dSYM.zip"
    )

**Comment by PeloWriter** [comment]
Sorry, bot, we're still fixing this.

**Comment by PeloWriter** [comment]
The Cocoa docs have been fully updated with our newer Cocoa SDK, which you can read about [here](https://docs.sentry.io/platforms/apple/)
