### ISSUE TITLE
Missing documentation for setting Customize Tags (and other configuration pages) for Dart/Flutter

### ISSUE THREAD

**Issue by yuhang04210** [getsentry/sentry-docs#2655]
Currently, Sentry uses the Dart library  for the[ Customize Tags](https://docs.sentry.io/platforms/flutter/enriching-events/tags/) . However , It says The platform or SDK you've selected either does not support this functionality, or it is missing from documentation.

**Comment by bruno-garcia** [comment]
Are you trying our 4.0.0-alpha already? Or 3.0.1?

**Comment by bruno-garcia** [comment]
We're working on 4.0,0 docs : https://github.com/getsentry/sentry-docs/pull/2599

If you're trying our new 4.0.0 version (first, thank you), the preview docs are here:

https://sentry-docs-git-ref-flutter-v4.sentry.dev/platforms/flutter/enriching-events/tags/

**Comment by marandaneto** [comment]
sorry late reply, yes as you can see, we already have a PR but we are going to merge it when we reach a beta or GA version of the SDK, right now it's an alpha and under development, the current PR for docs don't contain the specific bits for Flutter.

Please let us know if you are trying out the v4 alpha, feedback is welcomed, thanks.

**Comment by bruno-garcia** [comment]
It's resolved: https://docs.sentry.io/platforms/flutter/enriching-events/tags/
