### ISSUE TITLE
Ruby SDK Fingerprinting

### ISSUE THREAD

**Issue by donaldong** [getsentry/sentry-docs#2671]
Currently on [Sentry doc](https://docs.sentry.io/platforms/ruby/data-management/event-grouping/sdk-fingerprinting/),
> The platform or SDK you've selected either does not support this functionality, or it is missing from documentation.

But the latest Raven gem support sending events by fingerprint: https://github.com/getsentry/sentry-ruby/blob/7a0cebc54c5508d379769c7af688c8218721d734/spec/raven/event_spec.rb#L799

Extend default:
```ruby
Raven.capture_exception(StandardError.new('foo'), fingerprint: ['{{ default }}', 'foo'])
```

Overwrite default:
```ruby
error = StandardError.new('foo')
Raven.capture_exception(error, fingerprint: [error.inspect])
```

**Comment by HazAT** [comment]
cc @st0012

**Comment by PeloWriter** [comment]
@st0012 - please let me know if we can update to add the missing samples.

**Comment by st0012** [comment]
I'm working on the examples now. will open a PR soon.
