### ISSUE TITLE
Content partially hidden when navigating to an anchor

### ISSUE THREAD

**Issue by rhcarvalho** [getsentry/sentry-docs#2685]
This is most likely a CSS issue.

Current behavior when going to https://docs.sentry.io/platforms/go/#configure:

![image](https://user-images.githubusercontent.com/88819/99060523-73a32980-25a0-11eb-82f8-9ec6e6659e29.png)

---

What it should be instead:

![image](https://user-images.githubusercontent.com/88819/99060563-80278200-25a0-11eb-9842-eb0fd576d7cd.png)

**Comment by PeloWriter** [comment]
This issue still exists.
