### ISSUE TITLE
Not confident about using setExtra

### ISSUE THREAD

**Issue by craigdallimore** [getsentry/sentry-docs#2726]
Hello

We are using the sentry javascript SDK. I've just noticed that `setExtra` is possibly deprecated, per the section "Extra data, Additional data" on [this page](https://docs.sentry.io/platforms/javascript/enriching-events/context/).

We're presently using `setExtra` on version `5.21.x` and haven't seen any deprecation warnings. I'm not sure if it is safe or not to use that method; the documentation says:

> If you come across any usages of "extra" (setExtra in code) or "Additional Data" (in the UI), just mentally substitute it for context. Extra is deprecated in favor of context within most SDKs.

For clarity: should/must we stop using `setExtra` and use `setContext` instead?

**Comment by untitaker** [comment]
@craigdallimore we just stopped recommending it in docs, but as far as removal from SDKs goes we still have to initiate a proper deprecation phase. It may be that we are never going to remove it, but this decision is done per-SDK. I doubt JS is going to remove it anytime soon.

The deprecation note in the docs is purely there to help people understand existing code. It's not meant as a substitute for proper deprecation announcement or changelog entry.

should yes, must no.
