### ISSUE TITLE
Several Sentry.init

### ISSUE THREAD

**Issue by happylolonly** [getsentry/sentry-docs#2753]
We have the app that uses remote configuration, after request, and Sentry key will be there.
I thought to add some temp key to init Sentry at the beginning of the React app, but 2 `Sentry.init` doesn't work. (second not called), possible somehow to do it?

**Comment by happylolonly** [comment]
Still interested

**Comment by PeloWriter** [comment]
This isn't a documentation issue, but you are welcome to use the forum (forum.sentry.io) to ask or contact support.
