### ISSUE TITLE
Create Kotlin code snippets anywhere we have Java

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-docs#2777]
All the Java code examples could have a Koltin one too:

https://github.com/getsentry/sentry-docs/tree/master/src/includes

The Kotlin code will go inside the same file as the Java one.

Similar to the .NET code samples that have C# and F#:

https://github.com/getsentry/sentry-docs/blob/master/src/includes/set-tag/dotnet.mdx

![image](https://user-images.githubusercontent.com/1633368/102792032-e6f54380-4375-11eb-892d-82fb5f2c7cfd.png)

**Comment by bruno-garcia** [comment]
Adding to it: Anywhere we have Java code snippets, which include Android ;)

https://github.com/getsentry/sentry-docs/tree/master/src/platforms/android

There are some more snippets here:

https://github.com/getsentry/sentry-docs/tree/master/src/platforms/java

**Comment by bruno-garcia** [comment]
Hit `t` and search for `java.mdx` and `android.mdx`:

![image](https://user-images.githubusercontent.com/1633368/104468649-af994180-5585-11eb-8f46-ddf2867cdac1.png)

![image](https://user-images.githubusercontent.com/1633368/104468695-baec6d00-5585-11eb-9d28-c49bce323a6b.png)

**Comment by marandaneto** [comment]
This is done, we can iterate if we find missing ones
