### ISSUE TITLE
Is sentry-docs/src/platforms/php/common/default-integrations.mdx correct?

### ISSUE THREAD

**Issue by gnumoksha** [getsentry/sentry-docs#2781]
The [page](https://docs.sentry.io/platforms/php/default-integrations/) shows 4 integrations, but `\Sentry\Integration\IntegrationRegistry::getDefaultIntegrations` has 7.

I had to disable `FatalErrorListenerIntegration` and having only `RequestIntegration`, `ErrorListenerIntegration`, and `ExceptionListenerIntegration` enabled seems to decrease the information I see on sentry.io.

**Comment by gnumoksha** [comment]
ping

**Comment by PeloWriter** [comment]
@HazAT - can you please review?
