### ISSUE TITLE
Java: Add new tags configuration to migrations

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-docs#2801]
The Java migration docs is missing APIs added as feedback of the 3.0 release.

Such as adding default tags:
https://docs.sentry.io/platforms/java/guides/spring-boot/configuration/#options

**Comment by maciejwalkowiak** [comment]
Tags are already there, the only properties that were missing were `inAppIncludes` and `inAppExcludes` that have been added with: https://github.com/getsentry/sentry-docs/pull/2816

**Comment by bruno-garcia** [comment]
Oh, my bad. Thanks.
