### ISSUE TITLE
Drop `dotnet` wizard in favor of `C#` and `F#`

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-docs#2805]
It's a general source of confusion to users because no one is writing `.NET`.
Folks write C# mostly, other popular languages are VB and F#.

The goal: Add `C# WinForms`, `F# WinForms`, `C# ASP.NET` etc.

Having `.NET` there might still be OK while we figure out if that's even used. But should be removed from the "popular" list. There we can add `C# ASP.NET Core` instead.

Example:
![image](https://user-images.githubusercontent.com/1633368/102920630-0fa23980-4459-11eb-94b3-8ce503472908.png)

Related:
* aspnet wizard #2804
* feat(wizard): winforms #2800
* feat: dotnet wpf #2799

**Comment by PeloWriter** [comment]
I can incorporate this into the work on .NET

**Comment by bruno-garcia** [comment]
fyi @bitsandfoxes @jamescrosswell

**Comment by stephanie-anderson** [comment]
@bruno-garcia is this talking about the in-product onboarding flow?

**Comment by bruno-garcia** [comment]
now that we have .NET showing the framework choices I think we can close this

![image](https://github.com/getsentry/sentry-docs/assets/1633368/dcbb5b12-31bf-4313-8139-2bfff8a179b1)
