### ISSUE TITLE
Provide a description for acceptable key/value parameters in "Customize tags"

### ISSUE THREAD

**Issue by deeTEEcee** [getsentry/sentry-docs#2823]
In raven-python, we pass in tags through a dict object but some of our keys have slashes in it and it looks like slashes aren't accepted. Apparently, they get dropped but one tag called "release" ends up with "Error: invalid data." 

The errors aside, a description in the docs (e.g: only alphanumeric characters are accepted, length of only up to 32, etc.) would help users out here as I've noticed this kind of error has also been posted in many different locations (sentry forums, the raven client issues pages, etc.).

**Comment by PeloWriter** [comment]
Thanks for writing in. The Raven Python SDK is deprecated, so we won't be updating the documentation for it any more. We have handy [migration guide](https://docs.sentry.io/platforms/python/migration/) to help you get to a current version.

**Comment by deeTEEcee** [comment]
@PeloWriter I think you misunderstand me. I'm referring to https://docs.sentry.io/platforms/python/enriching-events/tags/ for all languages.

**Comment by PeloWriter** [comment]
Thanks for writing back to clarify. Yes, I thought you were referring only to Raven Python.

I'll reopen. Focusing on "description in the docs (e.g: only alphanumeric characters are accepted, length of only up to 32, etc.) would help users out here as I've noticed this kind of error has also been posted in many different locations."

cc: @HazAT

**Comment by vivianyentran** [comment]
Closing as the docs have been updated to clarify acceptable values:

> Tag keys have a maximum length of 32 characters and can contain only letters (a-zA-Z), numbers (0-9), underscores (_), periods (.), colons (:), and dashes (-).

> Tag values have a maximum length of 200 characters and they cannot contain the newline (\n) character.
