### ISSUE TITLE
Support to get only Major version from release registry

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-docs#2829]
Today we retrieve version as `{{ packages.version('sentry.cocoa') }}`

We'd like to specify for example: `{{ packages.version('sentry.cocoa', 'major') }}` so only `6` comes instead of `6.0.13`

Value is fetched: https://github.com/getsentry/sentry-release-registry

/cc @HazAT

**Comment by philipphofmann** [comment]
As discussed with @HazAT, he has no objections to this change.

**Comment by stephanie-anderson** [comment]
@bruno-garcia @philipphofmann would this still be needed?

**Comment by philipphofmann** [comment]
I can't recall why we wanted this. If @bruno-garcia has no objections, I'm fine closing the issue.

**Comment by bruno-garcia** [comment]
No idea why we'd want this :D sorry
