### ISSUE TITLE
Alert time window documentation is unclear

### ISSUE THREAD

**Issue by daotoad** [getsentry/sentry-docs#2838]
The Metric Alerts section on [Time Windows](https://docs.sentry.io/product/sentry-basics/guides/alert-notifications/metric-alerts/#3-choose-a-time-window) says:

> 3: Choose a Time Window
> 
> Decide how often you want your metric evaluated. Your choices range between one minute and four hours.
> 
> Triggers are evaluated every minute, regardless of this value.

What is not clear is what data is used when the triggers are evaluated.

Is the trigger evaluated against a moving window or a series of buckets of data?

Assume we have an alert that is triggered by more than 60 events in an hour:
* do we start a new bucket every hour and check once a minute to see if we have exceeded 60 events in that bucket?
* Or do we look at the last hour and see if the total number of events in that range is greater than 60?

The use of the term "time window" would lead me to believe that the latter is true.  But the UI shows a graph that is plotted based on the former approach.

**Comment by wedamija** [comment]
@daotoad Metric alerts are evaluated every minute, and look back over the last `time_window` period of time. So for an hour `time_window`, we'd evaluate:
 - 2:00pm-3:00pm
 - 2:01pm-3:01pm
 - 2:02pm-3:02pm
 - etc

**Comment by PeloWriter** [comment]
Closing as we have updated the docs. Thanks for letting us know this was confusing.
