### ISSUE TITLE
Elixir docs missing for `before_send_event`

### ISSUE THREAD

**Issue by Bastes** [getsentry/sentry-docs#2854]
[Here's the page](https://docs.sentry.io/platforms/elixir/configuration/filtering/)

The page metions a `beforeSend` callback which seems to fit the actual `before_send_event` I see in the source code and tests but gives no information nor examples as to how to leverage it to send events to the sentry servers.

**Comment by Bastes** [comment]
Wasn't the status "Accepted"?

**Comment by chadwhitacre** [comment]
Yes, sorry @Bastes, bot rampage due to human error from yours truly. 😞 Corrected now!

**Comment by imatwawana** [comment]
Resolved on [PR 4330](https://github.com/getsentry/sentry-docs/pull/4330)
