### ISSUE TITLE
Fix Data Filtering IA

### ISSUE THREAD

**Issue by PeloWriter** [getsentry/sentry-docs#2870]
In Release Health, we have a section regarding Data Filtering. It's not the right place:

- [x] Move this content to be part of our content in Product > Error Monitoring > Inbound Data Filters @PeloWriter 
- [x] Move Inbound Data Filters to Product > Data Management
- [x] In the Error Monitoring section of the filters page, develop content that clarifies each of our filtering types (perhaps a page for each, including examples of usage) - the content has been moved, but we need to further develop this content
- [ ] Explain how sampling works @RaduW

**Comment by PeloWriter** [comment]
PR here that captures the first item here - https://github.com/getsentry/sentry-docs/pull/2885

**Comment by doralchan** [comment]
@PeloWriter These filters are also applicable under transactions

**Comment by PeloWriter** [comment]
Based on @doralchan 's comment, we should move this out of Error Monitoring once filters apply to xns, as well.

**Comment by jan-auer** [comment]
@PeloWriter updated the issue description, to reflect our last discussion. This must've mixed up somewhere in note taking. We discussed to move this under "Data Management".

**Comment by PeloWriter** [comment]
ah, great catch. Thanks. I was going to make that suggestion, so glad we are aligned. I will incorporate this location change also since the content work has begun in https://github.com/getsentry/sentry-docs/pull/2885

**Comment by PeloWriter** [comment]
For this iteration, we can close the issue. Data Filtering IA is current for feature set.
