### ISSUE TITLE
Provide session examples

### ISSUE THREAD

**Issue by PeloWriter** [getsentry/sentry-docs#2892]
The definition of what a session is varies by platform. This concerns the [Health page](https://docs.sentry.io/product/releases/health/#release-health-data).

- [x] We should provide a general notion of what a session is (along the lines of "a continuous interaction of a user with your application") and then give examples for various platforms.
- [x] The terminology list on the health page mixes session statuses and release health metrics. We can better structure this by grouping the session statuses together
- [x] There is no explanation of what a "user" is. Also, the description of "crash free users" and "active users" is lacking detail.

**Comment by jan-auer** [comment]
Updated the PR description. I would propose the following structure (pending proper naming):

```
release health data
- session
  - crash
  - abnormal
  - errored
- user
- release & environment

release health {metrics,features}:
- session & user counts
- crash free sessions & users
- adoption
```
