### ISSUE TITLE
Create a wizard for Spring, logback, log4j2

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-docs#2897]
Original issue: https://github.com/getsentry/sentry-java/issues/1167

**Comment by PeloWriter** [comment]
I'll make these updates, if you'd like me to, @marandaneto.

**Comment by marandaneto** [comment]
please go ahead @PeloWriter :) thank you.

**Comment by PeloWriter** [comment]
I'm also going to update Spring Boot, as it's out of date.

**Comment by PeloWriter** [comment]
Closing as these are now complete.
