### ISSUE TITLE
Explain Release Navigation

### ISSUE THREAD

**Issue by PeloWriter** [getsentry/sentry-docs#2903]
Create a doc (likely best candidate= release index page) that shows how to navigate around:

You get to release details here by clicking the project name, not by clicking the commit, at the moment. Alternately, rather than through the "Releases" side bar, first load the details of an issue and then look at the right sidebar for the "last seen", then click on the release ID.

**Comment by armenzg** [comment]
Documenting your comment visually.

Through an issue on the right side click on the SHA commit:
![image](https://user-images.githubusercontent.com/44410/104773239-bd47f600-5742-11eb-9947-3c1bcffbf5be.png)

Through the releases page by clicking the project name:
![image](https://user-images.githubusercontent.com/44410/104773254-c5079a80-5742-11eb-878d-84ac45849183.png)

**Comment by PeloWriter** [comment]
PR here - https://github.com/getsentry/sentry-docs/pull/2905
