### ISSUE TITLE
Fix Java/Kotlin code snippets for Performance API

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-docs#2912]
Breaking changes were introduced on https://github.com/getsentry/sentry-java/pull/1165 and https://github.com/getsentry/sentry-java/pull/1188
we'd need to reflect them on docs once it's released.

**Comment by marandaneto** [comment]
cc @maciejwalkowiak

**Comment by maciejwalkowiak** [comment]
Covered in #2833

**Comment by PeloWriter** [comment]
Let me know if this is appropriately captured in https://github.com/getsentry/sentry-docs/pull/2970
