### ISSUE TITLE
Mobile: Capacitor docs and wizard

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-docs#2919]
The new Sentry Capacitor plugin is [getting closed to have its first preview](https://github.com/getsentry/sentry-capacitor/issues/21) bits released on npm (for Android only).

- [x] Add docs: Docs for writing docs [is here](https://docs.sentry.io/contributing/approach/write-getting-started/). The goal is a top level platform like `/platforms/capacitor`, with fallback to JavaScript. Note that it's preview and only Android is supported.
- [ ] Add a Wizard: Similar to [this](https://github.com/getsentry/sentry-docs/blob/master/src/wizard/android/index.md), create a folder `capacitor` and add `index.md`
- [x] Get logo in: https://github.com/getsentry/platformicons/issues/32

/cc @cSparkle

**Comment by PeloWriter** [comment]
Sorry, bot, still working on this.

**Comment by PeloWriter** [comment]
Looks like we're almost there. We don't yet seem to have developed the wizard for this, @bruno-garcia

**Comment by bruno-garcia** [comment]
@PeloWriter Wizard is coming as soon as we get some stable bits out which is indeed super close.

**Comment by bruno-garcia** [comment]
Done through #3859
