### ISSUE TITLE
Create an `ionic` wizard

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-docs#2925]
Today using cordova, but once capacitor is out we should also include it.

**Comment by bruno-garcia** [comment]
The wizard could list the supported integrations: 
Install cordova, and `@sentry/angular` for example. And also include the performance monitoring setup like the Angular wizard.

A note that only cordova is supported by Capacitor "coming soon". Linking to https://github.com/getsentry/sentry-cordova/issues/154

**Comment by bruno-garcia** [comment]
Logo landing on: https://github.com/getsentry/sentry-docs/pull/3321

**Comment by PeloWriter** [comment]
Since we've updated labels, this one needed proper labeling for triage.

**Comment by bruno-garcia** [comment]
Now that we have capacitor and Cordova we could tackle this but while the 3izqrd is a single page it makes this rather hard. Unless we add a single wizard for each: Ionic Angular Capacitor. Ionic Cordova Angular.
Ionic Capacitor Vue.

And wouldn't allow us selecting npm vs yarn or TypeScript vs JavaScript
