### ISSUE TITLE
Java/Android docs say "automatically sending traces " which is incorrect

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-docs#2956]
![image](https://user-images.githubusercontent.com/1633368/106059869-58d15300-60c1-11eb-8d06-c475e49ce6a5.png)

https://docs.sentry.io/platforms/android/performance/

**Comment by PeloWriter** [comment]
I can include this fix in the PR I'm working on for Performance SDK docs.

**Comment by bruno-garcia** [comment]
Thank you Fiona. I hit "edit" but saw there was some includes going on and I can't pick this up now. Appreciate if this can get fixed soon since it's a bad confusion to have

**Comment by marandaneto** [comment]
my bad, we've reused the Java docs but the "automatically" wording only fits the auto instrumentation on Java/Spring but not on Android, yet.

**Comment by marandaneto** [comment]
I did a quick workaround as we went GA already, thanks!

**Comment by PeloWriter** [comment]
Fixing as part of https://github.com/getsentry/sentry-docs/pull/2970
