### ISSUE TITLE
[Ruby] Confusion on how to configure asynchronous notification

### ISSUE THREAD

**Issue by cecilian** [getsentry/sentry-docs#2958]
Hello,
In the "Configuration options", under the description for the `async` setting it says:

> When an error or message occurs, the notification is immediately sent to Sentry, synchronously. This means that returning a response to a user may be delayed.
> We recommend creating a background job, using your background job processor, that will send Sentry notifications. 

But right after that, under the `background_worker_threads`, it says:

> If config.async isn't provided, Sentry will send events in a non-blocking way with its own background worker. 

Therefore it is unclear what the default is.
What does happen if one does *not* set either `config.async` or `config.background_worker_threads`? Is the notification sent "synchronously" or " in a non-blocking way with its own background worker"? 

Thank you

**Comment by PeloWriter** [comment]
@st0012 - can you take a look.

cc: @HazAT
