### ISSUE TITLE
Java JUL docs and migration page (JUL bits) from Java 1.x to 4.x

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-docs#2973]
https://github.com/getsentry/sentry-java/pull/1211 and https://github.com/getsentry/sentry-java/issues/1037

**Comment by marandaneto** [comment]
cc @maciejwalkowiak

**Comment by marandaneto** [comment]
https://docs.sentry.io/platforms/java/guides/jul/

**Comment by scoopex** [comment]
Thanks for your work. We builded a simple Jboss Module for Keycloak based on your work, many thanks!

https://github.com/flip-corp/keycloak-sentry
