### ISSUE TITLE
Add Unreal Engine platform

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-docs#2981]
We support the Unreal engine via the Native platform, see https://docs.sentry.io/platforms/native/guides/ue4/

It's missing which platforms are supported though, probably Win and Linux only? @jan-auer 

It's also possible to develop mobile games with Unreal but it's unclear if we whether support it or not, this raised this issue:
https://github.com/getsentry/sentry-java/issues/1210

Ideally, we'd have its own Unreal platform under the docs that links to the desired platform, for example, redirecting Win/Linux to the Native platform, but if Android or iOS, link to the Android or iOS platform, so people could add them directly as we don't support as a 1st class citizen SDK like Flutter for example (Add one SDK and works for all platforms), yet.

**Comment by bruno-garcia** [comment]
The crashreporter works on Windows, Linux and macOS.

We could lift Unreal Engine to be a top level platform (like Unity) with a fallback to native (like Android->Java).

Then we can also add docs for Android and iOS under Unreal Engine (per #1210)

**Comment by marandaneto** [comment]
> Then we can also add docs for Android and iOS under Unreal Engine (per #1210)

wrong #ID?

**Comment by bruno-garcia** [comment]
> > Then we can also add docs for Android and iOS under Unreal Engine (per #1210)
> 
> wrong #ID?

Fixed. Tks

**Comment by bruno-garcia** [comment]
I merged this: https://github.com/getsentry/sentry-docs/pull/3005 but the platform now under `native` is called `ue4`.

Ideally when moving it to top-level, and naming the platform, call it `unreal`.

**Comment by bruno-garcia** [comment]
The key to be: `unrealengine`: https://github.com/getsentry/platformicons/pull/34

Didn't add a `-` because it's what's used to nest platforms.

**Comment by jan-auer** [comment]
Moving Unreal Engine to a top-level platform aligns with our [platform delineation guides](https://docs.sentry.io/contributing/platforms/#delineation). As for what we call it, I'm uncertain. `unreal` is shorter for the URL and slub, but in the UI we should probably spell out the full "Unreal Engine". 

We support all three platforms: Windows, Linux, and macOS. The latter is slightly different internally as it sends AppleCrashReports, but regardless we do offer the same level of support on all platforms.

**Comment by bruno-garcia** [comment]
I suggest we call it `unreal-engine`. We called `unreal` in the UE4 endpoint because it was shorter but I believe for a URL it'll be better to be more descriptive.

Also UE5 was announced so we don't want to use ue4 as version info will be sub pages.

**Comment by bruno-garcia** [comment]
Changing my mind here and agree with @jma that `unreal` is best
