### ISSUE TITLE
Double-check missing mobile options

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-docs#2985]
Double-check if there are missing options for all the mobile SDKs (src/platforms/common/configuration/options.mdx), 
I suspect there are a few of them either missing the supported platform, or a new option should be added to the docs as it's not supported by non-mobile SDKs, eg `anrEnabled` for Android would be one of them.

See related issues:
#2879
#2924

**Comment by PeloWriter** [comment]
Here's guidelines on [how to update](https://docs.sentry.io/contributing/approach/write-configuration/#basic-options) the file (and please ping me with any question).

**Comment by PeloWriter** [comment]
Added `transport`, 'auto-session-tracking`, and `integrations` to Flutter.

**Comment by PeloWriter** [comment]
From @marandaneto - For `auto-session-tracking`, unrelated to this PR but on RN it is `enableAutoSessionTracking` not `autoSessionTracking`, I think it falls back to JS as it's being shown @PeloWriter
For `cache-directory-path` RN does not offer it, the user would need to init the Android SDK manually to do so.

**Comment by bruno-garcia** [comment]
Java/Android have the wrong option name (and wrong default for Android):

https://docs.sentry.io/platforms/android/configuration/options/#cache-directory-path

**Comment by marandaneto** [comment]
Flutter supports `anrEnabled`

**Comment by marandaneto** [comment]
.NET supports `ExceptionFilters ` https://github.com/getsentry/sentry-docs/pull/3731#discussion_r650762949

**Comment by bruno-garcia** [comment]
> .NET supports `ExceptionFilters ` [#3731 (comment)](https://github.com/getsentry/sentry-docs/pull/3731#discussion_r650762949)

Only through an extension method that takes the type argument: https://docs.sentry.io/platforms/dotnet/usage/#ignoring-errors

**Comment by marandaneto** [comment]
I've created an issue per platform.
