### ISSUE TITLE
React-native auto instrumentation docs

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-docs#2995]
Reflect changes from RN 2.2 GA on the docs:

https://github.com/getsentry/sentry-react-native/issues/1272

**Comment by marandaneto** [comment]
please open a PR on top of https://github.com/getsentry/sentry-docs/pull/2970 so we avoid conflicts.

**Comment by jennmueng** [comment]
Alright, thanks for creating the issue @marandaneto , will get right on it.
