### ISSUE TITLE
Building docs should break if version can't be resolved.

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-docs#3004]
When resolving a version from the release-registry fails, the docs should break completely.

This way we can troubleshoot the issue and avoid publishing docs and wizard with broken installation instructions.

i.e:
![image](https://user-images.githubusercontent.com/1633368/106669451-ba8a3500-6579-11eb-88bf-2cc0c484f5af.png)

**Comment by a-hariti** [comment]
Can we have a concrete repro of this issue? @stephanie-anderson @bruno-garcia
