### ISSUE TITLE
Missing documentation for SDK fingerprinting for PHP

### ISSUE THREAD

**Issue by spawnia** [getsentry/sentry-docs#3035]
## Important Details

This an issue with: PHP SDK documentation

## Description

I was trying to figure out how to add addtional fingerprinting onto some of the errors thrown in my PHP application and thus went to: https://docs.sentry.io/platforms/javascript/data-management/event-grouping/sdk-fingerprinting/

### What you expected to happen

I would like to see code snippets that inform me of a correct and idiomatic implementation.

### Possible Solution

Add code snippets similar to https://docs.sentry.io/platforms/javascript/data-management/event-grouping/sdk-fingerprinting/

Also, hi @stayallive 👋

**Comment by stayallive** [comment]
Oh, I would also expect some snippets there, let me fix that 👍

**Comment by spawnia** [comment]
Let me hit you with my current guess:

```php
// Those messages come from within graphql-php.
// They have pretty stable messages but can stem from many underlying issues,
// so we split them up for better granularity in the created Sentry issues.
if ($e instanceof InvariantViolation) {
    withScope(function (Scope $scope) use ($sentry, $e) {
        $scope->setFingerprint(['{{ default }}', $e->getMessage()]);
        $sentry->captureException($e);
    });

    return;
}
```

**Comment by stayallive** [comment]
That's exactly right! Thanks for that 😉
