### ISSUE TITLE
Document new ProGuard mapping location in settings.

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-docs#3046]
We're moving the proguard mapping file from the `Debug Info` into its own page under project settings.
Any links or texts pointing user to "debug info" must be updated once the feature flag is dropped.

**Comment by marandaneto** [comment]
nothing to be changed on https://docs.sentry.io/platforms/android/proguard/ and https://docs.sentry.io/product/cli/dif/#proguard-mapping-upload

we need to special case ProGuard on this page https://docs.sentry.io/platforms/android/data-management/debug-files/

probably only this sentence:

> Debug information files can be managed on the Debug Files section in Project Settings. This page lists all uploaded files and allows to configure symbol servers for automatic downloads.

@PeloWriter do you know if we should change this elsewhere? reason is https://github.com/getsentry/sentry/pull/23835
as ProGuard has its own menu on project settings now

**Comment by PeloWriter** [comment]
I think we also need to modify this for Android on this page https://docs.sentry.io/platforms/android/data-management/debug-files/symbol-servers/:

> To configure external repositories, go to Project Settings > Debug Files. Above the list of uploaded files, there are two settings to configure external repositories:

**Comment by PeloWriter** [comment]
And here, we mention Project Settings > Debug Files (this page also is missing a code sample):
https://docs.sentry.io/platforms/android/data-management/debug-files/upload/

> In Sentry, your uploaded files are associated with projects. You can view and manage uploads at Project Settings > Debug Files. This screen displays the most important properties of debug files:

**Comment by bruno-garcia** [comment]
> I think we also need to modify this for Android on this page [docs.sentry.io/platforms/android/data-management/debug-files/symbol-servers](https://docs.sentry.io/platforms/android/data-management/debug-files/symbol-servers/):
> 
> > To configure external repositories, go to Project Settings > Debug Files. Above the list of uploaded files, there are two settings to configure external repositories:

That one stays because "Debug File" and "Symbol Server" is still the same, related to native.

**Comment by bruno-garcia** [comment]
> And here, we mention Project Settings > Debug Files (this page also is missing a code sample):
> [docs.sentry.io/platforms/android/data-management/debug-files/upload](https://docs.sentry.io/platforms/android/data-management/debug-files/upload/)
> 
> > In Sentry, your uploaded files are associated with projects. You can view and manage uploads at Project Settings > Debug Files. This screen displays the most important properties of debug files:

This one also stays.

Having ProGuard mixed up in that was the actual problem, since they are different.
