### ISSUE TITLE
Mobile SDKs: Add list of features

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-docs#3063]
It often comes up: Does the X SDK support Y feature?

We're missing a page in the docs that lists what features the SDK have.
Ideally it would split in what you get from simply calling `init`, and what you can get with additional configuration or using the API

This page could be built using the feature map provided by the release registry:

https://github.com/getsentry/sentry-release-registry/issues/39

**Comment by PeloWriter** [comment]
Let's discuss how best to publish this - would be a nice quick reference if we then link it to the content for that SDK.

**Comment by bruno-garcia** [comment]
OK. I was thinking each SDK would get a new page, in that case there woudn't need such link. You have something else in mind?

@ndmanvar might have ideas too

**Comment by PeloWriter** [comment]
This section of the page could include a bulleted list of supported features:
![Screen Shot 2021-02-17 at 10 50 27 AM](https://user-images.githubusercontent.com/61481573/108252840-f393df00-710d-11eb-8b92-068c98ed0cb0.png)

By linking, I had meant we could then link them how to set it up or how to use (depending on the feature). But that can be a next step if it's not programmatically feasible for the first iteration.

**Comment by bruno-garcia** [comment]
For now the feature list is being added to the getting started page. That information will be used to seed the registry once getsentry/sentry-release-registry#39 is done
