### ISSUE TITLE
Documentation needed for Apple Privacy Questionnaire

### ISSUE THREAD

**Issue by zackdotcomputer** [getsentry/sentry-docs#3072]
## Important Details

This an issue with: 

SDK documentation

iOS SDK

## Description

As a developer submitting an app that uses Sentry, I need to declare to Apple what data my app and any third party SDKs collect. It would be helpful if there was clear guidance about what data Sentry's SDK collected that needs to be declared to Apple.

### What you expected to happen

That page should exist in the iOS SDK documentation.

### Possible Solution

Create the page?

**Comment by zackdotcomputer** [comment]
Please don't close it action bot

**Comment by bruno-garcia** [comment]
We put up some content to address this:
https://docs.sentry.io/product/security/mobile-privacy/#apple-app-store

Feel free to reopen this issue if something is missing
