### ISSUE TITLE
Document ASP.NET Core Performance Monitoring

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-docs#3090]
In order to get transactions from ASP.NET Core users must add the tracing middleware.

Propagating traces work out of the box if they use HttpClientFactory, otherwise adding the `HttpMessageHandler` is required.

These are not documented yet.

These go into _included instrumentation_, like Spring Boot's:

https://docs.sentry.io/platforms/java/guides/spring-boot/performance/included-instrumentation/

/cc @Tyrrrz

**Comment by PeloWriter** [comment]
Guidelines here - https://docs.sentry.io/contributing/approach/write-performance/
