### ISSUE TITLE
Contribution to documentation is complicated for non-MacOS users

### ISSUE THREAD

**Issue by scoopex** [getsentry/sentry-docs#3092]
## Important Details

The [contribution guide](https://docs.sentry.io/contributing/environment/) does not provide a procedure for linux users.

This complicates contribution for linux users because we cannot review the results before creating pull requests.

## Description

Edit and crontribute documentation.

### What you expected to happen

Start to write documentation without doing extended research about the necessary tooling.

### Possible Solution

A installation procedure to documentation tooling on linux.

**Comment by scoopex** [comment]
duplicate to: #3091

**Comment by PeloWriter** [comment]
Thanks for raising this issue. Is it a reasonable workaround to use the preview option by creating a draft PR, then checking the preview option?
![Screen Shot 2021-02-16 at 9 07 08 AM](https://user-images.githubusercontent.com/61481573/108096922-5c0f8d00-7036-11eb-9bee-dfbb46d9030d.png)

**Comment by a-hariti** [comment]
the current way to getting started is especially optimized for a Unix like OS
