### ISSUE TITLE
Python docs defines but doesn't use transaction

### ISSUE THREAD

**Issue by alxu-sentry** [getsentry/sentry-docs#3103]
https://docs.sentry.io/platforms/python/performance/custom-instrumentation/#add-more-spans-to-the-transaction defines a variable `transaction` but doesn't actually use it. This issue was pointed out at https://github.com/getsentry/sentry-docs/pull/2741#pullrequestreview-543249849 but not resolved there. I think applying the suggested change doesn't actually make sense though, since then we just have two identical code blocks. I'm inclined to say that this whole section should be cut down and simply recommend `sentry_sdk.start_span`.

**Comment by alxu-sentry** [comment]
@untitaker @rhcarvalho

**Comment by untitaker** [comment]
opened a PR, thanks
