### ISSUE TITLE
Android and Java SDK right-bar links not showing up

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-docs#3127]
We've recently [added Java and Android to the SDK release registry](https://github.com/getsentry/sentry-release-registry/pull/41).

One of the things this enables is displaying the extra information about the SDK on the docs.

For example, Python:
![image](https://user-images.githubusercontent.com/1633368/108442876-cd616280-7225-11eb-8ad1-9dd7f8e861e6.png)

The SDK name is defined in the `config.yml`:
https://github.com/getsentry/sentry-docs/blob/00f85e3a3d48a3596c9fef5161e2082e0d433d99/src/platforms/python/config.yml#L4

Which matches the release registry:
https://github.com/getsentry/sentry-release-registry/blob/8b74a094880ad033fa556fcb2c6f7f3b5488e4ee/sdks/sentry.python

The Java and Android SDKs:

https://github.com/getsentry/sentry-docs/blob/00f85e3a3d48a3596c9fef5161e2082e0d433d99/src/platforms/android/config.yml#L4
https://github.com/getsentry/sentry-release-registry/blob/8b74a094880ad033fa556fcb2c6f7f3b5488e4ee/sdks/sentry.java.android

https://github.com/getsentry/sentry-docs/blob/00f85e3a3d48a3596c9fef5161e2082e0d433d99/src/platforms/java/config.yml#L4
https://github.com/getsentry/sentry-release-registry/blob/8b74a094880ad033fa556fcb2c6f7f3b5488e4ee/sdks/sentry.java

**Comment by PeloWriter** [comment]
I can confirm that neither Java nor Android display. `PlatformSdkDetail.tsx` appears to be the file that pulls the info.

**Comment by marandaneto** [comment]
it does now after @tonyo fix :)
