### ISSUE TITLE
Java Contexts example should use complex object

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-docs#3132]
Contexts expects an object to be serialized. A String will not be accepted.

https://docs.sentry.io/platforms/java/enriching-events/context/

One alternative is to declare type above and pass an instance, as done in other platforms such as Flutter:

https://docs.sentry.io/platforms/flutter/enriching-events/context/

**Comment by marandaneto** [comment]
@bruno-garcia the Java code will wrap the primitive types or String within an Object with a value field:

it'd become:

```
"key": {
  "value": your primitive value or String
}
```

so it's not broken, but it'd be better to align the examples using an object instead, true.

**Comment by bruno-garcia** [comment]
I forgot the work around, I think we should do this everywhere we take `Object` such as .NET.

**Comment by marandaneto** [comment]
afaik, it always overwrites it
