### ISSUE TITLE
Document what type of globbing is used for error message filtering

### ISSUE THREAD

**Issue by caleb15** [getsentry/sentry-docs#3140]
## Summary

It would be useful to know exactly what globbing implementation is used.

## Motivation

To be able to effectively use error message filtering feature.

## Additional Context

Currently the description just links to https://en.wikipedia.org/wiki/Glob_(programming), but a developer is likely to already know what globbing is - what's useful to them is exactly what characters are allowed. For example, is [!abc] allowed? What about extended globbing?

**Comment by PeloWriter** [comment]
Let's add the information to [this page.](https://docs.sentry.io/product/data-management-settings/filtering/)

Discussing globbing in general and providing a few syntax examples.

**Comment by PeloWriter** [comment]
We included globbing information in[ this PR](https://github.com/getsentry/sentry-docs/pull/3154)
