### ISSUE TITLE
{{ packages.version(sdk, version) }} isn't working

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-docs#3145]
## Important Details

https://docs.sentry.io/platforms/java/ and android are not getting the latest version from release-registry
https://github.com/getsentry/sentry-release-registry/tree/master/packages/maven/sentry

## Description

{{ packages.version(sdk, version) }} isn't working

### What you expected to happen

get the latest version from release-registry and show the latest version (currently 4.1.0) on the docs

### Possible Solution

no idea, could it be because these files are under `src/includes`?
https://raw.githubusercontent.com/getsentry/sentry-docs/master/src/includes/getting-started-install/java.mdx

**Comment by marandaneto** [comment]
I already spotted this bug before btw https://github.com/getsentry/sentry-docs/pull/2105 but at that time we didn't have release-registry for Java, so we just removed it.

**Comment by bruno-garcia** [comment]
Related to #3127


It's actually not on the registry

https://release-registry.services.sentry.io/sdks

**Comment by PeloWriter** [comment]
Is this a duplicate of https://github.com/getsentry/sentry-docs/issues/3127?

**Comment by bruno-garcia** [comment]
Just ran a manual deploy and it's still not there.

@tonyo is there anything else we need to do to get java up on the registry?

**Comment by tonyo** [comment]
The registry doesn't pick up the maven things because of some parsing woes, I'll take a look.

**Comment by tonyo** [comment]
Should be fixed on the registry side now

![image](https://user-images.githubusercontent.com/1120468/108856649-9060eb80-75ea-11eb-9226-f8d07bb43fda.png)

**Comment by marandaneto** [comment]
> Should be fixed on the registry side now
> 
> ![image](https://user-images.githubusercontent.com/1120468/108856649-9060eb80-75ea-11eb-9226-f8d07bb43fda.png)

nice, not on docs though, https://docs.sentry.io/platforms/android/ or https://docs.sentry.io/platforms/java/
still points to 4.0.0

**Comment by marandaneto** [comment]
@tony does it correct to you though? `io.sentry:sentry:{{ packages.version('sentry.java', '4.0.0') }}` maybe it's the syntax off now

**Comment by tonyo** [comment]
@marandaneto On the next merge/deploy of docs it should pick up the new version

**Comment by marandaneto** [comment]
looks like its working https://docs.sentry.io/platforms/android/

thanks a lot @tonyo

**Comment by bruno-garcia** [comment]
🚀 thanks!
