### ISSUE TITLE
Maintain Parallel Context

### ISSUE THREAD

**Issue by PeloWriter** [getsentry/sentry-docs#3159]
## Issue

Platform/SDK documentation navigation

## Description

It would be valuable to maintain parallelism in the context of navigation. For example, if I'm on .NET Performance, then click Java, I'd like to stay in Performance. I'm trying to compare them, not go back to the beginning.

### Suggested Solution

maintain the context of what I'm viewing.

**Comment by a-hariti** [comment]
Addressed in #9499
