### ISSUE TITLE
Include statements in Product Guides cause UX issues

### ISSUE THREAD

**Issue by PeloWriter** [getsentry/sentry-docs#3172]
## Issue

Sentry Product guides - all 

## Description

The `include` statements to display code samples are using an old dropdown. When a language/platform/SDK is selected, the user is then sent back to the top of the page, losing their spot in the content.

In some cases, we can simplify the dropdown to use the tab option that we have on the SDK pages. But in many cases, we are reflecting code samples for a vast majority of our supported platforms, so creating tabs would be cumbersome. A dropdown is likely a reasonable choice in this second case, though design ideas are welcome.

### Suggested Solution

Align the dropdowns with our current style (I believe they are using an old format) and ensure they maintain the user's reading location.

**Comment by Enxhi369** [comment]
Is there away to upload add it as is and start upgrading or

**Comment by PeloWriter** [comment]
Still an issue that we need to tackle

**Comment by PeloWriter** [comment]
Noted also in https://github.com/getsentry/sentry-docs/issues/3584. We can fix the include statement (done in this [PR](https://github.com/getsentry/sentry-docs/pull/3589)), but the display issue remains.
