### ISSUE TITLE
Document min. supported version for Gson (Java/Android)

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-docs#3177]
## Issue

The min. supported version for Gson on Java and Android is https://github.com/google/gson/releases/tag/gson-parent-2.7

## Description

We need to document that, App's that have Gson as a transitive dependency older than that, won't work.

### Suggested Solution

Write down min. supported version for Gson

**Comment by PeloWriter** [comment]
FYI -  @chadwhitacre - I've removed the errant label.
