### ISSUE TITLE
ReportingObserver does not capture browser crashes

### ISSUE THREAD

**Issue by rohitkataria-sentryio** [getsentry/sentry-docs#3192]
## Issue

This an issue with:

Javascript

Integrations: ReportingObserver

## Description

The ReportingObserver Integration at: https://docs.sentry.io/platforms/javascript/configuration/integrations/plugin/#reportingobserver gives an _impression_ that because of this integration, Sentry can capture browser crashes( the “Aw, Snap!” kind) . 

However, with Katie's help, we learnt that the ReportingObserver API itself is almost always incapable of catching browser crashes. So naturally, Sentry won't capture them as well. 

Further, some snippets from the official API docs too confirm the observed behavior:

https://developer.mozilla.org/en-US/docs/Web/API/CrashReportBody#examples says:
“It is difficult to retrieve a crash report via a ReportingObserver, as by that point the page would have crashed!”

https://developer.mozilla.org/en-US/docs/Web/API/ReportingObserver/ReportingObserver#parameters says:
“...and crash (although this last type usually isn’t retrievable via a ReportingObserver).” 

### Suggested Solution

We should add more details in ReportingObserver section of our docs to reflect above. So customers don't think that Sentry isn't capturing browser crashes for them wherein our own docs talk about this integration which (incorrectly?) claims to be capturing crash.

**Comment by chadwhitacre** [comment]
@rohitkataria-sentryio Can I let you or @lobsterkatie or someone from @getsentry/team-webplatform [triage](https://develop.sentry.dev/processing-tickets/#3-triage) this? Thank you. 🙇‍♂️
