### ISSUE TITLE
Migration guide for Dart/Flutter

### ISSUE THREAD

**Issue by PeloWriter** [getsentry/sentry-docs#3196]
> determine if we need a migration guide

ideally yes, migrating the Dart v3 to Dart v4 or Flutter v4, but we should not block this PR by that

_Originally posted by @marandaneto in https://github.com/getsentry/sentry-docs/issues/3187#issuecomment-790415760_

**Comment by ueman** [comment]
Breaking Changes so far between Sentry v4 and (upcoming) v5:
- nullability related changes: Most static methods of Sentry require non-null values
- Classes were renamed: https://github.com/getsentry/sentry-dart/pull/357

**Comment by ueman** [comment]
Migration Guide Draft: https://github.com/getsentry/sentry-docs/issues/3196
