### ISSUE TITLE
Update Dart Docs

### ISSUE THREAD

**Issue by PeloWriter** [getsentry/sentry-docs#3197]
Update Dart docs using the same structure as the Flutter docs update.

_Originally posted by @marandaneto in https://github.com/getsentry/sentry-docs/pull/3187#issuecomment-790422111_

**Comment by marandaneto** [comment]
@imatwawana Hi, Would you like to help us out on that? Adding the new format for the Dart docs with the integration list and features list, We could help/review also the technical bits, thank you.

**Comment by imatwawana** [comment]
> @imatwawana Hi, Would you like to help us out on that? Adding the new format for the Dart docs with the integration list and features list, We could help/review also the technical bits, thank you.

Do you have a time frame that you want this done within? If it's urgent, I don't know if I can make it happen as soon as you need. If it's not, then I can probably fit it in.

**Comment by marandaneto** [comment]
@imatwawana no hard deadline on that, feel free to fit it in on your own schedule, thanks a bunch.
