### ISSUE TITLE
Docs Overhaul: Round 3

### ISSUE THREAD

**Issue by dcramer** [getsentry/sentry-docs#32]
Proposal to overhaul docs to be more unified, and friendly to new users.

e.g. https://docs.mesosphere.com/

A few notes:
1. We could remove the two-site docs and simply have a section like "Installing the Sentry Server"
2. An intro page would be _very_ good to guide people to what might matter

**Comment by dcramer** [comment]
@ckj @ehfeng @mitsuhiko

**Comment by ckj** [comment]
Those are great. I'm +1, but not looking forward to the dev env unless we've made it better since last time.

**Comment by cameronmcefee** [comment]
No longer applicable
