### ISSUE TITLE
Elixir docs for the Add Context section don't match how the library works, or the library is out of date

### ISSUE THREAD

**Issue by hexpunk** [getsentry/sentry-docs#3213]
## Issue

This an issue with:

Platform/SDK documentation for Elixir, specifically the [Add Context](https://docs.sentry.io/platforms/elixir/enriching-events/context/) section.

## Description

- The documentation mentions in the [Structured Content section](https://docs.sentry.io/platforms/elixir/enriching-events/context/#structured-context) to use the [`set_context`](https://github.com/getsentry/sentry-elixir/blob/94b37b5217f22097e264a41fe7b9a202cc32b716/lib/sentry/context.ex#L261) function.  However, that function is private in the Sentry lib and can't be called directly in my code.
- The [Structured Content section](https://docs.sentry.io/platforms/elixir/enriching-events/context/#structured-context) is missing a code example.
- Since I couldn't use `set_context` directly, I chose to use [`set_extra_context`](https://github.com/getsentry/sentry-elixir/blob/94b37b5217f22097e264a41fe7b9a202cc32b716/lib/sentry/context.ex#L93) instead.  However, the [Additional Data section](https://docs.sentry.io/platforms/elixir/enriching-events/context/#additional-data) of the documentation says:
  
  >Additional Data is deprecated in favor of structured contexts and should be avoided when possible.

  The `set_extra_context` function is not marked as deprecated in the code.
- The [Additional Data section](https://docs.sentry.io/platforms/elixir/enriching-events/context/#additional-data) refers to the `set_extra_context` function as `set_extra`, which is incorrect.

### Suggested Solution

Either the documentation should be updated to match how the Elixir library seems intended to be used or the Elixir library should be updated to match how the other language libraries work.

**Comment by rhcarvalho** [comment]
@mitchellhenke would you mind having a look at this? Thanks!

**Comment by dustinfarris** [comment]
How does this work again?  I'm not seeing extra information show up in Sentry.
