### ISSUE TITLE
React-specific content needed for performance/automatic-instrumentation

### ISSUE THREAD

**Issue by lobsterkatie** [getsentry/sentry-docs#3216]
## Issue

This an issue with:

JS performance docs

## Description

React is pulling from the common browser docs for the "included instrumentation" content, and therefore makes no mention of the react router integration as a config option, and also says navigation transactions come by default (which they only do if you include the integration, which the code sample doesn't).

### Suggested Solution

Create react-specific content for this page which both talks about and demonstrates the react router integration. (This page has info on it: https://docs.sentry.io/platforms/javascript/guides/react/configuration/integrations/react-router/#react-router-v4v5.)

We also might need to make a specific performance/set-up doc.

**Comment by chadwhitacre** [comment]
@lobsterkatie Can I let you or someone from @getsentry/team-webplatform [triage](https://develop.sentry.dev/processing-tickets/#3-triage) this? Thank you. 🙇‍♂️

**Comment by rhcarvalho** [comment]
I'm considering this triaged, ready for someone to work on the content as suggested by Katie. Thanks @chadwhitacre!

**Comment by PeloWriter** [comment]
The Getting Started configuration code sample has been updated, but the performance/auto-instrumentation page still needs updating. @onurtemizkan - can you please take a look?

**Comment by onurtemizkan** [comment]
Sure, @PeloWriter 👍
