### ISSUE TITLE
Update iOS docs

### ISSUE THREAD

**Issue by PeloWriter** [getsentry/sentry-docs#3235]
Apple docs (iOS, tvOS, macOS, watchOS) need a few updates:

- [x] adopt the common Getting Started page - @PeloWriter 
- [x] add a list of features `src/includes/getting-started-primer` - @PeloWriter 
- [x] determine if the Usage content should display - code samples are populated - @PeloWriter 
- [x] In Advanced Usage, evaluate redundancy between the section "Dealing with Scopes" and the common "Scopes and Hubs" content - @PeloWriter 
- [x] In Advanced Usage, evaluate whether "Capturing uncaught exceptions on macOS" should be surfaced on the Usage page (if we display it) - @PeloWriter 
- [x] From Advanced Usage, move integration content to use the Configuration->Integrations-> Default Integrations structure - @PeloWriter 
- [x] From Advanced Usage, evaluate whether "Known Limitations" content is current - @philipphofmann can you please let me know?
- [x] Clarify whether display of Ruby samples is accurate for Debug Symbols, as other pages use Swift and Objective C - is this related to the odd cocoa includes, @philipphofmann ? If so, I will review and fix.
- [x] populate a sample for `src/includes/configuration/before-send-hint` - @philipphofmann can you please provide?
- [x] Identify any missing options on Basic Options page - @philipphofmann can you please let me know what's missing, if any?

**Comment by PeloWriter** [comment]
Follow up - The Advanced Usage page is named usage.mdx, thus it is overwriting the common content. If we move the content from that page (as noted above), there's no need to rename it as the file will no longer be needed.

**Comment by philipphofmann** [comment]
* "Known Limitations" is up to date
* Ruby sample for using Fastlane is up to date
* The Cocoa SDK doesn't support hints. I opened up a PR for this: https://github.com/getsentry/sentry-docs/pull/3266

**Comment by philipphofmann** [comment]
Basic options: diagnostic-level, traces-sample-rate, and traces-sampler will be available in 7.0.0, which is currently in alpha.
The rest looks up to date.

**Comment by PeloWriter** [comment]
Also need to:

- [ ] Review the debug symbols content for redundancy with common.

**Comment by PeloWriter** [comment]
Since the iOs docs for performance are in a PR, I'm enabling the config options `traces-sampler` and `traces-sample-rate`.
