### ISSUE TITLE
Getting started configure section on Android should mention the auto-init false.

### ISSUE THREAD

**Issue by Gvetri** [getsentry/sentry-docs#3265]
## Issue

This an issue with:

Platform/SDK documentation (Which one?)
Sentry Android
Sentry Product (Which area?)
Documentation

## Description
As a user, I was trying to implement Sentry in my app, I followed this documentation https://docs.sentry.io/platforms/android/#configure, and it was not working. I was getting an exception. I was using the second approach.
```
import io.sentry.android.core.SentryAndroid

SentryAndroid.init(this) { options ->
  options.dsn = "https://examplePublicKey@o0.ingest.sentry.io/0"
}
```

Initialized sentry in MyApplication.kt and getting an error. Looking in the documentation, I was missing the following meta-data in my manifest as explained in the migration guide (https://docs.sentry.io/platforms/android/migration/#manual-installation).

```
<application>
    <meta-data android:name="io.sentry.auto-init" android:value="false" />
</application>
```

After I added this to my manifest, the approach of the getting started guide worked.  I'm not migrating from one version of sentry to another one, it's a new install, and the version is 4.3.0. 

### Suggested Solution

Add the following code snippet to the getting started page. 
```
<application>
    <meta-data android:name="io.sentry.auto-init" android:value="false" />
</application>
```

**Comment by PeloWriter** [comment]
@bruno-garcia and @marandaneto - can you please review?

**Comment by bruno-garcia** [comment]
Thanks for poiting this out. That makes sense. We should add:

```
<application>
    <meta-data android:name="io.sentry.auto-init" android:value="false" />
</application>
```

In between `Or ..` and the code snippet here:

![image](https://user-images.githubusercontent.com/1633368/112075627-3b63b700-8b4f-11eb-96bc-6ad33b8ef769.png)

**Comment by marandaneto** [comment]
the other option would be instead of adding more code snippet and pollute the "automatic mode" which is much nicer, to link `manually instrumenting Sentry` text to https://docs.sentry.io/platforms/android/configuration/manual-init/ as they will click and read it, wdyt?

**Comment by bruno-garcia** [comment]
> the other option would be instead of adding more code snippet and pollute the "automatic mode" which is much nicer, to link `manually instrumenting Sentry` text to https://docs.sentry.io/platforms/android/configuration/manual-init/ as they will click and read it, wdyt?

Also works for me. Probably best
