### ISSUE TITLE
Update Cordova Docs

### ISSUE THREAD

**Issue by PeloWriter** [getsentry/sentry-docs#3285]
Cordova docs need a few updates:

- [x] Adopt the common content for Getting Started - @PeloWriter 
- [x] Adding missing verification step to the Getting started (`/includes/getting-started-verify`) - @jennmueng 
- [x] Add a list of features (`/includes/getting-started-primer`)- team
- [x] Clarify if Cordova supports attachments (page is inherited from JS content) - @jennmueng 
- [x] Clarify if Cordova supports performance (page is inherited from JS content) - @jennmueng 
- [x] Clarify if CDN is supported (Cordova is not listed [here](https://docs.sentry.io/platforms/javascript/guides/cordova/install/cdn/#available-bundles)) - @jennmueng 
- [ ] Verify the list of Options - @jennmueng 
- [x] Clarify if Ionic is a guide or an Integration - @jennmueng

**Comment by jennmueng** [comment]
@PeloWriter 
- Attachments should work
- Performance will be supported in 1.0.0
  - This includes `BrowserTracing` auto routing instrumentation support. 
  - Manual Instrumentation
- CDN is not supported.
- Options will need to be updated to reflect 1.0.0
- Ionic is a guide, will completely rewrite it.

**Comment by bruno-garcia** [comment]
Relates to: https://github.com/getsentry/sentry-docs/issues/3074
