### ISSUE TITLE
Enable consistent content for Debug Information Files

### ISSUE THREAD

**Issue by PeloWriter** [getsentry/sentry-docs#3299]
## Issue

This an issue with:

Platforms that support Debug Information

## Description

Debug Information needs to be consistent and available across platforms.

### Suggested Solution

- Flutter and Apple don't have the "Debug Information Files" pages, while Android does, we need to enable it there, too, and edit it down to the mobile stuff.
- On Native, we have Debug Information. It's a simple primer on what to do and why, linking to the data management page. Develop this content for all platforms, requiring debug information and add platform specific content to it, like Flutter now has.
- Clean up language to "Debug Information" consistently, as that's what we call it in the product. 
- Add the keyword "debug symbols" (so developers can find this content)

**Comment by PeloWriter** [comment]
Following up with @jan-auer, we're going to make this content more modular as we expand support. 

Debug File Formats:
- For Android, only display the ELF and Proguard information
- For iOS, only display the Mach0 and dSYM information
- For Native (and related guides) as well as Rust (and related guides), display the above plus PE and PDB as well as Breakpad
- For WASM, note that this content is already refined for WASM, so we will verify the correct content still displays

Debug Identifiers:
- All platforms need the introductory content
- For Android, only display the GNU and ProGuard content
- For iOS, only display the GNU content
- For Native (and related guides) as well as Rust (and related guides), only display GNU and PDB content
- For WASM, note that this content is already refined for WASM, so we will verify the correct content still displays

Uploading Files, Symbol Servers, and Source Contexts are applicable to all platforms.

We do not currently display this content for the Apple family, instead we have content on Uploading Debug Symbols. This content should be added to the Mach0 and dSYM content in Debug File Formats - do you agree, @bruno-garcia @philipphofmann ?

**Comment by PeloWriter** [comment]
Also, @bruno-garcia and @marandaneto - we should evaluate how/if Dart and/or Flutter use this content

**Comment by marandaneto** [comment]
@PeloWriter Platforms like Flutter, React Native and Cordova are like a mix of the mobile platforms (Android/iOS) and Web, so we'd need to account for those too

**Comment by bruno-garcia** [comment]
> Also, @bruno-garcia and @marandaneto - we should evaluate how/if Dart and/or Flutter use this content

I second @marandaneto here. Also, `fastlane` plugin for upload is the preferred way for iOS developers but probably not so relevant for other Native guides.

Unity is soon going to be in the same boat as Flutter where. In fact, eventually we'll have minidumps for Unity and Flutter desktop, so lets please plan a structure that fits these.

**Comment by PeloWriter** [comment]
@marandaneto - I've got a draft PR to sort out what displays for which SDK (Native, Rust, iOS, Android, and WASM (which appears to be duplicated as a guide in both JS and Native, so I'll sort this out, too). 

Can you please review so we can sort out what should display for Flutter/Dart, RN, and Cordova, plus Unity (if yet known).

**Comment by marandaneto** [comment]
> @marandaneto - I've got a draft PR to sort out what displays for which SDK (Native, Rust, iOS, Android, and WASM (which appears to be duplicated as a guide in both JS and Native, so I'll sort this out, too)).
> 
> Can you please review so we can sort out what should display for Flutter/Dart, RN, and Cordova, plus Unity (if yet known).

hey @PeloWriter sorry delay, looks like the PR is closed.
what is the outcome of https://github.com/getsentry/sentry-docs/pull/3735#issuecomment-861828678 ?

**Comment by marandaneto** [comment]
RN now has it https://docs.sentry.io/platforms/react-native/upload-debug/
Flutter has it https://docs.sentry.io/platforms/flutter/upload-debug/
Apple has it https://docs.sentry.io/platforms/apple/dsym/

**Comment by mstange** [comment]
Is there a plan to still have pages that have the information for all the platforms? For example, https://docs.sentry.io/platforms/apple/data-management/debug-files/symbol-servers/ currently describes the directory structures of various types of symbol servers across all platforms, and such a complete list is a really useful resource to have.

**Comment by marandaneto** [comment]
@mstange that's a common page across all the SDKs, See https://docs.sentry.io/platforms/android/data-management/debug-files/symbol-servers/
if there's something missing, please let us know so we can work on it :)
