### ISSUE TITLE
Scope Synchronization - Android

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-docs#3311]
## Issue

Scope Synchronization - Android

## Description

Scope Synchronization got lost after refactoring Android docs -> https://github.com/getsentry/sentry-docs/pull/3252/files

### Suggested Solution

Add it back to https://docs.sentry.io/platforms/android/using-ndk/

**Comment by marandaneto** [comment]
related to:

#### Scope Synchronization

If you want to set context data in the Java layer, then receive that context data when a native (C/C++) crash happens, you need to synchronize the Java `Scope` with the native `Scope`. This feature was introduced in version `3.0.0` of the Android SDK and requires an opt-in:

```xml {filename:AndroidManifest.xml}
<application>
    <meta-data android:name="io.sentry.ndk.scope-sync.enable" android:value="true" />
</application>
```

**Comment by marandaneto** [comment]
cc @PeloWriter

**Comment by PeloWriter** [comment]
It's now included in the list of features. Should it be removed from there? 
![Screen Shot 2021-03-24 at 10 09 54 AM](https://user-images.githubusercontent.com/61481573/112353609-21c68a80-8c89-11eb-8c00-6d9da1e378b5.png)

**Comment by marandaneto** [comment]
@PeloWriter never mind, the content was moved to https://docs.sentry.io/platforms/android/enriching-events/scopes/#scope-synchronization thanks!
