### ISSUE TITLE
Document the new Unity SDK

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-docs#3313]
We're working a [new Unity SDK](https://github.com/getsentry/sentry-unity).
It's based on the .NET SDK so the docs will change considerably from the current version.

The current SDK is called "Sentry Unity lite" and would be worth keeping, perhaps as a subpage where can we point users to from the getting started if the main/new SDK isn't a solution for them (say WebGL Unity, or Unity 5.6 users).

**Comment by marandaneto** [comment]
isnt this already done @bruno-garcia @bitsandfoxes https://docs.sentry.io/platforms/unity/ ?

**Comment by bitsandfoxes** [comment]
@marandaneto, yes! The docs have been replaced and the Unity Lite SDK is now relegated to the migration page.
