### ISSUE TITLE
LH sidebar scrolls back to top when navigating between pages

### ISSUE THREAD

**Issue by imatwawana** [getsentry/sentry-docs#3327]
## Issue

This an issue with:
All areas of Docs

## Description

LH sidebar should not go back to top when you navigate between pages. Currently when you navigate between pages in 
Docs, the LH sidebar scrolls back to top rather than reflecting where you are in the navigation. Because the sidebar nav content is quite long, if the link for the page you're on is "below the fold" in the sidebar, you can't see where you are in the navigation. Very confusing user experience. 

### Suggested Solution

This seems to be an issue with Gatsby but someone posted a potential workaround at the end of this now closed issue:
https://github.com/gatsbyjs/gatsby/issues/4260

While the issue thread says that this was being worked on in v2 of Gatsby, it's unclear if it was actually fixed.

**Comment by untitaker** [comment]
This would be most needed on mobile but it's unclear what the fix there is, as there's no such thing as overflow scroll.

**Comment by untitaker** [comment]
Besides mobile, is there a realistic where the selected sidebar item actually disappears below the fold? I can't find me without making my viewport tiny.

**Comment by imatwawana** [comment]
I was actually thinking about this for desktop. If you click on anything in the Integration section of the product docs, the LH navigation scrolls back up so you can't see that you have something in Integrations selected. I'm on a 22" monitor doing this if that's helpful. Anything beyond the Account Management section of the product docs is affected.

**Comment by a-hariti** [comment]
this was addressed in #9438
