### ISSUE TITLE
Document auto instrumentation for Java DB queries

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-docs#3337]
Related to https://github.com/getsentry/sentry-java/pull/1095

**Comment by marandaneto** [comment]
cc @maciejwalkowiak

**Comment by maciejwalkowiak** [comment]
Since https://github.com/getsentry/sentry-docs/pull/3353 got closed, and db-proxy & p6-spy modules were reverted, I believe this issue can be closed as "won't do".
