### ISSUE TITLE
Missing API endpoints in docs

### ISSUE THREAD

**Issue by MedAliMarz** [getsentry/sentry-docs#3340]
## Issue

This an issue with:

Platform/SDK documentation (API endpoints documentation)

## Description

I am looking for API documentation for these operations:
- ~~Project creation~~
- Organization deletion
- Event CRUD
- Issue creation
### Suggested Solution

For example the project creation endpoint can be extracted from interacting with the UI (using network tab in developer tool), but i am not sure if it is available for usage only through the UI or not.

**Comment by PeloWriter** [comment]
Did you have a chance to review our [API docs](https://docs.sentry.io/api/)?

**Comment by MedAliMarz** [comment]
@PeloWriter Thanks for mentioning the docs, I rechecked it and I found only the `Project creation`, but couldn't find the others. I will appreciate knowing if it is possible to use undocumented API endpoints .

**Comment by PeloWriter** [comment]
@NisanthanNanthakumar or @manuzope - can you help out here?

**Comment by manuzope** [comment]
Hi @MedAliMarz, here's our guidance on using undocumented endpoints: https://develop.sentry.dev/docs/api/#can-customers-use-private-endpoints. You can use them but they could change at any time, without any notice.

If you'd like those endpoints to be public, I'd recommend following the instructions [here](https://develop.sentry.dev/docs/api/#requesting-an-api-to-be-public).

**Comment by MedAliMarz** [comment]
Thank you @manuzope for the clarification.
