### ISSUE TITLE
User consent and PII docs for Mobile SDKs

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-docs#3344]
## Issue

We need to have a section in our mobile SDKs about user consent and PII.

## Description

If we don't have it yet, we need to be more explicit about user consent and PII in our mobile SDKs, the initial reason stems the issue below:

https://github.com/getsentry/sentry-dart/issues/371
Google is refusing Apps with our SDKs because we are not explicit enough about User consent and PII.
This is mostly about the Apps targeting the Kids category.

### Suggested Solution

Either we have a new section about that or making it easier to find out.
We don't collect PII by default unless the devs set it (eg setUser(...)).
It's possible to filter data using beforeSend callback or EventProcessors (client-side)
It's possible to filter data with data scrubbing on the server (server-side)
It's possible to disable the SDK auto init and init manually only if the user has given consent, it's also possible to close the SDK if the user refuses the consent.
It's possible to init the SDK after the user giving consent, etc...

what else?

**Comment by marandaneto** [comment]
@PeloWriter can you help us out on that? its a matter of wording, the SDKs have all the needed features.

**Comment by PeloWriter** [comment]
For the mobile docs, I'd suggest we add a section that lists the above in bulleted form, with links to each of the appropriate supporting content added to the Configuration code sample. So, something like:

### User Consent and PII

Sentry's SDKs have features enabled that support user privacy:

- [No PII is collected by default]((/platform-redirect/?next=/data-management/sensitive-data/#personally-identifiable-information-pii), unless your development team configures your SDK to do so
- Data can be filtered in your SDK using [the `beforeSend` callback]((/platform-redirect/?next=/data-management/sensitive-data/#scrubbing-data) and/or [filtered at time of ingestion](/product/data-management-settings/filtering/)
- Auto initialization of the SDK can be disabled to allow the user to either provide consent then initialize manually or close the SDK if consent is not provided.

**Comment by marandaneto** [comment]
that's for all Mobile SDKs not only Android, the content could be even `common`, might need some small tweaks depending on the platform though

**Comment by marandaneto** [comment]
https://docs.sentry.io/product/security/mobile-privacy/
