### ISSUE TITLE
Add iOS to list of supported performance monitoring SDKs

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-docs#3349]
This is a manually curated list of supported SDKs:

https://docs.sentry.io/product/performance/getting-started/

As iOS goes into GA we need to add it to the list under the _Mobile_ section.

**Comment by PeloWriter** [comment]
Another reason that an [automated SDK feature list](https://github.com/getsentry/sentry-release-registry/issues/39) would be valuable.

**Comment by PeloWriter** [comment]
This was fixed in https://github.com/getsentry/sentry-docs/pull/3468
