### ISSUE TITLE
Laravel setup docs need updating for Laravel 8.x

### ISSUE THREAD

**Issue by nie7321** [getsentry/sentry-docs#3351]
## Important Details

How are you running Sentry?
Saas (sentry.io)

## Description
Laravel 8 changed how [exception handlers are registered](https://laravel.com/docs/8.x/errors#reporting-exceptions). The Sentry setup docs should reflect this.

## Steps to Reproduce
1. Go to the [Laravel setup docs](https://sentry.io/northwestern-it/competitive-applications/getting-started/php-laravel/)

### What you expected to happen
There should be an example for 8.x+ along these lines:

```php
    public function register()
    {
        if (app()->bound('sentry')) {
            $this->reportable(function (Throwable $e) {
                app('sentry')->captureException($e);
            });
        }
    }
```

**Comment by rhcarvalho** [comment]
@ste93cry @Jean85 would you be able to help validate this?

**Comment by ste93cry** [comment]
Nope sorry, I don't know Laravel, @stayallive is the person in charge of its SDK

**Comment by stayallive** [comment]
I'll add it later, but I want to note that the current docs work perfectly fine even in Laravel 8.

There is just a newer and shinier way and I did add yet another version specific snippet yet since we support version 5.x, 6.x, 7.x and 8.x and only 8.x supports this newer syntax 😉

**Comment by rhcarvalho** [comment]
Thanks, everybody!

**Comment by stayallive** [comment]
This can be closed too since the docs now reflect the requested changes.
