### ISSUE TITLE
SDK Fingerprinting examples missing for Ruby SDK

### ISSUE THREAD

**Issue by rohitkataria-sentryio** [getsentry/sentry-docs#3359]
## Issue

This an issue with: SDK documentation 

Link: https://docs.sentry.io/platforms/ruby/data-management/event-grouping/sdk-fingerprinting/

## Description

Missing examples, like we have for other SDKS, for using the SDK fingerprinting feature . 

### Suggested Solution

Put examples, like we have for other SDKS, for using the SDK fingerprinting feature .

**Comment by ojab** [comment]
I guess this one is fixed by https://github.com/getsentry/sentry-docs/pull/3578
