### ISSUE TITLE
Document Symfony integrations

### ISSUE THREAD

**Issue by rhcarvalho** [getsentry/sentry-docs#3362]
We should add a few notes about how to use the `IgnoreErrorsIntegration` integration in place of the deprecated SDK option (`excluded_exceptions `).

_Originally posted by @ste93cry in https://github.com/getsentry/sentry-docs/issues/3161#issuecomment-792947319_

Document how to use the integration in a way similar to what is done for the [JS SDK](https://docs.sentry.io/platforms/javascript/configuration/integrations/), by adding  a complete new section to the configuration that is called integrations e.g. https://docs.sentry.io/platforms/php/guides/symfony/configuration/integrations.

See also https://docs.sentry.io/contributing/approach/write-configuration/#integrations

Note: if there are other undocumented integrations apart from `IgnoreErrorsIntegration`, we should document them as well.

**Comment by ste93cry** [comment]
Here's the full list of integrations [available](https://github.com/getsentry/sentry-php/tree/fb4f83e6e2d718d1e5fbfe3a20cced83f47f040f/src/Integration) in PHP:

| Integration | Enabled out-of-the-box |
|-|-|
| `EnvironmentIntegration` | x |
| `ErrorListenerIntegration` | x |
| `ExceptionListenerIntegration` | x |
| `FatalErrorListenerIntegration` | x |
| `FrameContextifierIntegration` | x |
| `IgnoreErrorsIntegration` |  |
| `ModulesIntegration` |  |
| `RequestIntegration` | x |
| `TransactionIntegration` | x |

**Comment by rhcarvalho** [comment]
Is there any framework-specific integration, or any of those PHP integrations that doesn't apply to a specific framework?

With the way the docs repo works, if they're all common to PHP, Symfony and Laravel then we can write once and reuse content.

**Comment by ste93cry** [comment]
>Is there any framework-specific integration, or any of those PHP integrations that doesn't apply to a specific framework?

No, there aren't. All PHP integrations work for all frameworks, and AFAIK there are no specific integrations implemented in the framework SDKs
