### ISSUE TITLE
Clarify when to use `Sentry.captureException` in documentation. 

### ISSUE THREAD

**Issue by kopax-polyconseil** [getsentry/sentry-docs#3392]
## Description

I am reading the documentation and it seems Sentry already catch all Errors https://docs.sentry.io/platforms/react-native/usage/

So what's the point of using `Sentry.captureException` in our try catch block ? 

If that's required, when does sentry does not catch error ? 

### Suggested Solution

Clarify when to use `Sentry.captureException` in documentation

**Comment by bruno-garcia** [comment]
The choice is yours in: Do you want to handle the error and continue with your flow normally? Or do you need to "abort" the operation and let the error bubble up?

```
try {
readFile();
catch (e) {
// Couldn't load the file but that's OK. Just let me know it failed:
Sentry.captureException(e);
}
.. Code continues here
```

vs:

```
try {
readFile();
catch (e) {
// Couldn't load the file but that's OK. Just let me know it failed:
Sentry.captureException(e);
}
.. Code continues here
```

```
try {
readFile();
catch (e) {
// Not going to capture here because I don't know what to do with this error. I'll let it bubble up
throw e;
}
.. Code can't get this far is reading the file fails
```

The code above is equivalent to simply not doing a try catch at all, but I used it to illustrate the options.

In the event that you don't have your own `try catch`, the exception will be **unhandled**. Sentry's SDK can capture those automatically and will mark the event in Sentry as such. This also means, in most platforms (like React Native) that the app will crash.

**Comment by PeloWriter** [comment]
Thanks for your question. Closing as it's been answered.
