### ISSUE TITLE
Docs for Flutter Desktop

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-docs#3399]
## Issue

Docs for Flutter Desktop

## Description

We'd need to write down that we have limited support for Flutter desktop, similar to Web.
These docs need to be clear about debug symbols (do we need for MacOS/Linux and Windows) and how?
Windows require the `release` to be set manually either via env. var or thru the options.

### Suggested Solution

Write down the docs

**Comment by marandaneto** [comment]
cc @ueman

**Comment by ueman** [comment]
- Change most iOS mentions to iOS/macOS
- Debug Symbols for macOS
- Add a note about release numbers on Linux and Windows (I need to look it up)
- Add limitations of Desktop (no native integration on Windows and Linux)
- go through the existing documentation and see what else needs to be edited
