### ISSUE TITLE
Document all options for Sentry.init()

### ISSUE THREAD

**Issue by chadwhitacre** [getsentry/sentry-docs#3400]
Ticketing [from Twitter](https://twitter.com/jorisw/status/1381169077746601986) ...

## Issue

This is an issue with all SDKs, presenting case is [JavaScript](https://docs.sentry.io/platforms/javascript/configuration/options/).

## Description

User was attempting to configure Sentry and looking to understand all available options, but only "common" options are documented.

### Suggested Solution

Document an exhaustive list of options for `Sentry.init()` somewhere.

**Comment by bruno-garcia** [comment]
Technically they are often documented, but not on docs.sentry.io. There are many reasons for that, including:

* They are already part of the SDK API doc
* It's a lot of work
* Often contributors add features to SDKs but don't add the options here

For example the options documentation of the [.NET SDK options](https://getsentry.github.io/sentry-dotnet/api/Sentry.SentryOptions.html), [ASP.NET Core options](https://getsentry.github.io/sentry-dotnet/api/Sentry.AspNetCore.SentryAspNetCoreOptions.html) and [Java](https://getsentry.github.io/sentry-java/).

Perhaps we could link to these generated API docs when applicable as opposed to manually maintaining a list of options to all SDKs?

**Comment by untitaker** [comment]
Are there concrete options missing? The list should be exhaustive for python

**Comment by PeloWriter** [comment]
We should document all options - we have the foundation provided and have been auditing as we make updates in other content areas. 

It is work to keep them up to date, so a programmatic process would ease this. We've captured that idea in [this issue](https://github.com/getsentry/sentry-docs/issues/3050).

**Comment by chadwhitacre** [comment]
> We've captured that idea in [this issue](https://github.com/getsentry/sentry-docs/issues/3050).

Ah, nice. Close this as a dupe, then?

**Comment by PeloWriter** [comment]
Closing as a duplicate.
