### ISSUE TITLE
Project/Org name vs slug

### ISSUE THREAD

**Issue by cameronmcefee** [getsentry/sentry-docs#343]
I'm under the impression that we're moving away from names in favor of slugs. We need to figure out how to reflect this in the docs:

- Where does `___PROJECT_NAME___` need to be come `___PROJECT_ID___`?
- Where does `___ORG_NAME___` need to be come `___ORG_ID___`?
- The example switcher needs to be updated to show slugs

I assume that the names are just vanity values and can probably be replaced everywhere. Is that correct?

@dcramer @mitsuhiko

**Comment by dcramer** [comment]
Should be fine to use slug anywhere where name is (its only vanity)

**Comment by mitsuhiko** [comment]
Just to be clear about what I wrote in the channel: the docs `____PROJECT_NAME____` was supposed to be the slug and `___PROJECT_ID____` the numeric id.
