### ISSUE TITLE
Go Example on Add Context uses SetExtra Instead of SetContext

### ISSUE THREAD

**Issue by keokilee** [getsentry/sentry-docs#3448]
## Issue

This an issue with:
Platform/SDK documentation - https://docs.sentry.io/platforms/go/enriching-events/context/

## Description

On the *Add Context* page, the section on *Structured Context* describes usage of `SetContext`, but the Go example uses `SetExtra`. On the same page further down, the section on *Additional Data* mentions that you can use `SetExtra` to add additional data, but Additional Data is deprecated.

### Suggested Solution

The code snippet on this page could reference `SetContext` instead of `SetExtra`.

**Comment by PeloWriter** [comment]
@rhcarvalho - could you please take a look?

**Comment by rhcarvalho** [comment]
The misuse of `setExtra` is also present in other platforms under `src/includes/set-context/` 😢 
Going to send a fix.
