### ISSUE TITLE
Add documentation about tracing

### ISSUE THREAD

**Issue by VincentLanglet** [getsentry/sentry-docs#3463]
## Issue

This an issue with:
https://docs.sentry.io/platforms/php/guides/symfony/

## Description

Tracing support is new in sentry-symfony
https://github.com/getsentry/sentry-symfony/pull/477
https://github.com/getsentry/sentry-symfony/pull/426
https://github.com/getsentry/sentry-symfony/pull/460
https://github.com/getsentry/sentry-symfony/pull/430
https://github.com/getsentry/sentry-symfony/pull/423

The doc should be updated to explain how to use it.

**Comment by rhcarvalho** [comment]
Noting there's already https://docs.sentry.io/platforms/php/guides/symfony/performance/.
