### ISSUE TITLE
Python: Missing documentation for Release Health

### ISSUE THREAD

**Issue by rhcarvalho** [getsentry/sentry-docs#3473]
## Issue

This an issue with:

Platform/SDK documentation (Which one?) https://docs.sentry.io/platforms/python/configuration/releases/#release-health

Sentry Product (Which area?) https://docs.sentry.io/product/releases/health/setup/

## Description

Looking at the documentation on how to use Release Health. Following through the links for Python leads to a missing documentation box.

![image](https://user-images.githubusercontent.com/88819/116226553-66938480-a753-11eb-8bf1-9687fa8d7398.png)

### Suggested Solution

Add the missing docs.

**Comment by DanLipsitt** [comment]
@rhcarvalho Is this missing functionality or just missing documentation?

**Comment by rhcarvalho** [comment]
@DanLipsitt the feature is implemented, missing docs.

cc @ahmedetefy

**Comment by vivianyentran** [comment]
Looks like this has been fixed
