### ISSUE TITLE
Moving mouse over headers cause flicker

### ISSUE THREAD

**Issue by rhcarvalho** [getsentry/sentry-docs#3474]
## Issue

This is a CSS issue affecting the docs site as a whole.

As an example, look at https://docs.sentry.io/product/releases/#apply-source-maps

## Description

There ~~are two problems~~ is a problem when moving mouse over headers.

1. (not so important) When the cursor is over anywhere in the area in blue the anchor icon appears

![image](https://user-images.githubusercontent.com/88819/116231638-6bf3cd80-a759-11eb-85e1-52e5c44624df.png)

The area that activates the hover event is considerably larger than the perceived line height of the headers.

(The blue line was draw using the Chrome Dev Tools "force element state :focus-visible")

<details>

![image](https://user-images.githubusercontent.com/88819/116231992-d573dc00-a759-11eb-9f2b-8e6c51600d29.png)

</details>

### Suggested Solution

The header heights should match the text height.

2. ~~(more annoying) Flicker caused by change of height~~ update 2021/10/29: not a problem anymore

<details>

https://user-images.githubusercontent.com/88819/116232882-f8eb5680-a75a-11eb-900e-41521ed1253f.mov

![image](https://user-images.githubusercontent.com/88819/116232254-284d9380-a75a-11eb-81a8-c1eaa7d0969d.png)
![image](https://user-images.githubusercontent.com/88819/116232269-33082880-a75a-11eb-8a93-14d49a81e81e.png)

### Suggested Solution

The line heights / heights should be the same and not change on hover.

</details>

**Comment by vivianyentran** [comment]
Closing this as the anchors are there by default now in the next.js site
