### ISSUE TITLE
Unify InAppInclude and InAppExclude on Options

### ISSUE THREAD

**Issue by philipphofmann** [getsentry/sentry-docs#3476]
## Issue

Apple has its [own documentation](https://github.com/getsentry/sentry-docs/blob/78295b928c22805e7e565ca2bb699af778ecb56b/src/includes/grouping/in-app/apple.mdx#L19) on inAppIncludes and inAppExcludes.

## Description

Java, Android, Unity, and .NET have this feature as well.

### Suggested Solution

We should try to unify the documentation for these.

**Comment by PeloWriter** [comment]
If it helps, an `include` can call an `include`. So, if we have it documented for apple, other SDKs can use it. 

For example, Flutter calls a Dart code sample, then adds Flutter specific content in `src/includes/capture-error/flutter.mdx`
