### ISSUE TITLE
Rails Getting Started docs can't be copy pasted

### ISSUE THREAD

**Issue by ariccio** [getsentry/sentry-docs#3487]
## Issue

This an issue with:

Platform/SDK documentation (Which one?)
Sentry Rails documentation

## Description

[What were you looking for/trying to do/expecting?]

[Getting Started#Configure](https://docs.sentry.io/platforms/ruby/guides/rails/#configure) includes an option for `traces_sample_rate ` and an empty `traces_sampler` stub, :

```
  # To activate performance monitoring, set one of these options.
  # We recommend adjusting the value in production:
  config.traces_sample_rate = 0.5
  # or
  config.traces_sampler = lambda do |context|
    true
  end
```

This means that dumb people, like me, will run into rate limiting problems if they mindlessly copy and paste it. Maybe leave the lambda commented out?

### Suggested Solution

[If you have an idea on how we can solve this, please share]
Leave only one of them uncommented.

**Comment by ariccio** [comment]
I only figured out that I was missing something when I saw, in [tracing options](https://docs.sentry.io/platforms/ruby/guides/rails/configuration/options/#tracing-options) this message for `traces_sampler`:

```
The platform or SDK you've selected either does not support this functionality, or it is missing from documentation.
```

It's only five minutes of my day, but hey, five minutes that nobody else needs to lose to being boneheaded!

**Comment by PeloWriter** [comment]
Thanks @ariccio for pointing this out. I'll route to the team for review.

**Comment by PeloWriter** [comment]
@st0012 - can you take a look?

**Comment by st0012** [comment]
There are 2 problems mentioned in this issue:
1. The tracing option example sends all transactions if copied-pasted by users.
2. The traces_sampler example is missing.

I will fix problem 2 in https://github.com/getsentry/sentry-docs/pull/3495 along with other document updates for the new `4.4.0` version.

But I won't touch problem 1 for now. It looks like other SDK's example options also send all transactions, like [python's](https://docs.sentry.io/platforms/python/#configure) or [javascript's](https://docs.sentry.io/platforms/python/#configure). And I think this should be addressed universally.

cc @rhcarvalho @HazAT

**Comment by rhcarvalho** [comment]
At that specific part of the docs, I think we suggest setting the rate to 1 to test that transactions are being captured. A smaller rate leaves the doubt "is it working?"

What we could do is to make the Ruby example match the others, so at least we have consistency. The expectation is that either one of the two config options is used, and not both, so it is confusing to put both together uncommented.
