### ISSUE TITLE
Android ProGuard documentation should clarify Rules

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-docs#3488]
We received feedback that it isn't clear on the docs if users should be defining ProGuard rules when setting up Sentry, to make sure the SDK works properly once ProGuard minifies the app.

The SDK does in fact include some rules that make it into the app so no user action is needed But this needs to be better clarified on the docs.

A potential location for that is on the [ProGuard](https://docs.sentry.io/platforms/android/proguard/) page since it's likely where users will land (or search) when looking for this information.

**Comment by marandaneto** [comment]
we can just append a small note:

The Android SDK already ships the ProGuard rules automatically, no extra configuration is needed.
