### ISSUE TITLE
Document enableNativeCrashHandling in sentry-react-native

### ISSUE THREAD

**Issue by pz250089** [getsentry/sentry-docs#3498]
Should perhaps go here: https://docs.sentry.io/platforms/react-native/configuration/options/

Sth like:

`enableNativeCrashHandling` - default true

If switched on, the Uncaught exception handler will be put on the application thread both Android and iOS. See 
eg. `@sentry/react-native/android/src/main/java/io/sentry/react/RNSentryModule.java`

**Comment by PeloWriter** [comment]
@jennmueng @bruno-garcia - can you please take a look?

**Comment by jennmueng** [comment]
@PeloWriter Yes alot of React Native options are missing from the docs, it makes sense to add it to our TODO to document them in one go.

**Comment by PeloWriter** [comment]
Per a brief convo with @bruno-garcia 
- the options in this file: https://github.com/getsentry/sentry-react-native/blob/master/src/js/options.ts
- their name is there as well as type and a description
