### ISSUE TITLE
Update .NET content

### ISSUE THREAD

**Issue by PeloWriter** [getsentry/sentry-docs#3515]
.NET docs need a few updates:

- [x] Adopt the common content for Getting Started - @PeloWriter
- [x] Add performance to Configuration step in Getting Started- @PeloWriter 
- [x] Review Ignoring Exceptions content IA - @PeloWriter  
- [x] Review Unit testing in relation to Scopes and Hubs common content - @PeloWriter 
- [ ] Add missing code sample for [Sampling Inheritance](https://docs.sentry.io/platforms/dotnet/configuration/sampling/#inheritance) - @bruno-garcia 
- [x] Fix format issue  on Diagnostic Logger page - @PeloWriter 
- [x] Update Migration title to "Migration Guide" - @PeloWriter 
- [x] Add a list of features (/includes/getting-started-primer) including compatibility, unit/integration tests, and samples - @bruno-garcia @PeloWriter 
- [ ] Verify the list of Options - @bruno-garcia 
- [ ] Add missing code sample for [unsetting a user at logout ](https://docs.sentry.io/platforms/dotnet/enriching-events/scopes/) - @bruno-garcia 
- [ ] Add missing code sample for [setting a user](https://docs.sentry.io/platforms/dotnet/enriching-events/identify-user/) - @bruno-garcia 
- [x] Change Attachments "this feature is supported..." to a Note - @PeloWriter 
- [ ] Add missing code sample to examples of [scrubbing sensitive data](https://docs.sentry.io/platforms/dotnet/data-management/sensitive-data/) (contextual information and user details) - @bruno-garcia 
- [ ] Update wizard for F# and C# (tracked in https://github.com/getsentry/sentry-docs/issues/2805) - @PeloWriter

**Comment by bruno-garcia** [comment]
Some SDKs (packages) have additional options:

- [ ] [`sentry.dotnet`](https://github.com/getsentry/sentry-dotnet/blob/main/src/Sentry/SentryOptions.cs)
- [ ] [`sentry.dotnet.serilog`](https://github.com/getsentry/sentry-dotnet/blob/main/src/Sentry.Serilog/SentrySerilogOptions.cs)
- [ ] [`sentry.dotnet.nlog`](https://github.com/getsentry/sentry-dotnet/blob/main/src/Sentry.NLog/SentryNLogOptions.cs)
- [ ] [`sentry.dotnet.aspnetcore`](https://github.com/getsentry/sentry-dotnet/blob/main/src/Sentry.AspNetCore/SentryAspNetCoreOptions.cs)
- [ ] [`sentry.dotnet.xamarin`](https://github.com/getsentry/sentry-xamarin/blob/main/Src/Sentry.Xamarin/SentryXamarinOptions.cs)

**Comment by PeloWriter** [comment]
yep. I'm starting with the top-level platform. Currently, .NET has these related guides, which should either inherit .NET content or overwrite with their own:

- ASP.NET
- ASP.NET Core
- AWS Lambda
- Entity Framework
- Extensions.Logging
- log4net
- NLog
- Serilog
- Windows Forms
- Windows Presentation Foundation
- Xamarin

Of these, I only see guide-specific content for ASP.NET Core performance and Xamarin-specific content for ignoring exceptions.

**Comment by stephanie-anderson** [comment]
Hey @bitsandfoxes , could you have a look in the next weeks and see if there is anything we still need to add?

**Comment by bitsandfoxes** [comment]
Will do.
