### ISSUE TITLE
Better Surface SDK Examples Repo

### ISSUE THREAD

**Issue by PeloWriter** [getsentry/sentry-docs#3530]
As noted on [Twitter](https://twitter.com/thatsmekaustubh/status/1389642193871147009), we need to better surface that we offer [an examples repo](https://github.com/getsentry/examples) for many of our SDKs.

We have this listed in the primer for some of the mobile SDKS, but it should become part of our standard list if it's available.

**Comment by lobsterkatie** [comment]
We should validate all of the examples in there before we do this, probably. Just checked it out and a few of them haven't been touched in a long time.
