### ISSUE TITLE
Document local scopes for Dart/Flutter

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-docs#3566]
## Issue

https://github.com/getsentry/sentry-dart/releases/tag/5.1.0-beta.1 via https://github.com/getsentry/sentry-dart/pull/463 can now use withScope but its not documented.

https://docs.sentry.io/platforms/dart/enriching-events/scopes/#local-scopes

## Description

Document behavior like Apple does https://docs.sentry.io/platforms/apple/enriching-events/scopes/#local-scopes

### Suggested Solution

Document behavior like Apple does https://docs.sentry.io/platforms/apple/enriching-events/scopes/#local-scopes

**Comment by marandaneto** [comment]
cc @ueman let's add a note that this is beta still, how to add a note you can learn from this page, https://docs.sentry.io/platforms/java/guides/spring/advanced-usage/ there's a note about the feature being beta too

**Comment by PeloWriter** [comment]
We took a look at the language for Beta and Early Adopter notes, and updated to:

This feature is available as a Beta. Features available in Beta are still in-progress and may have bugs. We recognize the irony. 

We wrap this in the usual Note /Note markdown tags (which I can't fully copy here as GH then makes them Notes :)).

I will update our Contributor Guidelines (thanks for alerting me to this being missing)
