### ISSUE TITLE
Platform/SDK documentation for PHP lacks examples and information

### ISSUE THREAD

**Issue by hellodaniel** [getsentry/sentry-docs#3573]
## Issue

This an issue with:
Platform/SDK documentation for PHP

## Description

I've been trying (for days) to get sampling to work with PHP. The documentation is scant and provides no examples instead stating, for each example given _"The platform or SDK you've selected either does not support this functionality, or it is missing from documentation."_ It's unclear to me if, in fact, the PHP SDK does support sampling or not as, no matter what I try, sampling does not flow through to Sentry. 

Even implementing the most simple version of sample rates for PHP has resulted in zero samples taken of several dozen projects. 

This is for the docs available here: 
https://docs.sentry.io/platforms/php/configuration/sampling/
https://docs.sentry.io/platforms/php/configuration/filtering/

### Suggested Solution
Provide PHP examples or, at least, tell us if this can be done in PHP

**Comment by stayallive** [comment]
I think this issue can be closed since all snippet have been filled in by now 💪

**Comment by imatwawana** [comment]
Is this the work you've done on your PR [4422](https://github.com/getsentry/sentry-docs/pull/4422)?

**Comment by stayallive** [comment]
No this was already done before, if you click the links from the original post:

- https://docs.sentry.io/platforms/php/configuration/sampling
- https://docs.sentry.io/platforms/php/configuration/filtering

You can see all the snippets are already present, I think I missed this issue when I PR'ed those :)

**Comment by imatwawana** [comment]
Ah okay. Got it!
