### ISSUE TITLE
"Manage Your Event Stream, a Guide": confusing steps

### ISSUE THREAD

**Issue by OliverJAsh** [getsentry/sentry-docs#3580]
## Issue

This an issue with:
https://docs.sentry.io/product/accounts/quotas/manage-event-stream-guide/#-what-issues-are-consuming-my-quota

## Description

> The Sentry workflow starts with a real-time alert notifying you about an error in your code. If you want to take a more proactive approach to resolve your busiest errors, follow steps 1 - 6 from above. For step 4 select the columns as seen below:

I don't see any steps "above" in this guide which relate to this?

**Comment by imatwawana** [comment]
Thanks for pointing this out @OliverJAsh. Looks like some old content didn't get updated as this article underwent some changes.
