### ISSUE TITLE
Sentry API unclear

### ISSUE THREAD

**Issue by zabojad** [getsentry/sentry-docs#3595]
I'm having an issue understanding the following thing:

From the documentation:

> `import * as Sentry from "@sentry/browser";`
> To identify the user:
> JavaScript
> `Sentry.setUser({ email: "john.doe@example.com" });`
> You can also clear the currently set user:
> JavaScript
> `Sentry.configureScope(scope => scope.setUser(null));`

Is there a difference between `Sentry.setUser(...)` and `Sentry.configureScope(scope => scope.setUser(...));`?

Can I use `Sentry.setUser(null)` to reset the user when he logouts? 

Whether there is a difference or not, the API documentation should tell it explicitly, especially when the same documentation page is using both syntaxes like this one : [docs.sentry.io/platforms/react-native/enriching-events/identify-user/](https://docs.sentry.io/platforms/react-native/enriching-events/identify-user/)

**Comment by jennmueng** [comment]
Both are the same as calling `Sentry.setUser` wraps the `Sentry.configureScope` call, but I agree that this could be confusing when both are used in the context that you linked.

**Comment by PeloWriter** [comment]
@jennmueng - any docs update required here?

**Comment by jennmueng** [comment]
@PeloWriter, yeah we should choose one or the other, having each example use a different call method makes it confusing and to the untrained user would look like you need to call `configureScope` to clear the user

**Comment by hckhanh** [comment]
I agree,
When I looked at the docs, I thought `Sentry.setUser(...)` and `Sentry.configureScope(scope => scope.setUser(...));` are different.

**Comment by marandaneto** [comment]
`Sentry.setUser(...)` is just a shortcut for `Sentry.configureScope(scope => scope.setUser(...));`
