### ISSUE TITLE
Apple `withScope` doc issue

### ISSUE THREAD

**Issue by ueman** [getsentry/sentry-docs#3601]
## Issue

The following page
https://docs.sentry.io/platforms/apple/enriching-events/scopes/#local-scopes
has an incomplete example.

## Description

The example in the "Local Scope" should have an example which sets a tag.

### Suggested Solution

Here's an example for Swift. Obj-C has to be aligned accordingly.

```swift
import Sentry

SentrySDK.capture(error: error) { scope in
    // will be tagged with my-tag="my value"
    scope.setTag(value: "my-tag", key: "my value")
    scope.setLevel(...)
}

// will not be tagged with my-tag
SentrySDK.capture(error: error)
```

**Comment by marandaneto** [comment]
cc @philipphofmann

**Comment by philipphofmann** [comment]
Thanks, @ueman for pointing that out.
