### ISSUE TITLE
Node Docs Updates

### ISSUE THREAD

**Issue by PeloWriter** [getsentry/sentry-docs#3605]
Node docs need a few updates:

- [ ] Add a list of features (/includes/getting-started-primer)
- [x]  Verify the list of Options - @onurtemizkan
- [ ] Review redundancy between common Filtering content and Node-specific Hints content - @PeloWriter 
- [x] Review integrations content for completeness and currency - @onurtemizkan
- [ ] Update integrations to current structure - @PeloWriter 
- [ ] Review Event Processors for redundancy with common content
- [ ] Review source maps content structure and accuracy (review current JS content to see if it can be used) - @onurtemizkan
- [ ] Review wizard - @PeloWriter 
- [ ] Update performance to use the common content - @PeloWriter

**Comment by PeloWriter** [comment]
This is already triaged, just adding the label for tracking.

**Comment by PeloWriter** [comment]
More feedback for the source maps work, from @framerate on Discord:

Mentioned this a few times other places but I feel like this documentation drastically needs to be improved, as it was critical to my integration: 

https://docs.sentry.io/platforms/node/configuration/integrations/pluggable-integrations/#rewriteframes

Also, doesn't RewriteFrames have 3 options, not two? (but all 3 need to be better fleshed out and have examples)

https://github.com/getsentry/sentry-javascript/blob/master/packages/integrations/src/rewriteframes.ts#L31

**Comment by PeloWriter** [comment]
And more detail from our helpful friend on Discord:

If anyone comes here and reads my errors, here are the two fixes (thanks to Sentry guys on twitter)

1) the webpack:// prefix is only on dev and likely a different problem to solve. Test your electron app with a prod build and you'll likely see a file path with bundle.min.js at the end

2) Its likely that the stripCommonPrefix option in the webpack app (and API as a whole?) is broken. See github open issues for more info. Also possible it works but Sentry's UI just doesn't show you any difference.

3) You have to use Integrations.RewriteFrames() from @sentry/integrations to strip out the file path on every frame (gross).

If the Artifacts on the Sentry UI says ~/bundle.min.js (note the ~/ shows up here regardless if you tell it to stripCommonPrefix. Bug?) you have to strip the path down to the file name but make sure to send it WITH the ~/ from RewriteFrames

I've reached out to support to try and fix documentation and debug whether stripeCommonPrefix is actually broken or not and hopefully I can help the next people with this problem :thumbsup:

**Comment by framerate** [comment]
Thanks @PeloWriter. I also have a related issue I was posting info here: https://github.com/getsentry/sentry-webpack-plugin/issues/228

I don't think `stripCommonPrefix` and other options are actually doing anything/what we think they are. And if they are, they don't seem to be updating the "Artifacts" page on the Sentry web UI (i.e. stripCommonPrefix still showed `~/bundle.min.js` with the `~/` common prefix. 

Possible its user error, but if so, that comes back to docs error since I was misinformed :) Feel free to reach out directly if I can help in any way!

**Comment by PeloWriter** [comment]
@onurtemizkan - would you be able to review and update with @framerate's input?

**Comment by onurtemizkan** [comment]
Yes, @PeloWriter and thanks for the valuable input @framerate. We'll need to add clear examples for sentry-webpack-plugin/CLI options, and also to add scenarios for common usage like CRA, Next.JS etc. I'm starting to work on those.

**Comment by framerate** [comment]
Let me know how I can help!
