### ISSUE TITLE
Add UWP documentation for unhandled exceptions

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-docs#3665]
UWP through the .NET SDK doesn't capture a category of unhandled exception that require hooking into the `Application` class. @lucas-zimerman implemented this on his community plugin: https://github.com/lucas-zimerman/ContribSentry.UWP/blob/master/src/UwpSentryIntegration.cs

This is a source of customer complains since it isn't clear at this point. Until the .NET SDK can ship this OOTB, we need to clearly state the UWP integration required (similarly done for WPF and WinForms).

**Comment by PeloWriter** [comment]
Does this resolve https://github.com/getsentry/sentry-docs/pull/3686?

**Comment by lucas-zimerman** [comment]
Yes @PeloWriter
