### ISSUE TITLE
SDk package does not work when its an integration

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-docs#3672]
## Issue

See https://docs.sentry.io/platforms/android/configuration/integrations/timber/
<img width="329" alt="Screenshot 2021-06-02 at 13 35 40" src="https://user-images.githubusercontent.com/5731772/120473547-6d8f6180-c3a7-11eb-85a7-9ca3eab10b92.png">

https://raw.githubusercontent.com/getsentry/sentry-docs/master/src/platforms/android/configuration/integrations/timber.mdx
`sdk: sentry.android.timber`

should have been the timber package and not the android one

## Description

be redirected to the timber package

### Suggested Solution

make it work also for integrations

**Comment by marandaneto** [comment]
it works for Guides though, see https://docs.sentry.io/platforms/java/guides/spring/
but sometimes Integrations requires a new package, but they are not a standalone package like a Guide.

**Comment by PeloWriter** [comment]
@marandaneto - is this an issue with our tooling? If so, would you please add the Label "enhancement" so I can track?

**Comment by marandaneto** [comment]
@PeloWriter yes, integrations inherits the `sdk` config that pulls release registry data from the platform only, but not the integration itself, even if the `sdk` config is set
