### ISSUE TITLE
Basic usage example of tracing in Node.js SDK is confusing

### ISSUE THREAD

**Issue by nvie** [getsentry/sentry-docs#3683]
## Issue

This an issue with:
Platform/SDK documentation: **Node.js**

## Description

The first/basic code example in the ["Configure" section](https://docs.sentry.io/platforms/node/#configure) is confusing:

```js
import * as Sentry from "@sentry/node";
import * as Tracing from "@sentry/tracing";  // <— 😕

Sentry.init({
  dsn: "<DSN>",

  // We recommend adjusting this value in production, or using tracesSampler
  // for finer control
  tracesSampleRate: 1.0,
});
```

On line 2, it imports `Tracing`, but then never uses it? This looks like a bug.

### Suggested Solution

If this is intentional, then I think clarifying that explicitly would help.

**Comment by HazAT** [comment]
Our tracing packages patches things on the global hub, therefore it’s marked as non side effect free.
But I agree we could add a comment.
