### ISSUE TITLE
Docs should mention to install the python sdk with flask extra, RuntimeError blinker crash

### ISSUE THREAD

**Issue by dmfigol** [getsentry/sentry-docs#371]
https://docs.sentry.io/platforms/python/flask/?platform=python
Docs should mention to install the package using `pip install sentry-sdk[flask]`.
Otherwise `blinker` is not installed and an app will crash with RuntimeError:
`RuntimeError: signalling support is unavailable because the blinker library is not installed.`

**Comment by untitaker** [comment]
Hi, thanks, will fix asap

**Comment by RSid** [comment]
The command in the docs doesn't seem to work for me? I get `no matches found: sentry-sdk[flask]==0.6.4` when I run `pip install --upgrade sentry-sdk[flask]==0.6.5`, but `pip install --upgrade sentry-sdk==0.6.5` installs correctly

**Comment by untitaker** [comment]
Hmm, we do have that version on pypi though. Version in the docs should
update itself on next deploy though

**Comment by untitaker** [comment]
@RSid do you still get this issue? I can't reproduce

**Comment by RSid** [comment]
I'm afraid so! Here's a screenshot: https://www.screencast.com/t/ROssjdMYL3b

**Comment by untitaker** [comment]
Okay, that's a zsh error. That error does not come from PyPI.

**Comment by untitaker** [comment]
@RSid #683 should fix it

**Comment by brianfinkelstein** [comment]
To use the flask extra in requirements.txt for a deployable service, this worked for me:
sentry-sdk[flask]==0.10.2

**Comment by ReFruity** [comment]
How should I mention this dependency in Pipfile?

**Comment by untitaker** [comment]
@ReFruity please refer to https://github.com/pypa/pipenv/issues/3026

it seems that it's not possible to specify extras in pipfiles. So just install `blinker`, `sentry-sdk` and `flask`

**Comment by obi1kenobi** [comment]
I believe Pipfiles do support extras with syntax:
```
my-package = { version = "==1.0.0", extras = ["foo", "bar"] }
```
I've been using this in my project for at least several months now, so I don't believe it's new.
