### ISSUE TITLE
Set up Performance Monitoring for React

### ISSUE THREAD

**Issue by lebreRafael** [getsentry/sentry-docs#3752]
## Issue

This an issue with:

@sentry/react documentation

## Description
I'm trying to set up Performance Monitoring for React.
I already have @sentry/react tracking errors in my react application.
The [documentation](https://docs.sentry.io/platforms/javascript/guides/react/performance/) says to switch from `@sentry/react` to `@sentry/browser`. The problem is that when we switch it is not possible to use `Sentry.ErrorBoundary` anymore.

### Suggested Solution

change this
```
// If you're using one of our integration packages, like `@sentry/react` or
// `@sentry/angular`, substitute its name for `@sentry/browser` here
import * as Sentry from "@sentry/browser";
```
to this
```
import * as Sentry from "@sentry/react";
```

**Comment by onurtemizkan** [comment]
Thanks, @lebreRafael. We're currently working on some improvements to our React docs. #3627
