### ISSUE TITLE
building assets for Sentry v8.5.0.dev0 (build UNKNOWN)

### ISSUE THREAD

**Issue by wanghe4096** [getsentry/sentry-docs#38]
pulled version information from 'sentry' module

building assets for Sentry v8.5.0.dev0 (build UNKNOWN)

Could not determine sentry version or build

---

Cleaning up...
Command /home/sentry/sentry-docs/.api-docs-venv/bin/python -c "import setuptools, tokenize;**file**='/home/sentry/sentry-docs/.api-docs-venv/build/sentry/setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record /tmp/pip-7H0A0_-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/sentry/sentry-docs/.api-docs-venv/include/site/python2.7 failed with error code 1 in /home/sentry/sentry-docs/.api-docs-venv/build/sentry
Storing debug log for failure in /home/sentry/.pip/pip.log
Traceback (most recent call last):
  File "/home/sentry/sentry-docs/bin/../doc-modules/sentry/api-docs/generator.py", line 19, in <module>
    from sentry.runner import configure
ImportError: No module named sentry.runner
Traceback (most recent call last):
  File "/home/sentry/sentry-docs/bin/../doc-modules/sentry/bin/dump-command-help", line 6, in <module>
    from sentry.runner import cli as root_command
ImportError: No module named sentry.runner
make: **\* [extract-docs] Error 1
sentry@iZ28sbg9kgvZ:~/sentry-docs$

**Comment by mattrobenolt** [comment]
Hey @wanghe4096, before digging into this, what are you trying to do? This repository only supports docs.getsentry.com and has very little value outside of that and we don't expect this to be consumed by many people except internally.

Is there something specific that you're trying to achieve?

**Comment by wanghe4096** [comment]
@mattrobenolt thanks , i wanted to created zh for sentry
