### ISSUE TITLE
Links broken for SDK-specific grouping docs

### ISSUE THREAD

**Issue by mbauer404** [getsentry/sentry-docs#3811]
## Issue

This an issue with:

SDK documentation (Which one?)
Links to SDK fingerprinting incorrect across all SDKs

## Description

When on the project grouping page in the SaaS Sentry UI:
https://sentry.io/settings/{{org_slug}}/projects/{{project_slug}}/issue-grouping/ 

there are three links that take the user to this docs page:
https://docs.sentry.io/platform-redirect/?next=%2Fdata-management%2Fevent-grouping%2F&_ga=2.22391678.492853336.1624896739-741903596.1612391252

When on that page, if you click on any SDK, it takes you to a  

**Page Not Found
We couldn't find the page you were looking for.**

docs page. Here is an example: 
https://docs.sentry.io/platforms/android/data-management/event-grouping/

### Suggested Solution

Update the links to direct to the new SDK Fingerprinting sections like this example:
https://docs.sentry.io/platforms/android/usage/sdk-fingerprinting/

**Comment by imatwawana** [comment]
This content was updated on [PR 3776 - Update Grouping Content](https://github.com/getsentry/sentry-docs/pull/3776) and even though there was a redirect added in the front matter of the page, it doesn't seem to be working properly to redirect to the new content on the product side of the docs here:
https://docs.sentry.io/product/data-management-settings/event-grouping/

This issue should probably be opened on [getsentry/sentry](https://github.com/getsentry/sentry) to update the link in the product at this point.
