### ISSUE TITLE
Search box is not visible on mobile browsers

### ISSUE THREAD

**Issue by ueman** [getsentry/sentry-docs#3837]
### Core or SDK?

Platform/SDK

### Which part? Which one?

develop.sentry.dev

### Description

The search box (and sign in link) on the develop.sentry.dev page is not visible on mobile browsers (like Chrome on Android) in portrait.
On bigger phones it's at least visible in landscape.

### Suggested Solution

Maybe move the search into the side bar.

**Comment by PeloWriter** [comment]
Thanks, @ueman.

**Comment by untitaker** [comment]
@imatwawana do you have a rough idea of where the search bar could be on mobile?

**Comment by imatwawana** [comment]
Let's go with this placement: 
![2021-12-13_13-02-40](https://user-images.githubusercontent.com/76437239/145864650-a50dec51-df7b-4d07-b9a4-5707def8e220.png)
