### ISSUE TITLE
Problem Install Laravel 8

### ISSUE THREAD

**Issue by asman03** [getsentry/sentry-docs#3838]
### Core or SDK?

Platform/SDK

### Which part? Which one?

install

### Description

hello, I have problem when installing sentry on laravel 8 this notification

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - sentry/sentry-laravel 2.x-dev is an alias of sentry/sentry-laravel dev-master and thus requires it to be installed too.
    - sentry/sentry-laravel[dev-master, 2.7.0] require sentry/sdk ^3.1 -> satisfiable by sentry/sdk[3.1.0].
    - sentry/sdk 3.1.0 requires http-interop/http-factory-guzzle ^1.0 -> satisfiable by http-interop/http-factory-guzzle[1.0.0].
    - http-interop/http-factory-guzzle 1.0.0 requires guzzlehttp/psr7 ^1.4.2 -> found guzzlehttp/psr7[1.4.2, ..., 1.x-dev] but the package is fixed to 2.0.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - Root composer.json requires sentry/sentry-laravel ^2.7 -> satisfiable by sentry/sentry-laravel[2.7.0, 2.x-dev (alias of dev-master)].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

can you help me with this? thank you

### Suggested Solution

.

**Comment by PeloWriter** [comment]
Hi @asman03 - this looks more like a support issue than an issue with our documentation. May I point you to our [support site](https://help.sentry.io/), Discord server, or [Forum](https://forum.sentry.io/c/sdks/5) to ask for help?

**Comment by asman03** [comment]
sure, it's help me
