### ISSUE TITLE
SOC2 Report location

### ISSUE THREAD

**Issue by foxgrover** [getsentry/sentry-docs#3863]
### Core or SDK?

Core Sentry product

### Which part? Which one?

Settings in the core web app

### Description

https://docs.sentry.io/product/security/soc2/ shows the location where we're supposed to be able to download the SOC2 report but that menu option doesn't exist and on the page that looks like what the doc is supposed to be referring to, "Security & Privacy" - the soc2 report isn't there for downloading.

### Suggested Solution

Update the docs to accurately reflect where to download the report.

**Comment by alek-sentry** [comment]
@foxgrover can you confirm what permissions your sentry account has? The "Legal and Compliance" settings pane is not available to "Member" user accounts.

**Comment by alek-sentry** [comment]
Thanks, @foxgrover 

I was able to confirm that viewing the "Legal & Compliance" settings pane requires either "Owner" or "Billing" permissions. Can you try again with an account with either of those permission levels?

**Comment by foxgrover** [comment]
We confirmed on the owner account that works. Thanks, Alek.

**Comment by PeloWriter** [comment]
Thanks everyone. Looks like this issue is resolved and no Docs update is required.
