### ISSUE TITLE
Document variant support for Sentry Android Gradle Plugin

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-docs#3893]
### Core or SDK?

Platform/SDK

### Which part? Which one?

sentry android gradle plugin

### Description

Document variant support implemented by https://github.com/getsentry/sentry-android-gradle-plugin/pull/140

### Suggested Solution

Document examples on how to use it in the gradle plugin page https://docs.sentry.io/platforms/android/proguard/#gradle-configuration -> https://github.com/getsentry/sentry-docs/edit/master/src/platforms/android/common/proguard.mdx

**Comment by marandaneto** [comment]
cc @cortinico in case you fancy it :) otherwise, I can do it once I am back from vacay late this month

**Comment by cortinico** [comment]
I'm quite full at the moment, but I'll keep this in the inbox :) Maybe I find some spare time

**Comment by cortinico** [comment]
Here you go :) https://github.com/getsentry/sentry-docs/pull/3991
