### ISSUE TITLE
Support for Crash Free sessions on .net sdk

### ISSUE THREAD

**Issue by prat-coder** [getsentry/sentry-docs#3895]
### Core or SDK?

Platform/SDK

### Which part? Which one?

.net sdk , Report Health

### Description

In the new .net sdk(3.8.0) version , it specifies that user can setup crash free sessions to check the health of the system using sentry. But on the setup page for reporting health, .netsdk is not listed under supported sdks.(https://docs.sentry.io/product/releases/health/setup/)

Please confirm if its available on the .netsdk 3.8.0.

### Suggested Solution

If its not available please correct the docs.

**Comment by bitsandfoxes** [comment]
Hey, thanks for bringing this up. 
.NET will be added to the list via https://github.com/getsentry/sentry-docs/pull/3897

**Comment by bruno-garcia** [comment]
Worth noting it's only for Client mode (so only desktop, mobile, not web servers)
