### ISSUE TITLE
Create includes for Serverless

### ISSUE THREAD

**Issue by PeloWriter** [getsentry/sentry-docs#3904]
### Core or SDK?

Platform/SDK

### Which part? Which one?

Serverless

### Description

In https://github.com/getsentry/sentry-docs/pull/3830, content updates highlighted the potential value of creating `include` statements for common pieces.

### Suggested Solution

Evaluate which content is common, then create the `include` statements and directories.

**Comment by imatwawana** [comment]
Linking this to [issue 3172](https://github.com/getsentry/sentry-docs/issues/3172) as includes currently don't work properly in Product docs

**Comment by antonpirker** [comment]
Will close because with the rewrite of the docs, this is obsolete.
