### ISSUE TITLE
Unclear/No definition of stat type for event counts in API

### ISSUE THREAD

**Issue by MaggotMouth** [getsentry/sentry-docs#3951]
### Core or SDK?

Core Sentry product

### Which part? Which one?

API

### Description

The API endpoints that require you to supply a `stat` query parameter for event counts does not indicate what any of the options mean.

https://docs.sentry.io/api/projects/retrieve-event-counts-for-a-project/
https://docs.sentry.io/api/organizations/retrieve-event-counts-for-an-organization/
https://docs.sentry.io/api/teams/retrieve-event-counts-for-a-team/

From what I can tell, these map to values seen in the UI as:
`Blacklisted` == `Filtered`  (inbound filters)
`Rejected` == `Dropped`  (spike protection, quota exceeded)

However, I am unable to see what `generated` and `received` map to, as they do not line up with any of the numbers I can see in the UI.

For example, in one of my projects, I have the following counts for a 1 hour period:
![Screenshot 2021-07-29 at 08 42 45](https://user-images.githubusercontent.com/2102169/127447275-c8bb0c77-63fb-4ffa-9995-0c4a85819cb5.png)

When querying the API for the 4 different stat options, these are the counts I get back:
```
Blacklisted: 3548
Received: 3781
Rejected: 0
Generated: 235
```

Where does the `Accepted: 1429` come from in the screenshot?  How does the `generated` and `received` counts tie in?

### Suggested Solution

Indicate what each of the options represent as seen in the UI, or how the UI generates it's numbers.

**Comment by sentaur-athena** [comment]
I'm going to close this issue since it's old and we have updated our API docs ever since. Please feel free to create a new ticket if you have feedback about the existing docs.
