### ISSUE TITLE
Links to Performance Docs by Platfoorm

### ISSUE THREAD

**Issue by scefali** [getsentry/sentry-docs#3956]
### Core or SDK?

Core Sentry product

### Which part? Which one?

Core Sentry

### Description

We use a JSON file (https://docs.sentry.io/_platforms/_index.json) to store metadata around docs for each platform. I am requesting we add information for the performance documentation links in that JSON so we can point to those pages directly in Sentry when we point to performance docs.

### Suggested Solution

N/A

**Comment by a-hariti** [comment]
Is this still relevant @stephanie-anderson ?

**Comment by stephanie-anderson** [comment]
@mjq Do you know is this the file we keep around for self-hosted?
