### ISSUE TITLE
No intialization docs/instructions for C# WPF apps

### ISSUE THREAD

**Issue by awbacker** [getsentry/sentry-docs#3993]
### Core or SDK?

Platform/SDK

### Which part? Which one?

C#

### Description

I need to initialize this a WPF app, and the documentation is quite unclear on that.  

### Suggested Solution

Please add a section to the WPF documentation discussing how to initialize the SDK explicitly in a WPF app, including access to the DSN in the app.config if that is required.

**Comment by bruno-garcia** [comment]
Until we address this, please refer to this example: https://github.com/getsentry/examples/tree/master/dotnet/WpfDotNetCoreCSharp

Also, if you create a project in Sentry, you can select WPF and installation instructions are there:

![image](https://user-images.githubusercontent.com/1633368/128522967-75557b2f-17ea-441a-814b-937a9f006c19.png)

![image](https://user-images.githubusercontent.com/1633368/128522990-525247b2-d801-4aa5-9608-87291138846f.png)
![image](https://user-images.githubusercontent.com/1633368/128523034-5ad0f798-de29-416e-b8db-5d313a70cb8c.png)

**Comment by bruno-garcia** [comment]
We've had this on the docs for many years now: https://docs.sentry.io/platforms/dotnet/guides/wpf/#configuration

No instructions about app.config but that's not related to .NET. It's [standard ConfigurationManager ](https://learn.microsoft.com/en-us/dotnet/api/system.configuration.configurationmanager.appsettings?view=dotnet-plat-ext-8.0).
