### ISSUE TITLE
Document Request Mode Sessions

### ISSUE THREAD

**Issue by mitsuhiko** [getsentry/sentry-docs#4070]
### Core or SDK?

Core Sentry product

### Which part? Which one?

releases

### Description

This page does not explain how server side sessions work: https://docs.sentry.io/product/releases/health/

### Suggested Solution

Add a description of how it works

**Comment by adhiraj** [comment]
@mitsuhiko @matejminar who's the most knowledgeable / best person to write this?

**Comment by ahmedetefy** [comment]
@adhiraj probably me actually

**Comment by fanley-sentry** [comment]
Thanks Ahmed.
