### ISSUE TITLE
Feedback: can we drop the empty whitespace header only visible before scroll?

### ISSUE THREAD

**Issue by benvinegar** [getsentry/sentry-docs#409]
![image](https://user-images.githubusercontent.com/2153/46265028-a2043e80-c4d7-11e8-96b4-c78174e3a559.png)

It takes up a lot of room – especially on my 13" MBP – for which I'd rather be reading docs.

cc @cameronmcefee

**Comment by JTCunning** [comment]
This is the GOAT of all screenshots.

**Comment by benvinegar** [comment]
The design has changed at this point and this original ticket no longer applies.
