### ISSUE TITLE
What is the deal with wrapConsoleMethod() ?

### ISSUE THREAD

**Issue by grapho** [getsentry/sentry-docs#41]
I noticed recently that raven now wraps up all the console methods, but I do not see any documentation that describes why? or how it could possibly be useful? Has anyone come across this yet and could point me to some documentation on its use?

the issue I come across is I can no longer do simple debugging with `console.log()` .. the source becomes `raven.js` and i can no longer track where in my code it is eminating from?

**Comment by dcramer** [comment]
I would open this against the JS SDK repo, as this repo is entirely for our docs website.

**Comment by grapho** [comment]
oh so it is not meant to be documented? my bad

**Comment by dcramer** [comment]
The docs are also in the other repo but realistically all concerns to an SDK we keep in that repo as not all authors watch other repos 






On Tue, May 17, 2016 at 2:12 PM -0700, "Seth" <notifications@github.com> wrote:












oh so it is not meant to be documented? my bad
