### ISSUE TITLE
Android Advanced Data Scrubbing URL Missing

### ISSUE THREAD

**Issue by btseytlinTCP** [getsentry/sentry-docs#4101]
### Core or SDK?

Platform/SDK

### Which part? Which one?

Android

### Description

Looking for Advanced Data Scrubbing tips for Android. Specifically looking for handling of stacktraces and scrubbing PII/PHI out of it. https://docs.sentry.io/platforms/android/data-management/advanced-datascrubbing/

### Suggested Solution

An updated URL would help. Thank you!

**Comment by imatwawana** [comment]
Thanks for the catch! Can you let us know where you found the incorrect URL?

**Comment by imatwawana** [comment]
@btseytlinTCP, can you let us know where you found the URL that you indicated?

**Comment by btseytlinTCP** [comment]
Hey, sorry I can't find it now!

**Comment by imatwawana** [comment]
Ah okay. If you find where the link was broken, feel free to open a new issue. In the meantime, I think this is the content that you were looking for, though it's platform-agnostic: 
https://docs.sentry.io/product/data-management-settings/scrubbing/advanced-datascrubbing/
