### ISSUE TITLE
[DOC] 'Retrieve a Project' and 'Update a Project' quotes: 'the slug of the project to delete.'

### ISSUE THREAD

**Issue by markstory** [getsentry/sentry-docs#412]
_From @retomerz on October 1, 2018 11:39_

Both pages 'Retrieve a Project' [1] and 'Update a Project' [2] quotes this

> Parameters:     project_slug (string) — the slug of the project to delete. 

![image](https://user-images.githubusercontent.com/9657405/46286383-47262200-c57f-11e8-8057-a97f8eedb890.png)

Seems to be a Copy&Paste error from the 'Delete a Project' page.

[1] https://docs.sentry.io/api/projects/get-project-details/
[2] https://docs.sentry.io/api/projects/put-project-details/

_Copied from original issue: getsentry/sentry#9948_

**Comment by markstory** [comment]
_From @untitaker on October 1, 2018 11:40_

Hi, could you refile this against getsentry/sentry-docs? Thanks!

**Comment by untitaker** [comment]
Thanks Mark, was too lazy myself :)
