### ISSUE TITLE
Next.js SDK generated files with tokens/secrets?

### ISSUE THREAD

**Issue by holloway** [getsentry/sentry-docs#4122]
### Core or SDK?

Platform/SDK

### Which part? Which one?

Next.js

### Description

On this page https://docs.sentry.io/platforms/javascript/guides/nextjs/ it talks about generated files.

Of the files being generated (`sentry.client.config.js` `sentry.server.config.js` `next.config.js` and `sentry.properties`) it's unclear how secrets/tokens in (eg) `sentry.properties` such as `auth.token` should be handled.

It's best practice not to commit secrets/tokens to Git, but it's unclear whether these variables are security sensitive or not.

In a typical project would all these files be committed to Git as-is? If a project is open source would these files be committed?

The code generator uses environment variables for the DSN with `process.env.SENTRY_DSN || process.env.NEXT_PUBLIC_SENTRY_DSN` so can I assume that there are no other security sensitive values, or else they'd follow this pattern too?

If we're supposed to manually sanitise these files and change values to `process.env.SOMETHING` then how, and what file format is `sentry.properties`?

### Suggested Solution

Some advice on how to handle conventional projects and whether there are any security sensitive details in the generated files would be appreciated.

**Comment by iker-barriocanal** [comment]
Hi @holloway, thanks for your feedback! This was missing on the getting started page, but should be fixed on https://github.com/getsentry/sentry-docs/pull/4123. If you want to learn more about configuring `sentry-cli`, see https://docs.sentry.io/platforms/javascript/guides/nextjs/manual-setup/#configure-sentry-cli.
