### ISSUE TITLE
Deprecated SDKs migration guides 

### ISSUE THREAD

**Issue by priscilawebdev** [getsentry/sentry-docs#4137]
### Core or SDK?

Platform/SDK

### Which part? Which one?

"What's new" broadcast

### Description

Recently, some improvements have been implemented in the 'What's New' UI through the PR https://github.com/getsentry/sentry/pull/27711, making it clearer to the user which SDKs are deprecated and should be migrated and which SDKs have a new version and should be updated.

![image](https://user-images.githubusercontent.com/29228205/133050477-04f36d38-4725-49c9-bfaf-9e1fc6c11b32.png)

Deprecated SDKs are now being displayed on the top of the list with a 'deprecated' tag.  Along with each alert, a link to the migration documentation is also displayed and there are two problems with this:

1. Links from different domains are offered, as sometimes the migration documentation is only available in the repository of the new SDK. Example: 

https://github.com/getsentry/sentry-javascript/blob/master/MIGRATION.md#migrating-from-raven-js-to-sentrybrowser

2.  We currently don't have a migration guide available for all deprecated raven SDKs or the migration guide is not very clear. Example:

React Native migration content is in Docs, though I don't see specific mention of Raven: https://docs.sentry.io/platforms/react-native/migration/

### Suggested Solution

1. Consolidate all migration guides on our official docs website

2.  Provide migration guide for all supported platforms

3. Make our migration guides as clear as possible

**Comment by rahulchhabria** [comment]
@stephanie-anderson i think we can close this ticket since versioning should help

**Comment by chargome** [comment]
closing as I think https://docs.sentry.io/platforms/javascript/migration/ covers all cases
