### ISSUE TITLE
Suggest adding setTags method to Customize Tags field

### ISSUE THREAD

**Issue by ESTAID** [getsentry/sentry-docs#4145]
## Description

I'm making good use of the documentation you provided. But I was embarrassed because Even though `setTags` type is defined, there was no description of the `setTags` method in [Customize Tags](https://docs.sentry.io/platforms/javascript/guides/react/enriching-events/tags/) field. So I'd like to suggest adding `setTags` method to Customize Tags field.

**Comment by vladanpaunovic** [comment]
Good point @ESTAID, while at this, we should also document `removeTag`

**Comment by lforst** [comment]
I think this was already resolved. If not, feel free to clarify this issue a bit and we'll address it! Thanks!
