### ISSUE TITLE
Where are the `OperationType` Docs

### ISSUE THREAD

**Issue by thomaspurchas** [getsentry/sentry-docs#4159]
There seem to be special op types that are render differently in the performance tab, but they don't seem to documented or explained anywhere making it tricky to use them properly in an SDK.

https://github.com/getsentry/sentry-data-schemas/blob/3647b8cab1b3cfa289e8d7d995a5c9efee8c4b91/relay/event.schema.json#L2727

**Comment by AbhiPrasad** [comment]
These need to be documented in the develop docs see: https://github.com/getsentry/develop/issues/392. Closing this issue as the doc status for span operations is tracked in the linked issue.
