### ISSUE TITLE
Document how to create a project

### ISSUE THREAD

**Issue by lobsterkatie** [getsentry/sentry-docs#4160]
### Core or SDK?

Core Sentry product

### Which part? Which one?

Project creation

### Description

It's fairly obvious in the UI, I'll admit, but it might be worth adding a sentence or two to the Projects product guide telling people how to make a new project, for the folks who are docs-first type learners.

UPDATE: Found it. We should link to this from the projects page: https://docs.sentry.io/product/sentry-basics/guides/integrate-frontend/create-new-project/.

**Comment by imatwawana** [comment]
Fixed on [PR 4193](https://github.com/getsentry/sentry-docs/pull/4193)
