### ISSUE TITLE
Add performance to Java wizard and its integrations

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-docs#4189]
### Core or SDK?

Platform/SDK

### Which part? Which one?

sentry-java

### Description

Add performance to Java wizard and its integrations

### Suggested Solution

document them similar to Android https://github.com/getsentry/sentry-docs/pull/4188
Files: https://github.com/getsentry/sentry-docs/tree/master/src/wizard/java

**Comment by marandaneto** [comment]
cc @maciejwalkowiak

**Comment by maciejwalkowiak** [comment]
Java already has the performance documented - should anything change there?
We can easily add wizard for Spring Boot integration, for Spring (non-boot) setup is more complex so perhaps it just makes sense to link docs?

**Comment by marandaneto** [comment]
makes sense to document the spring boot bits and link the performance setup for spring (non-boot).
good idea
