### ISSUE TITLE
Add fallback userID to Capacitor, Cordova, Xamarin, and Unity

### ISSUE THREAD

**Issue by philipphofmann** [getsentry/sentry-docs#4206]
### Core or SDK?

Platform/SDK

### Which part? Which one?

Capacitor, Cordova, Xamarin, and Unity

### Description

Android and Cocoa use the `installationId` as a fallback for the userID if none is set. We should also document this behavior for Capacitor, Cordova, Xamarin, and Unity. For more context see https://github.com/getsentry/sentry-docs/pull/4201

### Suggested Solution

Add the same note as in https://github.com/getsentry/sentry-docs/pull/4201 if needed. 

Is it needed for
* Capacitor (@jennmueng, please answer)
~* Xamarin (@bitsandfoxes or @bruno-garcia , please answer)~ Doesn't have a native SDK under it
* Unity (@bitsandfoxes or @bruno-garcia , please answer)

**Comment by chadwhitacre** [comment]
@bruno-garcia Should this be triaged as "Backlog"?

**Comment by chadwhitacre** [comment]
(sentry-docs vs. sentry-[sdk], slightly different label dance, sorry :-/ )

**Comment by lucas-zimerman** [comment]
@philipphofmann Is this also relevant for Flutter and React Native?

**Comment by philipphofmann** [comment]
@lucas-zimerman we already updated the docs for Flutter and React Native, see https://github.com/getsentry/sentry-docs/pull/4201

**Comment by kahest** [comment]
The note is present in all mentioned SDKs:
https://docs.sentry.io/platforms/javascript/guides/capacitor/enriching-events/identify-user/
https://docs.sentry.io/platforms/javascript/guides/cordova/enriching-events/identify-user/
https://docs.sentry.io/platforms/unity/enriching-events/identify-user/
https://docs.sentry.io/platforms/dotnet/guides/xamarin/enriching-events/identify-user/
