### ISSUE TITLE
Electron docs list integrations that are not compatible with the Electron SDK

### ISSUE THREAD

**Issue by timfish** [getsentry/sentry-docs#4215]
### Core or SDK?

Platform/SDK

### Which part? Which one?

Electron

### Description

The `OfflineIntegration` gets included with the Electron docs but that integration is not compatible with the Electron SDK as events are sent from node and that integration is specifically designed to work in the browser. 

ref: https://github.com/getsentry/sentry-electron/issues/369

This is mostly a placeholder issue for the moment. The SDK is currently undergoing a [large refactor for v3](https://github.com/getsentry/sentry-electron/pull/361) that will require a substantial reworking of the docs.

### Suggested Solution

Wait for the v3 changes?

**Comment by AbhiPrasad** [comment]
Yeah let’s wait till v3 - I’ll backlog this anyway so we’ll make sure it’s in our radar.

**Comment by timfish** [comment]
I probably need to take another look and do a PR if anything still needs fixing!

**Comment by vladanpaunovic** [comment]
Ok, feel free to go for it once you have time.
