### ISSUE TITLE
wasm-split links are deprecated

### ISSUE THREAD

**Issue by prodoelmit** [getsentry/sentry-docs#4223]
### Core or SDK?

Platform/SDK

### Which part? Which one?

Data Management

### Description

There are several pages with links to `wasm-split` tool. Those links are broken

### Suggested Solution

Fresh link is https://github.com/getsentry/symbolicator/tree/master/crates/wasm-split

**Comment by imatwawana** [comment]
Thanks for letting us know. I'm pretty sure I've found all the broken ones and I've linked a PR to fix them.
