### ISSUE TITLE
Email Delivery IPs

### ISSUE THREAD

**Issue by Schtailian** [getsentry/sentry-docs#4254]
### Core or SDK?

Core Sentry product

### Which part? Which one?

https://docs.sentry.io/product/security/ip-ranges/#email-delivery

### Description

It does not state if the SendGrid IP addresses under #email-delivery, are only used by Sentry or if other SendGrid clients might use the same addresses.

### Suggested Solution

State in the documentation that the IPs are exclusive to Sentry or that they are not.

**Comment by chadwhitacre** [comment]
Can you chase down @getsentry/ops on this one, @imatwawana? 🐭
