### ISSUE TITLE
Add missing integrations to default integrations Apple

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-docs#4256]
### Core or SDK?

Platform/SDK

### Which part? Which one?

sentry-cocoa

### Description

all default integrations https://docs.sentry.io/platforms/apple/guides/ios/configuration/integrations/default/

### Suggested Solution

add missing integrations eg SentryNetworkTrackingIntegratio, SentryPerformanceTrackingIntegration, SentryAppStartTrackingIntegration and SentryFramesTrackingIntegration

**Comment by vivianyentran** [comment]
@philipphofmann Are these missing integrations still relevant?

**Comment by philipphofmann** [comment]
Yes, but the mentioned integrations aren't enabled by default. They are only enabled when you enable tracing. I think we can close this, as the tracing docs explain the features well. People don't care if they are integrations or not. If fixed one small thing with https://github.com/getsentry/sentry-docs/pull/11014. We can close this.
