### ISSUE TITLE
Silence stack trace do not working

### ISSUE THREAD

**Issue by higimo** [getsentry/sentry-docs#4258]
### Core or SDK?

Core Sentry product

### Which part? Which one?

SDK nextJS

### Description

`sentry.client.config.js`:
```
Sentry.init({
    dsn: SENTRY_DSN || 'https://nooooooooooooooooooo.ingest.sentry.io/1337',
    tracesSampleRate: 1.0,
    maxBreadcrumbs: 2,
    maxValueLength: 1,
    attachStacktrace: false,
    autoSessionTracking: false,
});
```

Not working=( I see stack trace in sentry issue and network tabs in my browser. 

### Suggested Solution

I want stack trace is off

**Comment by lobsterkatie** [comment]
Hi, @higimo.

As explained [in the docs](https://docs.sentry.io/platforms/javascript/configuration/options/#attach-stacktrace), the `attachStacktrace` option only. controls whether or not stacktraces are added to log messages captured using `captureMessage`. Exceptions always have stacktraces attached where possible. To remove those, you'll have to use `beforeSend` to check for and delete `event.exception.values[0].stacktrace`.

I'm curious, though - what's your use case? Why _wouldn't_ you want to see the codepath leading to your errors?
