### ISSUE TITLE
Transactions Overview

### ISSUE THREAD

**Issue by scefali** [getsentry/sentry-docs#4270]
### Core or SDK?

Core Sentry product

### Which part? Which one?

Transactions

### Description

Many of Sentry's users are confused about what a transaction is, why they should care about them, and how to effectively manage their quota limits. A docs page dedicated to answering these questions would be very helpful. Such a page would cover the following topics:

- What is a transaction?
- What can transactions be used for? (probably links to the performance and discover docs)
- What does it mean if I hit my transaction limit?
- How do I increase my transaction limit?
- What can I do to manage my transaction limit better (ex: sampling)?

### Suggested Solution
We are missing a clear definition of a transaction and why you would use them, so that will be added. We have a lot of content on quota management (which answer the last three questions), but it was mostly written before Performance was a feature, so it's not often clear where that content applies to transactions as well. The following updates 

Planned updates:

- [x] Add a [long definition of a transaction](https://docs.sentry.io/product/performance/transaction-summary/#what-is-a-transaction) on the Transaction Summary page
- [x] Add a [brief definition of a transaction](https://docs.sentry.io/product/performance/) on the Performance Monitoring page
- [x] Update [Quota Management docs](https://docs.sentry.io/product/accounts/quotas/manage-transaction-quota/) with clearer references to transactions
- [ ] Add [link](https://docs.sentry.io/product/performance/transaction-summary/#what-is-a-transaction) from Transaction Summary page to quota management docs

**Comment by silent1mezzo** [comment]
@scefali are the first two questions answered in https://docs.sentry.io/product/performance/ and https://docs.sentry.io/product/sentry-basics/tracing/distributed-tracing/#traces-transactions-and-spans ?

Definitely agree with things on limits. 

re: `What can I do to manage my transaction limit better (ex: sampling)?` curious to hear your thoughts on what more could be added than what's already in the SDK docs

**Comment by imatwawana** [comment]
@silent1mezzo & @scefali I suspect that what will end up being part of the solution here is making the [Tracing](https://docs.sentry.io/product/sentry-basics/tracing/distributed-tracing) page a bit more easily digestible. From what I can tell, some of these questions are already answered in the existing content, and I don't know that all of these questions should be answered in one page, but some of them probably should be. We'll definitely have to hammer out the scope of this. I've chatted with @wmak about this already, and I'll give some thought over the next few days about what I think will make sense.
