### ISSUE TITLE
Fix imports for Sentry react native

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-docs#4275]
### Core or SDK?

Platform/SDK

### Which part? Which one?

sentry react native sdk

### Description

correct imports for the sentry react native SDK

import is wrong on docs page https://docs.sentry.io/platforms/react-native/enriching-events/tags/

### Suggested Solution

RN sdk should have its own file for https://github.com/getsentry/sentry-docs/tree/master/src/includes/enriching-events/import

value should be probably:

`import * as Sentry from '@sentry/react-native';`

**Comment by rahulchhabria** [comment]
@stephanie-anderson i think this is done and can be closed.
