### ISSUE TITLE
Old source map is fail to work, when I upload the new source map release files?

### ISSUE THREAD

**Issue by samyoo-zhang** [getsentry/sentry-docs#4276]
### Core or SDK?

Platform/SDK

### Which part? Which one?

source map

### Description

We upload the new version of the source map file to the platform. At this time, there are old and new versions of source map files on the platform. Due to cache, some user is still using the old version of the page. At this time, when the user uploads an error to sentry, why can't I find the exact error location of the corresponding source file through the source map?

### Suggested Solution

Could you please support that if some user is still using the old version of the page and the user uploads an error to sentry at this release,  the old version source map is also available.

**Comment by lobsterkatie** [comment]
@samyoo-zhang - If everything is working correctly, this is already what happens. I'd suggest reaching out for support: https://docs.sentry.io/support/.
