### ISSUE TITLE
Release health is not enabled by default in .NET sdk

### ISSUE THREAD

**Issue by rodolfoBee** [getsentry/sentry-docs#4290]
### Core or SDK?

Platform/SDK

### Which part? Which one?

.NET SDK

### Description

Page: https://docs.sentry.io/platforms/dotnet/configuration/releases/#release-health

As commented in the source code, AutoSessionTracking defaults to FALSE instead of TRUE as mentioned in the docs.

https://github.com/getsentry/sentry-dotnet/blob/main/src/Sentry/SentryOptions.cs#L552-L562

### Suggested Solution

Edit the text/code snippets to reflect actual SDK behaviour.

**Comment by philipphofmann** [comment]
Thanks for reporting this @rbisol.
