### ISSUE TITLE
Document data scrubbing options for Relay

### ISSUE THREAD

**Issue by rbisol** [getsentry/sentry-docs#4317]
### Core or SDK?

Core Sentry product

### Which part? Which one?

Relay

### Description

The first use case for Relay is data scrubbing (as mentioned here: https://docs.sentry.io/product/relay/#use-cases-for-relay).

The issue is that there is virtually no documentation on "how" to scrub data using relay. 

The only line I found is "Relay uses the privacy settings configured in Sentry, and scrubs PII before forwarding data to Sentry.", which does not mention this is only true for relay running on managed mode.

### Suggested Solution

Add documentation on how to scrub data for all three modes: managed, static, and proxy.

**Comment by jan-auer** [comment]
Relates to https://github.com/getsentry/sentry-docs/issues/3576

**Comment by TBS1996** [comment]
such a page was added in january this year: https://docs.sentry.io/product/relay/pii-and-data-scrubbing/
