### ISSUE TITLE
Apple: Clarify CI and Debug for Upload dSYMs Docs

### ISSUE THREAD

**Issue by philipphofmann** [getsentry/sentry-docs#4319]
### Core or SDK?

Platform/SDK

### Which part? Which one?

Apple/Cocoa

### Description

The docs for uploading [dSYMs](https://docs.sentry.io/platforms/apple/dsym/)  doesn't clearly state which setup you should use when developing and which setup in CI.

### Suggested Solution

Clearly state which setup you can use in the following scenarios:
* Debugging locally
* Releasing with CI
* Publishing to Testflight with CI
* Publishing to Testflight locally
* Building and releasing locally

**Comment by rahulchhabria** [comment]
@philipphofmann can we assign this to you?

**Comment by philipphofmann** [comment]
We improved and simplified the [uploading dSYMs page for Appl](https://docs.sentry.io/platforms/apple/guides/ios/dsym/)e since I opened this issue 2 years ago. Every CI/development setup is different. I think we don't need to recommend which ones developers should use. I think we can close this and open a new issue if it comes up again.
