### ISSUE TITLE
Inconsistent notes on getting started pages

### ISSUE THREAD

**Issue by iker-barriocanal** [getsentry/sentry-docs#4351]
### Core or SDK?

Platform/SDK

### Which part? Which one?

All the platforms

### Description

Each platform's getting started page has a different format, which makes them inconsistent:

- Sometimes, the text is bold.
- Sometimes, the note is short.
- Sometimes, the note is long.
- Sometimes, there is no note.

<details>
<summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/32816711/140043905-c27c5e96-eef9-46ba-83ad-c205348ea8f0.png)

![image](https://user-images.githubusercontent.com/32816711/140044017-ab5ce72d-30b8-4eba-832f-7a9d8655d5ec.png)

![image](https://user-images.githubusercontent.com/32816711/140044097-19c28413-22b4-44d6-b847-cfc1a13d6e59.png)

![image](https://user-images.githubusercontent.com/32816711/140044146-a4b2e4cf-f2e2-4808-ad3c-f6c48b731b64.png)

![image](https://user-images.githubusercontent.com/32816711/140044167-3ed31d56-392f-4f1a-8f52-cebfd83a4c82.png)

</details>

The contents of the notes are also different from one platform to another. What should notes say?

### Suggested Solution

Be consistent in both format and content on all pages.

**Comment by stephanie-anderson** [comment]
There has been lots of improvements since this issue has been created; yet, we should have a final review of the current state of our getting started pages, and eventually close this issue, if all guides are consistent

**Comment by rahulchhabria** [comment]
@lizokm can you give this a quick review, please? i think we can close this since the majority of the formatting issues were handled during the migration.
