### ISSUE TITLE
Layer ARN selector is broken

### ISSUE THREAD

**Issue by moltar** [getsentry/sentry-docs#4358]
### Core or SDK?

Platform/SDK

### Which part? Which one?

Lambda layer

### Description

The Lambda layer selector on the doc page seems to be broken.
https://docs.sentry.io/platforms/node/guides/aws-lambda/layer/
https://docs.sentry.io/platforms/python/guides/aws-lambda/layer/

The current selection appears below the cursor (2 places down). And also makes it difficult to select the first option.

https://user-images.githubusercontent.com/491247/140247798-5babc260-d88a-4edb-abf6-d2453a364739.mp4

### Suggested Solution

Not sure.

**Comment by moltar** [comment]
Browser is latest Firefox on macOS btw.

**Comment by a-hariti** [comment]
It seems that this is not an issue anymore
