### ISSUE TITLE
Platform redirect missing from Filtering

### ISSUE THREAD

**Issue by rohitkataria-sentryio** [getsentry/sentry-docs#4363]
### Core or SDK?

Core Sentry product

### Which part? Which one?

Data Management --> Inbound Filters

### Description

When on: https://docs.sentry.io/product/data-management-settings/scrubbing/ and clicking “the SDK documentation”, it takes me to platform redirect.

Similarly, when on https://docs.sentry.io/product/data-management-settings/event-grouping/ and clicking on “using SDK Fingerprinting” , takes me to platform redirect.

But when on https://docs.sentry.io/product/data-management-settings/filtering/ , clicking on “your SDK to filter projects” , takes me to Javascript specific filtering options.

### Suggested Solution

 I would expect it to take me to platform redirect and from there to the filtering options of the SDK I'm interested in, just like it does for scrubbing and grouping (see links above)

**Comment by untitaker** [comment]
I wonder if we can lint against this too?

**Comment by rohitkataria-sentryio** [comment]
Not sure if this would be a separate issue, but same thing about environments: 
On  https://docs.sentry.io/product/sentry-basics/environments/#creating-environments , we see "your SDK, as documented for each SDK" which again takes user to JS specific guide. 

If I can be greedy, I would like to see a platform specific  **landing page** that would redirect for any SDK specific implementation, such as filtering/environment shared above (and then also for all of "Enriching events")

**Comment by chadwhitacre** [comment]
(P.S. @rohitkataria-sentryio Any chance you could make your `getsentry` org membership public? That way the bot will avoid applying "Status: Unrouted" in the future. 🙏)

**Comment by imatwawana** [comment]
> Not sure if this would be a separate issue, but same thing about environments: On https://docs.sentry.io/product/sentry-basics/environments/#creating-environments , we see "your SDK, as documented for each SDK" which again takes user to JS specific guide.
> 
> If I can be greedy, I would like to see a platform specific **landing page** that would redirect for any SDK specific implementation, such as filtering/environment shared above (and then also for all of "Enriching events")

I'm going to go ahead and fix these two instances, but my understanding is that if you've already chosen an SDK in our docs, even if you navigate between product and platform, your SDK selection is maintained. At least that's what we've got indicated in our [contributing docs](https://docs.sentry.io/contributing/linking/#from-product-to-platform) for the use case for a platform redirect. But when I'm testing it now, it doesn't seem to be working that way. @untitaker, can you confirm my understanding of how platform selection is supposed to work?

**Comment by imatwawana** [comment]
PR to fix links mentioned in above: 
https://github.com/getsentry/sentry-docs/pull/4366

**Comment by untitaker** [comment]
>@untitaker, can you confirm my understanding of how platform selection is supposed to work?

that would be great behavior, I am not sure if this is currently implemented. it definetly used to work that way at some point, but perhaps before we moved to gatsbyjs. @dcramer probably knows

**Comment by rahulchhabria** [comment]
@stephanie-anderson - i think we can close this for now.

**Comment by vivianyentran** [comment]
closing since the link now points to a platform redirect
