### ISSUE TITLE
Apple: Add Default Context Page

### ISSUE THREAD

**Issue by philipphofmann** [getsentry/sentry-docs#4389]
### Core or SDK?

Platform/SDK

### Which part? Which one?

Apple

### Description

Apple doesn't have a page for Default Context as [Android](https://docs.sentry.io/platforms/android/enriching-events/context/default-context/) does.

### Suggested Solution

Add the Default Context page to Apple. We can use [Android](https://github.com/getsentry/sentry-docs/blob/master/src/platforms/android/common/enriching-events/context/default-context.mdx) as a reference.

**Comment by marandaneto** [comment]
Dart/Flutter needs it too
