### ISSUE TITLE
"Contributing to Sentry" only show instructions for OSX

### ISSUE THREAD

**Issue by mdamien** [getsentry/sentry-docs#44]
Since the dev servers and the test environnement is on linux, it would be nice to add the instructions for linux too. Latest Ubuntu would be fine I think.

I guess, you could just add a link to [the official installation from source](https://github.com/getsentry/sentry-docs/blob/master/docs/serverdev/index.rst) process.

I can make a PR if this issue is confirmed.

**Comment by untitaker** [comment]
I think this has been fixed, thanks for your contribution!
