### ISSUE TITLE
Consistent formatting for instruction types

### ISSUE THREAD

**Issue by cameronmcefee** [getsentry/sentry-docs#441]
Our docs are all over the place with how we format things. Here's a proposed spec for how we consistently format things. I'm not available to make these changes currently, but I'll come back here when I have some time to open a PR to apply this if everyone is on board.

- `code`
  - Anything code or code related
  - API slugs
  - Command line examples
  - File system references
     > Open `foo/bar.png`
- _emphasis_
  - References to UI
    > Click the _New project_ button
  - Menu actions, on the actions, no the separators
    > Open the menu at _View_ > _Source_
- “double quotes”
  - Proposed textual content
    > Name your project “My project” 
- **bold**
  - Do not use as the primary method for formatting. Use it as you would normally use bold, to provide emphasis.

cc @getsentry/sdks @rsomething @jessla

**Comment by benvinegar** [comment]
👍
