### ISSUE TITLE
Blockquotes don't work for the wizard

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-docs#4411]
### Core or SDK?

Platform/SDK

### Which part? Which one?

sentry-docs

### Description

Blockquotes don't work when used on the wizard

it should have worked tho since native markdown is described as supported in the docs page https://docs.sentry.io/contributing/onboarding-wizard/

### Suggested Solution

find a replacement that works for the wizard and replace it in all the wizard files
eg https://github.com/getsentry/sentry-docs/blob/master/src/wizard/react-native/index.md?plain=1#L10

**Comment by marandaneto** [comment]
@imatwawana can you help us with that? thanks

**Comment by imatwawana** [comment]
> @imatwawana can you help us with that? thanks

I'll do some research and see what I can find.

**Comment by chadwhitacre** [comment]
(P.S. @marandaneto Can you make your [org membership public](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-user-account/managing-your-membership-in-organizations/publicizing-or-hiding-organization-membership)? That way the bot won't drop you into the routing/triage queue. 🙏 )

**Comment by marandaneto** [comment]
@chadwhitacre TIL, thanks

**Comment by imatwawana** [comment]
There's no reason this component shouldn't render in a markdown file, so I suspect this is being caused by the interaction between the frontend code and the markdown file. It's been suggested that there might be missing CSS. I've opened an issue on that repo: https://github.com/getsentry/sentry/issues/30126
