### ISSUE TITLE
how to view Breadcrumb?

### ISSUE THREAD

**Issue by BestAndroider** [getsentry/sentry-docs#4459]
### Core or SDK?

Platform/SDK

### Which part? Which one?

x

### Description

i add a breadcrumb in my code，but i can not fund how to find them in the sentry website,where is my breadcrumb,the document tells me how to add breadcrumb in my code ,but do not tells me how to find them, and i find them for a long time but.......

### Suggested Solution

the document should be not only tells people how to do in the code ,and how to find these data in the sentry website is needed too.....

**Comment by imatwawana** [comment]
Hi @BestAndroider, on the Breadcrumbs setup page, the text below is at the top of the page, but do you think it would be helpful to have a reminder at the bottom of the page, after you finish the setup?

![2021-12-02_09-28-43](https://user-images.githubusercontent.com/76437239/144441558-e57fd84e-b041-4c26-8276-a5850edc0449.png)
