### ISSUE TITLE
Make RN docs RN friendly

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-docs#4461]
### Core or SDK?

Platform/SDK

### Which part? Which one?

sentry-docs

### Description

RN docs inherit a lot from JS docs, but its not always the same, code snippets also change.it's

eg https://github.com/getsentry/sentry-docs/pull/4457

### Suggested Solution

make RN docs RN friendly, add missing RN code snippets, with proper importing and semantically correct code snippets

**Comment by marandaneto** [comment]
related to https://github.com/getsentry/sentry-docs/issues/4454

**Comment by rahulchhabria** [comment]
@stephanie-anderson i think we can close this issue.
