### ISSUE TITLE
Clarify Expectations of OOM

### ISSUE THREAD

**Issue by philipphofmann** [getsentry/sentry-docs#4499]
### Core or SDK?

Platform/SDK

### Which part? Which one?

Apple

### Description

In https://github.com/getsentry/sentry-cocoa/issues/1152 a user complained that the OOM errors of Cocoa have a wrong user ID. 

### Suggested Solution

We should clarify the expectation of OOM that it is not a normal Sentry event and the context like userID might not be accurate.

**Comment by rahulchhabria** [comment]
@philipphofmann @stephanie-anderson i think this has gone stale and not relevant anymore. closing. please reopen if i missed something.
