### ISSUE TITLE
Code from the build system leaking into code samples

### ISSUE THREAD

**Issue by cameronmcefee** [getsentry/sentry-docs#4547]
### Core or SDK?

Platform/SDK

### Which part? Which one?

@sentry/react

### Description

https://docs.sentry.io/platforms/javascript/guides/react/

The first code sample includes what appears to be part of the build system that made its way into the sample

```
# Using npm
npm install --save @sentry/react @sentry/tracing
# Using yarn
yarn add @sentry/react @sentry/tracing


export const _frontmatter = {}
```

The last line there probably isn't part of the directions

### Suggested Solution

Remove the last line. I spent a minute trying to figure out where it was coming from, but it seems to be deep in the mire of generated content.

**Comment by imatwawana** [comment]
Fixed by [PR 4652](https://github.com/getsentry/sentry-docs/pull/4652)
