### ISSUE TITLE
App Start is time-to-initial-display

### ISSUE THREAD

**Issue by philipphofmann** [getsentry/sentry-docs#4554]
### Core or SDK?

Platform/SDK

### Which part? Which one?

Apple, Android, React-Native

### Description

The docs on app start don't clearly state that we measure the [time-to-initial-display](https://developer.android.com/topic/performance/vitals/launch-time#time-initial) and not the [time-to-fully-display](https://developer.android.com/topic/performance/vitals/launch-time#time-full). 

### Suggested Solution

Point that out on

- [Apple](https://docs.sentry.io/platforms/apple/performance/instrumentation/automatic-instrumentation/#app-start-instrumentation)
- [Android](https://docs.sentry.io/platforms/android/performance/instrumentation/automatic-instrumentation/#app-start-instrumentation)
- [React Native](https://docs.sentry.io/platforms/react-native/performance/instrumentation/automatic-instrumentation/#app-start-instrumentation)

**Comment by marandaneto** [comment]
Before doing that, we need to validate that our platforms do TTID correctly, currently, our docs state where it starts and where it ends (by a function call, or notification name).

**Comment by kahest** [comment]
@philipphofmann is this still relevant? I'm assuming this is affected by https://github.com/getsentry/develop/pull/776 once we have it for the mentioned platforms (Android ✅ ).

**Comment by philipphofmann** [comment]
Yes, we can close this. We should update this once we have TTID and TTFD.
