### ISSUE TITLE
Add Quarkus to the list of supported platforms

### ISSUE THREAD

**Issue by gastaldi** [getsentry/sentry-docs#4557]
### Core or SDK?

Platform/SDK

### Which part? Which one?

Java

### Description

It would be nice to have [Quarkus](https://quarkus.io) listed as an available platform. Instructions on how to enable it are described in https://quarkiverse.github.io/quarkiverse-docs/quarkus-logging-sentry/dev/index.html

### Suggested Solution

Instructions are available here: https://quarkiverse.github.io/quarkiverse-docs/quarkus-logging-sentry/dev/index.html

**Comment by bruno-garcia** [comment]
Quarkus is currently community support. The code itself is on their repo and the docs is there too. 
For that reason for the time being we won't be documenting it here.

**Comment by bruno-garcia** [comment]
We could list it here: https://docs.sentry.io/platforms/#community-supported

**Comment by gastaldi** [comment]
Thanks for the feedback @bruno-garcia.

Speaking on behalf of the Quarkus team, we will be more than happy if we could have someone from the Sentry team to help us maintain the Sentry integration. We'd be thrilled if we could be listed as a supported solution in the https://docs.sentry.io/platforms/java/, as I have received some feedback from some users having trouble finding instructions on how to integrate their Quarkus apps with Sentry in the official documentation.

**Comment by gastaldi** [comment]
> We could list it here: [docs.sentry.io/platforms/#community-supported](https://docs.sentry.io/platforms/#community-supported) Would be willing to open a PR?

It looks like that section mentions different SDKs. The Quarkus extension uses the existing Sentry Java SDK, so I am a bit unsure if it makes sense to be listed there.

**Comment by bruno-garcia** [comment]
The Quarkus integration is built on top of our Java SDK but it isn't maintained by Sentry. Neither it is in Sentry's organization on GitHub. So having the docs for it here could be difficult to maintain as we don't have anyone on staff involved in the development of this integration. That said, we could have a link to the Quarkus docs. That's what I referred to when pointing to the Community Supported part of the docs, it could say:

* Quarkus - Built on top of the Sentry SDK for Java and maintained by the Quarkus team

We could also consider the link elsewhere if that would make more sense.

While we really appreciate that you folks created this and maintain this but at this time we don't have the bandwidth to take over, or contribute more than what was done in the past ([for example, some version updates done by Maciej](https://github.com/quarkusio/quarkus/pulls?q=is%3Apr+sort%3Aupdated-desc+author%3Amaciejwalkowiak+is%3Aclosed) for example).

That's not to say we can't reconsider that in the future, Quarkus is a growing project and there will be more demand. Sentry is also growing the team responsible for SDKs so there might be more bandwidth for this in the future.
