### ISSUE TITLE
Failure to locate `sentry-cli` should result in error, not warning

### ISSUE THREAD

**Issue by armcknight** [getsentry/sentry-docs#4564]
If a customer has already integrated the invocation of `sentry-cli` into their Xcode project, we should break their build instead of simply emitting a warning if the executable cannot be located/run (as described [here](https://docs.sentry.io/platforms/apple/dsym/?_ga=2.128113675.689385093.1640731068-498091088.1640731068#uploading-symbols-with-sentry-cli)). If we allow their build to succeed, then they will wind up with unsymbolicated results in their dashboard, which is not desirable. In a worse case, they may run a deploy to beta/production on a remote machine where `sentry-cli` has not been installed, and not know that they are going to encounter these unsymbolicatable results until it's too late. I would want that build to fail if it were me.

A possible additional option that I've used in the past is to allow certain warnings/errors to be configured to be escalated/downgraded with an option like `--warnings-as-errors` or `--errors-as-warnings`.

**Comment by philipphofmann** [comment]
Hey @armcknight, https://github.com/getsentry/sentry-cli/issues/1092 is completed now. Do you want to revisit this issue now?
