### ISSUE TITLE
[PHP] send_attempts option not documented

### ISSUE THREAD

**Issue by Jean85** [getsentry/sentry-docs#4579]
### Core or SDK?

Platform/SDK

### Which part? Which one?

PHP

### Description

As reported in https://github.com/getsentry/sentry-php/issues/1204#issuecomment-814051457, `send_attempts` option of the PHP SDK is not documented.

### Suggested Solution

Add docs about the (PHP specific) option

**Comment by imatwawana** [comment]
@stayallive - can you take a look?

**Comment by mfb** [comment]
It'd be more clear to document this as 

> Controls how many times the SDK will attempt to **resend** an event to Sentry. The default is `3`.

As `3` will cause the event to be sent 4 times if there was a 500 error.

**Comment by stayallive** [comment]
@mfb good call, done in #4599.
