### ISSUE TITLE
API Documentation Error: /api/events/get-group-details/

### ISSUE THREAD

**Issue by lukashaertel** [getsentry/sentry-docs#460]
The endpoint does not exist

**Comment by markstory** [comment]
Where are you seeing the invalid documentation?

**Comment by lukashaertel** [comment]
the endpoint listed on the documentation responds 404

Mark Story <notifications@github.com> schrieb am Do., 11. Okt. 2018, 16:33:

**Comment by markstory** [comment]
Which documentation page gives you that URL though?

**Comment by lukashaertel** [comment]
The one mentioned in the title: https://docs.sentry.io/api/events/get-group-details/

**Comment by untitaker** [comment]
I have now verified the endpoint does exist. Make sure you have the correct credentials set, don't forget the trailing slash and it's "issues", not "issue". Just saying this because all three issues bit me when trying to reproduce your problem :)
