### ISSUE TITLE
PHP Performance Monitoring Instrumentation 

### ISSUE THREAD

**Issue by masinette** [getsentry/sentry-docs#4626]
### Core or SDK?

Platform/SDK

### Which part? Which one?

php

### Description

PHP automatic instrumentation for Performance Monitoring, is not available. Might be worth it to adjust the wording a bit here: [https://docs.sentry.io/platforms/php/#performance-monitoring](https://docs.sentry.io/platforms/php/#performance-monitoring) to clarify that.

### Suggested Solution

Please include a disclaimer explaining that automatic instrumentation is not currently available for php.

**Comment by imatwawana** [comment]
@stayallive - It probably makes sense to deal with this issue at the same time as [4613](https://github.com/getsentry/sentry-docs/issues/4613).
