### ISSUE TITLE
Sentry for JIRA documentation URL is incorrect

### ISSUE THREAD

**Issue by liamjones** [getsentry/sentry-docs#4648]
### Core or SDK?

Platform/SDK

### Which part? Which one?

Sentry for JIRA plugin

### Description

The documentation link in your JIRA 'manage apps' section for Sentry and in the [Atlassian Marketplace listing](https://marketplace.atlassian.com/apps/1219432/sentry-for-jira?hosting=cloud&tab=support) is incorrect.

It links to https://docs.sentry.io/integrations/jira/?utm_campaign=partner&utm_source=marketplace&utm_medium=text&utm_content=atlassian&utm_term=jira which 404s

### Suggested Solution

Either provide a redirect in the docs site or change the URL in the plugin.

I believe the URL should now be https://docs.sentry.io/product/integrations/project-mgmt/jira/

**Comment by manuzope** [comment]
Fixed! Thanks for the heads up, @liamjones!
