### ISSUE TITLE
Create Performance SDK configuration primer

### ISSUE THREAD

**Issue by imatwawana** [getsentry/sentry-docs#4660]
### Core or SDK?

Platform/SDK

### Which part? Which one?

All

### Description

[From customer feedback](https://www.notion.so/sentry/Performance-Custom-Implementation-Roadblocks-67439fb9bd2947e4a178fd71eba957cb). In summary, users are trying to figure out how to send custom transactions and the problem they ran into was not understanding where in their application to put the appropriate code. 

### Suggested Solution

We can't tell you where to specifically add this in your code because that's dependent on your application and what you're trying to capture. But we can provide guidance on how to think about setting up performance in your application. Kind of a performance primer/best practices with the following proposed outline/topics to cover:

- Turn on performance
- Review auto instrumentation - be aware of what's there since some of this will be useful to you and some of it won't
- See how custom/manual instrumentation can work for you
- Spans and transactions
- How do you start a transaction in the first place

Down the road, based on conversations with customers, we could also provide some specific examples of where you would add the custom instrumentation.

**Comment by smeubank** [comment]
Immediate questions to answer:
Can we get more concrete examples from apps the customers struggle to understand how instrument? 
- example apps and code from our customers with first feedback on this issue

How can we make react and react-native developer docs better?

Second phase topics:
Why doesn't feedback come with other SDKs/frameworks?
- component tree based
- popularity of react and react-native

Is it an issue with wording?
- can we do a better job of explaining the product and concepts behind instrumentation. Taking more care to hold someone's hand through setting up their app with sentry for performance
