### ISSUE TITLE
Missing details regarding when and where to invoke setUser

### ISSUE THREAD

**Issue by dharshan0011** [getsentry/sentry-docs#4665]
### Core or SDK?

Platform/SDK

### Which part? Which one?

Identify Users under Enriching Events

### Description

Missing details regarding where to call the setUser method. I am calling it as soon as the user logs in. However, most of the time we have our JWT token stored in local storage hence the user need not to login until it expires. This didn't work for me, though. I am still trying to troubleshoot it. Anyways, the docs must elaborate on when and where is the ideal place to call the setUser method. 

### Suggested Solution

Include details on when and where to call setUser method. An example would also help.

**Comment by imatwawana** [comment]
@dharshan0011, to help me route this, what SDK were you using?
