### ISSUE TITLE
Consider removing legacy client docs from search

### ISSUE THREAD

**Issue by jan-auer** [getsentry/sentry-docs#467]
This is more of a discussion than an actual issue. Search currently includes the legacy `/clients/`. I was wondering if we should consider to omit those from search, or maybe highlight them to distinguish them from current docs to reduce the chance for confusion.

Example: https://docs.sentry.io/search/?q=express

**Comment by cameronmcefee** [comment]
This is relatively easy to do. Does every sdk under `/clients/` have an updated equivalent? If so, I can just hide everything in there from the search index. Otherwise we should be selective and only hide sdks that have new versions.

**Comment by untitaker** [comment]
Maybe we can just push the search results for legacy to the bottom

**Comment by cameronmcefee** [comment]
That is an option, but with Lunr it isn't entirely straightforward. There isn't any sort of coherent ranking ability (at least within the things that don't require some sort of mathematical algorithm beyond me), so we'd need to manually sort the results, which often include many very low-quality matches, and we don't paginate. As it stands, manually sorting would result in putting them at the end of the long list which is effectively the same as deleting.

**Comment by untitaker** [comment]
I am concerned about people who still use an old SDK even though there is a newer one and want to look something up.

**Comment by jan-auer** [comment]
Search has been massively improved, and I would consider this particular issue solved.
