### ISSUE TITLE
typo in React docs?  "Sentry.init has to be called in the somewhere before"

### ISSUE THREAD

**Issue by techieshark** [getsentry/sentry-docs#471]
In  [sentry-docs/src/collections/_documentation/platforms/javascript/react.md](https://github.com/getsentry/sentry-docs/blob/22e7ff5c6ced4c446d79e2e5a63dd47061859256/src/collections/_documentation/platforms/javascript/react.md), I'm not sure what the meaning of the comment in the code example is:

```
import * as Sentry from '@sentry/browser';
// Sentry.init has to be called in the somewhere before

class ExampleBoundary extends Component {
...
```

Where is "in the somewhere before"? Is this a typo?

From the [Vue docs](https://github.com/getsentry/sentry-docs/blob/22e7ff5c6ced4c446d79e2e5a63dd47061859256/src/collections/_documentation/platforms/javascript/vue.md), it looks like the code example should perhaps be similar:

```
import * as Sentry from '@sentry/browser';

// Sentry.init has to be called before we can report to Sentry
Sentry.init({
  dsn: 'your-dsn',
  ... /* other options, see: https://docs.sentry.io/learn/configuration/?platform=javascript */
}) 


class ExampleBoundary extends Component {
...
```

@HazAT  how's that look?

**Comment by HazAT** [comment]
Thanks for pointing this out, this PR should make it clearer
https://github.com/getsentry/sentry-docs/pull/472
