### ISSUE TITLE
Incorrect redirects for Performance Monitoring and Release Health for several SDKs

### ISSUE THREAD

**Issue by rohitkataria-sentryio** [getsentry/sentry-docs#4718]
### Core or SDK?

Platform/SDK

### Which part? Which one?

Android, React Native, DotNet, iOS, Flutter, NextJS

### Description

For any of the SDKs at the url: https://docs.sentry.io/platforms/<sdk-name>/, that is, the landing page for a given SDK, the links to Performance monitoring and Release Health on that main page (not the left side bar), take the user to the corresponding  **product** section of the documentation. 

So far, I have observed this for these SDKs: Android, React Native, DotNet, iOS, Flutter, NextJS 

If a user is anyways on SDK specific docs and wants to go ahead and set up either Performance Monitoring or Release Health for these SDKs, then we should  not be redirecting them one level up and leave them to concepts, rather take them one level down to implementation section of that SDK.

For instance: https://docs.sentry.io/platforms/apple/guides/ios/ does this correctly where is says "Automatic [Performance Tracking](https://docs.sentry.io/platforms/apple/guides/ios/performance/instrumentation/)" but not just above it where it says: "[Release Health](https://docs.sentry.io/product/releases/health/) tracks crash free users and sessions"

Flutter, at https://docs.sentry.io/platforms/flutter/  is in fact not listing Performance Monitoring on its landing page as all the other SDKs do. 

### Suggested Solution

Keep the user within the SDK specific docs for Performance Monitoring and Release Health.

**Comment by lobsterkatie** [comment]
I actually think it makes sense as is. @bruno-garcia , what do you think?
