### ISSUE TITLE
Broken link 

### ISSUE THREAD

**Issue by bityob** [getsentry/sentry-docs#4732]
### Core or SDK?

Core Sentry product

### Which part? Which one?

https://help.sentry.io/

### Description

This [page](https://help.sentry.io/account/security/why-am-i-seeing-filtered-in-my-event-data/) has a link to **[Sensitive Data](https://docs.sentry.io/data-management/sensitive-data/)** page - 
![image](https://user-images.githubusercontent.com/20026896/154270437-f1e9a8bb-3d0a-4543-b703-207ea4014401.png)

but the page doesn't exists.

![image](https://user-images.githubusercontent.com/20026896/154270354-73c31576-183e-424d-ad09-9f4d6a75c863.png)

Page - https://help.sentry.io/account/security/why-am-i-seeing-filtered-in-my-event-data/
Link - https://docs.sentry.io/data-management/sensitive-data/

### Suggested Solution

Fix link

**Comment by bityob** [comment]
@souredoutlook why closed?

**Comment by bityob** [comment]
Still borken

**Comment by souredoutlook** [comment]
@bityob Thanks for bringing that up - looks like the relevant commit was merged but not deployed (hence the automated closure). Will get it looked after today. The specific change to the document below:

```
To learn more about what fields and values Sentry considers sensitive, please see our documentation on [Server-Side Data Scrubbing](https://docs.sentry.io/product/data-management-settings/scrubbing/server-side-scrubbing/).
```
