### ISSUE TITLE
list of frameworks isn't displayed if there are no headings on a page

### ISSUE THREAD

**Issue by imatwawana** [getsentry/sentry-docs#4740]
### Core or SDK?

Platform/SDK

### Which part? Which one?

Node.js, Native, Python 

### Description

The right sidebar isn't rendering for some frameworks under Node.js, Native, and Python. This is because there are no headings on these pages, so the system doesn't generate the page-level TOC. Since it doesn't generate that, the list of frameworks that would be part of that isn't displayed.

Under Node.js
- Azure Functions
- Connect

Under Native
- Google Crashpad

Under Python
~~- Celery~~
- Apache Spark

### Suggested Solution

Change the behaviour of the page-level TOC for pages that don't have headings.

**Comment by imatwawana** [comment]
The list of frameworks doesn't show up if there's nothing for the right-side menu to render (that is, no headings on the page). Changing this to an enhancement and updating the title.

**Comment by a-hariti** [comment]
Could you provide more context and how to repro this issue @imatwawana ?
