### ISSUE TITLE
Add example of specifying plugins in requirements.txt

### ISSUE THREAD

**Issue by TheSavior** [getsentry/sentry-docs#48]
Currently the installation with docker page: https://docs.getsentry.com/on-premise/server/installation/docker/

says

```
On top of that, we have a requirements.txt file for installing plugins.
```

and links to

https://docs.getsentry.com/on-premise/server/plugins/

which does not explain how to use the requirements.txt file for installing plugins. It would be ideal to have an example that explained how to install plugins and pin versions.

**Comment by hpurmann** [comment]
How does this file work? I still can't find documentation on how to install the github sso auth plugin inside of Docker.

**Comment by philicious** [comment]
in case anyone else stumbles over this:
you have to add `https://github.com/getsentry/sentry-auth-google/archive/52020f577f587595fea55f5d05520f1473deaad1.zip` to `requirements.txt`

Explanation:
the Dockerfile for the onbuild images like `sentry:9.0-onbuild` does `pip install -r requirements.txt` (see https://github.com/getsentry/docker-sentry/blob/f648178adf33bec68be47550a82850e18deb0cd8/9.0/onbuild/Dockerfile#L10 )
**Note: This only works for the onbuild images**

So the requirements.txt is a pip thing and not a sentry feature. Therefore add the value you see in any sentry plugin install info like `pip install https://github.com/getsentry/sentry-auth-google/archive/master.zip`

Also see https://github.com/getsentry/sentry-auth-google/issues/27#issuecomment-397082005 on how to use the requirements.txt

**Comment by csonuryilmaz** [comment]
@hpurmann as @philicious said:
> ... the requirements.txt is a pip thing and not a sentry feature. Therefore add the value you see in any sentry plugin install info ...

So I clicked on links for my favorite plugins from [this page](https://docs.sentry.io/server/plugins/) collected these values from plugins' github pages: 
`sentry-redmine sentry-gitlab sentry-slack sentry-github`
Now my requirements.txt looks like this:
```
[root@sentry onpremise]# cat requirements.txt 
# Add plugins here
sentry-redmine
sentry-gitlab
sentry-slack
sentry-github
```
And it seems working:
```
[root@sentry onpremise]# make build
...
Installing collected packages: sentry-redmine, python-gitlab, sentry-gitlab, sentry-slack, sentry-github
  Running setup.py install for sentry-redmine: started
    Running setup.py install for sentry-redmine: finished with status 'done'
  Running setup.py install for python-gitlab: started
    Running setup.py install for python-gitlab: finished with status 'done'
  Running setup.py install for sentry-gitlab: started
    Running setup.py install for sentry-gitlab: finished with status 'done'
  Running setup.py install for sentry-github: started
    Running setup.py install for sentry-github: finished with status 'done'
Successfully installed python-gitlab-1.7.0 sentry-github-0.1.2 sentry-gitlab-0.2.0 sentry-redmine-0.1.0 sentry-slack-0.5.0
...
```

**Comment by grv231** [comment]
I just tried this today (creating custom **on-premise** sentry image), and the following works for me:

```
# Add plugins here
pagerduty
asana
```
Additionally, I didn't need to run to execute  `pip install -r requirements.txt` in the Dockerfile since iI used the sentry:onbuild image. Following is documented [here](https://github.com/getsentry/docker-sentry/blob/f648178adf33bec68be47550a82850e18deb0cd8/9.0/onbuild/Dockerfile#L10)

Hope this helps other people :)
