### ISSUE TITLE
Documentation for .sentryclirc file is missing from page

### ISSUE THREAD

**Issue by axelson** [getsentry/sentry-docs#4800]
### Core or SDK?

Platform/SDK

### Which part? Which one?

Javascript platform Webpack configuration

### Description

On https://docs.sentry.io/platforms/javascript/sourcemaps/uploading/webpack/ it says:

> Create .sentryclirc file with necessary configuration, as documented on this page

However, that is the only mention of the `.sentryclirc` file on the page

### Suggested Solution

Instead it should either link to a page like https://docs.sentry.io/product/cli/configuration/ or contain info about the format of the `.sentryclirc` (probably the former).

**Comment by imatwawana** [comment]
Thanks for the catch @axelson!
