### ISSUE TITLE
table doesn't resize properly

### ISSUE THREAD

**Issue by imatwawana** [getsentry/sentry-docs#4824]
### Core or SDK?

Core Sentry product

### Which part? Which one?

https://docs.sentry.io/product/accounts/membership/

### Description

The page layout is broken on this page such that when you resize the page, the table overlaps the right side menu. The error seems to be specific to this page as other tables don't show this issue.
![image](https://user-images.githubusercontent.com/76437239/157699282-78d7aac8-b9f1-4987-8112-22df064e5f43.png)

### Suggested Solution

Fix the table column/width limitation so that tables are resized properly no matter their width.

**Comment by sdzhong** [comment]
**This seems to happen when surpassing a certain number of table columns and/or a certain width of the table.**

You can see the same behavior in the tables in https://docs.sentry.io/product/integrations/ (see screenshot).

1. The Deployment table is spilling into the sidebar https://github.com/getsentry/sentry-docs/blob/master/src/docs/product/integrations/index.mdx#deployment
2. The Data & Visualization is not spilling into the sidebar https://github.com/getsentry/sentry-docs/blob/master/src/docs/product/integrations/index.mdx#data--visualization

![image](https://user-images.githubusercontent.com/89550162/158452230-4e723c6e-882d-4263-b0ba-5d1a73b8dc59.png)

The table spillover problem is happening not just in https://docs.sentry.io/product/accounts/membership/, but also in others, like https://docs.sentry.io/product/integrations/

P.S. The spillover seems to be appearing for tables where there are > 4 columns.

**Comment by imatwawana** [comment]
Thanks for the investigation and clarification, @sdzhong!

**Comment by roggenkemper** [comment]
This also seems to be happening on this page https://docs.sentry.io/product/sentry-basics/search/searchable-properties/
