### ISSUE TITLE
Add missing platforms for `upload-dif`

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-docs#4853]
### Core or SDK?

Platform/SDK

### Which part? Which one?

Multiple

### Description

Only 3 platforms (Android, Native and Wasm) have the content:

https://github.com/getsentry/sentry-docs/tree/master/src/includes/upload-dif

This means, that we show this, to all other platforms:
![image](https://user-images.githubusercontent.com/1633368/159096892-e7bc3973-7e8c-40c2-83e1-6723580cd575.png)

### Suggested Solution

Either add more platforms (Unity, Cocoa, JavaScript (sourcemaps?) or whatever else. 
If a platform doesn't apply, perhaps we hide this content from the menu altogether?

**Comment by imatwawana** [comment]
@bruno-garcia, it looks like the page this include is on https://docs.sentry.io/platforms/android/data-management/debug-files/upload/ only shows up for:
- native
- android
- cocoa
- apple
- unity

So it would be simplest to hide this page from the menu for cocoa, apple, and unity.
