### ISSUE TITLE
Is Main thread deadlock in iOS still experimental?

### ISSUE THREAD

**Issue by yuval-sentry** [getsentry/sentry-docs#4866]
### Core or SDK?

Platform/SDK

### Which part? Which one?

iOS

### Description

under [iOS docs](https://docs.sentry.io/platforms/apple/guides/ios/) it says: Main thread deadlock (experimental)
Is that still the case? it looks like we do have it in our SDK:
https://github.com/getsentry/sentry-cocoa/blob/c06c857ff90589996b75f63ce289038ffbb29c24/Sources/SentryCrash/Recording/Monitors/SentryCrashMonitor_Deadlock.m

### Suggested Solution

https://github.com/getsentry/sentry-cocoa/blob/c06c857ff90589996b75f63ce289038ffbb29c24/Sources/SentryCrash/Recording/Monitors/SentryCrashMonitor_Deadlock.m

**Comment by yuval-sentry** [comment]
Done.
Thanks!

**Comment by philipphofmann** [comment]
We are working on reporting ANRs https://github.com/getsentry/sentry-cocoa/issues/1052 right now. After finishing this we are going to delete this note (Main thread deadlock (experimental)) in the docs and we are also going to delete https://github.com/getsentry/sentry-cocoa/blob/c06c857ff90589996b75f63ce289038ffbb29c24/Sources/SentryCrash/Recording/Monitors/SentryCrashMonitor_Deadlock.m. Thanks for raising this @yuval-sentry.
