### ISSUE TITLE
Wrong left header behaviour in "Contributing to docs" section

### ISSUE THREAD

**Issue by stefanosiano** [getsentry/sentry-docs#4915]
### Core or SDK?

Core Sentry product

### Which part? Which one?

Contributing to docs

### Description

I was having a look at the “Contributing to docs” page https://docs.sentry.io/contributing/
I found an issue in the headers on the left, which occurs only when i’m visiting one of the “root” pages of that header. 

Basically if I’m in one of:
https://docs.sentry.io/contributing/environment/
https://docs.sentry.io/contributing/approach/
https://docs.sentry.io/contributing/platforms/
https://docs.sentry.io/contributing/linking/
https://docs.sentry.io/contributing/pages/
https://docs.sentry.io/contributing/onboarding-wizard/

If i reload the page the header is not highlighted anymore, and the link shown from the browser on mouse hover (i use chrome and opera) is different from what it should be:
should be https://docs.sentry.io/contributing/ but it’s https://docs.sentry.io/product/
should be https://docs.sentry.io/contributing/environment/ but it’s https://docs.sentry.io/product/sentry-basics/
should be https://docs.sentry.io/contributing/approach/ but it’s https://docs.sentry.io/product/issues/
should be https://docs.sentry.io/contributing/platforms/ but it’s https://docs.sentry.io/product/projects/
should be https://docs.sentry.io/contributing/linking/ but it’s https://docs.sentry.io/product/alerts/
should be https://docs.sentry.io/contributing/pages/ but it’s https://docs.sentry.io/product/performance/
should be https://docs.sentry.io/contributing/onboarding-wizard/ but it’s https://docs.sentry.io/product/releases/

When i click on the links the correct page is shown, but if i cmd+click to open the link in a new page (i’m used to do it) i am redirected to the wrong page.

when i try to disable javascript the left header is the general docs header, not the contributing one.

### Suggested Solution

I guess the contributing header is loaded through javascript after page load, and while it doesn't change the links, it catches the clicks to open the correct page.
This is just a guess, obviously.

**Comment by imatwawana** [comment]
See issue #4580

**Comment by stephanie-anderson** [comment]
This behaviour seems to be fixed due to the migration from Gatsby to Next.js
