### ISSUE TITLE
Typo in Welcome to Sentry page

### ISSUE THREAD

**Issue by rebeccabilbro** [getsentry/sentry-docs#4948]
### Core or SDK?

Core Sentry product

### Which part? Which one?

landing page

### Description

There is a minor typo in the landing page (Welcome to Sentry). Under the heading "Install Sentry" the word "languages" is misspelled.

![Screen Shot 2022-04-19 at 5 27 08 PM](https://user-images.githubusercontent.com/8760385/164105385-be50d8f7-b44b-4d87-af11-e2763adb2e3f.png)

### Suggested Solution

lanaguages => languages

**Comment by dashed** [comment]
@rebeccabilbro This should be already fixed in https://github.com/getsentry/sentry/pull/33748

**Comment by imatwawana** [comment]
thanks @dashed!
