### ISSUE TITLE
Missing information on what exactly is migrated over from opensource to SaaS in export section

### ISSUE THREAD

**Issue by adam000034** [getsentry/sentry-docs#4950]
### Core or SDK?

Core Sentry product

### Which part? Which one?

Migration

### Description

Right now according to the migration docs [[here:](https://docs.sentry.io/product/sentry-basics/migration/#3-export-your-data)] it seems information is covered at a high level.

### Suggested Solution

A high-level description of what data would be migrated over would be helpful in the Export Your Data section I think would be a good solution.

**Comment by imatwawana** [comment]
Hi @adam000034, we're looking at making this information more robust, but I just wanted to check if you'd seen this brief explanation further up on the same page: 

> To make this migration as seamless as possible, Sentry has a migration workflow that allows you to migrate most of your account's settings and configurations. This includes project settings, alert rules, enabled data scrubbers, team settings, saved search queries, integration platform metadata (Sentry 10), and so on.

Does this provide the level of detail you're looking for or are you looking for more?

**Comment by adam000034** [comment]
@imatwawana Actually I think we are good.  Now that I read it again and discussing with my team, I think we are good for now.  Thanks!

**Comment by adam000034** [comment]
Feel free to close this
