### ISSUE TITLE
Sentry OKHttpInterceptor not working

### ISSUE THREAD

**Issue by brandlee** [getsentry/sentry-docs#4983]
### Steps to Reproduce

1. I did it as the document said
2. network 404 captured
3. not report to the server, in sentry.io, I cannot see the log

### Expected Result

see the error log of the 404 network request

### Actual Result

nothing

**Comment by imatwawana** [comment]
Hi @brandlee - this looks more like a support issue than an issue with our documentation. Please check out our [support site](https://help.sentry.io/), Discord server, or [Forum](https://forum.sentry.io/c/sdks/5) to get some help.
