### ISSUE TITLE
Add info about unsetting user context on logout

### ISSUE THREAD

**Issue by charlax** [getsentry/sentry-docs#500]
Would you mind adding how to unset the user context in https://github.com/getsentry/sentry-docs/blob/master/src/collections/_documentation/learn/context.md ?

Thanks!

**Comment by untitaker** [comment]
Hi @charlax, this is documented at https://docs.sentry.io/learn/scopes/?platform=python. Basically you push a new scope onto the stack, add your values there, run your code in it and then pop it again to have the values removed.

In the last example, the custom tag `my-tag` will not exist outside of the `with`-block.

**Comment by untitaker** [comment]
could you check if #503 clarifies this bit for you?

**Comment by charlax** [comment]
Thanks for the quick response! I'm a bit unclear what you consider a scope in the JS browser SDK. For instance, I'd like to set the user on login and unset it on logout.

I'm looking for the equivalent of `Raven.setUserContext()`, basically.

**Comment by untitaker** [comment]
@charlax the exact equivalent to `setUserContext` is `configureScope` and `setUser`, here: https://docs.sentry.io/learn/context/?platform=javascript#capturing-the-user

Scope pushing and popping is more useful if you want to apply data to just one function call, in which case you would wrap it in `withScope`. Then you can set context data and be sure it will only apply to the code in `withScope`.

**Comment by untitaker** [comment]
That seems correct. I think passing null should work too

**Comment by charlax** [comment]
I'd recommend adding this to the document, since it's quite easy to forget to do this on logout. What do you think?

**Comment by untitaker** [comment]
@charlax yeah we can do that
