### ISSUE TITLE
There is no Redis 3.2 at Docker Hub

### ISSUE THREAD

**Issue by BerkhanBerkdemir** [getsentry/sentry-docs#504]
[Server/Installation](https://github.com/getsentry/sentry-docs/blob/master/src/collections/_documentation/server/installation/index.md#services) part says that use Redis 3.2; however, there is no Redis 3.2 anymore at hub.docker.com.

Should you need to update that information?

**Comment by untitaker** [comment]
3.2-alpine exists as a tag. What do you mean?

**Comment by BerkhanBerkdemir** [comment]
Sorry, @untitaker. I didn't think to look at `tags` page. I just saw on homepage :cry:

**Comment by untitaker** [comment]
np 😄
