### ISSUE TITLE
Capacitor instructions for Android

### ISSUE THREAD

**Issue by ludufre** [getsentry/sentry-docs#5084]
### Core or SDK?

Platform/SDK

### Which part? Which one?

Capacitor 3.0 Android

### Description

The documentation to implement Sentry on Capacitor is outdated.

With Capacitor 3.0 not need to modify the MainActivity.java (part Android Specifics in tutorial)

https://docs.sentry.io/platforms/javascript/guides/capacitor/

### Suggested Solution

Remove the `Android Specifics` part.

**Comment by marandaneto** [comment]
@lucas-zimerman

**Comment by lucas-zimerman** [comment]
> @lucas-zimerman

Oh I didn't notice there was also an issue on Sentry Docs.

Made this PR to document the new way of integrating Capacitor 3 on Android.
https://github.com/getsentry/sentry-docs/pull/5093
