### ISSUE TITLE
Aspnetcore Setting a Sampling Function docs incorret key value

### ISSUE THREAD

**Issue by Rassilion** [getsentry/sentry-docs#5124]
### Core or SDK?

Platform/SDK

### Which part? Which one?

Aspnetcore

### Description

In the Aspnetcore "Setting a Sampling Function" docs example script is not working, looks like key value "url" changed to "__HttpPath"

document page: https://docs.sentry.io/platforms/dotnet/guides/aspnetcore/configuration/sampling/#setting-a-sampling-function

I'm trying send a pull request but I could not found that page in this repo.

### Suggested Solution

Change 
```
context.CustomSamplingContext.GetValueOrDefault("url")
```

to 

```
context.CustomSamplingContext.GetValueOrDefault("__HttpPath")
```

**Comment by bruno-garcia** [comment]
Thanks for raising. The snippets are here: https://github.com/getsentry/sentry-docs/tree/master/src/includes
We'd appreciate a PR

**Comment by mattjohnsonpint** [comment]
@lucas-zimerman - want to improve this doc if you have some time?

**Comment by lucas-zimerman** [comment]
Will do :)

**Comment by mattjohnsonpint** [comment]
That's not quite the best way. There's an extension method that should be used instead.

**Comment by lucas-zimerman** [comment]
> Actually, it looks like the example doc referenced is showing _custom_ context information. The build in one is available with just `context.TryGetHttpPath()`.
> 
> The docs could still be a little clearer about this.

Thing is, TryGetHttpPath is only available on Asp.NET where the mentioned doc is shared across all .NET targets
Maybe mention `TryGetHttpPath` if using with ASP.NET Core, otherwise the longer method.

**Comment by mattjohnsonpint** [comment]
I see.  Yeah - no need to split the docs up.  Just put them both in the same example with a comment such as `// assuming ASP.NET Core` on one and `// or from your own custom data` on the other.

**Comment by lucas-zimerman** [comment]
@bruno-garcia  could you close this Issue?
