### ISSUE TITLE
Tag documentation is not specific to the platform

### ISSUE THREAD

**Issue by fabiendem** [getsentry/sentry-docs#5146]
### Core or SDK?

Platform/SDK

### Which part? Which one?

Platforms > React Native > Enriching Events > Customize Tags

### Description

In the React Native documentation https://docs.sentry.io/platforms/react-native/enriching-events/tags/

To enrich events with tags, the documentation recommends the import from `"@sentry/browser";`:
```
import * as Sentry from "@sentry/browser";
```
while we can and should rely on the react-native package. `setTag` and `setTags` are available there.

### Suggested Solution

Update the platform specific documentation around tags with the correct imports.
In the case of React Native:
```
import * as Sentry from "@sentry/react-native";
```

**Comment by marandaneto** [comment]
Dupe https://github.com/getsentry/sentry-docs/issues/4275
