### ISSUE TITLE
Add guide for fastify

### ISSUE THREAD

**Issue by zdila** [getsentry/sentry-docs#5150]
### Core or SDK?

Platform/SDK

### Which part? Which one?

i don't know

### Description

Please add guide for Fastify.

### Suggested Solution

Please add guide for Fastify.

**Comment by imatwawana** [comment]
Hi @zdila - We don't currently have plans to fully support Fastify, but here's a link to the [GitHub repo for a Fastify-Sentry plugin](https://github.com/zentered/fastify-sentry). The ReadMe should hopefully get you started.

**Comment by AbhiPrasad** [comment]
@zdila if you're interesting in official support for Fastify, please leave a reaction/comment on https://github.com/getsentry/sentry-javascript/issues/4784!

**Comment by imatwawana** [comment]
> @zdila if you're interested in official support for Fastify, please leave a reaction/comment on [getsentry/sentry-javascript#4784](https://github.com/getsentry/sentry-javascript/issues/4784)!

Thank you @AbhiPrasad! I wasn't sure where this request could be logged. @zdila, I'm going to close this issue, but please go ahead and comment on [the issue mentioned](https://github.com/getsentry/sentry-javascript/issues/4784).
