### ISSUE TITLE
Add attachments docs for Node SDK

### ISSUE THREAD

**Issue by AbhiPrasad** [getsentry/sentry-docs#5195]
### Core or SDK?

Platform/SDK

### Which part? Which one?

@sentry/node

### Description

Attachments support has been added for the Node SDK, but the docs for attachments only show up on the browser SDK: https://docs.sentry.io/platforms/javascript/enriching-events/attachments/.

### Suggested Solution

Make sure that the Node SDK docs have details about how to use attachments under the `Enriching Events` title

**Comment by WeeJeWel** [comment]
@AbhiPrasad I cannot seem to add attachments to Sentry in Node.js.

```js
const scope = new Sentry.Scope();

scope.setTag('foo.bar', 123); // works

// Add coredump.txt
scope.addAttachment({
  filename: 'coredump.txt',
  data: '...', // about 18kb string, doesn't work
  contentType: 'text/plain',
});

// Add esp32.log
if (typeof HOMEY_ESP32_LOG_PATH === 'string') {
  scope.addAttachment({
    filename: 'esp32.log',
    data: '...', // about 200kb string, doesn't work
    contentType: 'text/plain',
  });
}

// Capture message
Sentry.captureException(new Error('Crash'), scope);
```

Unfortunately, this shows up as `No attachments found` under the issue in the web ui. Can you help?
