### ISSUE TITLE
Point out stitchAsyncCode in docs and wizard

### ISSUE THREAD

**Issue by philipphofmann** [getsentry/sentry-docs#5215]
### Core or SDK?

Platform/SDK

### Which part? Which one?

Cocoa/Apple

### Description

We have an experimental feature [`stitchAsyncCode`](Point out the experimental feature [`stitchAsyncCode`](https://github.com/getsentry/sentry-cocoa/blob/17a7a28bf01bb7c7a095bbd0cded5e6bc1dd65aa/Sources/Sentry/Public/SentryOptions.h#L144-L152) that no one knows about.

### Suggested Solution

Point out the experimental feature [`stitchAsyncCode`](https://github.com/getsentry/sentry-cocoa/blob/17a7a28bf01bb7c7a095bbd0cded5e6bc1dd65aa/Sources/Sentry/Public/SentryOptions.h#L144-L152) in the docs and the wizard.

**Comment by bruno-garcia** [comment]
@philipphofmann the issues with it resulting in different stack traces depending on model/version was resolved?

**Comment by philipphofmann** [comment]
> @philipphofmann the issues with it resulting in different stack traces depending on model/version was resolved?

No, but the feature is experimental and we would like to get some feedback, which we never did. So I would like to point out the experimental feature.
