### ISSUE TITLE
Build-Type missing from Searchable Properties

### ISSUE THREAD

**Issue by zoesyc** [getsentry/sentry-docs#5228]
### Core or SDK?

Core Sentry product

### Which part? Which one?

Issues

### Description

Build-Type missing from Searchable Properties

### Suggested Solution

Add Build-Type to [Searchable Properties](https://docs.sentry.io/product/sentry-basics/search/searchable-properties/#properties-table)

**Comment by vivianyentran** [comment]
From testing in the product, Build-type doesn't seem to be a searchable property, so I'm going to close this.
