### ISSUE TITLE
Python ASGI documentation causes errors in FastAPI

### ISSUE THREAD

**Issue by minboost** [getsentry/sentry-docs#5272]
### Core or SDK?

Platform/SDK

### Which part? Which one?

https://docs.sentry.io/platforms/python/guides/asgi/

### Description

Integrating with FastAPI with the following line throws various errors, depending on what is implemented

```python
asgi_app = SentryAsgiMiddleware(asgi_app)
```

Some errors could include:
```bash
@app.middleware("http")
AttributeError: 'SentryAsgiMiddleware' object has no attribute 'middleware'
```

```bash
@app.on_event('shutdown')
AttributeError: 'SentryAsgiMiddleware' object has no attribute 'on_event'
```

Integrating the middleware as described in the [FastAPI docs](https://fastapi.tiangolo.com/advanced/middleware/) fixes the problem:
```python
asgi_app.add_middleware(SentryAsgiMiddleware)
```

### Suggested Solution

Update the documents with an example for FastAPI and/or a note that some ASGI middleware must be installed differently than shown in the example.

**Comment by vladanpaunovic** [comment]
Hey @minboost, until now Sentry didn't have a native support for FastAPI so users had to use our ASGI integration.

Well, worry no more! 💪 

This week, we will release a [beta version of FastAPI integration](https://github.com/getsentry/sentry-python/pull/1495) and I recommend you give it a try and see whether it resolves this issue for you or not.

If curious, you can always check our [FastAPI milestone](https://github.com/getsentry/sentry-python/milestone/8) for checking what will come up.

**Comment by kerenkhatiwada** [comment]
Updated labels based on the above. If it's wrong please let me know!

**Comment by antonpirker** [comment]
Documentation was updated.
