### ISSUE TITLE
Updating sample rate in docs 

### ISSUE THREAD

**Issue by pevensentry** [getsentry/sentry-docs#5284]
### Core or SDK?

Core Sentry product

### Which part? Which one?

Performance/Transactions

### Description

I have spoken to multiple customers who noted setting their sample rate to 100% based on what is in the docs and what shows when creating a project for the first time. Some customers noted they exhausted their monthly quota right away and forgot about performance monitoring because they couldn't use it for almost a month without buying additional transactions.

### Suggested Solution

Update transaction sample rate to 2% in documentation so new customers don't immediately exhaust it.

**Comment by bruno-garcia** [comment]
The problem is that if we add 2% in there, users are unlikely to see anything in Sentry when they are testing out the product.

Our goal was to add 100% so we're sure they'll see something come up when they try it for the first time. 
We put a big disclaimer that this value must be adjusted before going to production:

[For example](https://github.com/getsentry/sentry-docs/blob/master/src/wizard/android/index.md):
```
    <!-- Set tracesSampleRate to 1.0 to capture 100% of transactions for performance monitoring.
       We recommend adjusting this value in production. -->
    <meta-data android:name="io.sentry.traces.sample-rate" android:value="1.0" />
```

**Comment by pevensentry** [comment]
Makes sense. Do you think a lower number like 25% or even 50% would still demonstrate the product is working? I've had 3 customers mention they weren't able to continue using performance after testing it out because they ran through their quota right away. 

If you don't think 25% or 50% is enough, maybe we can set up an in-app notification on the projects tab letting them know they are projected to use up their transaction quota in X days.

**Comment by imatwawana** [comment]
> ...maybe we can set up an in-app notification on the projects tab letting them know they are projected to use up their transaction quota in X days.

I can't speak to whether a lower amount would do the job, but we do have an 80% of quota warning that comes up on every org scoped page in-app when you hit that level of your quota. In addition to the email (and Slack if you've set that up) notifications that get sent to org owners.

**Comment by pevensentry** [comment]
I think that helps, but if the 80% warning shows up a few days after they enable transactions, they don't have a lot of quota left to test it out. I think an alert (similar to the 80% one) that forecasts if a customer is going to run out of their quota within X days from when their quota restarts could be helpful. We could show them a message prompting them to either lower their sample rate or purchase additional quota for the current billing cycle. I'll chat with AJ and Steve to see if this is possible.
