### ISSUE TITLE
add noindex header tag to docs previews

### ISSUE THREAD

**Issue by imatwawana** [getsentry/sentry-docs#5302]
### Core or SDK?

Core Sentry product

### Which part? Which one?

All docs

### Description

Preview URLs are showing up in results when you search for our content in search engines. For example, when searching `filtering out options request, sentry java`, the following URLs are included in the results:

https://sentry-docs-o2paie5ivq-uc.a.run.app/guides/manage-event-stream/
https://sentry-docs-git-patch-1.sentry.dev/platforms/python/configuration/filtering/

### Suggested Solution

The x-robots-tag needs to be added in the header of our preview docs so that they aren't indexed by search engines, per these directions: 
https://vercel.com/support/articles/are-vercel-preview-deployment-indexed-by-search-engines

**Comment by a-hariti** [comment]
It seems that this is not an issue anymore as the preview deployments reply with `x-robots-tag: noindex`
