### ISSUE TITLE
"Custom Grouping Behavior" title links to title above - "Promises" in legacy JS client docs

### ISSUE THREAD

**Issue by miluoshi** [getsentry/sentry-docs#5321]
### Core or SDK?

Platform/SDK

### Which part? Which one?

https://docs.sentry.io/clients/javascript/usage/

### Description

See the 3 h2 titles. The ids don't match with titles so the title links are broken too
![image](https://user-images.githubusercontent.com/1130547/180420311-baeabbc0-e883-4e65-a66f-e88805050f81.png)
 

### Suggested Solution

Update id's of "Custom Grouping Behavior" and "Preventing Abuse" titles

**Comment by imatwawana** [comment]
This is a known linking issue with the way our docs are being built as the sidebar links are automatically generated from the headings. I'm linking this to [issue 4915](https://github.com/getsentry/sentry-docs/issues/4915) as I suspect they'll have the same solution. Thanks for reporting this.

**Comment by stephanie-anderson** [comment]
This works now, and was most likely fixed by the Next.js migration
