### ISSUE TITLE
Add experimental features section to wizard

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-docs#5324]
### Core or SDK?

Platform/SDK

### Which part? Which one?

- [x] Unity
- [ ] Android

### Suggested Solution

Add a section for experimental features, similar to: https://github.com/getsentry/sentry-docs/pull/5323/files

Add `attachScreenshot` to it.

**Comment by bitsandfoxes** [comment]
We now have IL2CPP as an experimental feature and a [mention to opt into screenshots](https://github.com/getsentry/sentry-docs/pull/5403) on the Unity wizard.

**Comment by bruno-garcia** [comment]
Is it in the Android sdk too?
