### ISSUE TITLE
Code Snippet for AutoUIPerformanceTracking

### ISSUE THREAD

**Issue by sdzhong** [getsentry/sentry-docs#5340]
### Core or SDK?

Platform/SDK

### Which part? Which one?

iOS

### Description

There is mention in https://docs.sentry.io/platforms/apple/guides/ios/performance/instrumentation/automatic-instrumentation/, 

> To enable this feature, enable AutoUIPerformanceTracking.

Can there be a code snippet to show this feature enabled?

### Suggested Solution

Add code snippet to show this feature enabled.

**Comment by bruno-garcia** [comment]
Thanks for raising, The name is wrong there, I opened #5341 to fix it

**Comment by bruno-garcia** [comment]
This value is `true` by default btw, so for as long as you pick a sample rate, you'll see transactions coming in.
Basically go through this: https://docs.sentry.io/platforms/apple/performance/
