### ISSUE TITLE
Update Automatic Release Management

### ISSUE THREAD

**Issue by t-h-man** [getsentry/sentry-docs#5348]
### Core or SDK?

Core Sentry product

### Which part? Which one?

Repository integration - [Automatic release management ](https://docs.sentry.io/product/releases/setup/release-automation/)

### Description

The way the [documentation](https://docs.sentry.io/product/releases/setup/release-automation/) has been made, it insinuates that simply adding the appropriate integration is enough to start seeing commit data (suspect commits). That is not the case however, since the customer then actually needs to either proceed with additional commands through the [Sentry-CLI/API](https://docs.sentry.io/product/releases/suspect-commits#enable-suspect-commits) OR set up one of the release automation options which are mentioned further in the same doc.

### Suggested Solution

Add a Step 4 with similar wording as the second step in [this article](https://docs.sentry.io/product/releases/setup/#3-enable-suspect-commits).

**Comment by imatwawana** [comment]
@georgekallilas - when you have a minute, can you [make your github profile public](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-your-membership-in-organizations/publicizing-or-hiding-organization-membership) so the issues you create as a team member don't have triage SLOs applied.

**Comment by georgekallilas** [comment]
> @georgekallilas - when you have a minute, can you [make your github profile public](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-your-membership-in-organizations/publicizing-or-hiding-organization-membership) so the issues you create as a team member don't have triage SLOs applied.

Done! Thanks for pointing that out
