### ISSUE TITLE
Adjust sections in Issue Owners page for clarity on Auto Assignment and Evaluation Flow

### ISSUE THREAD

**Issue by sdzhong** [getsentry/sentry-docs#5386]
### Core or SDK?

Core Sentry product

### Which part? Which one?

https://docs.sentry.io/product/issues/issue-owners/

### Description

The [Evaluation Flow section](https://docs.sentry.io/product/issues/issue-owners/#evaluation-flow) is relevant to the [Automatically assign issues](https://docs.sentry.io/product/issues/issue-owners/#auto-assign) toggle/feature. 

### Suggested Solution

The Issue Ownership page would be more sensible if the `Evaluation Flow` section is set as a subsection of the `Auto-Assign` section.

**Comment by imatwawana** [comment]
Maybe I'm wrong, but it seems like the evaluation flow affects suggested assignees, auto-assignment, and issue alerts, not just auto-assignment. Can someone on @getsentry/ecosystem confirm? If so, then I'd probably restructure the page in this order:
How it Works
- Ownership Rules
- Code Owners
Evaluation Flow
- Example
Where It Works
- Suggested Assignees
- Auto-Assign
- Issue Alerts
Troubleshooting

**Comment by imatwawana** [comment]
Agreed on structure above with @leeandher but we'll remove the Issue Alerts section entirely since it doesn't really belong here and the content is already covered in the issue alert configuration docs.
