### ISSUE TITLE
Search doesn't index keywords from code samples

### ISSUE THREAD

**Issue by mattjohnsonpint** [getsentry/sentry-docs#5418]
### Core or SDK?

Platform/SDK

### Which part? Which one?

all

### Description

Often I'll want to search the docs for details about a specific configuration option set in the SDK.  Unfortunately, our search engine appears to be excluding code from its indexing, so we miss a lot.

As an example, here is a detailed doc page for a feature in the iOS SDK:

https://docs.sentry.io/platforms/apple/guides/ios/configuration/out-of-memory/

It is enabled/disabled by setting the `enableOutOfMemoryTracking` option.  But if you search for `"enableOutOfMemoryTracking"`, you get only one result and it belongs to the Flutter SDK, not the iOS SDK.  The reason that one shows up at all is because its property is mentioned in text, not in a code block.

Another example, search for `"enableSwizzling"`.  There are no results, despite there being a whole doc on this subject that includes that option in the code.

https://docs.sentry.io/platforms/apple/guides/ios/configuration/swizzling/

### Suggested Solution

We should index keywords in code samples.  This could add some noise, but better to have too many hits than to miss something important.

Until this is fixed, it seems like we should try to always mention the property name in text, not just in the sample code - however, updating all the docs for this would be quite the chore.

**Comment by a-hariti** [comment]
This is not the case anymore, exact keywords from snippets show up in search results
