### ISSUE TITLE
Formatting problem for Issue Stats note

### ISSUE THREAD

**Issue by sdzhong** [getsentry/sentry-docs#5453]
### Core or SDK?

Core Sentry product

### Which part? Which one?

https://docs.sentry.io/product/stats/#issue-stats

### Description

The note for Issue Stats
> This feature is available only if your organization is on a Business plan.
Is not rendering properly.

<img width="1006" alt="image" src="https://user-images.githubusercontent.com/89550162/186013028-b800030b-c148-446f-a603-e20a47ad5062.png">

### Suggested Solution

I'm expecting the note to appear the same as the note in Health Stats https://docs.sentry.io/product/stats/#health-stats
<img width="965" alt="image" src="https://user-images.githubusercontent.com/89550162/186012956-827615b5-788c-466e-84ee-900b39773298.png">

**Comment by imatwawana** [comment]
I'm fairly certain this is related to our overall linking issues in docs right now. Related to issues #4580, #4915, and #5321. I'm going to open a parent issue so link all of these to.

**Comment by imatwawana** [comment]
Rather than creating a new parent issue, I've just linked all of these issues to issue 4580 and I'll keep tracking them there.

**Comment by imatwawana** [comment]
Related to #5867

**Comment by evanpurkhiser** [comment]
This has something to do with the `gastby-remark-terms` plugin, maybe @untitaker knows more?

You can tell if you look at the generated DOM
![image](https://github.com/getsentry/sentry-docs/assets/1421724/a5874e33-ddcb-4d7c-87fb-4d5f47259412)

It's put the whole note inside a `term-wrapper`. The only place that is defined is here https://github.com/getsentry/sentry-docs/blob/48dfe316e3fcfc360328b379f5bd579969665540/src/gatsby/plugins/gatsby-remark-terms/index.js#L121

That said it appears to have a slightly different structure, so it's not totally clear what's going on here

**Comment by untitaker** [comment]
It works fine if I disable javascript in my browser, it's another hydration thing
