### ISSUE TITLE
Customize the text of placeholder on user feedback

### ISSUE THREAD

**Issue by jsabino** [getsentry/sentry-docs#546]
Hi,

I would like to customize placeholder text in user feedback modal. However in the showReportDialog method documentation there is no parameter to change this text.

**Comment by nancorrea** [comment]
I did it like that:


    $(function(){
        var interval = setInterval(function(){
             if($('body .sentry-error-embed').length) {
                 $('#id_name').attr('placeholder', 'Seu nome');
                 $('#id_email').attr('placeholder', 'Seu e-mail');
                 $('#id_comments').attr('placeholder', 'Eu estava criando...');
                 clearInterval(interval);
             }
        }, 100)
     });

**Comment by jsabino** [comment]
Hi Renan, thanks for the response.

I would like that the showReportDialog method have an argument to change this label, like all others.

Today i'm calling the showReportDialog like this:
```
Sentry.showReportDialog({
	title: "Ocorreu um erro",
	subtitle: "Nosso time foi notificado.",
	subtitle2: "Se você quiser ajudar, conte-nos o que aconteceu abaixo.",
	labelName: "Nome",
	labelComments: "O que aconteceu?",
	labelClose: "Fechar",
	labelSubmit: "Enviar",
	errorGeneric: "Um erro desconhecido ocorreu durante o envio do seu relatório. Por favor, tente novamente.",
	errorFormEntry: "Alguns campos estão inválidos. Por favor, corrija e tente novamente.",
	successMessage: "Seu feedback foi enviado. Obrigado!"
});
```

So, currenty, only placeholders text can't be changed on this method call.

**Comment by duygualyzc** [comment]
Hi @jsabino , 
I'm wondering if giving this parameters works for you?

**Comment by duygualyzc** [comment]
Hi @jsabino, I'm wondering if giving this parameters work for you?

**Comment by janjaap** [comment]
Any update on this issue?

**Comment by hedgie001** [comment]
I did it like that:
`Sentry.showReportDialog({
        user: {
            email: user.email,
            name: user.name
        },
        title: i18next.t("error.feedback.title"),
        subtitle: i18next.t("error.feedback.subtitle"),
        lang: i18next.language,
        onLoad: () => {
            const input = document.getElementById("id_comments");
            input && input.setAttribute("placeholder", commentPlaceholder);
        }
    });`
