### ISSUE TITLE
Add legacy banner to all raven docs

### ISSUE THREAD

**Issue by sl0thentr0py** [getsentry/sentry-docs#5513]
### Core or SDK?

Platform/SDK

### Which part? Which one?

Legacy Clients

### Description

This banner is only visible on the top-level Raven docs.

<img width="831" alt="image" src="https://user-images.githubusercontent.com/6536764/189929561-e277b4ec-5326-476d-a657-2c2985489447.png">

https://docs.sentry.io/clients/

### Suggested Solution

We should add the banner to _all_ Legacy Client sub-pages.

**Comment by lobsterkatie** [comment]
I wonder if we could also change the wording to include:

- when it was deprecated (summer 2018, i.e. 4 years ago and counting)
- the fact that large swaths of our current project can't be used if you don't upgrade
- the fact that raven SDKs are no longer supported

"We recommend using the updated SDK for new projects" just feels not nearly opinionated enough. Some slightly nicer version of, "No, legit, dude. Upgrade now - all of your projects. Just do it. Right now. Don't read these docs. Go upgrade." feels like it's closer to what we'd actually like people to do.

**Comment by AbhiPrasad** [comment]
Perhaps we also increase the severity by saying that the Raven SDKs will not get security fixes anymore since they are deprecated and folks can easily move onto sentry-sdk versions.

**Comment by stephanie-anderson** [comment]
This was resolved by https://github.com/getsentry/sentry-docs/pull/7007

![Screenshot 2023-06-14 at 18 00 49](https://github.com/getsentry/sentry-docs/assets/7096858/6d804a60-a348-428a-bf27-eed9e99ab5b7)
