### ISSUE TITLE
Logging is not listed as a default integration for Python SDK

### ISSUE THREAD

**Issue by runfalk** [getsentry/sentry-docs#552]
https://docs.sentry.io/platforms/python/default-integrations/ doesn't show the logging integration.

https://github.com/getsentry/sentry-python/blob/e4e246b22d701e5d850a83c82bf4f1fa40f82314/sentry_sdk/integrations/__init__.py#L34 clearly shows it is being used.

**Comment by untitaker** [comment]
thx, will be fixed
