### ISSUE TITLE
Sidekiq/delayed job specific documentation nowhere to be found

### ISSUE THREAD

**Issue by ngouy** [getsentry/sentry-docs#5528]
### Core or SDK?

Platform/SDK

### Which part? Which one?

Ruby + sidekiq

### Description

When digging in the code, I realized there is exactly the option that we needed for sentry-sidekiq (also available for delayed job) that is `report_after_job_retries`

I can see that there is a file in this repo talking about it here https://github.com/getsentry/sentry-docs/blob/master/src/platforms/ruby/common/configuration/integration_options.mdx

But it's literally impossible to find that on the rendered doc on the website
nor here https://docs.sentry.io/platforms/ruby/guides/delayed_job/
nor here https://docs.sentry.io/platforms/ruby/guides/sidekiq/

It seems like none of the "integration options" present on  https://github.com/getsentry/sentry-docs/blob/master/src/platforms/ruby/common/configuration/integration_options.mdx  end up being rendered anywhere on the official docs

### Suggested Solution

I have no idea why is that

But should be great to have specific doc directly on the official doc, without having to dig or this repo, or the code itself

**Comment by imatwawana** [comment]
Hi @ngouy - I think this is what you're looking for: 
https://docs.sentry.io/platforms/ruby/configuration/integration_options/#sentry-sidekiq

**Comment by ngouy** [comment]
Ok nice

TBF I was looking all over the place but not at the right one obviously

Was expecting it somewhere here
https://docs.sentry.io/platforms/ruby/guides/sidekiq/

**Comment by imatwawana** [comment]
> Ok nice, thanks for the guidance
> 
> TBF I was looking all over the place but not at the right one obviously
> 
> Was expecting it somewhere here https://docs.sentry.io/platforms/ruby/guides/sidekiq/

Understood and thanks for circling back. Our intent is to keep getting started page for every SDK relatively light weight so that people are be able to get the SDK installed and verify it's working quickly. Then, they can get into all the other configuration options as they want/need. Hope that's helpful!

**Comment by ngouy** [comment]
make sense 👍 
If I may, maybe you could have a one-liner explanation + link back to the specific configuration part on the getting started page
(I'm bad with copy but something like)
> [Configuration options]([docs.sentry.io/platforms/ruby/configuration/integration_options/#sentry-sidekiq](https://docs.sentry.io/platforms/ruby/configuration/integration_options/#sentry-sidekiq)) are available for this integration.
