### ISSUE TITLE
NIT: Is legal message correct?

### ISSUE THREAD

**Issue by lucas-zimerman** [getsentry/sentry-docs#5532]
### Core or SDK?

Core Sentry product

### Which part? Which one?

docs

### Description

![image](https://user-images.githubusercontent.com/8229322/190982870-02cc5259-bf4e-4f0e-a083-30f538bc9e97.png)
I am getting those warnings on the `gonna` and `So`

### Suggested Solution

replace gonna by going to  and So by `So, `

If needed I can open the PR :D

**Comment by imatwawana** [comment]
@chadwhitacre - i leave this up to you!

**Comment by chadwhitacre** [comment]
So what we're gonna find is that the informal tone is intentional.

> NIT: Is legal message correct?

Binary answer: yes. :)
