### ISSUE TITLE
Quota notification customisation

### ISSUE THREAD

**Issue by rodolfoBee** [getsentry/sentry-docs#5578]
### Core or SDK?

Core Sentry product

### Which part? Which one?

Quota notifications

### Description

The follow page mentions that users `cannot change or disable these[Quota] notifications.`
https://docs.sentry.io/product/alerts/notifications/#quota-notifications

However, there is a session to change some of the options in User Settings -> Notifications -> Quotas: 
![Screenshot 2022-09-28 at 08 40 07](https://user-images.githubusercontent.com/64906376/192953534-07c179ba-6653-4e13-8e1c-1867a0f98e9c.png)

### Suggested Solution

Inform the user that some customisation is possible. 

Change the text to something like: You can change the delivery method or disable these notifications by going to User Setting -> Notifications -> Quotas.

**Comment by imatwawana** [comment]
@rbisol - Which roles and plans is this feature limited to?

**Comment by rbisol** [comment]
Quota notifications are sent only to owners, and they are sent to users on all plans. I tested with a user and I could see the settings with all roles. 

The billing team might be able to confirm the intended behaviour.
