### ISSUE TITLE
Incorrect linking and current page not highlighted in left nav

### ISSUE THREAD

**Issue by imatwawana** [getsentry/sentry-docs#5607]
### Core or SDK?

Core Sentry product

### Which part? Which one?

API Reference > Requests

### Description

There are two problems described in the video that occur when you navigate directly by URL to any of the first five pages docs.sentry.io/api/ (not the ones under Endpoints). These are: [Authentication](https://docs.sentry.io/api/auth/), [Paginating Results](https://docs.sentry.io/api/pagination/), [Permissions & Scopes](https://docs.sentry.io/api/permissions/), [Rate Limits](https://docs.sentry.io/api/ratelimits/), [Requests](https://docs.sentry.io/api/requests/). 

1. Once on one of the pages above, hover over any of the links in the left side nav under Endpoints, the URLs are all pointing to the pages under docs.sentry.io/product/data-management-settings/. If you navigate based on going to Docs and then clicking on links in the navigation however, then the URLs on hover are correct.

2. When you navigate to one of these five pages this way, the current page isn't highlighted in the left side nav.

See video for what was originally reported:
https://www.loom.com/share/cd6f494da5c04f1e89cec814fcf19e5b

### Suggested Solution

The first is a known linking issue where the system seems to be caching other page information similar to #4580.
We haven't yet found a resolution to this, but when that's resolved, this issue will likely be resolved. The second issue is likely related, though this is the first time we're seeing it.

**Comment by imatwawana** [comment]
Related to:
#4580 
#4915 
#5453 
#5453

**Comment by Neeleshrj** [comment]
Hi, is this up for Hacktoberfest contributions?

**Comment by imatwawana** [comment]
Hi @Neeleshrj - I wouldn't recommend this issue as one for Hacktoberfest. We've had someone who has a lot of experience with this repo work on it without success already, and we think it's going to need dedicated resources for a while. 

Below are some issues that are also about improving/fixing our docs infrastructure (I haven't linked these issues because I don't want them to appear as if they're related to this one) that you might want to work on instead:

- 3497 - Dark mode missing from docs.sentry.io 
- 4358 - Layer ARN selector is broken
- 4593 - Top page nav disappears on mobile
- 4824 - Table doesn't resize properly

You can find more like these if you search for issues with the `bug` or `enhancement` labels. Of course, you're still welcome to work on this issue, but I wanted to give you some other options.

**Comment by Neeleshrj** [comment]
Got it, Thanks!

**Comment by stephanie-anderson** [comment]
Was most likely solved by the migration to Next.js
