### ISSUE TITLE
Document difference between `pageload` and `navigation` transactions

### ISSUE THREAD

**Issue by AbhiPrasad** [getsentry/sentry-docs#5654]
### Core or SDK?

Platform/SDK

### Which part? Which one?

JavaScript Browser Performance Monitoring

### Description

Document difference between pageload and navigation transactions.

### Suggested Solution

Add docs to https://docs.sentry.io/platforms/javascript/performance/instrumentation/automatic-instrumentation/ explaining the difference between pageload and navigation transactions.

**Comment by mydea** [comment]
**Why was this issue closed?**

This issue hasn't been touched recently and no longer seems relevant. 
Hence, we're closing it to maintain a clean and transparent backlog.

Please feel free to leave a comment if you think this issue should be reopened.
