### ISSUE TITLE
Square brackets break fingerprinting rules

### ISSUE THREAD

**Issue by spaspala** [getsentry/sentry-docs#5723]
### Core or SDK?

Core Sentry product

### Which part? Which one?

Issue Grouping > Fingerprinting Rules

### Description

When setting fingerprinting rules, if I want to include a message that has `[` and `]` in it, the rule will not work.

Example: `error.type:UnhandledRejection message:"Non-Error promise rejection captured with value: FirebaseError: [code=already-exists]: Document already exists: projects/{org slug}/databases/(default)/documents/snippets/*" -> {rule name}`

Found out that the workaround to this is replacing the square brackets with asterisks (`*`). So the example above would look like: `error.type:UnhandledRejection message:"Non-Error promise rejection captured with value: FirebaseError: *code=already-exists*: Document already exists: projects/{org slug}/databases/(default)/documents/snippets/*" -> {rule name}`

### Suggested Solution

Add in the documentation a section that explains that when setting issue grouping rules, square brackets will not work and asterisks should be used in their place.

**Comment by imatwawana** [comment]
Hi @spaspala! Thanks for bringing this up. I think GitHub might be interfering with what you're trying to input, so I'm not super clear if you're trying to indicate quotation marks or asterisks. Can you try formatting your before and after examples as code using the angled brackets in the toolbar of the comment field?
![image](https://user-images.githubusercontent.com/76437239/200618072-a74a23b2-1e17-4305-a432-66bbc8276d41.png)

**Comment by spaspala** [comment]
Thank you for pointing this out @imatwawana, I have updated it!

**Comment by imatwawana** [comment]
Much clearer, thank you!
