### ISSUE TITLE
Recommend 1.0 tracesSampleRate

### ISSUE THREAD

**Issue by philipphofmann** [getsentry/sentry-docs#5729]
### Core or SDK?

Platform/SDK

### Which part? Which one?

All SDKs

### Description

All SDKs have something like
```
  // Set tracesSampleRate to 1.0 to capture 100% of transactions for performance monitoring.
  // We recommend adjusting this value in production.
  tracesSampleRate: 1.0,
```

in the getting started section and the wizard. See https://github.com/getsentry/sentry-docs/search?q=Set+tracesSampleRate+to+1.0

### Suggested Solution

When Dynamic Sampling is GA, we should change this to recommend that they should set this 1.0 and not adjust it in production, but instead, DS will take care of it.

@imatwawana, can you help with the proper wording please?

**Comment by imatwawana** [comment]
What about:

```
// Set tracesSampleRate to 1.0 to capture 100% of transactions for performance monitoring.
// We recommend sending 100% of transactions and allowing Sentry to dynamically sample your data server-side. 
```

**Comment by stephanie-anderson** [comment]
Until backpressure management is implemented in all (backend) SDKs, we should not suggest to setting the tracesSampleRate to 100%. Will close this issue for now, we will followup on an SDK basis
