### ISSUE TITLE
Point out tracesSampleRate in Getting Started

### ISSUE THREAD

**Issue by philipphofmann** [getsentry/sentry-docs#5730]
### Core or SDK?

Platform/SDK

### Which part? Which one?

Mobile SDKs

### Description

We see a significantly lower sent first transaction by SDK rate on the mobile SDKs than on other platforms in [Amplitude](https://analytics.amplitude.com/sentry/chart/4kdf4rd/edit/xpoyjmo). One reason could be that the getting started section of the mobile SDKs doesn't point out the tracesSampleRate. Adding it doesn't hurt.

### Suggested Solution

We should point out the `tracesSampleRate`, as we do in the wizard, in the getting started section

Cocoa Wizard, for example: 
https://github.com/getsentry/sentry-docs/blob/3fad325abb2cc5515868d9b7a859e8fa20e11a99/src/wizard/apple/ios.md?plain=1#L33-L39

[JavaScript](https://docs.sentry.io/platforms/javascript/#configure), already does this.

- [x] #5731
- [x] #5732
- [x] #5733
- [x] #5734
- [x] #5735
- [ ] #5736

**Comment by stephanie-anderson** [comment]
@philipphofmann @kahest the wizard is no longer part of this repository - is this still needed? If so, could you please transfer the issue to `sentry` or close it? Thanks! 🙏

**Comment by philipphofmann** [comment]
It's still required for the manual setup, but we already do this for
- [x] Apple: https://docs.sentry.io/platforms/android/manual-setup/
- [x] Android: https://docs.sentry.io/platforms/android/manual-setup/
- [x] .NET: https://docs.sentry.io/platforms/dotnet/#configure
- [x] Flutter: https://docs.sentry.io/platforms/flutter/
- [x] RN: https://github.com/getsentry/sentry-docs/issues/5735

But not for Unity.
