### ISSUE TITLE
.NET: Point out tracesSampleRate in Getting Started

### ISSUE THREAD

**Issue by philipphofmann** [getsentry/sentry-docs#5733]
See https://github.com/getsentry/sentry-docs/issues/5730 for more details.

**Comment by jamescrosswell** [comment]
Will be completed via [#7772 Aspcore guidance 2275](https://github.com/getsentry/sentry-docs/pull/7772) once [#2602 Configure Sentry tracing middleware automatically](https://github.com/getsentry/sentry-dotnet/pull/2602) has been released (v3.40.0).

**Comment by philipphofmann** [comment]
@jamescrosswell, I guess we can close this issue as https://github.com/getsentry/sentry-docs/pull/7772 and https://github.com/getsentry/sentry-dotnet/pull/2602 are completed?

**Comment by jamescrosswell** [comment]
Yep, thanks @philipphofmann !

**Comment by philipphofmann** [comment]
Closing cause completed with https://github.com/getsentry/sentry-dotnet/pull/2602.
