### ISSUE TITLE
mirror beta tag from app UI in docs

### ISSUE THREAD

**Issue by imatwawana** [getsentry/sentry-docs#5749]
### Core or SDK?

Core Sentry product

### Which part? Which one?

All docs

### Description

Right now we talk about Early Adopter features in the docs, but in the app these are labeled as beta features:
![image](https://user-images.githubusercontent.com/76437239/200864747-b6bb3c7f-e81c-4c09-a966-49bdd50b74cd.png)

It would be good to have consistency between the docs and the UI in this way so it's clearer to users that these have the same meaning. Long term, it would be ideal to have parity in the terms being used between Settings, the UI label, and the docs.

### Suggested Solution

Use the same beta label in the docs on features that are in Early Adopter along with the EA note, both in the left sidebar TOC and on the page, like so:
![image](https://user-images.githubusercontent.com/76437239/200868046-24288c2e-af9f-4108-8f22-ca2c2fe79600.png)

**Comment by a-hariti** [comment]
do you think this is still relevant @lizokm ?

**Comment by lizokm** [comment]
I do actually think it would be nice to have "alpha", "beta", and "new" tags that mirror what we have in the product, in docs. Let me get the design files.

**Comment by lizokm** [comment]
@a-hariti Here's a link to the Figma file that has these tag designs. https://www.figma.com/file/j1Oxdgbl2PxBBI1LXnpAhj/File-For-Liza?type=design&node-id=0%3A1&mode=design&t=2tL0HGRgmlnV7xZj-1
