### ISSUE TITLE
add feedback buttons to docs

### ISSUE THREAD

**Issue by imatwawana** [getsentry/sentry-docs#5750]
### Core or SDK?

Core Sentry product

### Which part? Which one?

All areas

### Description

There's not currently a fast/easy way to provide feedback on docs apart from submitting a PR or creating an issue. 

### Suggested Solution

Add a thumbs up/thumbs down option at the bottom of a page to allow users to quickly indicate if they found a piece of documentation helpful or not.

**Comment by a-hariti** [comment]
This is redundant in light of #9483
