### ISSUE TITLE
add automatic copy function to heading links

### ISSUE THREAD

**Issue by imatwawana** [getsentry/sentry-docs#5751]
### Core or SDK?

Core Sentry product

### Which part? Which one?

All areas

### Description

When you click a heading link in the docs, it doesn't copy the heading URL to the clipboard: 
![image](https://user-images.githubusercontent.com/76437239/200869456-6760d70b-dc94-489b-b389-eb14996ed51b.png)

 When people want to share page-level links, it requires an extra step.

### Suggested Solution

Update the heading link behaviour so that clicking the link also copies the link URL.

**Comment by a-hariti** [comment]
It doesn't make sense from UX perspective to have a click override clipboard content.
