### ISSUE TITLE
Does distributed tracing cost extra?

### ISSUE THREAD

**Issue by devinrhode2** [getsentry/sentry-docs#5766]
### Core or SDK?

Core Sentry product

### Which part? Which one?

distributed tracing

### Description

I can't find anything regarding the cost of distributed tracing. Does it cost extra?

### Suggested Solution

mention if this feature is free for all, or what the costs might be.

**Comment by imatwawana** [comment]
Hi @devinrhode2 - Distributed tracing is available on all of our plans, free and paid. We only add notes about plan-gated features vs features that are available on all plans in our docs, but you can see a breakdown of plans and features on our [pricing page](https://sentry.io/pricing/) (you need to scroll down a bit to get to the plan comparison section).
