### ISSUE TITLE
z-index menu issue

### ISSUE THREAD

**Issue by jakubHynek** [getsentry/sentry-docs#5781]
### Core or SDK?

Platform/SDK

### Which part? Which one?

Website navbar

### Description

![22F294BE-A02E-4187-94D5-853706DA320D](https://user-images.githubusercontent.com/73801338/201876577-c3aeae88-a930-4cad-a0c4-7e77e3868017.jpeg)
happening on iPhone SE (new gen)

### Suggested Solution

🪄🎩

**Comment by a-hariti** [comment]
I think this issue is not applicable to the Next.js docs anymore
