### ISSUE TITLE
Add clarity around full stack exception linking requiring tracing to be enabled

### ISSUE THREAD

**Issue by shanamatthews** [getsentry/sentry-docs#5797]
### Core or SDK?

Platform/SDK

### Which part? Which one?

Most relevant on the Javascript sdk

### Description

It's not obvious that linking backend exceptions to frontend exceptions only works automatically if you've set up tracing. 

https://docs.sentry.io/platforms/javascript/performance/connect-services/ 

### Suggested Solution

Not sure of the best place to put this info. https://docs.sentry.io/platforms/javascript/performance/connect-services/ makes sense, but that doc is already under performance, which isn't an intuitive place to look for this info for users who aren't using performance.

Maybe https://docs.sentry.io/platforms/javascript/troubleshooting/ for when users run into the perceived bug of duplicate frontend issues?

**Comment by imatwawana** [comment]
nudge @bruno-garcia & @lobsterkatie

**Comment by bruno-garcia** [comment]
The docs starts with `When tracing is enabled` and it's under performance as @shanamatthews mentioned. It seems to me it's clear when looking at Performance that you can get connected services. Perhaps better clarification of exception linking could happen there.

With regards to explaining how to link errors across services outside the performance docs, I'm not sure where in the current structure it would best land. The suggestion of adding an note to _troubleshooting_ makes total sense. But there's a chance to add a proper section somewhere after error tracking onboarding referring to "linking errors across your stack" and pointing users to performance.

**Comment by imatwawana** [comment]
I'm hesitant to add even more to the getting started page for JS. What if we updated the page description for Performance to something like "Learn how to enable performance and connect your frontend and backend projects."?
