### ISSUE TITLE
Update Apple dSYM upload as bitcode is deprecated

### ISSUE THREAD

**Issue by philipphofmann** [getsentry/sentry-docs#5823]
### Core or SDK?

Platform/SDK

### Which part? Which one?

Cocoa

### Description

https://developer.apple.com/documentation/Xcode-Release-Notes/xcode-14-release-notes is not up to date as bitcode was deprecated with Xcode 14.

### Suggested Solution

We could move the section on Bitcode to the bottom of the page with a note that bitcode is dprecated.

**Comment by bruno-garcia** [comment]
Makes sense, and relevant to Unity (cc @bitsandfoxes )
