### ISSUE TITLE
Contributing.md contains broken team links.

### ISSUE THREAD

**Issue by tashachin** [getsentry/sentry-docs#583]
Hi Sentry docs team!

Just wanted to let you know that all the URLs pointing to the GitHub Teams produce 404 errors. Are those teams deprecated?

**Comment by untitaker** [comment]
Hi, those team names are meant for mentioning in issues like here. I can access some of those teams so I guess it's a permission thing that decides whether the link 404s. But mentioning should still work regardless

**Comment by tashachin** [comment]
Oh, good to know!

Maybe it'd make sense to add a "NOTE: ____" that clarifies that?

**Comment by untitaker** [comment]
Reading up on GitHub teams I am not quite sure if that entire section has any relevance to outside collaborators since they can't see the team. So I would probably add a note that this is only relevant for Sentry staff? I'll check with a colleague on monday

**Comment by aklajnert** [comment]
Hi @untitaker, it seems like mentioning doesn't work for people outside sentry. Mentioning a team in the pull request just puts the mention in plain text, without turning it into a hyperlink so I guess nobody gets any notification.

**Comment by untitaker** [comment]
@aklajnert thanks, I think it would make sense to clarify this in the docs (but keep the info about teams)

**Comment by lynnagara** [comment]
I think 3 of the team links are actually broken / incorrect - @getsentry/api, @getsentry/ui and, @getsentry/team. I seem to be able to access the rest.

**Comment by BYK** [comment]
I'll go ahead and remove these.

**Comment by BYK** [comment]
Seems like this got fixed some time around #1629.
