### ISSUE TITLE
Way to download entire docs offline

### ISSUE THREAD

**Issue by Sternbach-Software** [getsentry/sentry-docs#5868]
### Problem Statement

I want to read through the documentation like a book (to become a Sentry guru) and see how many pages there are, so that I can pace myself accordingly, but there is no indication of how big the documentation page graph is, nor a clear start and end destination, nor a way to download them all at once offline for use in my favorite ebook reader.

#### Solutions that don't require technical writers
 - Add a button to download every page of documentation into one HTML file
 - add a button to download every page of documentation into one PDF file
#### Solutions that require technical writers
 - organize the documentation into a table of contents and create an EPUB or PDF, with cross-referencing internal hyperlinks

**Comment by lobsterkatie** [comment]
@Sternbach-Software FYI, it would be a _very_ long PDF, as each of the very many platforms/frameworks/languages gets its own copy of the all of the SDK docs pages, so that each can be customized.

**Comment by Sternbach-Software** [comment]
Why wouldn't there be multiple pdfs?

**Comment by Sternbach-Software** [comment]
How do I do this?

**Comment by AbhiPrasad** [comment]
@Sternbach-Software you can clone the GH repo: https://github.com/getsentry/sentry-docs

and then you'll have access to all the markdown files offline - you can feed those into something like [pandoc](https://pandoc.org/epub.html) and generate epubs accordingly.
