### ISSUE TITLE
JS SDK - Http context is badly documented, making it confusing to understand

### ISSUE THREAD

**Issue by larsqa** [getsentry/sentry-docs#5884]
### Core or SDK?

Platform/SDK

### Which part? Which one?

JavaScript related SDK

### Description

1. The *Http context* is written in many formats across the documentation:
    - [Http context](https://docs.sentry.io/platforms/javascript/guides/capacitor/data-management/sensitive-data/#scrubbing-data)
    - [HttpContext](https://docs.sentry.io/platforms/javascript/guides/nextjs/configuration/integrations/default/#httpcontext)
    - [Http](https://docs.sentry.io/platforms/node/configuration/integrations/default-integrations/#http)
2. First, after doing some in-depth analysis in the source code, I found that there are two types of the Http context:
     - Server side [`Http`](https://github.com/getsentry/sentry-javascript/blob/master/packages/node/src/integrations/index.ts#L2) context, accessible with `import * as Sentry from "@sentry/nodejs"` (or `@sentry/nextjs`,...) and `Sentry.Integrations.Http`
     - Client side [`HttpContext`](https://github.com/getsentry/sentry-javascript/blob/master/packages/browser/src/integrations/index.ts#L5) context, accessible with `import * as Sentry from "@sentry/browser"` and `Sentry.Integrations.HttpContext`
 3. `Http` and `HttpContext` are mentioned in the docs, but sparingly and due to `Http` and `HttpContext` interchangeably mentioned - it seems like both are similar but different.
    - [`HttpContext`](https://docs.sentry.io/platforms/javascript/guides/nextjs/configuration/integrations/default/#httpcontext) - *This integration attaches HTTP request information, such as URL, user-agent, referrer, and other headers to the event. It allows us to correctly catalogue and tag events with specific OS, browser, and version information.*
    - [`Http`](https://docs.sentry.io/platforms/node/configuration/integrations/default-integrations/#http) - *This integration wraps the http and https modules to capture all network requests as breadcrumbs and/or tracing (The process of logging the events that took place during a request, often across multiple services.) spans.*
4. It's not mentioned if JS framework like Next.js, which runs both server and client side, uses either `Http` or `HttpContext` or a combination of both.
5. The [Data Scrubbing Docs](https://docs.sentry.io/platforms/javascript/guides/nextjs/data-management/sensitive-data/#scrubbing-data) mention that sensitive information may appear in the Http Context. However, it fails to mention how to scrub data out of Http context, both in `Http` or `HttpContext` cases.

### Suggested Solution

Fix all 5 points, stay more consistent or make them more distinctive to understand their use cases and how to correctly use them.

**Comment by lobsterkatie** [comment]
Hi, @larsqa.

Thanks for this feedback! Agreed that some parts of this could be clearer.

@lizokm FYI, this is about more than the JS inheritance problem you'll soon get tired of hearing me complain about, but it's a good example. Let's chat about this on Monday.

**Comment by larsqa** [comment]
@lobsterkatie 
Additionally, [here](https://docs.sentry.io/product/data-management-settings/scrubbing/advanced-datascrubbing/#value-types) is mentioned that the http context is exposed in the request interface.
> $http: Matches the HTTP request context of an event. Alias for request

But the [Http integration page](https://docs.sentry.io/platforms/node/configuration/integrations/default-integrations/#http) mentions that the http context is exposed in breadcrumbs an/or tracing spans.

Which one is it now?
