### ISSUE TITLE
Tooltip on API Authentication page is too transparent

### ISSUE THREAD

**Issue by blx** [getsentry/sentry-docs#5900]
### Core or SDK?

Core Sentry product

### Which part? Which one?

API - Authentication

### Description

The background of the tooltip that appears when hovering over "token" on the page https://docs.sentry.io/api/auth/ is not strong enough, and causes background text to overlap:

<img width="833" alt="Screenshot 2022-12-05 at 6 45 19 PM" src="https://user-images.githubusercontent.com/887504/205796817-cace90aa-04e4-49ed-b67b-ac24a0651692.png">

(This is in recent Chrome, recent macOS)

### Suggested Solution

Adjust the opacity of the tooltip background

**Comment by a-hariti** [comment]
This used to be probably a z-index issue, there's currently no way repro this since we don't have definition lists and therefore no tooltips @stephanie-anderson
