### ISSUE TITLE
Session Replay - SDK Documentation on the docs site

### ISSUE THREAD

**Issue by jas-kas** [getsentry/sentry-docs#5903]
## Core or SDK?

Platform/SDK

## Which part? Which one?

Session Replay SDK documentation needs to be included in the following existing areas on our docs site (see existing sdk specific snippets [here](https://github.com/getsentry/sentry-docs/tree/master/src/wizard/javascript/replay-onboarding)): 

- [@sentry/browser](https://docs.sentry.io/platforms/javascript/)
- [@sentry/angular](https://docs.sentry.io/platforms/javascript/guides/angular/)
- [@sentry/ember](https://docs.sentry.io/platforms/javascript/guides/ember/)
- [@sentry/react](https://docs.sentry.io/platforms/javascript/guides/react/)
- [@sentry/svelte](https://docs.sentry.io/platforms/javascript/guides/svelte/)
- [@sentry/vue](https://docs.sentry.io/platforms/javascript/guides/vue/)
- [@sentry/gatsby](https://docs.sentry.io/platforms/javascript/guides/gatsby/)
- [@sentry/nextjs](https://docs.sentry.io/platforms/javascript/guides/nextjs/)
- [@sentry/remix](https://docs.sentry.io/platforms/javascript/guides/remix/)

## Description

Session Replay is a new product that is going to market in FY'24 Q1. Session Replay requires the installation of any of the SDKs mentioned above, as well as the `@sentry/replay` package. Installing the package requires users to also set sampling rates and general privacy settings.

Additionally, there are a number of optional configuration options that users can leverage (re: general integration, privacy, optimization and `rrweb`).

This is the **ideal SDK documentation state for Session Replay**. We are doing some temporary SDK doc changes for the second cohort we're enabling on Mon. Dec. 12th for closed beta.

This does not cover [Product Guide](https://docs.sentry.io/product/) documentation.

## Suggested Checklist of Docs to Create or Update
_(multiple issues can be created from this one)_

### New pages
- [x] Dedicated section titled "Session Replay", similar to what is seen for "Performance Monitoring", in the [browser SDK](https://docs.sentry.io/platforms/javascript/). This can come after the "Performance Monitoring" section.
- [x] First page under the section is titled "Set up Session Replay" and includes "Pre-requisites", "Installation", "Set up", "Sessions", "Sampling", and "Error Linking" from our [README](https://github.com/getsentry/sentry-javascript/tree/master/packages/replay#sentry-session-replay), and ["Verify"](https://docs.sentry.io/platforms/javascript/performance/#verify) section if applicable.
- [x] Second page under the section is titled "Custom Instrumentation" and includes two subpages - one for general configs "Identifying Users", "Start and Stop Recording", "General Integration Configuration", "Optimization Configuration", and "rrweb Configuration" from our [README](https://github.com/getsentry/sentry-javascript/tree/master/packages/replay#sentry-session-replay).
- [x] The second subpage under "Custom Instrumentation" will be dedicated to privacy configs and examples. It will cover the table titled "Privacy configuration" and all the Privacy config examples with images seen in our [README](https://github.com/getsentry/sentry-javascript/tree/master/packages/replay#privacy-configuration).
- [x] Add a **beta note** as seen in other docs to all of the above pages.

Repeat dedicated section titled "Session Replay" and the above checklist items in other applicable framework SDKs with any framework-specific quirks worth noting:
- [x] [@sentry/angular](https://docs.sentry.io/platforms/javascript/guides/angular/)
- [x] [@sentry/ember](https://docs.sentry.io/platforms/javascript/guides/ember/)
- [x] [@sentry/react](https://docs.sentry.io/platforms/javascript/guides/react/)
- [x] [@sentry/svelte](https://docs.sentry.io/platforms/javascript/guides/svelte/)
- [x] [@sentry/vue](https://docs.sentry.io/platforms/javascript/guides/vue/)
- [x] [@sentry/gatsby](https://docs.sentry.io/platforms/javascript/guides/gatsby/)
- [x] [@sentry/nextjs](https://docs.sentry.io/platforms/javascript/guides/nextjs/)
- [x] [@sentry/remix](https://docs.sentry.io/platforms/javascript/guides/remix/)

### Existing pages
- [ ] For **@sentry/browser**: Mention Session Replay CDN Bundles in [Installation Methods > CDN](https://docs.sentry.io/platforms/javascript/install/cdn/)
- [ ] For **all applicable SDKs**: Provide examples of Session Replay CDN bundles on the [Pluggable Integrations](https://docs.sentry.io/platforms/javascript/configuration/integrations/plugin/) page
- [ ] For **all applicable SDKs**: Add "Set up Session Replay" in the "[Next Steps](https://docs.sentry.io/platforms/javascript/guides/react/#add-readable-stack-traces-to-errors)" as the last link on the "Getting Started" pages, taking the user to the dedicated Session Replay section
- [ ] For [**@sentry/remix**](https://docs.sentry.io/platforms/javascript/guides/remix/), [**@sentry/nextjs**](https://docs.sentry.io/platforms/javascript/guides/nextjs/): Add "Session Replay" in the Features list on the "Getting Started" page
- [ ] For **all applicable SDKs**: On the "[Identify Users](https://docs.sentry.io/platforms/javascript/guides/nextjs/enriching-events/identify-user/)" page, mention that this setting applies to how users are identified in Session Replay

**Comment by jas-kas** [comment]
cc/ @ryan953 @mydea @Lms24 @smeubank

**Comment by bruno-garcia** [comment]
Assigned to myself, hoping I can give it hand

**Comment by bruno-garcia** [comment]
Sorry I added "Resolved" but we since decided to split in multiple PRs

**Comment by bruno-garcia** [comment]
Raised a few changes ^
Tomorrow I'll put up the SDK PRs

**Comment by bruno-garcia** [comment]
The top level menu with Session Replay has landed. It's available /javascript/ and its guides:

![image](https://user-images.githubusercontent.com/1633368/206555666-a9a78a5c-630c-4506-b16d-6f38edcf8c9b.png)

This gives us a link to give to customer, add to outgoing emails, etc. In those pages we have a banner announcing this is a Beta feature:
![image](https://user-images.githubusercontent.com/1633368/206555787-a82a08d1-270d-40e9-b5c9-3ef71ecd7714.png)

Since we're on a closed beta, Replay snippets throughout the hot path might cause confusion. In each reference we would need to include the Beta warning above. Explain why someone might not see it yet the Replay button in Sentry.

For that reason I'm closing this issue as done. The items not completed will be moved to a pre-GA issue.
