### ISSUE TITLE
tracesSampleRate behaves differently than described in the documentation

### ISSUE THREAD

**Issue by gkarat** [getsentry/sentry-docs#5905]
### Core or SDK?

Platform/SDK

### Which part? Which one?

React

### Description

We use Sentry and collect transactions in our project for the performance reporting. We tried to adjust `tracesSampleRate` several times and decrease the value so that we send **less** of them and don't reach our limit fast. 

However, after ~2 months of gathering transactions, we now see that with each adjustment (decrease) of the rate, there started to come **more** transactions. This all means these two values are actually indirect proportional to each other. The documentation states differently. So there is either a bug in SDK, or in the documentation.

We haven't tried yet to increase the rate to fix that issue. But our stats tab in Sentry confirms our theory.

Our commit history of the file where the `tracesSampleRate` is set:

https://github.com/RedHatInsights/insights-chrome/commits/prod-beta/src/js/sentry.ts

Screenshot:

![изображение](https://user-images.githubusercontent.com/31385370/205949284-cb4ebe89-084e-438d-baf3-bd29b7ebe9c6.png)

### Suggested Solution

Fix docs/fix SDK.

**Comment by AbhiPrasad** [comment]
As some additional context, this is how the JavaScript SDK works here: https://github.com/getsentry/sentry-javascript/blob/44a5cd6ece1eb66c1c8d14b0f65a69ef8f57f533/packages/tracing/src/hubextensions.ts#L104

```ts
transaction.sampled = Math.random() < (sampleRate as number | boolean);
```

Here, the higher the sample rate, the more likely `sampled` will be true.

If you supply the support folks at Sentry with your org/plan details, they can probably help dig deeper!

**Comment by gkarat** [comment]
I have just contacted support, thank you. If it will turn out that there is a problem on our side, I will close the issue.

**Comment by gkarat** [comment]
The issue turned out to be in our side, and we used not the most accurate info for our project (we viewed Stats which displays the info for the whole org, whereas we needed only for our project). Closing the ticket.
