### ISSUE TITLE
[OTEL] Go SDK Support for OpenTelemetry

### ISSUE THREAD

**Issue by smeubank** [getsentry/sentry-docs#5951]
### Core or SDK?

Platform/SDK

### Which part? Which one?

Golang

### Description

With the addition of OpenTelemetry support to the Go SDK we should provide example code snippets and explanations of what users will need to do to send their OpenTelemetry to Sentry

### Suggested Solution

Belongs under Performance Instrumentation. Should cover any nuances to the Go integration which is discovered during development and testing

> You need to register SentrySpanProcessor and SentryPropagator

Node and Ruby documentation already existing

**Comment by tonyo** [comment]
Done via #6208
