### ISSUE TITLE
Add SwiftUI APM docs

### ISSUE THREAD

**Issue by philipphofmann** [getsentry/sentry-docs#5966]
### Core or SDK?

Platform/SDK

### Which part? Which one?

Apple

### Description

With https://github.com/getsentry/sentry-cocoa/pull/2271 the Apple SDK adds support for APM for SwiftUI.

We need to add docs here https://docs.sentry.io/platforms/apple/performance/instrumentation/automatic-instrumentation/, and we should point out the feature in the list of features in Getting started, and the wizard. The docs should explain how SwiftUI APM works in combination with UIKit.

**Comment by philipphofmann** [comment]
I would not add it as APM, but it also doesn't belong to custom instrumentation IMO. I would add an extra section below custom instrumentation for SwiftUI. What do you think?
<img width="254" alt="Screenshot 2023-01-10 at 09 59 16" src="https://user-images.githubusercontent.com/2443292/211506696-65036f97-826c-462d-a037-a5d6011f970f.png">

**Comment by brustolin** [comment]
Yes. Thats also what I was thinking.

**Comment by brustolin** [comment]
Done with #6046
