### ISSUE TITLE
tracesSampleRate or sampleRate - docs are unclear which I should set

### ISSUE THREAD

**Issue by CaptainN** [getsentry/sentry-docs#5974]
### Core or SDK?

Platform/SDK

### Which part? Which one?

JS integration

### Description

I'd like to slow down the number of reports going to Sentry. In the docs ([here](https://docs.sentry.io/platforms/javascript/configuration/sampling/)) it's clear that there is a setting to change that rate - but there are 2 different keys mentioned (tracesSampleRate or sampleRate), which seem to do the same thing? It's unclear which one I should use.

### Suggested Solution

Pick one or the other, or more clearly describe why I might choose one or the other in my project.

**Comment by AbhiPrasad** [comment]
Hey @CaptainN, thanks for writing in! `tracesSampleRate` controls the rate at which our performance monitoring data is sent to Sentry (transactions), while `sampleRate` controls the rate at which error events are sent to Sentry. Which type of data are you looking to manage here?
