### ISSUE TITLE
Docs: Update screen shots on docs/privacy page so they're clearer and more obviously represent a customers app (not sentry-in-sentry)

### ISSUE THREAD

**Issue by ryan953** [getsentry/sentry-docs#5978]
>[...] more illustrative/abstract route for the supplemental screenshots? i found it a tiny bit disorienting seeing the Sentry UI as an illustration of what I should expect to see in my own UI
> i think the scale of this is a bit off, but i think something like this would've helped it click a hair sooner

![Image](https://user-images.githubusercontent.com/187460/208253674-e2d62406-5499-464b-bd59-d182c989afd9.png)

The only places where we have images right now is on the privacy page: https://docs.sentry.io/platforms/javascript/session-replay/privacy/ and on the marketing page: https://sentry.io/for/session-replay/

The Docs page should be updated first to make it clear that it's a customers app being masked/blocked out.

**Comment by Jesse-Box** [comment]
How about this @bruno-garcia @ryan953 @jas-kas 

![Replay-PIIScrubbing](https://user-images.githubusercontent.com/6508377/217759075-c70a0afd-2885-4487-8a3e-8dbf14cffcaf.png)

**Comment by jas-kas** [comment]
@bruno-garcia Took a look https://docs.sentry.io/platforms/javascript/session-replay/privacy/ and we still have 2 screenshots there that use the Sentry UI as an example under "Blocking" and "Ignoring". I wouldn't call this ticket complete IMO

**Comment by bruno-garcia** [comment]
hm, they are just small parts of a page so I didn't see a problem with them.

**Comment by Jesse-Box** [comment]
### Masking
![Masking](https://user-images.githubusercontent.com/6508377/219010926-5027e19c-e945-4d1b-bc09-41bad5d826cb.png)

### Blocking
![Masking + Blocking](https://user-images.githubusercontent.com/6508377/219011524-ecab2202-4709-47be-9ca3-3bf9754fe3a9.png)

### Ignoring
![Masking-VS-Ignoring](https://user-images.githubusercontent.com/6508377/219011551-fd8894a5-304c-4d0c-83a5-9596f4d49ee3.gif)

**Comment by jas-kas** [comment]
These look great, @Jesse-Box!

For the **masking** mock, I really like the actual site v. what the playback will be. I have a few comments:

- "What the customer sees" is somewhat vague because a customer of ours can think it means them. How about "What your user sees", "What your customer sees". (User might the most 'correct' here)

- Can we have an illustration in the circle/avatar space for the actual site to show we mask images

For **Ignoring**

- The green pill makes me think it's also my live website since that's what we used for Masking mock above. But really, it's two different privacy options. Can we visualize this a little differently?










cc @ryan953 to review as well :)

**Comment by ryan953** [comment]
I think the ignoring gif could benefit from a "what the customer sees" example on the left, so three <input>'s. Because the 'ignore' state has nothing animating i don't really grok it from the gif alone. Idk if that side should be animating or not.
I'm thinking like three input boxes, so the typing happens in two boxes simultaneously, but not the third box. i think that would drive home that the third box is skipping those events.


Also, i like that the "what the customer sees" snippet shows it's a profile page, gives just enough context so the masked stuff on the right side make more sense. This is important to show first because it adds context to the blocking example too

**Comment by Jesse-Box** [comment]
So on the wording for the masking

I would change it to, “what your customer sees” and “what you'll see by default” because I assume we're talking to developers in the first place.

**Comment by ryan953** [comment]
Lets set this as 'todo' and change the assignment when it's ready for someone put up a PR

**Comment by Jesse-Box** [comment]
New versions!

### Masking
![Comparison](https://user-images.githubusercontent.com/6508377/219349195-c3e26161-83c8-43a5-adf7-16dd6d417bee.png)

### Blocking
![Full Mock](https://user-images.githubusercontent.com/6508377/219349374-1b5edcc0-afe8-42f0-81d1-84d7f637e813.png)

### Ignoring
![Ignoring Comparison](https://user-images.githubusercontent.com/6508377/219349462-41d4af4f-298f-489a-b4f5-fb25fe6a375b.gif)

**Comment by jas-kas** [comment]
@ryan953 What do you think of the **Ignoring** screenshots now? Imo all 3 look good to 🐿

**Comment by ryan953** [comment]
> What do you think of the Ignoring gif now? Imo all 3 mocks look good to 🐿

That gif is amazing. I'm gonna :shipit: all 🚀
