### ISSUE TITLE
Apple View Hierarchy Docs

### ISSUE THREAD

**Issue by philipphofmann** [getsentry/sentry-docs#5984]
Add docs for the view hierarchy feature to the Apple docs added with https://github.com/getsentry/sentry-cocoa/pull/2491.

**Comment by brustolin** [comment]
We are waiting to have the new View hierarchy feature to be available in the product to update the docs.

**Comment by philipphofmann** [comment]
Fixed with https://github.com/getsentry/sentry-docs/pull/6091.
