### ISSUE TITLE
Add cURL example to crons docs

### ISSUE THREAD

**Issue by davidenwang** [getsentry/sentry-docs#5993]
### Core or SDK?

Core Sentry product

### Which part? Which one?

Crons

### Description

Looking to use the code examples from https://docs.sentry.io/product/crons/getting-started/#step-2-set-up-health-checks to instrument my monitor, but would have liked to see a cURL example.

### Suggested Solution

Add cURL to the example code, demonstrating a check-in creation and update flow.

**Comment by originell** [comment]
thank you :)
