### ISSUE TITLE
Out of the box performance tracing for WebFlux

### ISSUE THREAD

**Issue by alphec** [getsentry/sentry-docs#6020]
### Core or SDK?

Platform/SDK

### Which part? Which one?

Sentry for Spring Boot

### Description

The page https://docs.sentry.io/platforms/java/guides/spring-boot/webflux/ suggest that WebFlux works quite similar to WebMVC. In case of performance tracing for HTTP calls this is to my knowledge not the case. I would have expected that this page mentions this.

### Suggested Solution

Please mention that out of the box performance tracing is not supported (yet).

**Comment by hubertdeng123** [comment]
@adinauer Is there any action to be done here, maybe linking opentelemetry to docs there 🤔? Tracking down Untriaged issues and wanted to know if this belongs on the backlog or can be closed

**Comment by adinauer** [comment]
I'll discuss with the team whether we want to link to OTEL in the docs.
