### ISSUE TITLE
Support for VB.Net

### ISSUE THREAD

**Issue by masinette** [getsentry/sentry-docs#6023]
### Problem Statement

**Customer Feedback** 

> Hello, we are using Sentry in our .Net 4.8 in our winforms desktop app and could use an example of this using vb.net instead of c#
> 
> https://docs.sentry.io/platforms/dotnet/enriching-events/tags/
> 
> We are wanting to add username and other tags to the sentry event and error logs.

### Solution Brainstorm

Include vb.net example

**Comment by bruno-garcia** [comment]
Moving to the docs.
We'd love to take contributions for VB examples (and F# for that matter) but truth is that given 90% of .NET code is written in C#, it's unlikely we'll prioritize code snippets in other .NET languages.

@mattjohnsonpint wdyt?

**Comment by mattjohnsonpint** [comment]
We already have this for winforms, as VB has two different initialization options (with "Application Framework" or without.)

https://docs.sentry.io/platforms/dotnet/guides/winforms/#visual-basic-initialization

Unlikely we'll add VB snippets to the docs for other stuff, unless it's specific to VB.  (Anything we show for C# will also work with VB.NET or any other .NET language.)
