### ISSUE TITLE
Sentry's documentation needs better guidance for Auth0 + Next.js

### ISSUE THREAD

**Issue by watadarkstar** [getsentry/sentry-docs#6033]
### Core or SDK?

Platform/SDK

### Which part? Which one?

@sentry/nextjs

### Description

After some Googling I found that Sentry's documentation needs better guidance on the following topic. 

Suppose you have an Auth0 + Next.js app and you want to set the user context. Where do you do that client side and server side?

### Suggested Solution

I tried doing it in the `afterCallback` for Auth0 as seen below but I'm still getting the IP address as the user in Sentry. This is probably due to the serverless nature of Vercel / Next.js as this only gets called once when the user logs in server side.

```typescript
import * as Sentry from "@sentry/nextjs";

...
const afterCallback = async (_req: any, _res: any, session: Session) => {
 Sentry.setUser({
    id: session?.user?.sub,
    email: session?.user?.email,
    username: session?.user?.nickname,
    name: session?.user?.name,
    avatar: session?.user?.picture,
  });

  return session;
};
...
```

My test page in Next.js `pages/sentry/test1.tsx`:

```typescript
const Test1 = () => <h1>SSR Test 1</h1>;

export function getServerSideProps() {
  throw new Error("SSR Test 1");
}

export default Test1;
```

For the client side, I did this which generally worked:

```typescript
import { useEffect } from "react";
import { setUser } from "@sentry/nextjs";
import { useUser } from "@auth0/nextjs-auth0";

function SentryUserManager() {
  const { user } = useUser();

  useEffect(() => {
    if (user) {
      setUser({
        email: user.email ?? undefined,
        name: user.name ?? undefined,
      });
    } else {
      setUser(null);
    }
  }, [user]);
  return null;
}

export default SentryUserManager;
```

And then in _app.tsx:

```typescript
import { UserProvider } from "@auth0/nextjs-auth0";
import SentryUserManager from "../components/SentryUserManager";

...
return <UserProvider>
            <SentryUserManager />
</UserProvider>
...
```

My test page:

```typescript
import { useEffect } from "react";

const Test3 = () => {
  useEffect(() => {
    throw new Error("Client Test 3");
  }, []);

  return <h1>Client Test 3</h1>;
};

export default Test3;
```

**Comment by lforst** [comment]
Hi, thanks for the feedback, we already discussed this a bit here https://github.com/getsentry/sentry-javascript/discussions/6676 but just in case somebody stumbles over this issue:

Setting a user works the same in Next.js as it would in any other HTTP framework. Each request has its own isolated scope where you need to call `setUser`. Unfortunately, Next.js currently doesn't provide an easy way to run code in every route except for middleware. However, middleware is still not ideal as it may run on an isolated machine when deployed, making it pointless to set a user.

The current "workaround" is to call `setUser` in each individual route. I guess writing some sort of helper function makes sense in this case.

I am not sure if we should add this to the docs as this is very verbose and we try to keep the docs as concise as possible. Adding this would feel like explaining React/Next.js concepts to people which I would like to avoid.

I hope that this issue and https://github.com/getsentry/sentry-javascript/discussions/6676 is enough context for people searching online to figure out what they need to do. Thank you very much for bringing it up though!
