### ISSUE TITLE
bad code sample for before_send in python

### ISSUE THREAD

**Issue by jeremy-dragonfly** [getsentry/sentry-docs#6040]
### Core or SDK?

Core Sentry product

### Which part? Which one?

before_send

### Description

On this page:
https://docs.sentry.io/platforms/python/configuration/filtering/
the sample code under "Using Hints" shows
`if exc_info and isinstance(exc_info[0], DatabaseUnavailable)`
but I think we want something like
`if exc_info and exc_info[0] == DatabaseUnavailable`
since `exc_info[0]` is already a type object (I'm not actually sure of the Pythonic way to do this comparison, but hopefully you get the idea).

### Suggested Solution

See above

**Comment by sl0thentr0py** [comment]
thx for reporting @jeremy-dragonfly!
