### ISSUE TITLE
List fields scrubbed by default data scrubbers

### ISSUE THREAD

**Issue by rodolfoBee** [getsentry/sentry-docs#6087]
### Core or SDK?

Core Sentry product

### Which part? Which one?

https://docs.sentry.io/product/data-management-settings/scrubbing/server-side-scrubbing/

### Description

The current documentation described nicely what we try to scrub from events, but not where we scrub the information from.

For example, credit card numbers are scrubbed from additional context, but not from tags or exception value. See the example event that uses randomly generated credit card number and IP address. The same value was used on all fields with same name (password, IP and card).

![Screenshot 2023-01-17 at 11 59 21](https://user-images.githubusercontent.com/64906376/212882012-a2cd02a0-27ff-4626-89a4-8106125bbfd6.png)

### Suggested Solution

Have a list that informs where the scrubbed is applied (fields that match `pii = "true"` in the relay repository where the scrubbing is done).

**Comment by rbisol** [comment]
Example of field marked as pii=true: https://github.com/getsentry/relay/blob/2a0976d7d9ecfd4daa6cb2390c224d09f9a79bbd/relay-general/src/protocol/breadcrumb.rs#L101

**Comment by olksdr** [comment]
Added to the @getsentry/ingest team board. We will discuss if we can add more docs here.

**Comment by jan-auer** [comment]
From Relay, we can auto-generate a list of fields and import it to docs, similar to [`document-metrics`](https://github.com/getsentry/relay/tree/master/tools/document-metrics).
