### ISSUE TITLE
Broken anchors in `fingerprint-rules` docs

### ISSUE THREAD

**Issue by leonard84** [getsentry/sentry-docs#6107]
### Core or SDK?

Core Sentry product

### Which part? Which one?

data-management-settings/event-grouping/fingerprint-rules

### Description

For some reason both the `h2` of `Matchers` and `Combined Matchers` have the same `id` (`matchers`), the `id` of `Variables` is `combining-matchers`. There seems to be an off by one issue in play. So it is currently impossible to link to the `Combined Matchers` section.

I had checked the source, but the `.mdx` file doesn't seem to contain manually assigned section ids.

https://docs.sentry.io/product/data-management-settings/event-grouping/fingerprint-rules/#matchers

### Suggested Solution

There seems to be an issue with the generator that turns the `.mdx` files into `.html`

**Comment by untitaker** [comment]
this might be the same root cause as https://github.com/getsentry/sentry-docs/issues/4580

**Comment by hubertdeng123** [comment]
Putting this on the backlog based on the relation to https://github.com/getsentry/sentry-docs/issues/4580
