### ISSUE TITLE
[OTEL] Kotlin docs

### ISSUE THREAD

**Issue by smeubank** [getsentry/sentry-docs#6125]
### Core or SDK?

Platform/SDK

### Which part? Which one?

Kotlin* via Java support

### Description

With the addition of OpenTelemetry support to the Go SDK we should provide example code snippets and explanations of what users will need to do to send their OpenTelemetry to Sentry

### Suggested Solution

Belongs under Performance Instrumentation. Should cover any nuances to the Go integration which is discovered during development and testing

> You need to register SentrySpanProcessor and SentryPropagator

Node and Ruby documentation already existing

**Comment by smeubank** [comment]
@adinauer should we create another issue for Kafka?

**Comment by adinauer** [comment]
We can add Kotlin samples to https://docs.sentry.io/platforms/java/guides/servlet/performance/instrumentation/opentelemetry/ as we usually do.

> should we create another issue for Kafka?

Not sure yet. We should probably play around with it on the sample first to see if it offers useful insights. What do you think?

**Comment by adinauer** [comment]
After playing around with kafka on the demo it looks like it's not generating any spans. So I don't see a reason to document. Generic Java docs (https://docs.sentry.io/platforms/java/performance/instrumentation/opentelemetry/) should be applicable for most frameworks only requiring users to figure out the correct location to init for their framework.
