### ISSUE TITLE
Java SDK wizard does not mention OTEL

### ISSUE THREAD

**Issue by adinauer** [getsentry/sentry-docs#6135]
### Core or SDK?

Platform/SDK

### Which part? Which one?

Java SDK

### Description

When creating a new project, the wizard does not mention our OTEL integration.

### Suggested Solution

It should at least mention OTEL works with Sentry and link existing docs.

**Comment by adinauer** [comment]
Decided not to do this for now. @smeubank should I close this or keep it open for later?

**Comment by stephanie-anderson** [comment]
Closing this issue for now
