### ISSUE TITLE
UI bug on fingerprint rules page

### ISSUE THREAD

**Issue by stellaatsentry** [getsentry/sentry-docs#6141]
### Core or SDK?

Core Sentry product

### Which part? Which one?

Fingerprint Rules

### Description

The code example shown in the video recording is placed incorrectly and the "copy" button is hidden behind the description of error.type.

https://user-images.githubusercontent.com/81985895/214237451-b5747b49-4417-41c2-8c73-5d6ce754be22.mov

### Suggested Solution

Changing the positioning would fix the issue :)

**Comment by lizokm** [comment]
I'm unable to reproduce. It seems to be working fine on my machine.

<img width="1030" alt="Screenshot 2023-01-25 at 3 42 40 PM" src="https://user-images.githubusercontent.com/26800704/214718510-0cae7ee2-e1c4-400c-8984-902803c8a849.png">
