### ISSUE TITLE
Update Sample rate to be the same for JS setup

### ISSUE THREAD

**Issue by smeubank** [getsentry/sentry-docs#6150]
### Core or SDK?

Platform/SDK

### Which part? Which one?

JS Browser Docs

### Description

[Getting Started](https://docs.sentry.io/platforms/javascript/guides/react/)
vs
[Set Up Performance](https://docs.sentry.io/platforms/javascript/guides/react/performance/)

we have 2 different rates in the snippets

### Suggested Solution

Should be the same everywhere

**Comment by sdzhong** [comment]
In addition--in the JS Browser docs, [Setting a Sampling Function](https://docs.sentry.io/platforms/javascript/configuration/sampling/#setting-a-sampling-function)--I believe the `tracesSampler` option should have an else `return 1;` instead of 0.1 

> } else {
>   // Default sample rate
>   return 0.1;
> }
