### ISSUE TITLE
Lack of working example for User Feedback dialog in Vue 

### ISSUE THREAD

**Issue by simonklimek** [getsentry/sentry-docs#6173]
### Core or SDK?

Platform/SDK

### Which part? Which one?

Vue

### Description

I am trying to implement feedback dialog window for Vue 2 application, and I struggle a lot due to lack of examples on the internet. 
I'm thinking would it be possible to trigger the feedback dialog on demand if user notice something wrong. Let say button called "leave us feedback" or "report an error" that's the idea.

In Sentry documentation for Vue2 there is code sample of adding  Sentry.showReportDialog method in router index file. I'm not sure does Vue js SDK support this method and barely I know how to test it. 

In my router index.js I import those libraries:

```
import * as Sentry from '@sentry/vue'
import { Integrations } from '@sentry/tracing''
```
In the other part of the Sentry documentation I came across totally different solution with sending POST API Call - https://docs.sentry.io/api/projects/submit-user-feedback/

I'm very confused with the documentation of this feature, especially for Vue app. 

The product overall is great I love Sentry :heart: 

### Suggested Solution

So I recommend enrich a little bit this area of the Sentry documentation.

**Comment by Lms24** [comment]
Hi @simonklimek thanks for writing in! 

Have you checked this page yet? https://docs.sentry.io/platforms/javascript/guides/vue/enriching-events/user-feedback/

It's definitely written a little generic as its pointing to the CDN version of the base JS browser SDK. While we should definitely improve the documentation here, this feature should work with the NPM version of the Vue SDK analogously. If not, we probably have some work to do ;) 

LMK if this helps!

**Comment by simonklimek** [comment]
Hi! @Lms24 

I managed to implement user feedback already using your way :
```
// vue router index.js
import * as Sentry from '@sentry/vue'
// ***
beforeSend(event, hint) {
      if (event.exception) {
        Sentry.showReportDialog({
          eventId: event.event_id,
          lang: 'pl',
        })
      }
      return event
    },
```

Everything works flawlessly now on my end.

However I still can't setup Postman for API requests following this part of documentation: https://docs.sentry.io/api/projects/submit-user-feedback/

I am trying to send feedback via API POST request and I receive 404 every time, I am using token created in Settings > sentry > Developer Settings The token has project read/write permission only. Not sure why it doesn't work.

**Comment by lforst** [comment]
@simonklimek are you sure you are referencing an event that actually exists via event_id?

**Comment by simonklimek** [comment]
@lforst Does it mean I cannot trigger User-Feedback dialog without corresponding sentry event error?

I was thinking of triggering the dialog on demand, there are the cases when something went wrong in the app without throwing sentry error (let say some UX issues on the front-end). And I want to send POST API with user feedback. 

@Lms24 Regarding the webpack plugin for Vue 2.7 the user-feedback dialog integration works well for me now, thanks! 
I had problems with setting up the source-maps - missing argument in webpack `devtool: 'source-map'`.

Everything else runs flawlessly, let me know if you planning to add user feedback on-demand I think it could be useful feature.

If it helps someone reading this I'm putting the working code integration for Vue 2.7 with webpack Sentry plugin.
file: `vue.config.js`
`
const SentryWebpackPlugin = require('@sentry/webpack-plugin')
const sentry =
  process.env.VUE_APP_ENVIRONMENT === 'development' ||
  process.env.VUE_APP_ENVIRONMENT === 'production'
    ? [
        new SentryWebpackPlugin({
          url: process.env.SENTRY_URL,
          authToken: process.env.VUE_APP_SENTRY_AUTH_TOKEN,
          org: 'sentry',
          project: 'frontend',
          include: './dist',
          ignore: ['node_modules', 'vue.config.js'],
          release: process.env.VUE_APP_MY_RELEASE
        })
      ]
    : []
module.exports = {
  css: {
    extract: { ignoreOrder: true }
  },
  configureWebpack: {
    devtool: 'source-map',
    sentry,
    module: {
      rules: [
        // FOR PINIA
        {
          test: /\.mjs$/,
          include: /node_modules/,
          type: 'javascript/auto'
        }
      ]
    }
  },
  runtimeCompiler: process.env.NODE_ENV !== 'development' ? false : true,

  devServer: {
    port: 8080
  }
}

`

**Comment by lforst** [comment]
> @lforst Does it mean I cannot trigger User-Feedback dialog without corresponding sentry event error?

@simonklimek I believe that is the case yes. User feedback needs an event first.

**Comment by Lms24** [comment]
> let me know if you planning to add user feedback on-demand I think it could be useful feature.

While I agree that this might be worthwile to have, it is something that's out of scope for us at the moment. 
I'm gonna close this issue as the core problem seems to be resolved. Let us know if you need additional information :)
