### ISSUE TITLE
Document Portable PDB

### ISSUE THREAD

**Issue by mitsuhiko** [getsentry/sentry-docs#6210]
### Core or SDK?

Core Sentry product

### Which part? Which one?

dotnet

### Description

The documentation on symbol servers misses the portable PDB section: https://docs.sentry.io/platforms/dotnet/data-management/debug-files/symbol-servers/

We also link to symsorter/symbolicator sometimes in the docs, it's also missing there (https://getsentry.github.io/symbolicator/advanced/symbol-server-compatibility/ and https://getsentry.github.io/symbolicator/advanced/symbol-lookup/). It needs to be documented there too and ensured that the docs are pushed out.

Documentation is also missing for how we find symbols on nuget I believe, at least I did not find it.

### Suggested Solution

bla

**Comment by loewenheim** [comment]
- [ ] Sentry symbol server documentation (https://docs.sentry.io/platforms/dotnet/data-management/debug-files/symbol-servers/)
- [ ] Symbolicator symbol server documentation (https://getsentry.github.io/symbolicator/advanced/symbol-server-compatibility/)
- [x] Symbolicator symbol lookup documentation (https://getsentry.github.io/symbolicator/advanced/symbol-lookup/) (https://github.com/getsentry/symbolicator/pull/1008)

**Comment by loewenheim** [comment]
@mitsuhiko PPDB should now be documented everywhere.
