### ISSUE TITLE
In Next.js related documentation, it's not clear what properties can be set in the client or server config

### ISSUE THREAD

**Issue by barakbe-at-monday-dot-com** [getsentry/sentry-docs#6223]
### Core or SDK?

Platform/SDK

### Which part? Which one?

Sentry next.js SDK

### Description

Currently there's no way to understand from the documentation what properties can be set in the client vs. server config files.
For example, the 'debug' property.

### Suggested Solution

Show on each property if it's available on server's config or on client's config.

**Comment by lforst** [comment]
Hi, in general, all of the options can be used everywhere. Let us know if you come across one that doesn't work for a particular config. And we'll add a note. Thanks!
