### ISSUE TITLE
Next.js SDK - Tree shaking feature documentation results in an error, docs might need to be updated

### ISSUE THREAD

**Issue by barakbe-at-monday-dot-com** [getsentry/sentry-docs#6224]
### Core or SDK?

Platform/SDK

### Which part? Which one?

Initializing the SDK using new BrowserClient({})

### Description

I'm getting 'uncaught TypeError: options.transport is not a function'. 
Followed the documentation here:
ncaught TypeError: options.transport is not a function

I wasn't able to initalize the SDK correctly in order to custom it for the tree shaking feature.
Please update the documentation so I could reduce Sentry bundle size.

Thanks in advance.

### Suggested Solution

Update the documentation with the correct init process.

**Comment by lforst** [comment]
Hi, can you share how exactly you set up tree shaking, the SDK init, and what version of the SDK you're using? I believe the tree-shaking code snippet in the docs should be correct.
