### ISSUE TITLE
Record replays on docs.sentry.io

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-docs#6233]
### Steps to Reproduce

1. Bump Sentry SDK
2. Migrate Gatsby init to the latest SDK strategy
3. Enable Session Replay

**Comment by AbhiPrasad** [comment]
It seems that we need to set `GATSBY_SENTRY_DSN` in CI - @bruno-garcia could you help with that? This value should be the same as the one set by `SENTRY_DSN`

**Comment by chadwhitacre** [comment]
https://vercel.com/sentry/sentry-docs/settings/environment-variables

**Comment by bruno-garcia** [comment]
Works! Thanks folks
