### ISSUE TITLE
gatsby-remark-terms plugin not working properly in production

### ISSUE THREAD

**Issue by priscilawebdev** [getsentry/sentry-docs#6238]
### Steps to Reproduce

1. Go to the [Dynamic Sampling documentation]( https://docs.sentry.io/product/data-management-settings/dynamic-sampling/)

2.  See that the Note under [Dynamic Sampling & SDK Sampling](https://docs.sentry.io/product/data-management-settings/dynamic-sampling/#dynamic-sampling--sdk-sampling) is aligned to the center and does not have a proper Note styles 

### Expected Result

![image](https://user-images.githubusercontent.com/29228205/217192111-e65073ff-5a59-4f28-acb1-36fb048b7347.png)

### Actual Result

![image](https://user-images.githubusercontent.com/29228205/217192169-b9c92279-72eb-4001-82f7-82174df73e8e.png)

### Additional Info

Locally, when developing, everything seems to be working fine, but not in production.

@untitaker I saw that you created the plugin. Do you have any idea why this is occurring in production? 

On the page https://docs.sentry.io/product/data-management-settings/dynamic-sampling/benefits-dynamic-sampling/  the error doesn't occur and the only difference is that we say `in this section` instead of `on this page`

**Comment by lforst** [comment]
@lizokm Hi, Team Web Frontend is actually the JS SDK team. Can we rename the tag so this is a bit more clear?

I believe this is a frontend issue with the docs page, so we should probably re-route this. Don't know who is responsible for this though. #docsengineer

**Comment by hubertdeng123** [comment]
I believe this can go to visibility, if not please let me know :)

**Comment by untitaker** [comment]
I don't know that this has a team at all.

**Comment by silent1mezzo** [comment]
Ya, definitely not Visibility. @lizokm not sure if you have a team label?

**Comment by untitaker** [comment]
I believe this is another silly hydration bug with Gatsby that we cannot fix.

**Comment by hubertdeng123** [comment]
Got it, if that's the case I'll remove the team label and put this on the backlog since it can't really be triaged then. Thanks for following up!

**Comment by stephanie-anderson** [comment]
The page no longer exists in this way, but I also guess the underlying issue has been fixed by the Next.js migration. Please re-open if this is still a problem somewhere
