### ISSUE TITLE
[Documentation] List of "supported" operation types

### ISSUE THREAD

**Issue by jeengbe** [getsentry/sentry-docs#6252]
### Problem Statement

There should be some overview of which "op" types are suggested to be used, and which operations lead to which icon in breadcrumbs, for instance. Also maybe some guideline as to how to name them. Just something to guide consistent naming. :)

**Comment by lizokm** [comment]
Hi there! Could you give a little bit more context and be a bit more specific? Which operations are you referring to?

**Comment by jeengbe** [comment]
HI @lizokm!
Right, sorry, of course. In my head, I was referring to a clear thing 🙃 

I was talking about the kinds of spans and breadcrumbs that are created: names like `http.client`, `ui.click`, `middleware.express.use` etc. 

A guide for naming these would be nice. Also for the case that Sentry does or might in the future group or categorize events by their type. 
![image](https://user-images.githubusercontent.com/51749023/217468984-78805570-6f11-42cc-98cc-6c07755cba04.png)

I took the term "operation name" from the JavaScript SDK which has it `parentSpan.startChild({ op: "..." })`

**Comment by lizokm** [comment]
Ah! That makes sense. Thanks for the clarification. I'll pass this along for the team to look at :)

**Comment by mjq-sentry** [comment]
Hi @jeengbe! Does [the Span Operations page](https://develop.sentry.dev/sdk/performance/span-operations/) from our SDK guide have the info you're looking for? If not, please leave feedback here and I'll loop in the SDK team! Thanks!

**Comment by jeengbe** [comment]
Oh hey @mjq-sentry! It does indeed! That's a whole new subdomain of documentation I was unaware of, thanks! 🙂
