### ISSUE TITLE
Identify-users code snippet on rust is incorrect

### ISSUE THREAD

**Issue by TBS1996** [getsentry/sentry-docs#6257]
### Core or SDK?

Core Sentry product

### Which part? Which one?

Rust docs

### Description

https://docs.sentry.io/platforms/rust/enriching-events/identify-user/

``` rust
sentry::configure_scope(|scope| {
    scope.set_user(Some(sentry::User {
        email: "jane.doe@example.com".to_owned()
        ..Default::default()
    }));
});
```

The email field should be an option, there's also a missing comma

### Suggested Solution

```rust
sentry::configure_scope(|scope| {
    scope.set_user(Some(sentry::User {
        email: Some("jane.doe@example.com".to_owned()),
        ..Default::default()
    }));
});
```

**Comment by sl0thentr0py** [comment]
@TBS1996 mind just opening a PR and fixing it?

**Comment by TBS1996** [comment]
done #6270
