### ISSUE TITLE
Response is not accessible on Event

### ISSUE THREAD

**Issue by AdamBCo** [getsentry/sentry-docs#6296]
### Core or SDK?

Platform/SDK

### Which part? Which one?

iOS SDK

### Description

At the moment, the documentation states the following on this [page](https://docs.sentry.io/platforms/apple/configuration/http-client-errors/) for HTTP Client errors

``` 
Once enabled, this feature automatically captures HTTP client errors, like bad response codes, as error events and reports them to Sentry. The error event will contain the request and response data, such as url, status_code, and so on.
```

Unfortunately the response is not accessible in the current version of the SDK, just the request.

### Suggested Solution

Please add support for accessing the response on the error object.

**Comment by brustolin** [comment]
Hello @AdamBCo, I'm curious why you need to access the response in the error object.

And by "error object" you mean the event, as a quick workaround, we can do this:

```swift
event.context["response"]
```

This will return a Dictionary<String, any>.

**Comment by AdamBCo** [comment]
@brustolin We need a way of stopping 401 HTTP errors from being reported. How would we achieve that?

**Comment by marandaneto** [comment]
You can also configure the `HttpStatusCodeRange`.
https://docs.sentry.io/platforms/apple/configuration/http-client-errors/

**Comment by AdamBCo** [comment]
@marandaneto I want the range to be `HttpStatusCodeRange(min: 400, max: 599)`, but I don't want to get notified of 401's.

How can I do that?

**Comment by markushi** [comment]
Not an expert here, but `failedRequestStatusCodes` allows you to provide an array of ranges, so something like this should work for your use case:
````
options.failedRequestStatusCodes = [ 
    HttpStatusCodeRange(statusCode: 400),
    HttpStatusCodeRange(min: 402, max: 599)
]
````

**Comment by kahest** [comment]
The questions in this issue have been answered.
