### ISSUE TITLE
[Session Replay > Performance Overhead] Missing runtime impact

### ISSUE THREAD

**Issue by jeengbe** [getsentry/sentry-docs#6297]
### Core or SDK?

Core Sentry product

### Which part? Which one?

Session Replay > Performance Overhead

### Description

The [performance overhead page](https://docs.sentry.io/product/session-replay/performance-overhead/) is vague in that it doesn't contain the key information I was looking for. How much is the actual overhead in terms of CPU/RAM of sampling and storing the snapshots? 

### Suggested Solution

If no numbers are available, a simple note like "runtime overhead negligible" would also just be enough, but _some_ way for me to understand the impact of this feature :)

**Comment by benvinegar** [comment]
@jeengbe I'll quickly answer here: it's complicated. Basically, the overhead depends entirely on the number of DOM mutations observed. If it's a static website with very little change (e.g. a user just scrolling around a marketing page), I'd expect the overhead to be near-zero. If it's a complex dynamic application and the user is reloading large components – which re-render complex DOM trees – the overhead could be noticeable if the changes are rapid.

We have an example application we use that has dozens of simultaneous DOM animations (e.g. many blocks moving via x/y coordinate changes at 60fps) that is just streaming event data out by the millisecond. This application sees 30-40% CPU overhead. But by no means indicative of a typical end-user application (e.g. CSS animations would not trigger state changes like this).

Perhaps the language I'm using would be helpful on the documentation page itself. Thoughts?

**Comment by jeengbe** [comment]
Hey @benvinegar, thanks for the extensive answer! 

So, as always: it depends. 😄 


> Perhaps the language I'm using would be helpful on the documentation page itself. Thoughts?

_Something_ would be enough, be it _it depends_, and possibly a link to your comment. In its current stage, the page is missing the crucial aspect of runtime impact. I have no idea whether it's 0 impact or causing laptop to overheat 😁, and just something to give me an idea what to expect (even if it's just "it depends, but roughly ...") would be more than satisfying.

**Comment by tristanbes** [comment]
Hello,

as a Sentry customer (both APM and bug tracking) I'm very reluctant to activate this feature for 2 reasons:
- I don't know the overhead it adds to webperf (how much weight it adds to the SDK shipped to to browser, what is actually sent to sentry ? a video ? or DOM nodes user interacted with ? What is the impact on Web Vitals ?). 

To give more context, I work for a media site which is very different for a product/app behind login on which you can be more tolerant regarding added footprint/ perf overhead
80% of our traffic is coming from mobile, we get a lot of hits per months and are very dependant on webperf not to be penalized by Google

- The other reason is that we have a lot of 3rd party script (ads..) that generates a lot of noise and on which we cannot fix errors for them. I don't want to capture session for that use-case since the error is not generated by the user

**Comment by bruno-garcia** [comment]
> I don't know the overhead it adds to webperf (how much weight it adds to the SDK shipped to to browser)

Sentry itself is using this. But the overhead it adds on Sentry (Not noticeable for me at least) might not be the same that you detect on your site. But you can find out, by adding the SDK and browsing around. 

>  what is actually sent to sentry ? a video ? or DOM nodes user interacted with ?

It's not a video. This is covered on our [FAQ page](https://help.sentry.io/product-features/other/what-is-session-replay/#general). And also on [our docs](https://docs.sentry.io/product/session-replay/) and I strongly recommend going through it to better understand how it works. It'll clarify a lot of these questions. A snippet from the docs:

> A replay is not a video recording. It’s a video-like reproduction of a user session, built using the  [rrweb recording library](https://www.rrweb.io/). Replays are created from snapshots of your web application’s DOM state (the browser’s in-memory representation of HTML). A user session can span multiple page loads, including page refreshes.

>  What is the impact on Web Vitals ?.

If you use Sentry performance monitoring, you'll continue to see the Web Vitals. So how the new integration affects that will be visible in Sentry.

> The other reason is that we have a lot of 3rd party script (ads..) that generates a lot of noise and on which we cannot fix errors for them. I don't want to capture session for that use-case since the error is not generated by the user

Being able to sample not only by error, but also by what type of error is something we're looking into exploring further. This requires defining what that looks like.
