### ISSUE TITLE
Dynamic Sampling not available, but is listed in Docs.

### ISSUE THREAD

**Issue by WillSoper-MSN** [getsentry/sentry-docs#6341]
### Core or SDK?

Core Sentry product

### Which part? Which one?

Website documentation

### Description

I spent *ages* trying to find the "Dynamic Sampling" option in the UI, after finding this feature listed in the docs here: https://docs.sentry.io/product/data-management-settings/dynamic-sampling/benefits-dynamic-sampling/ 

I was about to raise a support ticket to ask where it was because I assumed I had missed something when I found this help article that explained it:

https://help.sentry.io/account/account-settings/dynamic-sampling/

It would be really helpful if the Docs reflected the current status of that feature.

### Suggested Solution

Have a header in the "Dynamic Sampling" section that explains this feature isn't currently available.

**Comment by ale-cota** [comment]
Hi @WillSoper-MSN,

Thanks a lot for reporting this issue and we're sorry you spent so much time before you were able to find any helpful information. We'll definitely take your suggestion and include a callout below the header to clarify the status of the feature in our documentation.

Dynamic Sampling is actually available, but only on the latest version of our plans. Your plan can be updated by any Organization Owner or Billing Member by going to Settings > Subscription > Manage Subscription". Once you do that, you'll also be able to see the feature in your settings.

Let me know if you have any other questions and thanks again for reporting this!
