### ISSUE TITLE
Apollo Node Integration limitations

### ISSUE THREAD

**Issue by Martomate** [getsentry/sentry-docs#6346]
### Core or SDK?

Platform/SDK

### Which part? Which one?

Node

### Description

When using the Apollo integration in NodeJS (documented [here](https://docs.sentry.io/platforms/node/guides/serverless-cloud/performance/database/opt-in/#apollo-server-integration)) I expected it to add spans for each GraphQL resolver but nothing happened.

After looking at the source code it turns out that the integration does not support ApolloServers where the schema was loaded using the `schema` property (like this: `new ApolloServer({ schema: ... })`).

### Suggested Solution

I would be nice if this was mentioned in the docs so people like me don't have to wonder why the integration doesn't do anything.

**Comment by Lms24** [comment]
Hey @Martomate thanks for writing in! I don't have a lot of context around our Apollo integration but I think you're right that we should mention this as a limitation. I opened a quick PR to add a note: #6359 

By the way, I quickly checked the integration's code and if the `schema` property is used, it should emit a warning if you set `debug: true` in your `Sentry.init` options. Not saying that this is ideal but that would be another way to debug the SDK if something isn't working as expected.
