### ISSUE TITLE
Add images to Product docs for Session Replay

### ISSUE THREAD

**Issue by ryan953** [getsentry/sentry-docs#6374]
All Replay product doc screenshots are in this Google Drive album: https://drive.google.com/drive/folders/1Z6MMOqDzsq2tuGHnkfrH15vV6RpNgFBE

- [ ] On [Session Replay](https://docs.sentry.io/product/session-replay/), insert `Replay - Timeline Scrub.jpg` before "What is a Replay?"

- [ ] On [Replay Page and Filters](https://docs.sentry.io/product/session-replay/replay-page-and-filters/), insert `Replay - Index Filters.jpg` after "Activity" bullet point

- [ ] On [Replay Details](https://docs.sentry.io/product/session-replay/replay-details/), insert `Replay - Context.jpg` after the first paragraph

- [ ] On [Replay Details](https://docs.sentry.io/product/session-replay/replay-details/), insert `Replay - Share.jpg` after the "Share Replays" section

- [ ] On [Replay Details](https://docs.sentry.io/product/session-replay/replay-details/), insert `Replay - Delete Button.jpg` after the "Delete Replays" section

- [ ] On [Replay Details](https://docs.sentry.io/product/session-replay/replay-details/), insert `Replay - Tags.jpg` after the "Tags" section

**Comment by ryan953** [comment]
@jas-kas I see two folders in the gdrive: "Plain" and "With Highlights" 

Which set of images should we use?

**Comment by Jesse-Box** [comment]
@jas-kas @ryan953 

### Session Replay (After Title)
![Hero](https://user-images.githubusercontent.com/6508377/222396445-2eb76e89-c9e4-4398-a7ac-96b6e24028ce.png)

### Session Replay > What is a Replay?
![DOM State](https://user-images.githubusercontent.com/6508377/222394898-6d0d7ee5-6476-43be-8058-408c8d4c2a61.png)

### Replay Page and Filters > Filtering Replays
![Search Filters](https://user-images.githubusercontent.com/6508377/222393114-9fae56d1-d226-4550-991d-95054471bde9.png)

### Replay Details
![Page Features](https://user-images.githubusercontent.com/6508377/222391365-e0e522a5-2d29-4a6f-b9d7-f205b4a78388.png)

### Replay Detaisl > Share Replay (Before Title)
![Page Actions](https://user-images.githubusercontent.com/6508377/222391356-16600b9c-d6ec-416f-bda2-88c6a23be00f.png)

### Replay Details > Tags Section
![Tags](https://user-images.githubusercontent.com/6508377/222391371-24ba68f1-40cc-4701-bbc8-aff7f41bf5d3.png)

**Comment by ryan953** [comment]
Just noticed that some of these screens will change REALLY SOON
See: 
- https://github.com/getsentry/sentry/issues/42784
- https://github.com/getsentry/sentry/issues/44759


Will we be able to update/recreate these on the fly after those changes land?

**Comment by jas-kas** [comment]
@ryan953 

> @jas-kas I see two folders in the gdrive: "Plain" and "With Highlights"
> Which set of images should we use?

Working with Jesse to revise screenshots. We added the Plain screenshots, so Jesse can add the highlights/annotations in a more Sentry-esque way. There was a Slack convo on this in our channel but should have updated this GH ticket for visibility.

> Just noticed that some of these screens will change REALLY SOON
> See:
> https://github.com/getsentry/sentry/issues/42784
> https://github.com/getsentry/sentry/issues/44759
> Will we be able to update/recreate these on the fly after those changes land?


I think that's always a struggle with docs, the screenshots *will* go out of date and that's okay. But as long as the customer can still recognize what page you're referring to, it's fine. We can also just put this ticket in the next sprint if we want this to be the latest version of these pages.

**Comment by jas-kas** [comment]
@Jesse-Box the new screenshots look great!

One small feedback item, for the "Replay Details" page, can the Additional Context be around all the tabs? Rather than just the trace?

**Comment by Jesse-Box** [comment]
@ryan953 
> Will we be able to update/recreate these on the fly after those changes land?

If I'm given a screenshot with data, I can quickly make the annotations

**Comment by ryan953** [comment]
Another item to tweak:

Label in image:
- In the [docs copy](https://docs.sentry.io/product/session-replay/replay-details/) we have a bullet point "Replay Player: video-like..."
- The [image](https://user-images.githubusercontent.com/6508377/222391365-e0e522a5-2d29-4a6f-b9d7-f205b4a78388.png) "Replay Details " with the 4 sections (4 colors) highlights the player section in green and uses the label "Replay Playback"
- I think the label in the image should match the text on the page. I think "replay player" is the better label to choose.

**Comment by ryan953** [comment]
I threw up a PR with the existing images so we can make sure they're in the right spot, and notice other tweaks we might want along the way.

**Comment by jas-kas** [comment]
@ryan953 @Jesse-Box 

> "Replay Playback" vs "Replay Player"
> In the [/product/session-replay/replay-details/](https://docs.sentry.io/product/session-replay/replay-details/) we have a bullet point "Replay Player: video-like..."
> The [image](https://user-images.githubusercontent.com/6508377/222391365-e0e522a5-2d29-4a6f-b9d7-f205b4a78388.png) "Replay Details " with the 4 sections (4 colors) highlights the player section in green and uses the label "Replay Playback"
> I think the label in the image should match the text on the page. I think "replay player" is the better label to choose.

Good catch! It should be "Replay Player" as Ryan says.

> In the [/product/session-replay/replay-details/](https://docs.sentry.io/product/session-replay/replay-details/) the first sentence refers to both "Almost every component..." and "... breakdown of each component ..."
> I interpret this to mean the bullet points below; which are "replay player", "breadcrumbs", "timeline", "console", "network", "dom events", "trace", "issues", "memory"
> The [image](https://user-images.githubusercontent.com/6508377/222391365-e0e522a5-2d29-4a6f-b9d7-f205b4a78388.png) highlights in red "additional context" (and it'll also include the tab labels)
> Should the label say "Additional Components" instead of "Additional Context"? something something... to match with the language in the paragraph.
> in the bullet points we don't use the word component or context to describe anything, only 'list'. ie: "A list of all network requests ..."

+1, let's match the language in the intro paragraph, so "Additional Components". (Although I don't think most people would be thrown off by the use of "Additional Context")

**Comment by Jesse-Box** [comment]
@ryan953 @jas-kas here's the new screenshot with the revised highlighting and labelling

![Page Features](https://user-images.githubusercontent.com/6508377/222732500-3f4d86bd-4227-4322-a2ae-1b5e7d65af55.png)

**Comment by ryan953** [comment]
@Jesse-Box fyi there's a purple pixel on the right side of that updated image, lots of transparency around it

i cropped it out and updated the pr
