### ISSUE TITLE
Node JS: Automatic instrumentation page is not clear and includes custom instrumentation details 

### ISSUE THREAD

**Issue by rohitkataria-sentryio** [getsentry/sentry-docs#6377]
### Core or SDK?

Platform/SDK

### Which part? Which one?

Node JS

### Description

Hi team, docs for Automatic Instrumentation for Node JS feel much different that rest of the SDKs where latter almost hyper focus on richer out of the box experience. 

I am not really clear from https://docs.sentry.io/platforms/node/performance/instrumentation/automatic-instrumentation/ that what exactly would be auto instrumented as part of automatic instrumentation ? 

I think it would be http.server calls which I can make out by comment in the code snippet that says:
// enable HTTP calls tracing

This definitely feels different than how explicit or deliberate we are about specifying auto instrumentations in say JS or mobile

Further, the code snippet on that (automatic instrumentation) page goes further to suggest that reader goes ahead and create a (custom) transaction. That code block, along with “#retrieving-a-transaction” on that page, feels redundant as that is anyways repeated under custom instrumentation.

### Suggested Solution

Remove custom instrumentation snip such as:
 const transaction = Sentry.startTransaction({
...
..
and other related code.

Remove https://docs.sentry.io/platforms/node/performance/instrumentation/automatic-instrumentation/#retrieving-a-transaction since the exact same thing is present in https://docs.sentry.io/platforms/node/performance/instrumentation/custom-instrumentation/#retrieve-a-transaction and no other SDK docs talk about it in the automatic instrumentation section.

**Comment by mydea** [comment]
Hi,

yes, it is true that this is not really ideal as of now. I'll take a stab at improving these docs!
