### ISSUE TITLE
[Javascript] Unclear instructions on how to connect backend and frontend traces

### ISSUE THREAD

**Issue by rchl** [getsentry/sentry-docs#6387]
### Core or SDK?

Platform/SDK

### Which part? Which one?

Javascript

### Description

The https://docs.sentry.io/platforms/javascript/performance/connect-services/#pageload describes how to create the HTML meta tags to connect server and client traces.

There are a couple issue with it:

Code:

```html
<meta name="sentry-trace" content="{{ span.toTraceparent() }}" />
```

Question: How to get the current span? I figured from other places in the documentation that something like `sentry.getCurrentHub().getScope()?.getSpan()` will probably do but it would be good to provide clarification on this page.

---

Code

```html
<meta name="baggage" content="{{ serializeBaggage(span.getBaggage()) }}" />
```

Question: What / where is `serializeBaggage`? It doesn't appear to exist anywhere within the Sentry SDK. Is it just an abstract concept and I am supposed to just serialize with `JSON.serialize` instead? Should be clarified.

Also, the `span.getBaggage()` method of span doesn't exist in the SDK... I can neither find it in the SDK code nor in the types. Found some references to it in the changelog:

> ref(tracing): Move getBaggage() from Span to Transaction class (#5299)

But I don't seem to be able to see it on transaction object either...

### Suggested Solution

See the questions.

**Comment by lforst** [comment]
Answered here: https://github.com/nuxt-community/sentry-module/issues/500

We need to fix the docs.
