### ISSUE TITLE
Question about Sampling of Sentry Performance

### ISSUE THREAD

**Issue by Yokoi-K** [getsentry/sentry-docs#6410]
### Core or SDK?

Core Sentry product

### Which part? Which one?

Sentry Performance

### Description

I would like to use Sampling with Sentry Performance.
However, I am unclear how Sampling works.
What happens if I specify the following in my Flutter app?

```dart
  await Sentry.init((options) => options.sampleRate = 0.25);
```

https://docs.sentry.io/platforms/flutter/configuration/sampling/

Is it per transaction event or unique per user?

I don't want one user to be selected for sampling multiple times and have multiple Events sent to them, so I want to see unique sampling per user.

### Suggested Solution

Please answer me. thanks🙏

**Comment by marandaneto** [comment]
@Yokoi-K 

can you elaborate on:

> What happens if I specify the following in my Flutter app?

I'm not sure what the following means here.

Maybe take a look at the [docs](https://docs.sentry.io/product/data-management-settings/dynamic-sampling/).

**Comment by Yokoi-K** [comment]
@marandaneto 

Sorry. I forgot to write it down.

### ↓Added↓

What happens if I specify the following in my Flutter app?

```dart
  await Sentry.init((options) => options.sampleRate = 0.25);
```

https://docs.sentry.io/platforms/flutter/configuration/sampling/

**Comment by marandaneto** [comment]
@Yokoi-K Also this doc -> https://docs.sentry.io/product/accounts/quotas/#6-sdk-sample-rate
That means 25% per user-device, so only 25% of the events will be sent to Sentry, does not matter the type of event.

If you want to filter per event, See this docs https://docs.sentry.io/platforms/flutter/configuration/filtering/#filtering-error-events, if using this case, you don't need to set a `sampleRate` at all, you need to make your own sampling logic/filtering.

**Comment by silent1mezzo** [comment]
Just to add a little clarity @Yokoi-K, `sampleRate` specifically samples Errors. For transactions you'll want to set `tracesSampleRate`
