### ISSUE TITLE
Sentry CLI, incorrect include-sources flag

### ISSUE THREAD

**Issue by noviwiden** [getsentry/sentry-docs#6415]
### Core or SDK?

Platform/SDK

### Which part? Which one?

iOS

### Description

https://docs.sentry.io/platforms/apple/guides/ios/dsym/#sentry-cli

The docs specifies `--include_sources`, with an underscore.
The correct flag is `--include-sources`, with a dash.

### Suggested Solution

Change occurrences of `--include_sources` to  `--include-sources`

**Comment by marandaneto** [comment]
Thanks for reporting @noviwiden 
https://github.com/getsentry/sentry-docs/pull/6451
