### ISSUE TITLE
Side bar naming incorrect

### ISSUE THREAD

**Issue by smeubank** [getsentry/sentry-docs#6424]
### Core or SDK?

Platform/SDK

### Which part? Which one?

Seen in python, possibly others

### Description

Was trying to check docs for logging and debugging. Followed link from Google. Noticed this causes the top most name of the Docs to change from Sentry for Python to Sentry to Logging, and remains so as you click arround to other parts of the docs.

https://docs.sentry.io/platforms/python/guides/logging/

<img width="819" alt="image" src="https://user-images.githubusercontent.com/47563310/223203625-ea62b33a-d84a-45d3-89f1-4c4da3fe7c92.png">

Recording:

![Python _ Sentry Documentation](https://user-images.githubusercontent.com/47563310/223204190-70f98b01-2801-4338-8fae-0272b0ade33c.gif)

### Suggested Solution

Not sure what would cause this, but it might be confusing. 

Not a high prio problem.

**Comment by silent1mezzo** [comment]
It's because we have a section on using Python's [logging module](https://docs.python.org/3/library/logging.html). This is true for a lot of the related guides, once you get past the initial Setup docs the title feels a little weird

**Comment by smeubank** [comment]
ignore this, confused myself

**Comment by smeubank** [comment]
@silent1mezzo beat me to it :D
