### ISSUE TITLE
Add Harakiri Use Case to WSGI based Frameworks

### ISSUE THREAD

**Issue by smeubank** [getsentry/sentry-docs#6428]
### Core or SDK?

Platform/SDK

### Which part? Which one?

Python (wsgi based frameworks)

### Description

Full background in this discussion:

https://github.com/getsentry/sentry-python/discussions/1783

[Harakiri:](https://uwsgi-docs.readthedocs.io/en/latest/Glossary.html)
> A feature of uWSGI that aborts workers that are serving requests for an excessively long time.

We could consider adding to docs as use case helper

### Suggested Solution

Consider:

[React Features](https://docs.sentry.io/platforms/javascript/guides/react/features/)

We don't neccesarrily need to provide specific support but we can suggest apporaches that may work for many users

**Comment by untitaker** [comment]
uwsgi kills the process if it takes too long. the sdk cannot instrument this unless we build something sophisticated. if we do something like "report error shortly before uwsgi kills the process", reliability of the transport is questionable imo. but also, you can just setup a metric alert for when there's a transaction that takes too long. you don't need to spend the user's errors quota on it

**Comment by smeubank** [comment]
> the sdk cannot instrument this unless we build something sophisticated

the idea is not to add some auto-instrumentation. Just add documenation about how a user could handle this if they want to. See the related discussion for how this user handled it, and there have been some blog posts. It is more about having a section in the docs to help guide users who may have similar wants. The user must set it up themselves but we can save them from searching around to figure it out

**Comment by cleptric** [comment]
@antonpirker You may add this to our backlog.

**Comment by antonpirker** [comment]
No, it is not that important yet.
