### ISSUE TITLE
[Keyboard Shortcuts] Needs More Documentation

### ISSUE THREAD

**Issue by souredoutlook** [getsentry/sentry-docs#6491]
### Core or SDK?

Core Sentry product

### Which part? Which one?

n/a

### Description

Sentry provides keyboard shortcuts in various contexts, for example, when completing search in the issue stream:

![image](https://user-images.githubusercontent.com/76002357/225934330-353d4a9e-735d-4c5b-a122-d5155ec848df.png)

or at any given time using cmd + K to bring up a general search:

![image](https://user-images.githubusercontent.com/76002357/225934499-bbe791e7-ff1b-46c7-a14f-bfe18d31fc82.png)

This isn't well documented in a central location.

### Suggested Solution

It would be great if we could document keyboard shortcuts in a central location.

**Comment by lizokm** [comment]
We could add a page to docs, but I would need someone to help me compile a list of keyboard shortcuts. Any idea who might be a good person to ask?

**Comment by souredoutlook** [comment]
Hey @lizokm I am not sure which stakeholders are best to consult. Might want to ask in #discuss-small-questions. Different teams have added shortcuts over the years but they don't seem to be documented anywhere.

**Comment by igorsantos07** [comment]
I second this idea. I'm doing my first review on a list of several issues, and a way to "mark as reviewed" through the keyboard would be handy. I tried pressing `?` to no avail - this is the default(?) shortcut-to-see-shortcuts, at least that I've seen around the web.

**Comment by stephanie-anderson** [comment]
I think that would make more sense to have in-product, not somewhere outside in our docs.
