### ISSUE TITLE
Manage Your Transaction Quota documentation page refers to nonexistent UI

### ISSUE THREAD

**Issue by rulatir** [getsentry/sentry-docs#6498]
### Core or SDK?

Core Sentry product

### Which part? Which one?

[? documentation ?]

### Description

[This section](https://docs.sentry.io/product/accounts/quotas/manage-transaction-quota/#how-can-i-see-a-breakdown-of-incoming-events) of the Manage Your Transaction Quotas documentation page mentions an interface element referred to as "Usage Stats tab". I find this element to be nonexistent. Either the documentation is outdated, or it refers to features available only in higher plans without clearly indicating that this is the case.

### Suggested Solution

If the page is outdated, update it.

If the page refers to features available only in higher plans, this should be clearly indicated in an emphasized block of text at the very top of the page.

**Comment by lizokm** [comment]
Thanks so much for pointing this out and apologies for the frustration! We've added a clarifying note to the section that you have to have a Team, Business, or Enterprise plan for this tab to be visible.
