### ISSUE TITLE
Warning about callback for with-scope in python sdk but no mention of what callback is

### ISSUE THREAD

**Issue by RileyEv** [getsentry/sentry-docs#6521]
### Core or SDK?

Platform/SDK

### Which part? Which one?

Python SDK

### Description

The warning at the bottom of this page https://docs.sentry.io/platforms/python/enriching-events/scopes/#local-scopes is not very clear. It refers to a callback with no link to what that is anywhere else on that page. On initial glance it could be confused for the code block inside the context manager, which would make you think there are very worrying side-effects related to using with-scope. It took some digging to work out that it was actually an optional parameter to the `push_scope` function.

> Important
Any exceptions that occur within the callback function for with-scope will not be caught, and all errors that occur will be silently ignored and not reported.

### Suggested Solution

Either demonstrate the callback on the page, or link to what the callback means.

**Comment by szokeasaurusrex** [comment]
Closing, as the warning referenced in this issue has already been removed from the [linked page](https://docs.sentry.io/platforms/python/enriching-events/scopes/#local-scopes)
