### ISSUE TITLE
JUL does not support MDC

### ISSUE THREAD

**Issue by wsargent** [getsentry/sentry-docs#6539]
### Core or SDK?

Core Sentry product

### Which part? Which one?

java.util.logging

### Description

In https://docs.sentry.io/platforms/java/guides/jul/usage/advanced-usage/ the MDC page links to Logback, but is about java.util.logging.  There isn't an MDC construct in JUL, and if Logback is being used then it could not be used with JUL.  It also refers to Logback/Log4j2 so that doesn't clear things up:

> When any SLF4J implementation supporting MDC is on the classpath (for example Logback, Log4j2), it’s possible to add extra data to events thanks to [the MDC system](https://logback.qos.ch/manual/mdc.html)

### Suggested Solution

I don't think this information on this page works and it should probably be deleted.

**Comment by adinauer** [comment]
Hello @wsargent, please take a look at our [JUL sample](https://github.com/getsentry/sentry-java/blob/191ca19e52ec121affacc3740995c5ab48910ee6/sentry-samples/sentry-samples-jul/src/main/java/io/sentry/samples/jul/Main.java). You can see in the sample that you need `slf4j` as an additional dependency for making MDC work with JUL (but no dependency on logback or similar). The sample does work, I just tested it, it successfully adds `requestId` and `userId` from MDC to the event. Hope this helps.

**Comment by will-sargent-eero** [comment]
I can see that!  It looks like it's using BasicMDCAdapter under the hood.

https://www.slf4j.org/api/org/slf4j/helpers/BasicMDCAdapter.html

Can we change the docs to add a link to the adapter and mention SLF4J as providing the feature?

**Comment by wsargent** [comment]
More precisely, the `slf4j-jdk14` package binding to JUL.

**Comment by adinauer** [comment]
@wsargent sounds good. Opened a PR to change the docs.
