### ISSUE TITLE
Highlight Source Context Feature

### ISSUE THREAD

**Issue by philipphofmann** [getsentry/sentry-docs#6553]
## Project

Use the [project issue](https://github.com/getsentry/team-sdks/issues/17) or directly go to the 
- [Project board](https://github.com/orgs/getsentry/projects/133)
- [Task list](https://github.com/orgs/getsentry/projects/133/views/3)

---

## Old info

Check if the upload debug image page mentions the [source context](https://docs.sentry.io/platforms/apple/data-management/debug-files/source-context/), ideally with a screenshot to encourage more users to use it. The [Apple docs](https://docs.sentry.io/platforms/apple/dsym/#sentry-cli) already mention source context, but not with a screenshot.

Point out the feature in the wizard. We still need to align on how to do this, but the minimum should be pointing it out as the Apple wizard does 
https://github.com/getsentry/sentry-docs/blob/d2e5dfa06f57b5001ebf30cfce5eda45223e516a/src/wizard/apple/ios.md?plain=1#L68

```[tasklist]
### Java/Android
- [ ] https://github.com/getsentry/sentry-docs/issues/6677
- [ ] https://github.com/getsentry/sentry-docs/issues/7134
- [ ] https://github.com/getsentry/sentry-docs/pull/7152
- [ ] https://github.com/getsentry/sentry-android-gradle-plugin/pull/509
- [ ] https://github.com/getsentry/sentry-docs/pull/7086
- [ ] https://github.com/getsentry/sentry-docs/pull/7100
- [ ] https://github.com/getsentry/sentry-docs/pull/7316
```

```[tasklist]
### iOS
- [ ] https://github.com/getsentry/sentry-docs/pull/7286
```

```[tasklist]
### React Native
- [ ] https://github.com/getsentry/sentry-react-native/issues/3096
- [ ] https://github.com/getsentry/sentry-docs/pull/7143
- [ ] https://github.com/getsentry/sentry-docs/pull/7144
- [ ] https://github.com/getsentry/sentry-docs/pull/7151
- [ ] https://github.com/getsentry/sentry-docs/pull/7154
- [ ] https://github.com/getsentry/sentry-docs/pull/7217
```

```[tasklist]
### Dart/Flutter
- [X] https://github.com/getsentry/sentry-dart/issues/1370
- [ ] https://github.com/getsentry/sentry-docs/pull/7157
- [ ] https://github.com/getsentry/sentry-docs/pull/7154
```

--- 

## Other relevant items

Not part of the initial roadmap, tbd if/when these are tackled.

```[tasklist]
### .NET
- [ ] Highlight Source Context Feature
```

```[tasklist]
### Unity
- [ ] Highlight Source Context Feature
```

**Comment by marandaneto** [comment]
@markushi it is for NDK tho, https://github.com/getsentry/sentry-dart/issues/1370, `uploadNativeSymbols` flag, so it is still needed.

**Comment by marandaneto** [comment]
@krystofwoldrich I left some comments at https://github.com/getsentry/sentry-docs/pull/7144
We can be more explicit about the Source context feature in RN.

Look at https://github.com/getsentry/sentry-docs/pull/7157
* Add source context with a link to the feature list
* Enable src/platforms/common/data-management/debug-files/index.mdx and tweak if necessary
* Add a section exclusively to source code context instead of the "Uploading With Xcode" section.
* Add section to the wizard as well

This applies to all SDKs, with all these changes, it will be hard for people to miss this feature, right now it's a bit hidden still even after the RN changes (although it works by default for JS events).

**Comment by stefanosiano** [comment]
Updates for Android:
There was a [notion doc](https://www.notion.so/sentry/Docs-restructuring-50ad264dfa8c4d3e910424e3554c4efa?pvs=4) to discuss changes.
Here are the docs PRs:
https://github.com/getsentry/sentry-docs/pull/7299 (small cleanup of manual config)
https://github.com/getsentry/sentry-docs/pull/7301 (reorganization of the side bar with creation of `Enhance Error Reporting` section)
https://github.com/getsentry/sentry-docs/pull/7316 (added mentions of source context in few places)

**Comment by kahest** [comment]
closing - this has been superseded by https://github.com/getsentry/team-sdks/issues/17
