### ISSUE TITLE
User Feedback is available for React Native

### ISSUE THREAD

**Issue by rohitkataria-sentryio** [getsentry/sentry-docs#6569]
### Core or SDK?

Core Sentry product

### Which part? Which one?

https://docs.sentry.io/product/user-feedback/

### Description

User Feedback API is available for React Native at - https://docs.sentry.io/platforms/react-native/enriching-events/user-feedback/

However, the product page shows React Native as one of the SDKs for which it is not. 

### Suggested Solution

Remove React Native SDK from https://docs.sentry.io/product/user-feedback/#set-up

**Comment by bruno-garcia** [comment]
https://github.com/getsentry/sentry-docs/pull/6471
