### ISSUE TITLE
Search isn't activated on typing in Search box for some users

### ISSUE THREAD

**Issue by shanamatthews** [getsentry/sentry-docs#6604]
### Steps to Reproduce

1. Open any page on https://docs.sentry.io/
2. Click in the search box
3. Start typing

This is 100% repro for Emily Vince, but Shana & Jonas couldn't repro this.

### Expected Result

Expected: 

Dropdown appears with search results
<img width="522" alt="Screenshot 2023-04-05 at 1 50 21 PM" src="https://user-images.githubusercontent.com/3520671/230208354-ebfa716f-99bf-4da0-8a08-cc83f08adbe1.png">

New network calls to Algolia show up after typing each character.

### Actual Result

Actual: 

No popup or results appear when typing. No network calls to Algolia appear in devtools

**Comment by shanamatthews** [comment]
We think this happens when the javascript on the page crashes. Here's what we believe is an example of the issue in Sentry: https://sentry.sentry.io/issues/3622183821/?project=1267915&query=is%3Aunresolved&referrer=issue-stream&stream_index=12

it doesn't have any useful info in the stack trace though :(

**Comment by a-hariti** [comment]
Could you please make sure the issue is still relevant and provide a concrete repro if applicable @shanamatthews ?
