### ISSUE TITLE
Documentation doesn't explain how App Hanging code works

### ISSUE THREAD

**Issue by JCTec** [getsentry/sentry-docs#6614]
### Problem Statement

I was trying to understand how the App Hanging detection integration works in Sentry, but I couldn't find any explanation in the [documentation](https://docs.sentry.io/platforms/apple/configuration/app-hangs/). While searching for more information, I came across [a GitHub thread](https://github.com/getsentry/sentry-cocoa/discussions/2715) that mentioned how the AppHang logic works, but this isn't explained in the documentation.

### Solution Brainstorm

It will be helpful to have an explanation of how Sentry reports the traces when an AppHang is detected and I believe that providing this information in the documentation would help users better understand how Sentry detects and reports app hangs. 

Thank you for considering my feedback.

**Comment by philipphofmann** [comment]
@JCTec, if I got it right, you would like to have the technical explanation of how the SDK enqueued a work item to the main thread in the [docs](https://docs.sentry.io/platforms/apple/configuration/app-hangs/)?

**Comment by JCTec** [comment]
> @JCTec, if I got it right, you would like to have the technical explanation of how the SDK enqueued a work item to the main thread in the [docs](https://docs.sentry.io/platforms/apple/configuration/app-hangs/)?
> 
> So basically the following:
> 
> > That is due to how our AppHang logic works. We enqueue an item to execute on the main threads loop and check if it doesn't get executed in a defined time we consider an app hang is ongoing. Getting the exact stacktrace works pretty well if the app is completely stuck, but if the run loop is extremely busy with different code locations, our logic might fire a bit too late and we give you a stacktrace that is not 100% correct.

Yes! Sorry for the delay, basically copying and pasting that information into the documentation will be helpful.
