### ISSUE TITLE
Unclear difference between Add Context and Identify Users

### ISSUE THREAD

**Issue by mafreud** [getsentry/sentry-docs#6628]
### Core or SDK?

Platform/SDK

### Which part? Which one?

Flutter sdk

### Description

In the Add Context, I think the example is not clear. Since Sentry has [Context Interface](https://develop.sentry.dev/sdk/event-payloads/contexts/) page, it would be better to include context interface page in Add Context example.

### Suggested Solution

Based on "Contexts Interface" page, in my opinion, the example of Add Context for Flutter could be changed from
```dart
import 'package:sentry/sentry.dart';

final character = {
  'name': 'Mighty Fighter',
  'age': 19,
  'attack_type': 'melee',
};
Sentry.configureScope((scope) => scope.setContexts('character', character));
```
https://docs.sentry.io/platforms/flutter/enriching-events/context/
to
```dart
import 'package:sentry/sentry.dart';

final deviceContext = {
  'name': 'Tim's iPhone',
  'family': 'iPhone',
  'orientation': 'portrait',
};
Sentry.configureScope((scope) => scope.setContexts('deviceContext', deviceContext));
```
What do you think?

**Comment by kahest** [comment]
Hi @mafreud, thank you for your suggestion! 

The example for adding a custom context is chosen that way intentionally, to show that this mechanism can be used to add arbitrary data. The list of common contexts generally used by SDKs is linked directly under the code snippet.
