### ISSUE TITLE
Improve docs on reducing noise

### ISSUE THREAD

**Issue by smeubank** [getsentry/sentry-docs#6644]
### Core or SDK?

Platform/SDK

### Which part? Which one?

Node but any server side would apply

### Description

I have FE and BE node service in EC2 on AWS with elastic beanstalk and some load balancer. There is a health check that calls my service. it is not calling a configurable endpoint. Regardless my issue is that doesn't bother me, I just want to ignore transactions generated due to those requests.

it's not easy to answer some simple questions

1. How many events do I get per transaction /endpoint
2. How many events came with header `x-agent: ELBalancerxyz`
3. Do I need discover to search this?
  - I see Header on transaction detail, I as a new user can understand I can search by tags, and some context but not all. Is header information a context?
4. Not clear how to find what context is available in SDK for [samplerContext](https://docs.sentry.io/platforms/node/configuration/sampling/#default-sampling-context-data)

Outcome: I set `tracesSampleRate: 0.0`  and rely on inheriting the sampling decision of my FE and cut out any noise going on from my BE service. Alternatively I could use the `parentSampled: true` this does arguable the same as sample rate 0. But as a "new user" I'm already very frustrated and confused, and probably made more jumps in logic than someone normally might be able to. Mind you my quota was also depleted fast enough I was only able to debug this as an employee

And I still don't have answers to many of the questions above

### Suggested Solution

Docs for what searchable should be more clear

How can I find counts of events per transaction? I can see the tpm is much higher and total events per project but this is scattered in the product, and not in any default view.

Docs for sampleContext - i see the default. What else is there and how do I find out? Can I see this in debug mode?

I'd like to be able to filter by specific user-agent without resorting to custom instrumentation

**Comment by nanoburd** [comment]
There is a metric for the TPM by transaction on the performance landing page. Does this work for this use case?

Why do you need to filter by the header?

**Side question:** Is there anytime where the total count of all events you send sentry is relevant for fixing a performance problem? Generally we felt it wasn't information that was needed so we just kept TPM.

**Comment by mydea** [comment]
I'm going to close this as it is rather old, feel free to reopen if still relevant.
