### ISSUE TITLE
(PHP) Add documentation for ignore_errors and ignore_transactions

### ISSUE THREAD

**Issue by smeubank** [getsentry/sentry-docs#6648]
This adds proper docs for ignoreErrors & ignoreTransactions as ways to filter events.

as described in develop, and if there are platform specific to not from implementation

https://develop.sentry.dev/sdk/features/#event-sampling

related changes performed in [JS Docs](https://github.com/getsentry/sentry-docs/pull/6642)

**Comment by shanamatthews** [comment]
Looks like this is a task for ya'll to add PHP docs for `ignoreErrors` & `ignoreTransactions`?

**Comment by smeubank** [comment]
@cleptric only created a docs issue for PHP. Let me know if there's something I leave out or questions

**Comment by stephanie-anderson** [comment]
Documentation for `ignoreErrors` & `ignoreTransactions` also exist for Laravel and Symfony. Will close this issue
