### ISSUE TITLE
Highlight Source Context Feature for Android (NDK)

### ISSUE THREAD

**Issue by romtsn** [getsentry/sentry-docs#6677]
Check if the upload debug image page mentions the [source context](https://docs.sentry.io/platforms/apple/data-management/debug-files/source-context/), ideally with a screenshot to encourage more users to use it. The [Apple docs](https://docs.sentry.io/platforms/apple/dsym/#sentry-cli) already mention source context, but not with a screenshot.

Point out the feature in the wizard. We still need to align on how to do this, but the minimum should be pointing it out as the Apple wizard does

**Comment by marandaneto** [comment]
@stefanosiano would you like to address this one as well?
The source context info is there but its missing the one for the NDK bits
https://docs.sentry.io/platforms/android/enhance-errors/source-context/
We have to highlight this for NDK, See https://docs.sentry.io/platforms/android/configuration/gradle/ and the `uploadNativeSymbols` flag.
