### ISSUE TITLE
Links on https://docs.sentry.io/product/data-management-settings/event-grouping/ show 404

### ISSUE THREAD

**Issue by kgarlikowski** [getsentry/sentry-docs#6678]
### Core or SDK?

Core Sentry product

### Which part? Which one?

Event grouping

### Description

Links under bullet 2 and 3 on https://docs.sentry.io/product/data-management-settings/event-grouping/ point to 404 page.

### Suggested Solution

Links should point to proper resources.

**Comment by lizokm** [comment]
Hi there! I'm unable to reproduce this. All links are working for me. Could you attach a screenshot?
Are the "fingerprint rules" and "stack trace rules" links the ones not working for you?

![Screenshot 2023-04-20 at 12 38 05 PM](https://user-images.githubusercontent.com/26800704/233470567-00dad72a-f566-47b8-9d1d-3d35a35ba841.png)

**Comment by kgarlikowski** [comment]
@lizokm Correct, those were not working, but now everything works just fine. Something must have changed.
