### ISSUE TITLE
Java (Logback integration) Configuration Docs point use deprecated method as example

### ISSUE THREAD

**Issue by tyler-evocalize** [getsentry/sentry-docs#670]
The example used for breadcrumbs still shows the use of the method `Sentry.record` which has been deprecated. See docs below:

```
void logWithBreadcrumbs() {
        // Record a breadcrumb that will be sent with the next event(s),
        // by default the last 100 breadcrumbs are kept.
        Sentry.record(
            new BreadcrumbBuilder().setMessage("User made an action").build()
        );

        // This sends a simple event to Sentry
        logger.error("This is a test");
    }
```

**Comment by marandaneto** [comment]
@maciejwalkowiak should we close this?

**Comment by maciejwalkowiak** [comment]
Yes please.

**Comment by marandaneto** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated. There's a large chance that this issue has been solved since.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.
Cheers!
