### ISSUE TITLE
Bad link on react-native troubleshooting page

### ISSUE THREAD

**Issue by evanpurkhiser** [getsentry/sentry-docs#6701]
### Core or SDK?

Core Sentry product

### Which part? Which one?

React native

### Description

https://docs.sentry.io/platforms/react-native/troubleshooting/#app-start-numbers-are-too-high-to-be-accurate

This page has a bad link to "[see the troubleshooting page for the iOS SDK](https://docs.sentry.io/platforms/apple/guides/ios/troubleshooting/)".

### Suggested Solution

Not sure what the right place is?

**Comment by marandaneto** [comment]
@evanpurkhiser this link should have led you to https://docs.sentry.io/platforms/apple/troubleshooting/#wrong-app-start-data
Linters didn't detect the change because it was the whole address instead of the relative link.
