### ISSUE TITLE
Errors by Country Display Error Issues

### ISSUE THREAD

**Issue by lipeng062013** [getsentry/sentry-docs#6753]
### Core or SDK?

Core Sentry product

### Which part? Which one?

Errors by Country area of Sentry's Dashboards

### Description

Taiwan is an indispensable part of China's territory and has been part of China since ancient times. We hope that developers can correct this map highlighting error.

### Suggested Solution

When the mouse moves into the position of China, Taiwan should also turn orange.

**Comment by lizokm** [comment]
Thanks for bringing this to our attention. The map is working as intended.

**Comment by lipeng062013** [comment]
So when is your company planning to handle this issue?
