### ISSUE TITLE
Android SDK's 'User Feedback' session does not describe `crashedLastRun` capability

### ISSUE THREAD

**Issue by cstavitsky** [getsentry/sentry-docs#6765]
### Core or SDK?

Platform/SDK

### Which part? Which one?

Android SDK

### Description

We added a `crashedLastRun` feature to Android [here](https://github.com/getsentry/sentry-java/issues/1125), however it is not documented.

The equivalent iOS feature is documented already at the [bottom of the User Feedback page](https://docs.sentry.io/platforms/apple/enriching-events/user-feedback/) for iOS.

### Suggested Solution

Add documentation and example for Android, just like we have for iOS.

**Comment by kahest** [comment]
@cstavitsky https://github.com/getsentry/sentry-java/issues/1125 ([PR](https://github.com/getsentry/sentry-java/pull/1739)) only added a marker that users can evaluate to find out if the last run crashed (called `isCrashedLastRun`). We have [another issue open to provide the Sentry event id of the crash](https://github.com/getsentry/sentry-java/issues/2560) that occurred on the last run, which should suffice for linking the user feedback to the event.
