### ISSUE TITLE
Replay: HTTP detail product docs

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-docs#6780]
### Core or SDK?

Core Sentry product

### Which part? Which one?

None

### Description

SDK/platform docs are getting added through: https://github.com/getsentry/sentry-docs/pull/6735

### Suggested Solution

Add product docs

**Comment by ryan953** [comment]
This is done.

We mention network req/resp here: https://docs.sentry.io/product/session-replay/replay-details/#:~:text=HTTP%20request%20body%20and%20headers.
and here: https://docs.sentry.io/platforms/javascript/session-replay/configuration/#network-details
