### ISSUE TITLE
incorrect link mapping

### ISSUE THREAD

**Issue by rohitkataria-sentryio** [getsentry/sentry-docs#6791]
### Core or SDK?

Platform/SDK

### Which part? Which one?

Node

### Description

Landing page: https://docs.sentry.io/platforms/node/configuration/integrations/default-integrations/

On the right sidebar, clicking on
-- ContextLines routes to #onunhandledrejection 
-- LocalVariables routes to #contextlines 
-- Modules routes to #localvariables 

### Suggested Solution

Mapping should be correct so we can pass on the exact/correct sub-links to our customers.

**Comment by mydea** [comment]
Hmm, this seems to be working for me locally 🤔 Somehow the IDs are incorrectly generated for the headings - they are actually also incorrect in the page itself, so it's not a problem with the sidebar but with the markup:
<img width="404" alt="image" src="https://user-images.githubusercontent.com/2411343/236134608-81d0da1b-6ecb-4deb-ac41-3167bc96cddc.png">

Maybe we "just" need to regenerate the page somehow...?

**Comment by mydea** [comment]
So I think it is working now again - not sure what happened there. @getsentry/product-owners-docs not sure if you want to take another look at what happened there, other than this I think we can close this?

**Comment by shanamatthews** [comment]
I think this is the same issue as #4580 (which also has some other dupes/related problems listed in the issue)

**Comment by shanamatthews** [comment]
There's a running theory that upgrading Gatsby will fix all these hydration issues, and we did deploy our Gatsby upgrade from 2 -> 3, so this *might* be fixed? 

The bug also seems to be intermittent though so I'll leave this open for now.
