### ISSUE TITLE
More detail about the inner workings of OpenAI integration

### ISSUE THREAD

**Issue by wanaryytel** [getsentry/sentry-docs#6806]
### Core or SDK?

Core Sentry product

### Which part? Which one?

Sentry issue page OpenAI integration documentation  
https://docs.sentry.io/product/issues/issue-details/ai-suggested-solution/

### Description

I was hoping to get an understanding of
- what product from OpenAI is being used to generate the AI insights. Is it OpenAI API or Chat GPT or something different? 
- what data is shared exactly with OpenAI?
- what is the data privacy & security policy that OpenAI has towards Sentry? Does using this feature compromise our company's data more than just using Sentry and in which way?

### Suggested Solution

I don't know the answers to these questions but I think those answers would be really useful for more people than just me.

**Comment by chadwhitacre** [comment]
Sorry for the noise @wanaryytel, trying to get this in front of the right people (and working through some wrinkles with [a significant, hot-off-the-press bot change](https://github.com/getsentry/team-ospo/issues/126) 😅).

**Comment by priscilawebdev** [comment]
Thanks for creating this issue @wanaryytel. I have added it to our backlog and will soon get back to you  😉

**Comment by stellar-gs** [comment]
Also looking for this info! In particular, Open AI's [data usage policy](https://openai.com/policies/api-data-usage-policies) states:

```
OpenAI will not use data submitted by customers via our API to train or improve our models, unless you explicitly decide to share your data with us for this purpose. You can [opt-in to share data](https://docs.google.com/forms/d/e/1FAIpQLSevgtKyiSWIOj6CV6XWBHl1daPZSOcIWzcUYUXQ1xttjBgDpA/viewform).
```

Does opting into this feature in Sentry mean that, by extension, we're sharing our data with OpenAI to train or improve their models? Or will it simply be limited to prompts passed to OpenAI that are retained for 30 days per:

```
Any data sent through the API will be retained for abuse and misuse monitoring purposes for a maximum of 30 days, after which it will be deleted (unless otherwise required by law).
```

**Comment by ale-cota** [comment]
Hi @wanaryytel and @stellar-gs! Thanks for bringing up these questions and sorry it took a while to get to this issue. To answer your questions:

- Q: what product from OpenAI is being used to generate the AI insights. Is it OpenAI API or Chat GPT or something different?
  - A: the Open AI API
- Q: what data is shared exactly with OpenAI?
  - A: The event data that gets sent is message, platform, exception type, exception mechanism, exception value and the exception’s stack trace 
- Q: what is the data privacy & security policy that OpenAI has towards Sentry? Does using this feature compromise our company's data more than just using Sentry and in which way? + Does opting into this feature in Sentry mean that, by extension, we're sharing our data with OpenAI to train or improve their models?
  - A: No, it does not. The event data that is sent will not be used to train their AI models.

We've added some more information and restructured the [docs page](https://docs.sentry.io/product/issues/issue-details/ai-suggested-solution/) to hopefully make this clearer.
