### ISSUE TITLE
Style lint making empty commits

### ISSUE THREAD

**Issue by mydea** [getsentry/sentry-docs#6837]
### Steps to Reproduce

I made a PR, and style lint made a bunch of empty commits "fixing" stuff:

<img width="372" alt="image" src="https://user-images.githubusercontent.com/2411343/236211607-0b89868d-45ba-40c4-884d-35fae48cbd93.png">

Some commits are fixing a single file, others seem to fix no file at all.

### Expected Result

There should be max. 1 style lint commit, or at least no empty style lint commits.

### Actual Result

Many commits, some of them seem empty.

**Comment by shanamatthews** [comment]
fixed now, feel free to reopen if we break it again
