### ISSUE TITLE
Add SvelteKit Onboarding Wizard Docs

### ISSUE THREAD

**Issue by Lms24** [getsentry/sentry-docs#6843]
### Core or SDK?

Platform/SDK

### Which part? Which one?

SvelteKit

### Description

Now that docs are merged (#6808), we should create onboarding wizard docs

### Suggested Solution

* general onboarding
* replay onboarding
* profiling onboarding (?)

**Comment by shanamatthews** [comment]
Just double checking you synced with @priscilawebdev on the plan & timing to move wizard docs to the product repo: getsentry/sentry#47470

**Comment by Lms24** [comment]
Yes, Priscila is going to move the wizard next week. I'll open a PR tomorrow.
