### ISSUE TITLE
Use Loader Script instead of @sentry/gatsby

### ISSUE THREAD

**Issue by mydea** [getsentry/sentry-docs#6884]
We are currently using `@sentry/gatsby` in the docs. Since we stopped using the Loader Script in getsentry: https://github.com/getsentry/getsentry/pull/10465 we should instead start using it for the docs, in order to dogfood this.

We should be able to cover everything we need for the docs with the Loader Script, including errors, performance and replay. We still dogfood @sentry/gatsby for the develop docs.

**Comment by HazAT** [comment]
Consider using new webpack v2 + debugIDs for Source Maps
