### ISSUE TITLE
Troubleshooting entry on docs re: SDK degrading performance

### ISSUE THREAD

**Issue by jas-kas** [getsentry/sentry-docs#6887]
Mention appropriate SDK version to get the [latest fix for Performance Overhead](https://github.com/getsentry/sentry-javascript/pull/7917) on our [SDK Troubleshooting docs](https://docs.sentry.io/platforms/javascript/session-replay/troubleshooting/).

This entry can evolve as more Performance Issue fixes come to light and we update the SDK version.

**Comment by billyvg** [comment]
@bruno-garcia I've added docs on `mutationLimit` here: https://github.com/getsentry/sentry/issues/50147

Maybe we can talk about optimizing large lists in this section as an example? (just random link i found for angular: https://www.thecodecampus.de/blog/optimize-the-performances-of-large-lists-in-your-angular-application/)

**Comment by bruno-garcia** [comment]
I also added an entry to the breadcrumb: https://github.com/getsentry/sentry-docs/pull/7109

![image](https://github.com/getsentry/sentry-docs/assets/1633368/59d8d308-53b1-425e-9645-481190d99341)

In the event folks get confused with that this actually means, and what to do about it
