### ISSUE TITLE
Replay on Backend errors: Product and SDK documentation

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-docs#6890]
Sentry is able to show a Replay of the web frontend to any error event involved in a trace. The requirements are that backend SDKs are supported, and on  a minimum supported version:

* https://github.com/getsentry/team-replay/issues/70

And since today tracing requires performance monitoring. Performance must be enabled. 

### Product docs

The breadcrumbs section in Errors hint Replay. We should add a screenshot with a Replay in there and explicitly note that backend events can also show it: https://docs.sentry.io/product/issues/issue-details/error-issues/?original_referrer=https%3A%2F%2Fdocs.sentry.io%2F#breadcrumbs

Same for the Issues section: https://docs.sentry.io/product/issues/issue-details/?original_referrer=https%3A%2F%2Fdocs.sentry.io%2F#tabs

### SDK docs

Mention on supported Web backend SDKs that if they have a FE, adding Session Replay will allow them to see the impact of issues on their users via SR.

### Part of Epic

* https://github.com/getsentry/sentry/issues/45529

**Comment by vivianyentran** [comment]
Documented here: https://docs.sentry.io/product/session-replay/getting-started/#replays-for-backend-errors
