### ISSUE TITLE
Remove: Artefacts vs release bundles 

### ISSUE THREAD

**Issue by smeubank** [getsentry/sentry-docs#6900]
- remove this [paragraph](https://docs.sentry.io/platforms/javascript/sourcemaps/#artifact-vs-release-bundles)
this will be confusing and most users simply don't need to know

<img width="740" alt="image" src="https://github.com/getsentry/team-webplatform-meta/assets/47563310/d34715bf-b977-4457-a8c5-8f8e12ef3974">

- renaming what is artifacts page to not talk about release bundles
- upload with debug ID is a sub page of trouble shooting we don't need to put that on a top level and present users with this complexity unless they need it.
- readding the image to the main page to explain why it helps in product

**Comment by ale-cota** [comment]
I believe we can close this with Ricky's PR from yesterday, right?
