### ISSUE TITLE
App Hang documentation missing for React Native

### ISSUE THREAD

**Issue by cstavitsky** [getsentry/sentry-docs#6902]
### Core or SDK?

Platform/SDK

### Which part? Which one?

React Native SDK

### Description

A customer wrote in, unsure whether App Hangs existed in React Native since they couldn't find it in the docs. There is already documentation for [App Hangs](https://docs.sentry.io/platforms/apple/configuration/app-hangs/) in the iOS docs. 

It appears that this functionality also [exists in the React Native SDK](https://github.com/getsentry/sentry-react-native/blob/c882ec195b7173581073dd6ed4e39576613ea46b/src/js/options.ts#L104C6-L124). However, there are no docs for App Hangs in React Native.

### Suggested Solution

Add App Hang docs for React Native, similar to what already exists in iOS.

**Comment by kahest** [comment]
cc @krystofwoldrich
