### ISSUE TITLE
Google Analytics is included multiple times

### ISSUE THREAD

**Issue by mydea** [getsentry/sentry-docs#6909]
### Steps to Reproduce

1. Go to e.g. https://docs.sentry.io/platforms/javascript/
2. Open browser dev tools
3. Look into `<head>`, see google analytics being loaded multiple times

### Expected Result

GA should only be loaded once (?)

### Actual Result

![image](https://github.com/getsentry/sentry-docs/assets/2411343/525b3a79-eb25-4418-bf60-9f6182a98d87)

Further below you can also see Google Tag Manager being loaded, three times actually.
Also google ads doubleclick is also loaded twice.

**Comment by scefali** [comment]
We are in the process of migrating from Universal Analytics to GA4. I suspect this is a result of that. I'll make sure that we remove the duplicates once that process is complete in mid June.
