### ISSUE TITLE
Sourcemaps documentation for TypeScript suggests information about Webpack

### ISSUE THREAD

**Issue by cdignam-segment** [getsentry/sentry-docs#6945]
### Core or SDK?

Platform/SDK

### Which part? Which one?

Node.js

### Description

I'm trying to verify that I've setup source maps correctly, but I'm seeing information for using webpack when I'm looking at Typescript documentation.

### Suggested Solution

There should be instructions that work for the most basic typescript setup. I think it's rare for a typescript setups for Node.js to use webpack

**Comment by Lms24** [comment]
This was addressed in https://github.com/getsentry/sentry-docs/pull/6956 and https://github.com/getsentry/sentry-docs/pull/6993 and we most likely forgot to close this issue. 

The [current documentation](https://docs.sentry.io/platforms/javascript/sourcemaps/uploading/typescript/) shows TSC-specific instructions again
