### ISSUE TITLE
Sidebar text wrapping is inconsistent

### ISSUE THREAD

**Issue by ceorourke** [getsentry/sentry-docs#6946]
### Core or SDK?

Core Sentry product

### Which part? Which one?

Sidebar

### Description

We hide the scrollbar when you're not hovering over it, but when there are titles that are just long enough to wrap when the sidebar is present, but not wrap when not present, this happens:

https://github.com/getsentry/sentry-docs/assets/29959063/5fd53fc1-57b6-407e-9a73-48a7c57d8694

### Suggested Solution

Pick one width and keep it consistent, or don't hide the scrollbar.

**Comment by evanpurkhiser** [comment]
![image](https://github.com/getsentry/sentry-docs/assets/1421724/30a092e6-6c5e-4b0c-8e82-313eaef0e7ce)

Due to this setting in MacOS
