### ISSUE TITLE
 getsantry[bot] style(lint): Auto commit lint changes adds changes from master

### ISSUE THREAD

**Issue by krystofwoldrich** [getsentry/sentry-docs#6964]
### Steps to Reproduce

I've opened https://github.com/getsentry/sentry-docs/pull/6951/commits and the ` getsantry[bot]` added changes from master to my PR. 

### Expected Result

The bot only lint the PR changes, and doesn't add content from other branches.

### Actual Result

The bot added changes from a different branch.

**Comment by shanamatthews** [comment]
@evanpurkhiser assigned this to you for now. Pretty annoying, but doesn't seem urgent.
