### ISSUE TITLE
Right sidebar isn't visible on mobile

### ISSUE THREAD

**Issue by shanamatthews** [getsentry/sentry-docs#6977]
### Steps to Reproduce

Open docs on mobile or on small window size

### Expected Result

right sidebar exists somewhere to choose framework guides

### Actual Result

it doesn't

### Additional Info

this blocks mobile users or users who have docs in a small window from noticing or accessing framework-specific guides

**Comment by natikgadzhi** [comment]
@shanamatthews, I was diving into Sentry docs, and I would love to help if I can, and if you're open to it! 

Looks like this behavior only happens for some languages, and not for others. Here's Rust (has the list of frameworks inline) and Ruby (only has the list of frameworks in the sidebar): 

|--|--|
|![Image](https://github.com/getsentry/sentry-docs/assets/43633/db0c55bd-b3a0-4cab-8c1b-e351f0364659)||

The difference seems to be that Rust, Javascript, Python, and PHP have their own `index.mdx` file, and all other platforms use `platforms/common/index.mdx` as a template instead.

We should be able to just render `<GuideGrid platform="php" />` in `common.mdx` perhaps, as long as we can inject the current platform name into the template, which I have zero clue how to do yet. 🙃
