### ISSUE TITLE
Session Replay documents are incorrect

### ISSUE THREAD

**Issue by speedy250** [getsentry/sentry-docs#6983]
### Core or SDK?

Core Sentry product

### Which part? Which one?

Session Replay

### Description

Documentation on the [Understanding Sessions](https://docs.sentry.io/platforms/javascript/session-replay/understanding-sessions/) page includes a section on manually starting a replay with this code:
```js
// This initializes Replay without starting any session
const replay = new Sentry.Replay({
  replaysSessionSampleRate: 0,
  replaysOnErrorSampleRate: 0,
});
```

However, the [Configuration page](https://docs.sentry.io/platforms/javascript/session-replay/configuration/) for Replay shows these two option attributes being part of the Sentry.init function. This causes confusion when trying to put these two concepts into practice

### Suggested Solution

The line `const replay = new Sentry.Replay({` should just say `const replay = new Sentry.init({`

This seems to go against what the rest of the documentation suggests, so generally the documentation on starting replays manually is lacking a thoroughness to really understand the systems and their interplay. (edited)

**Comment by billyvg** [comment]
Thanks for catching this @speedy250!
