### ISSUE TITLE
Document HTTP Client Errors (`enableCaptureFailedRequests`)

### ISSUE THREAD

**Issue by mattjohnsonpint** [getsentry/sentry-docs#6984]
### Core or SDK?

Platform/SDK

### Which part? Which one?

All SDKs

### Description

In https://github.com/getsentry/team-mobile/issues/38 - all SDKs added support for HTTP Client errors, per the developer docs here: https://develop.sentry.dev/sdk/features/#http-client-errors

However, only Apple has it documented:
- https://docs.sentry.io/platforms/apple/configuration/http-client-errors/
- https://docs.sentry.io/platforms/apple/configuration/options/#capture-failed-requests

All SDKs need to document this feature.

### Suggested Solution

If the Apple specific doc page is made generic and converted to a common page, then each SDK team can modify the examples as appropriate for their platform.

**Comment by mattjohnsonpint** [comment]
@jamescrosswell (contractor) recently completed this feature for .NET (see https://github.com/getsentry/sentry-dotnet/pull/2320) and can take a first stab at this. (Thanks James!)

**Comment by marandaneto** [comment]
@mattjohnsonpint We also have for other SDKs 
https://docs.sentry.io/platforms/dart/configuration/integrations/http-integration/ https://docs.sentry.io/platforms/android/configuration/integrations/okhttp/#http-client-errors
https://docs.sentry.io/platforms/javascript/configuration/integrations/plugin/#httpclient
They are just unified because they depend on integrations.

**Comment by jamescrosswell** [comment]
Docs on [Contributing to Docs](https://docs.sentry.io/contributing/) - meta but helpful ;-)

**Comment by mattjohnsonpint** [comment]
Ok.  So actually then, we should probably not generify the detail feature docs but rather just add new docs for .NET.  @jamescrosswell  - you can copy/past/modify the one from Apple to get started.

We do still need to make sure all platforms that expose `enableCaptureFailedRequests` on their main options class, have that option showing on the basic configuration page.  We should also add a link from there to the detail page where appropriate.

**Comment by hubertdeng123** [comment]
The bot is going crazy since it only expects one `Product Area` label. Issues like this don't seem to happen very often but seems like for now it is assigned to an owner, sorry for the noise everyone
