### ISSUE TITLE
@sentry/vite-plugin documentation is totally irrational

### ISSUE THREAD

**Issue by andylacko** [getsentry/sentry-docs#6997]
### Core or SDK?

Platform/SDK

### Which part? Which one?

@sentry/vite-plugin

### Description

using @sentry/vite-plugin 2.0.0

This is the most misleading documentation I've ever seen. No example how to setup the sourceMap paths properly, right now, my config is
```typescript
      sourcemaps: {
        assets: './dist/assets/**',
        deleteFilesAfterUpload: '**/*.js.map',
      },
```

deleting files after uploading works, at least the debugger is reporting it

`assets: './dist/assets/*.js.map'` doesn't work, although seem to me, it should be done that way

`assets: ./dist/assets/**` uploads the sourceMaps, but they are not visible in the release artefacts

Why even bothering having debugger which reports, that sourceMaps have been uploaded, when they are then displayed as 0 artefacts?

Should I try to set asset path to my javascript files or to .map files?

I have monorepo with regular vite project, no big modifications to build process, why is it so h ard to configure right?

### Suggested Solution

1 example with common vite configuration with all the paths working

**Comment by lforst** [comment]
Hi, thanks for the feedback. We updated the docs around this today.
