### ISSUE TITLE
Clarify graph ERRORS FILTERED IN THE LAST 30 DAYS (BY DAY) and update sections that use it

### ISSUE THREAD

**Issue by sdzhong** [getsentry/sentry-docs#6998]
### Core or SDK?

Core Sentry product

### Which part? Which one?

https://docs.sentry.io/product/accounts/quotas/manage-transaction-quota/#2-inbound-data-filters

### Description

Does the [Project] > Settings > Inbound Filters graph (which is titled `ERRORS FILTERED IN THE LAST 30 DAYS (BY DAY)`) show only errors filtered? Or does it show both error and transaction events filtered? When looking at filtering for Transactions docs page/section https://docs.sentry.io/product/accounts/quotas/manage-transaction-quota/#2-inbound-data-filters, we are presented a graph that is titled `ERRORS FILTERED IN THE LAST 30 DAYS (BY DAY)`: https://docs.sentry.io/static/7f414715ccf28990780b7acc86b20ed2/e9d87/manage-event-stream-03.png:
![image](https://github.com/getsentry/sentry-docs/assets/89550162/53004fcd-3c4d-4451-aaf0-211f2d6c5e35)

As a reader, I am interested in filtering about Transactions (not about Errors).

### Suggested Solution

If the https://docs.sentry.io/static/7f414715ccf28990780b7acc86b20ed2/e9d87/manage-event-stream-03.png graph only shows errors filtered, then the graph is not relevant to the docs page/section https://docs.sentry.io/product/accounts/quotas/manage-transaction-quota/#2-inbound-data-filters.

If the graph shows both error and transaction events filtered, then the title of the graph should be renamed from `ERRORS FILTERED IN THE LAST 30 DAYS (BY DAY)` to something like `ERRORS AND TRANSACTIONS FILTERED IN THE LAST 30 DAYS (BY DAY)`.

**Comment by JoshFerge** [comment]
This graph does indeed show transactions filtered as well. https://github.com/getsentry/sentry/blob/726a5ec8d74e449c6f026c18ef09d0961b4ad5fb/static/app/views/settings/project/projectFilters/projectFiltersChart.tsx#L95

**Comment by JoshFerge** [comment]
we need to update the docs screenshot here: https://docs.sentry.io/pricing/quotas/manage-transaction-quota/#2-inbound-data-filters
