### ISSUE TITLE
Improve OTel setup docs

### ISSUE THREAD

**Issue by shanamatthews** [getsentry/sentry-docs#6999]
### Core or SDK?

Platform/SDK

### Which part? Which one?

Next.js docs

### Description

This came out of a conversation with Cramer on using the new Next.js OTel feature with Sentry: https://nextjs.org/docs/pages/building-your-application/optimizing/open-telemetry

### Suggested Solution

I think we just need to make sure our docs get updated when we update the nextjs SDK to use their new OTel feature, but @AbhiPrasad should know more.

**Comment by shanamatthews** [comment]
Hey @AbhiPrasad - I wanted to make sure we didn't lose track of the feedback from Cramer on OTel + Next.js docs. Assigning this to you, since you offered to help on the slack thread.

**Comment by lforst** [comment]
@shanamatthews Abhi is ooo do you have a link to the slack thread?

**Comment by shanamatthews** [comment]
Yeah, it's super old so about to be deleted: https://sentry.slack.com/archives/CA2V2LBDL/p1682522260435059

Here's some relevant quotes:  

David Cramer
  [8:02 AM](https://sentry.slack.com/archives/CA2V2LBDL/p1682521367268089)
is the vercel hook useful to us? https://nextjs.org/docs/advanced-features/open-telemetry

[Advanced Features: Open Telemetry | Next.js](https://nextjs.org/docs/advanced-features/open-telemetry)
Learn how to instrument your Next.js app with OpenTelemetry. (85 kB)
https://nextjs.org/docs/advanced-features/open-telemetry



David Cramer
  [8:17 AM](https://sentry.slack.com/archives/CA2V2LBDL/p1682522246135369)
https://docs.sentry.io/platforms/node/ "how do i wire this up to opentelemetry"


David Cramer
  [8:17 AM](https://sentry.slack.com/archives/CA2V2LBDL/p1682522260435059)
does it automatically inject the otel stuff? i thought it was manual

David Cramer
  [1 month ago](https://sentry.slack.com/archives/CA2V2LBDL/p1682522400458559?thread_ts=1682522260.435059&cid=CA2V2LBDL)
but our docs are not good here


David Cramer
  [1 month ago](https://sentry.slack.com/archives/CA2V2LBDL/p1682522406856389?thread_ts=1682522260.435059&cid=CA2V2LBDL)
like id just assume the getting started and im done


Abhijeet Prasad
:fleur_de_lis:  [1 month ago](https://sentry.slack.com/archives/CA2V2LBDL/p1682522413538919?thread_ts=1682522260.435059&cid=CA2V2LBDL)
we do have https://docs.sentry.io/platforms/node/performance/instrumentation/opentelemetry/


David Cramer
  [1 month ago](https://sentry.slack.com/archives/CA2V2LBDL/p1682522413658999?thread_ts=1682522260.435059&cid=CA2V2LBDL)
probably worth thinking about this experience in 2023


David Cramer
  [1 month ago](https://sentry.slack.com/archives/CA2V2LBDL/p1682522415907489?thread_ts=1682522260.435059&cid=CA2V2LBDL)
when we have multi products


David Cramer
  [1 month ago](https://sentry.slack.com/archives/CA2V2LBDL/p1682522436705929?thread_ts=1682522260.435059&cid=CA2V2LBDL)
(this is obv not a node specific thing)


Abhijeet Prasad
:fleur_de_lis:  [1 month ago](https://sentry.slack.com/archives/CA2V2LBDL/p1682522465591429?thread_ts=1682522260.435059&cid=CA2V2LBDL)
We just haven’t gotten to updating this for next.js specifically, especially since it was just part of the last next release (13.3)


Abhijeet Prasad
:fleur_de_lis:  [1 month ago](https://sentry.slack.com/archives/CA2V2LBDL/p1682522480748349?thread_ts=1682522260.435059&cid=CA2V2LBDL)
we kept asking for heads up but they never even gave us a notice about it


Abhijeet Prasad
:fleur_de_lis:  [1 month ago](https://sentry.slack.com/archives/CA2V2LBDL/p1682522498225359?thread_ts=1682522260.435059&cid=CA2V2LBDL)
like I even had to go review their PRs to make sure stuff worked for Sentry lol


Abhijeet Prasad
:fleur_de_lis:  [1 month ago](https://sentry.slack.com/archives/CA2V2LBDL/p1682522525614959?thread_ts=1682522260.435059&cid=CA2V2LBDL)
https://github.com/vercel/next.js/issues/47113
[#47113 [NEXT-820] OTEL: add `http.route` to `SERVER` spans](https://github.com/vercel/next.js/issues/47113)
[Is there any way we could set](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/http.md#http-server-semantic-conventions) http.route here?
Without this it's impossible to do aggregate analysis on paramaterized routes, since they would all have different URLs, which is something APM providers (like Sentry for example) would need!
Originally posted by [@AbhiPrasad](https://github.com/AbhiPrasad) in [_https://github.com/vercel/next.js/pull/47066#discussion_r1135323331_](https://github.com/vercel/next.js/pull/47066#discussion_r1135323331)
From [SyncLinear.com](https://synclinear.com/) | [NEXT-820](https://linear.app/vercel/issue/NEXT-820/otel-add-httproute-to-server-spans)
Comments
3
<https://github.com/[vercel/next.js](https://github.com/vercel/next.js)|vercel/next.js>vercel/next.js | Mar 14th | Added by [GitHub](https://sentry.slack.com/services/B01UHAF1129)


David Cramer
  [1 month ago](https://sentry.slack.com/archives/CA2V2LBDL/p1682522552936829?thread_ts=1682522260.435059&cid=CA2V2LBDL)
yeah they i think recognize that failure and are trying to make it right


Abhijeet Prasad
:fleur_de_lis:  [1 month ago](https://sentry.slack.com/archives/CA2V2LBDL/p1682522740311079?thread_ts=1682522260.435059&cid=CA2V2LBDL)
Makes sense. Happy to help give feedback and make sure our docs are updated, just hope they don’t leave us behind once again.


David Cramer
  [1 month ago](https://sentry.slack.com/archives/CA2V2LBDL/p1682522795660809?thread_ts=1682522260.435059&cid=CA2V2LBDL)
yeah docs i think we should look at separately - i flagged in [#discuss-docs](https://sentry.slack.com/archives/C8H0BQRDJ)
