### ISSUE TITLE
Create Client Doc Spec

### ISSUE THREAD

**Issue by dcramer** [getsentry/sentry-docs#7]
A description of what client docs should look like (rough layout) and requirements.

Some examples:
- Main page should contain install, config, and general usage
- Frameworks should each be a dedicated page
- General TOC guidelines
- To be included, repo **must** be under the getsentry org on GitHub

**Comment by mitsuhiko** [comment]
We also need to make sure clients start defining the wizard configurations which is currently missing in all clients but the Python one.

**Comment by dcramer** [comment]
Here's how I'm thinking about it:

Integration
- Getting Started (Install, basic config, basic usage) -- this is the index page
- Configuration
- ... Frameworks
- ... Other


Getting Started (index.rst)
- Install
- Basic configuration
  - DSN
  - Release parameter
- Capture Exception
- User and tags context

**Comment by cameronmcefee** [comment]
Can we close this with the new docs that are on the way?

**Comment by PeloWriter** [comment]
We have this issue resolved now, I believe (see https://docs.sentry.io/contributing/approach/write-sdk-docs/).
