### ISSUE TITLE
SvelteKit: Incorrect Code Sample

### ISSUE THREAD

**Issue by hrueger** [getsentry/sentry-docs#7012]
### Core or SDK?

Platform/SDK

### Which part? Which one?

SvelteKit

### Description

The second code sample at https://docs.sentry.io/platforms/javascript/guides/sveltekit/ is incorrect.
It shows `TypeScript` as the language, but the file is a `.js` file. In addition, it imports the types `NextApiRequest, NextApiResponse` from `next` which has nothing todo with Svelte Kit.

### Suggested Solution

Update the sample to JavaScript and remove the type import line.

**Comment by Lms24** [comment]
Hey @hrueger thanks for reporting. Will fix this in a minute.
