### ISSUE TITLE
Document side-effects of using Sentry alongside other tools (Crashlytics)

### ISSUE THREAD

**Issue by romtsn** [getsentry/sentry-docs#7017]
### Core or SDK?

Platform/SDK

### Which part? Which one?

Android

### Description

There might be some side-effects/implicit behavior when using Sentry alongside other crash reporting tools like Crashlytics, especially when they are instantiated before ours and we don't have much time to process a crash.

### Suggested Solution

Document this

**Comment by kahest** [comment]
duplicate of https://github.com/getsentry/sentry-docs/issues/4583
