### ISSUE TITLE
Out of date documentation: relay configuration options

### ISSUE THREAD

**Issue by rodolfoBee** [getsentry/sentry-docs#7050]
### Core or SDK?

Core Sentry product

### Which part? Which one?

Relay

### Description

The following pages are out of date in regards to a release made 2023-04-17:
https://docs.sentry.io/product/relay/options/
https://docs.sentry.io/product/relay/operating-guidelines/

The release has breaking changes in terms of reverse proxy usage and connections options:
https://github.com/getsentry/relay/releases
https://github.com/getsentry/relay/commit/e8b2acc2cedd38db4ab5bc5d5d13f9996ceca528

### Suggested Solution

Revise and update the documentation.

**Comment by jan-auer** [comment]
The docs should also list the names of environment variables for options that can be configured through one.
