### ISSUE TITLE
[react-native] Improve react-native onboarding

### ISSUE THREAD

**Issue by smeubank** [getsentry/sentry-docs#7093]
### Core or SDK?

Platform/SDK

### Which part? Which one?

react-native

### Description

I want to setup my react-native application and should be able to find the simples route to setup as possible without being distracted by a lot of edge cases for config. Just the most important aspects to get error monitoring and performance and distributed tracing working OOTB.

This ticket will act to track a number of proposed improvements

### Suggested Solution

- [x] Set up for [prior SDK versions](https://docs.sentry.io/platforms/react-native/performance/#enable-tracing) should be moved down, or made expandable to put latest first
- [x] Combine [init and wrap snippets](https://docs.sentry.io/platforms/react-native/#initialize) if it is typically the same file and always needed
- [x] link to enable performance monitoring is a bit confusing since it is actually already setup, unless they're on an old SDK
- [x] top of page is a long list of features to scroll through before gettting to snippets, can this be cut down or collapsible?
- [ ] https://github.com/getsentry/sentry-docs/issues/7092

**Comment by kahest** [comment]
most of this has been improved on with https://github.com/getsentry/sentry-docs/pull/10165
we're keeping https://github.com/getsentry/sentry-docs/issues/7092 open to track this separately
