### ISSUE TITLE
Document how to add client hints, and sentry's behaviour wrt to client hints vs user agent strings

### ISSUE THREAD

**Issue by TBS1996** [getsentry/sentry-docs#7098]
### Core or SDK?

Core Sentry product

### Which part? Which one?

javascript? 

### Description

user agent strings are increasingly getting frozen, for example as shown here: https://github.com/getsentry/sentry/issues/50137

currently, in relay we try to get info from client hints first, and if that's not available we try again with the old user agent strings, this behaviour should be documented.

If client hints are not present our customers should fix this by requesting client hints from the end users. I think think this is a server configuration and not related to sentry, but I'm not sure. Regardless of how it's done, we should help customers enable this by documenting how it can be done.

See https://developer.chrome.com/en/articles/user-agent-client-hints/ for more details.

- [ ] Document how we prefer client hints and fall back on user agent strings

- [ ] Document how our customers can request client hint information in order to get more useful events

### Suggested Solution

Create relevant documentation

**Comment by AbhiPrasad** [comment]
> What does requesting client hints from users mean

The server has to send something that tell the browser that it can expose client hints to outgoing requests. This can be done via a `Accept-CH` header or a meta tag. Only the document request needs to set these headers, then all subsequent requests will get client hint info attached to them.

This means it requires no SDK changes, only server-side changes.
