### ISSUE TITLE
make requirements && make build builds the world, except actually building docs :)

### ISSUE THREAD

**Issue by torarnv** [getsentry/sentry-docs#71]
`make requirements && make build` as per the instructions installs a full sentry, runs test, and then finally doesn't produce anything:

```
(py27) [whopper:~/dev/sentry-all/sentry-docs] $ bin/web
bin/web: line 3: cd: build/html: No such file or directory
```

**Comment by torarnv** [comment]
Re-ran, now it created `build/html`, but it's empty. `build/doctrees` has a bunch of stuff though.

**Comment by cameronmcefee** [comment]
The docs have been overhauled so this is no longer applicable. Sorry we left you hanging :(
