### ISSUE TITLE
Unable to set IP address to {{auto}}

### ISSUE THREAD

**Issue by rodolfoBee** [getsentry/sentry-docs#7107]
### How do you use Sentry?

Sentry Saas (sentry.io)

### Version

3.19.1

### Steps to Reproduce

Follow the steps on this page to add auto IP address to user object:
https://docs.sentry.io/platforms/php/enriching-events/identify-user/

```
\Sentry\configureScope(function (\Sentry\State\Scope $scope): void {
  $scope->setUser(['ip_address' => "{{auto}}"]);
});
```

### Expected Result

Event is sent and the Sentry server infers the user/server's IP address. 

### Actual Result

Error message: 
Fatal error: Uncaught InvalidArgumentException: The "{{auto}}" value is not a valid IP address.

**Comment by rodolfoBee** [comment]
There might be an issue here then: I have `send_default_pii` set to true and `prevent storing IP address` set to false in the project settings, and no IP address is recorded. 

That is the reason I tried to add the user with {{auto}} ip address

**Comment by cleptric** [comment]
The SDK should send the client's IP address if `send_default_pii` is set to true.
See https://github.com/getsentry/sentry-php/blob/master/src/Integration/RequestIntegration.php#L143-L154
If this is not working, we would need further context of the application being used.

In any case, `{{auto}}` is not supported in the PHP SDK when manually setting the user's IP address.
