### ISSUE TITLE
tracePropagationTargets missing from Performance Monitoring docs for iOS and Android

### ISSUE THREAD

**Issue by thinkocapo** [getsentry/sentry-docs#7110]
### Core or SDK?

Platform/SDK

### Which part? Which one?

Android and iOS

### Description

Shouldn’t tracePropagationTargets be under Performance Monitoring documentation for Android & iOS :android: :iphone: ?

https://docs.sentry.io/platforms/apple/configuration/options/#trace-propagation-targets

In Javascript SDK’s, it’s mentioned under Performance documentation
In React Native SDK, it’s mentioned under Performance documentation

https://github.com/search?q=repo%3Agetsentry%2Fsentry-cocoa%20propagation&type=code

### Suggested Solution

Put it under  here like in React Native and JS

https://docs.sentry.io/platforms/react-native/performance/instrumentation/automatic-instrumentation/#tracepropagationtargets

https://docs.sentry.io/platforms/javascript/guides/react/performance/instrumentation/automatic-instrumentation/#tracepropagationtargets

**Comment by philipphofmann** [comment]
@brustolin, isn't that fixed with #7116?

**Comment by brustolin** [comment]
> @brustolin, isn't that fixed with #7116?

Not really. This is a lil bit different from the discussion on Slack. I will work on this.

**Comment by brustolin** [comment]
Cocoa docs were updated with https://github.com/getsentry/sentry-docs/pull/7160
