### ISSUE TITLE
Cannot load environment variables as described in the docs

### ISSUE THREAD

**Issue by areindl** [getsentry/sentry-docs#7158]
### Core or SDK?

Platform/SDK

### Which part? Which one?

@sentry/vite-plugin

### Description

I was trying to use the vite-plugin for sentry.

I was following [`this`](https://docs.sentry.io/platforms/javascript/guides/vue/sourcemaps/uploading/vite/) documentation.

The problem is that the plugin constantly fails to use the environment variables.

I have tried:

1. Just adding `SENTRY_ORG` (and the rest) to` .env`
2. Using the `process.env.SENTRY_ORG ` approach in `vite.config.js`
3. Using `import.meta.env.SENTRY_ORG `

The docs say to use `env.SENTRY_AUTH_TOKEN` which will throw an error.

What is the right way to do it?
 

### Suggested Solution

Describe how we can get it to work.

**Comment by lforst** [comment]
However, you get and pass the value doesn't matter.

You're right however that the current snippet will always throw an error - I opened a PR to fix.
