### ISSUE TITLE
Confusing docs on init(send_default_pii=True) for Cookies

### ISSUE THREAD

**Issue by rmendocna** [getsentry/sentry-docs#7177]
### Core or SDK?

Platform/SDK

### Which part? Which one?

https://docs.sentry.io/platforms/python/data-collected/

### Description

The paragraph which goes like

> ### Cookies
> 
> By default, the Sentry SDK doesn't send cookies. **Regardless of what send_default_pii is set to**, Sentry tries to remove any cookies that contain sensitive information, (such as the Session ID and CSRF Token cookies in Django).
> 
> To start sending cookies, set send_default_pii=True in the sentry_sdk.init() call.

### Cookies

By default, the Sentry SDK doesn't send cookies. Sentry tries to remove any cookies that contain sensitive information, (such as the Session ID and CSRF Token cookies in Django).

To start sending cookies, set send_default_pii=True in the sentry_sdk.init() call.

**Comment by lizokm** [comment]
Hi there. Thanks for the feedback! We've updated the text per your suggestion :)
