### ISSUE TITLE
Will Sentry offer Chinese version of documentation in the future?

### ISSUE THREAD

**Issue by FeynmanZhou** [getsentry/sentry-docs#718]
@ceorourke @cameronmcefee 
Hi guys,  will Sentry offer Chinese version of documentation in the future? Since there must be lots of Chinese developers and enterprises who want to get started with Sentry, it will be helpful and attractive if Chinese and more language versions get supported. I suppose the localization is quite important for such a great product.

**Comment by ceorourke** [comment]
Hi @FeynmanZhou while it'd be great to translate the docs into different languages (Chinese included), we change things so frequently we'd have to keep someone on retainer to keep up with it. At the moment that's not viable, but we'll keep this in mind for the future.

**Comment by violetgo** [comment]
Can we use the power of the community to accomplish translation?
