### ISSUE TITLE
Manual Intialization 

### ISSUE THREAD

**Issue by Nitin-UpSwing** [getsentry/sentry-docs#7205]
### Core or SDK?

Platform/SDK

### Which part? Which one?

Android Integration documentation

### Description

In this page (https://docs.sentry.io/platforms/android/configuration/manual-init/?original_referrer=https://sentry.io/) you are saying that we can manually initialize the sentry sdk after adding the plugin but after adding i have to add sentry dependency(implementation 'io.sentry:sentry-android:6.23.0') to import the sentry android sdk .

### Suggested Solution

So, please mention this in doc that we have to add dependency also if want to start it manually

**Comment by romtsn** [comment]
@Nitin-UpSwing hey, where exactly are you adding the sentry plugin? Is it the `app` module? If so, you will only be able to access Sentry classes in this module but not in the others. I can clarify that in the docs 👍

**Comment by Nitin-UpSwing** [comment]
Hey @romtsn I am adding sentry plugin in project level build.gradle.

And yes please clarify all these in doc with steps

**Comment by romtsn** [comment]
> Hey @romtsn I am adding sentry plugin in project level build.gradle.
> 
> And yes please clarify all these in doc with steps

yeah, but which project exactly? Root project or app module?

**Comment by Nitin-UpSwing** [comment]
As I mentioned  project level its mean Root project

**Comment by romtsn** [comment]
> As I mentioned project level its mean Root project

Our docs state that you have to add it to the `app` module (alongside `com.android.application` plugin). The plugin will have no effect if you add it to the root project.
![image](https://github.com/getsentry/sentry-docs/assets/4999776/966c6775-a34a-4c7c-96b9-d758e7ed49db)

Then you will be able to access Sentry SDK classes from within that module.
