### ISSUE TITLE
DSN isn't enough to use the cli

### ISSUE THREAD

**Issue by vasilvestre** [getsentry/sentry-docs#7206]
### Core or SDK?

Platform/SDK

### Which part? Which one?

Next/Node

### Description

I use the DSN to initialize my Sentry, it seems like an auth token is wanted.

sentry reported an error: Authentication credentials were not provided.

### Suggested Solution

Use the DSN or add to documentation that an auth token is required

**Comment by vasilvestre** [comment]
> DSNs are public and can therefore not be used to authenticate when uploading source maps. Can you share a bit more about the problem you were facing. What version of the Next.js sdk were you using? What setup flow were you using? Did you use the wizard?

I was misled reading the documentation, I'm not asking to create a new release but it does anyway and ask for a TOKEN that isn't in the guide. Maybe adding a note to inform about this would be good?

**Comment by lforst** [comment]
Ok, I think I understand.

We should add references to auth tokes to these docs here: https://docs.sentry.io/platforms/javascript/guides/nextjs/manual-setup/#configure-source-maps

**Comment by vasilvestre** [comment]
> Ok, I think I understand.
> 
> We should add references to auth tokes to these docs here: https://docs.sentry.io/platforms/javascript/guides/nextjs/manual-setup/#configure-source-maps

Yes exactly, the DX will be even greater :)
