### ISSUE TITLE
Koa integration example

### ISSUE THREAD

**Issue by rkulinski** [getsentry/sentry-docs#7215]
### Core or SDK?

Platform/SDK

### Which part? Which one?

Koa Integration

### Description

```
app.on("error", (err, ctx) => {
  Sentry.withScope((scope) => {
    scope.setSDKProcessingMetadata({ request: ctx.request });
    Sentry.captureException(err);
  });
});
```

https://docs.sentry.io/platforms/node/guides/koa/

This will make the app to silently swallow errors. Very misleading and confusing.

### Suggested Solution

In this example you should also include forwarding error, or at least add `console.error` line to it, to make it clear that it will swallow the errors.

**Comment by Lms24** [comment]
Hi @rkulinski thanks for pointing this out! I agree - we don't want our SDKs to swallow errors, so we shouldn't suggest this in the Koa guide either. If you have a concrete suggestion, would you be willing to open a PR for it? 

Places where we should change this:
* [Koa Getting Started guide](https://github.com/getsentry/sentry-docs/blob/9d8acb16e49df8b278fb732763bfe1360812c89c/src/platforms/node/guides/koa/index.mdx)
* [Koa Project Onboarding Wizard](https://github.com/getsentry/sentry-docs/blob/9d8acb16e49df8b278fb732763bfe1360812c89c/src/wizard/node/koa.md/#L32)

**Comment by renglish-rs** [comment]
I would suggest replacing the current `app.on('error')` docs with the `requestHandler` here 
https://docs.sentry.io/platforms/node/guides/koa/#monitor-performance

This one accurately captures exceptions and raises them all the way up the stack for another handler to process.

The current documentation also does not tell you that the Sentry app has bad Sentry Context leaking with Koa, and that you basically need to use `runWithAsyncContext` in almost all scenarios, so shifting to using a Koa Middleware instead would be a more accurate and safe way to support Koa users.

**Comment by renglish-rs** [comment]
In my use case I did not need to use the promise that was wrapping the middleware

```js
import Koa, { DefaultContext, Next } from 'koa';
import * as Sentry from '@sentry/node';

Sentry.init({
  dsn: "<SNIP>",
});
const app = new Koa();

const requestHandler = async (ctx: DefaultContext, next: Next) => {
  Sentry.runWithAsyncContext(async () => {
    const hub = Sentry.getCurrentHub();
    // eslint-disable-next-line arrow-body-style
    hub.configureScope((scope) => {
      // eslint-disable-next-line arrow-body-style
      return scope.addEventProcessor((event) => {
        scope.setSDKProcessingMetadata({ request: ctx.request });
        return Sentry.addRequestDataToEvent(event, ctx.request, {
          include: {
            user: false,
          },
        });
      });
    });

    try {
      await next();
    } catch (err) {
      // You can replace this with a console.error(err) if you want to prevent route errors from crashing Koa
      throw new Error(err);
      Sentry.captureException(err);
    }
  });
};

app.use(requestHandler);
```

**Comment by AbhiPrasad** [comment]
New Koa guide with `8.x`! https://docs.sentry.io/platforms/javascript/guides/koa/
