### ISSUE TITLE
`Sentry.autoDiscoverNodePerformanceMonitoringIntegrations` doesn't seem to exist

### ISSUE THREAD

**Issue by oliversalzburg** [getsentry/sentry-docs#7221]
### Core or SDK?

Core Sentry product

### Which part? Which one?

AWS Lambda

### Description

https://docs.sentry.io/platforms/node/guides/aws-lambda/performance/instrumentation/automatic-instrumentation refers to `Sentry.autoDiscoverNodePerformanceMonitoringIntegrations`, which doesn't seem to exist.

In particular, this is surprising, because I'm viewing the `serverless`-related documentation, and this page is using the `node` package. The latter exports the referenced method, but not the `serverless` package, that you'll be using in AWS Lambda.

### Suggested Solution

Re-export the method from `node` in the `serverless` package or fix the docs.

**Comment by Lms24** [comment]
Hi @oliversalzburg, thanks for raising this! Seems like we missed to export this function from our `@sentry/serverless` SDK when we internally refactored our tracing package.
For the sake of consistency we'll add the missing export to the SDK. However, we'll also adjust the docs with a warning that using this functionality comes with a potentially hefty performance impact that can significantly increase the runtime of a serverless function. Auto-discovery checks if certain database tools (e.g. Apollo, Postgres, etc) are installed by dynamically requiring them. This takes some time.

**Comment by oliversalzburg** [comment]
Oh, interesting. Thanks for the heads-up 🙂
