### ISSUE TITLE
Incorrect phase used in Maven Sentry plugin guide

### ISSUE THREAD

**Issue by vlad-artyomov** [getsentry/sentry-docs#7241]
### Core or SDK?

Platform/SDK

### Which part? Which one?

Spring Boot (Source Context feature)

### Description

In section about [Maven Sentry plugin](https://docs.sentry.io/platforms/java/guides/spring-boot/source-context/#using-the-maven-build-tool-plugin) I found an error:

![CleanShot 2023-06-22 at 11 58 01@2x](https://github.com/getsentry/sentry-docs/assets/9394989/048432ae-efbb-43df-be3b-e6dea82e6d6d)

When I tried to execute the Sentry plugin during `install` phase - the resulting `sentry-debug-meta.properties` was not included in the final JAR file and source code mapping was not working in the running application.

### Suggested Solution

Just change the phase to `generate-resources` according to the [Maven lifecycle](https://maven.apache.org/guides/introduction/introduction-to-the-lifecycle.html#default-lifecycle). Once I did this - everything started working as expected:

```xml
<execution>
    <phase>generate-resources</phase>
    <goals>
        <goal>uploadSourceBundle</goal>
    </goals>
</execution>
```

**Comment by vivianyentran** [comment]
@adinauer Can you confirm if the Maven Sentry plugin phase should be updated from install to generate-resources?

**Comment by adinauer** [comment]
It works for me, when I run `install` on our [sample](https://github.com/getsentry/sentry-maven-plugin/tree/main/examples/sentry-maven-plugin-example) but not if I run e.g. `package`. I guess if people don't run the `install` phase during their build source code wouldn't be uploaded so we can change it in the sample as well as docs. Thanks for the help @vlad-artyomov

**Comment by adinauer** [comment]
Docs and sample have been updated.
