### ISSUE TITLE
Old forum is unreadable

### ISSUE THREAD

**Issue by jeremy-rifkin** [getsentry/sentry-docs#7249]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Visit any page on the old forum, e.g. https://forum.sentry.io/t/unhandledrejection-non-error-promise-rejection-captured-with-value/14062

### Expected Result

Even though it's archived, text should be readable. 

### Actual Result

Text is not readable:
![image](https://github.com/getsentry/sentry/assets/51220084/388aafd2-c9aa-4af4-bda9-b04d5a1d8bc6)

### Product Area

Issues

### Link

https://forum.sentry.io/t/unhandledrejection-non-error-promise-rejection-captured-with-value/14062

**Comment by jeremy-rifkin** [comment]
It is likely dark mode was somehow set on my end, yes. I can try clearing cookies but text should be made readable on dark mode.

**Comment by chadwhitacre** [comment]
> text should be made readable on dark mode

We're not going to be able to invest in that, unfortunately. :-/ It's a royal PITA to edit the site now that it's in read-only mode, we have to contact Discourse customer support for them to flip it back to editable mode. Also this seems like a Discourse product problem unless we're customizing CSS (which seems unlikely to me). Could be confirmed by checking other Discourse forums, I guess, and if true would need to report to them.

**Comment by chadwhitacre** [comment]
> if true would need to report to them

If false we're still not going to be able to invest in this, so I'm gonna close this ticket. Thanks for filing @jeremy-rifkin, at least now there's an issue for others to find in the future to learn the workaround.

**Comment by jeremy-rifkin** [comment]
Thanks, I’ll report it upstream
