### ISSUE TITLE
Document precedence for setting DSN with Java client

### ISSUE THREAD

**Issue by danielcompton** [getsentry/sentry-docs#725]
https://github.com/getsentry/sentry-docs/blob/master/src/collections/_documentation/clients/java/config.md#configuration-methods-id2 describes the different ways to set the DSN, but doesn't describe which method takes precedence if multiple methods are used. Would it be possible to document this?

**Comment by marandaneto** [comment]
@maciejwalkowiak maybe still worth it? not sure if we document this already

**Comment by maciejwalkowiak** [comment]
Fixed in https://github.com/getsentry/sentry-docs/pull/2708/

**Comment by PeloWriter** [comment]
This is fixed, as noted. Thanks @maciejwalkowiak.
