### ISSUE TITLE
Unreal documentation for crash free sessions is a broken link

### ISSUE THREAD

**Issue by ImagineTheGames** [getsentry/sentry-docs#7252]
### Core or SDK?

Platform/SDK

### Which part? Which one?

Unreal SDK

### Description

https://docs.sentry.io/platforms/unreal/configuration/releases/#sessions

Goto this page it will say page not found, you cannot find the documentatino for crash free sessions setup.

### Suggested Solution

Fix the link.

**Comment by vivianyentran** [comment]
Hi, can you share where you're finding that link? I don't see it anywhere in our docs and it looks like that page just doesn't exist.
