### ISSUE TITLE
Profiling default mode

### ISSUE THREAD

**Issue by nakanaa** [getsentry/sentry-docs#7293]
### Core or SDK?

Platform/SDK

### Which part? Which one?

Profiling

### Description

The page at https://docs.sentry.io/platforms/node/profiling/ says that "the default profiling mode (lazy) ..." but the default seems to have been changed already in February: https://github.com/getsentry/profiling-node/pull/102

### Suggested Solution

Fix accordingly to changes

**Comment by JonasBa** [comment]
@nakanaa You are absolutely correct - we missed that when we changed it. We'll get that updated asap, thanks so much!
