### ISSUE TITLE
Restructure Android SDK Docs

### ISSUE THREAD

**Issue by smeubank** [getsentry/sentry-docs#7294]
### Background:

Success rates for developers create Android projects and sending events, are rather low in comparison to other platforms. We want to ship a number of improvements to address this and try to help android devs navigate setting up their Android apps with Sentry. This issue will focus on some improvements to the docs.

### Proposal:

- Getting started: includes a long list of features before getting to setup. Let's collapse or move them to reduce scroll
- Getting started: side bar too many top level Items
  - Source Context: can be the top level item with the build tools where we provide some type of plugin integration are sub items
  - Source Context: page and sub pages are then modeled after the source maps section from JS
- Android Native Development Kit: Is this top level? Does it belong under something with source context or does it cover more
  - how many devs need it and it what situation?
- Video tutorial: relevant?

Ideally the docs behave as much like a decision tree flow for users, arriving at relevant steps they need without needing to sort through a lot of the context for other scenarios on same pages.

**Comment by stefanosiano** [comment]
The docs were updated:
There was a [notion doc](https://www.notion.so/sentry/Docs-restructuring-50ad264dfa8c4d3e910424e3554c4efa?pvs=4) to discuss changes.
Here are the relevant docs PRs:
https://github.com/getsentry/sentry-docs/pull/7299 (small cleanup of manual config)
https://github.com/getsentry/sentry-docs/pull/7301 (reorganization of the side bar with deletion of video tutorial, move NDK and Gradle inside configuration and creation of Enhance Error Reporting section for Kotlin Compiler Plugin, Proguard and Source Context)

**Comment by stefanosiano** [comment]
@smeubank are all the points addressed or is there something else to do?
Can we close it or should we keep it open?

**Comment by stefanosiano** [comment]
@smeubank Can we close this issue?
