### ISSUE TITLE
Flutter "Source Context" requirements

### ISSUE THREAD

**Issue by ert485** [getsentry/sentry-docs#7302]
### Core or SDK?

Platform/SDK

### Which part? Which one?

Flutter

### Description

I'm having trouble with getting "source maps" / "source context" to work for my Flutter App (which is currently getting built only to web). The TroubleShooting documentation helped a bit, but there was a few things in that documentation that are throwing me off. 

I'll try to start with one point of confusion and see where that leads us.

from [Source Context](https://docs.sentry.io/platforms/flutter/troubleshooting/#source-context):
> Source Context support requires compiling your app using the split-debug-info build parameter on Flutter 3.10.0 and above

I'm not sure what `split-debug-info` is exactly (something specific to macOS/iOS?), but it doesn't seem to be available option for `flutter build web`. The phrasing of the quote above doesn't mention it being a requirement for any specific build platform option. So I can't tell if I need that requirement in my situation, and I don't know how to tell if that's the problem I'm facing.

### What I'm seeing in Sentry for my App:

- "source maps" and "source" are uploaded to Sentry (and they are associated with the same release as the issues that are missing source context)
- the stack trace is still minified (see image below)
- ![Screen Shot 2023-06-29 at 12 38 23 PM](https://github.com/getsentry/sentry-docs/assets/6201488/2d3ae643-0d62-4f88-a046-1961b039e507)

### Suggested Solution

Documentation: 
- Specify in what situations `split-debug-info` is needed for the "Source Context" feature to work
- any hints at what could still be wrong with my situation would be appreciated 😄

**Comment by marandaneto** [comment]
@ert485 This is for Android/iOS/macOS [only](https://docs.sentry.io/platforms/flutter/upload-debug/#when-to-upload), Source code context should work OOTB for Web as long as you [upload source maps](https://docs.sentry.io/platforms/flutter/upload-debug/#uploading-source-maps-for-flutter-web).
