### ISSUE TITLE
404 can't find storybook

### ISSUE THREAD

**Issue by YaYaPao** [getsentry/sentry-docs#7353]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Steps to Reproduce

1. open [Storybook Styleguide | Sentry Developer Documentation](https://develop-git-feat-document-user-feedback-api.sentry.dev/frontend/storybook/)
2. click link https://github.com/getsentry/sentry/tree/master/.storybook
3. 404 - page not found

It's used been in `docs-ui` directory, but after i update the latest code, it has been totally removed.

### Expected Result

Something about storybook, like .stories or some configs

### Actual Result

404 - page not found

### Product Area

Unknown

**Comment by malwilley** [comment]
Actually on second look, it looks like the URL you are using is an out of date deployment (https://develop-git-feat-document-user-feedback-api.sentry.dev/frontend/storybook/). If you view the up to date dev docs, this has already been removed. Closing.
