### ISSUE TITLE
Navigation issue on `Data Management` platform pages

### ISSUE THREAD

**Issue by kahest** [getsentry/sentry-docs#7381]
Linking to `Data Management` (or subpage) on any platform page (`https://docs.sentry.io/platforms/<platform>/data-management/**)` does not work - opening such a link always redirects to the platform's landing page.

Examples:
- https://docs.sentry.io/platforms/rust/data-management
- https://docs.sentry.io/platforms/apple/guides/ios/data-management/debug-files/file-formats/#mach-o-and-dsym
- https://docs.sentry.io/platforms/php/data-management/sensitive-data

Even navigating manually to these pages and reloading the page causes the same problem.

Notes:
- other section pages on platform (e.g. https://docs.sentry.io/platforms/rust/enriching-events) seem to work fine
- the **product** page for `Data Management` (https://docs.sentry.io/product/data-management-settings) also works
- tested in Chrome, Safari, Firefox, Opera

**Comment by shanamatthews** [comment]
This is probably my fault, I'll take a look.
