### ISSUE TITLE
URL wrong for sentry

### ISSUE THREAD

**Issue by nick4333** [getsentry/sentry-docs#7388]
### Core or SDK?

Core Sentry product

### Which part? Which one?

APIs

### Description

URL for at least one endpoint is incorrect, `/api/0/organization/{organization_slug}/monitors/{monitor_slug}/checkins/` should be `/api/0/organizations/{organization_slug}/monitors/{monitor_slug}/checkins/`. This causes great confusion for people who are coming to the sentry api for the first time because they will be met with only 404's and when they go to consult the sentry api they will think that everything they are doing is correct, when it is not. 

Link to the above endpoint https://docs.sentry.io/api/crons/retrieve-checkins-for-a-monitor/

### Suggested Solution

Change `organization` to `organizations` for all affected endpoints.

**Comment by rjo100** [comment]
Thanks for reporting this! We've fixed up the docs now and please let us know if you have any other issues or questions.
