### ISSUE TITLE
React-Native needs beforeSendTransaction

### ISSUE THREAD

**Issue by thinkocapo** [getsentry/sentry-docs#7411]
### Core or SDK?

Platform/SDK

### Which part? Which one?

React Native

### Description

`beforeSendTransaction` is available in React Native because it uses React and this callback is availablei n React

But it's not in the React Native Documentation.
https://docs.sentry.io/platforms/react-native/performance/instrumentation/automatic-instrumentation/#configuration-options

It is only in the React documentation
https://docs.sentry.io/platforms/javascript/guides/react/configuration/filtering/?original_referrer=https%3A%2F%2Fdocs.sentry.io%2Fplatforms%2Freact-native%2Fperformance%2Finstrumentation%2Fautomatic-instrumentation%2F#using-platformidentifier-namebefore-send-transaction-

### Suggested Solution

Add it to the React Native documentation.

**Comment by vivianyentran** [comment]
Hi, it's in the React Native documentation here: https://docs.sentry.io/platforms/react-native/configuration/filtering/?original_referrer=https%3A%2F%2Fgithub.com%2Fgetsentry%2Fsentry-docs%2Fissues%2F7411#using-platformidentifier-namebefore-send-transaction-

@shanamatthews do you think we should include that under performance config instead?

**Comment by shanamatthews** [comment]
In general, it seems like the filtering docs that are specific to transactions should live in the performance docs. This would be a change across all SDKs. Maybe something to put on the backlog.

**Comment by krystofwoldrich** [comment]
Released in JS 7.18.0

Included in RN since https://github.com/getsentry/sentry-react-native/releases/tag/4.9.0

The filtering page of RN docs contains the `beforeSendTransaction`
https://docs.sentry.io/platforms/react-native/configuration/filtering/#using--3
