### ISSUE TITLE
Streamline Remix Getting Started page

### ISSUE THREAD

**Issue by Lms24** [getsentry/sentry-docs#7429]
### Core or SDK?

Platform/SDK

### Which part? Which one?

@sentry/remix

### Description

The "Getting Started" page for Remix is quite long and verbose. Maybe we can streamline it a little. Some ideas:

### Suggested Solution

 * Features Overview: I know this isn't consistent over the individual SDKs but I think we should streamline this a little. Maybe just say that the Remix SDK supports automatic error and performance monitoring on client and server.  
 * Remove the Prisma code snippet. Unless there's a good reason to keep it I'd rather not put more than the basic setup on this page. 
 * Move the custom express server instructions further down, under its own heading. Let's focus on what's important for a standard setup and mention more custom stuff afterwards. Seems like right now, it's sort of in between.
* Add readable stack traces to errors: I believe I incorrectly included the wizard snippet here. Let's link to the remix-specific uploading instructions here as the wizard doesn't cover remix (yet).

Goal: Everything that's mandatory to configure should be on top; Optional/more custom stuff below.

**Comment by Lms24** [comment]
@onurtemizkan seems like I can't assign you to the issue, sorry. Please take a look at my suggestions and see if they make sense to you. Also feel free to streamline/improve other stuff you notice. I trust your Remix expertise here :D

**Comment by AbhiPrasad** [comment]
Let's also make sure we indicate that we only support node runtimes as per concerns raised in https://github.com/getsentry/sentry-javascript/issues/8536

**Comment by macpham** [comment]
I experienced the same thing @reichhartd mentioned, `7.57.0` works with CF Workers, but `7.58.0` did not. So something was introduced recently that causes the error mentioned in https://github.com/getsentry/sentry-javascript/issues/8536 but what you're saying is officially you don't even support Cloudflare?

**Comment by AbhiPrasad** [comment]
@macpham, the SDK has never officially supported Cloudflare workers, since we wanted the freedom to use Node APIs.
