### ISSUE TITLE
Document examples of `beforeAddRecordingEvent`

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-docs#7447]
`beforeAddRecordingEvent` is a powerful callback fro Session Replay.

But our current documentation doesn't clarify different possibilities this gives. For example, it can be used to resolve this use case: 
https://github.com/getsentry/sentry-javascript/issues/8390

Ask: Document 1 to 3 common/interesting use cases to help developers understand what can be achieved with this callback

**Comment by billyvg** [comment]
Here's 1 example https://github.com/getsentry/sentry-docs/pull/7547
