### ISSUE TITLE
Premises - not Premise

### ISSUE THREAD

**Issue by jensenbox** [getsentry/sentry-docs#746]
So pretty much everywhere the docs use the word **premise** when it should be **premises**.

https://grammarcops.wordpress.com/tag/premise-vs-premises/

The above article is a perfect example of this error.

More examples: https://www.google.com/search?q=premise+vs+premises

**Comment by jensenbox** [comment]
There seem to be a few stragglers - https://github.com/getsentry/sentry-docs/search?q=premise&type=code

**Comment by PeloWriter** [comment]
We'll fix these. Thanks for the nudge.
