### ISSUE TITLE
Source maps docs for create-react-app

### ISSUE THREAD

**Issue by smeubank** [getsentry/sentry-docs#7460]
### Core or SDK?

Core Sentry product

### Which part? Which one?

JS SDK source maps

### Description

Users with a react app based on create-react-app setup sometimes come looking for how to setup their source maps upload. If they are not using the basic create-react-app setup then it might be helpful to have a docs page to inform them how we propose they setup their application to work with sentry-cli

### Suggested Solution

The wizard flow contains this already, it might be simple enough to include the steps similar to what we already have here under [guides](https://docs.sentry.io/platforms/javascript/sourcemaps/#guides).

the create react app flow seems to be quite popular on the wizard, and argubaly user should just use the wizard, but if not docs would be good compliment

<img width="777" alt="image" src="https://github.com/getsentry/sentry-docs/assets/47563310/d6226375-a28e-4b20-b8fd-88380258ad21">

```
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject",
    "sentry:sourcemaps": "sentry-cli sourcemaps inject --org steven-eubank --project javascript-react-c0 ./build && sentry-cli sourcemaps upload --org steven-eubank --project javascript-react-c0 ./build"
  },
```

**Comment by Lms24** [comment]
Backlogging

**Comment by mydea** [comment]
is this still something we want to do? 🤔

**Comment by smeubank** [comment]
> is this still something we want to do? 🤔

i still think it is a good idea, we decided this cause it was one of the most popular routes for the source maps wizard, so it made sense to ensure people could find a guide via google too. It;s still pretty high up there.

**Comment by chargome** [comment]
I think this is actually well documented: https://docs.sentry.io/platforms/javascript/guides/react/sourcemaps/uploading/ 🤔 

We have clear docs for CRA / CLI / webpack (which is what they get once they eject from CRA)

Closing, please re-open if you feel there is something still missing!
