### ISSUE TITLE
Cant open

### ISSUE THREAD

**Issue by adddadfq** [getsentry/sentry-docs#7484]
### Core or SDK?

Core Sentry product

### Which part? Which one?

Sco2 report

### Description

Cant download SCO2 report

### Suggested Solution

Download option

**Comment by lizokm** [comment]
Hi there, sorry to hear you're having trouble! Please take a look at our support page: https://help.sentry.io/

**Comment by leedongwei** [comment]
<img width="891" alt="Screenshot 2023-08-01 at 4 11 12 PM" src="https://github.com/getsentry/sentry-docs/assets/1748388/c3638759-8f99-4c95-9e22-3c1a837a5e21">

It seems to be working fine for me. Can you share details of any errors that you're seeing? 

If you're using adblockers, you might need to disable them.

**Comment by adddadfq** [comment]
Can you please send the document over this mail.
