### ISSUE TITLE
breadcrumbs doc does not tell you what interface is

### ISSUE THREAD

**Issue by connorjclark** [getsentry/sentry-docs#7520]
### Core or SDK?

Platform/SDK

### Which part? Which one?

https://docs.sentry.io/platforms/native/enriching-events/breadcrumbs/

### Description

https://docs.sentry.io/platforms/native/enriching-events/breadcrumbs/ `sentry_value_new_breadcrumb` native API example is given, but I cannot discern what the API is and I found no link on the page to the native SDK API docs.

Specifically, I do not know what valid types are, or how these things appear in the UI (well, I do now, after trial-and-error).

### Suggested Solution

Link to the API reference.

**Comment by kahest** [comment]
The [docs page](https://docs.sentry.io/platforms/native/enriching-events/breadcrumbs/) has a sample showing the usage of `sentry_value_new_breadcrumb` which was extended a while back. The page also links to the [product docs](https://docs.sentry.io/product/issues/issue-details/breadcrumbs/) which explain how breadcrumbs (of specific types) show up on the product, and a link to the [developer docs](https://develop.sentry.dev/sdk/event-payloads/breadcrumbs/), which explain the breadcrumbs API interface.

I'm not sure what is missing, so I'm gonna close this for now, but feel free to comment with more concrete info on what is missing and we'll review.
