### ISSUE TITLE
Write about Rage & Dead clicks in the Docs

### ISSUE THREAD

**Issue by ryan953** [getsentry/sentry-docs#7543]
Our product and sdk/setup docs are in https://github.com/getsentry/sentry-docs/ and get deployed to https://docs.sentry.io/

We should outline what needs to be included, figure out what we're going to say. Starting in notion might make sense.

Then draft some markdown in the repo and do all the formatting & create new pages if needed. etc.

**Comment by ryan953** [comment]
cc @jas-kas

**Comment by lizokm** [comment]
Happy to work with you on this too!
