### ISSUE TITLE
Unclear "Important" section

### ISSUE THREAD

**Issue by subos2008** [getsentry/sentry-docs#7557]
### Core or SDK?

Platform/SDK

### Which part? Which one?

configureScope

### Description

A section has been added to https://docs.sentry.io/platforms/node/enriching-events/scopes/:

```
Important
Any exceptions that occur within the callback function for withScope will not be caught, and all errors that occur will be silently ignored and not reported.
```

As far as I can understand the first part of this sentence is saying any exceptions raised will be passed up - which is great. But what does the second part of the sentence mean? It appears to contradict the first part. 

### Suggested Solution

Split the sentence into two and run it by someone on the dev team to check the language. Errors are exceptions - you can't both "not catch them" and "silently eat them, suppressing errors". It has to be one or the other.

**Comment by Lms24** [comment]
Hi @subos2008 thanks for writing in! I don't entirely see the contradiction but afaict we're using "exception" and "error" interchangeably here which might cause some confusion. What this note is trying to say is that no error thrown within `configureScope` will be reported to Sentry. I'll reword this in a small PR.
