### ISSUE TITLE
Sentry CLI installed via Homebrew, used in Xcode Build Phase gives 'not installed' message (iOS SDK)

### ISSUE THREAD

**Issue by sebj** [getsentry/sentry-docs#7597]
### Core or SDK?

Platform/SDK

### Which part? Which one?

iOS SDK

### Description

In the page [_'Uploading Debug Symbols'_](https://docs.sentry.io/platforms/apple/guides/ios/dsym/?original_referrer=https%3A%2F%2Fduckduckgo.com%2F#xcode-build-phase), the section [_'Xcode Build Phase'_](https://docs.sentry.io/platforms/apple/guides/ios/dsym/?original_referrer=https%3A%2F%2Fduckduckgo.com%2F#xcode-build-phase) lists two different script options which can be copy-pasted into a new Xcode build phase. It seems like if sentry-cli has been installed via Homebrew (which is [listed in its documentation](https://docs.sentry.io/product/cli/installation/?original_referrer=https%3A%2F%2Fduckduckgo.com%2F#installation-via-homebrew) as one of the installation methods) on an Apple Silicon Mac, the scripts will log a warning/error that sentry-cli is not installed (even though it's accessible from Terminal)

### Suggested Solution

[SwiftLint's Xcode build phase documentation section](https://github.com/realm/SwiftLint#xcode) mentions the following, which I think might be applicable to Sentry (at least, it fixed Sentry's script issue for me!), and could be mentioned in the Uploading Debug Symbols page:

> If you installed SwiftLint via Homebrew on Apple Silicon, you might experience this warning:

> > warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint

> That is because Homebrew on Apple Silicon installs the binaries into the /opt/homebrew/bin folder by default. To instruct Xcode where to find SwiftLint, you can either add /opt/homebrew/bin to the PATH environment variable in your build phase
> ```
> if [[ "$(uname -m)" == arm64 ]]; then
>     export PATH="/opt/homebrew/bin:$PATH"
> fi
> 
> // ...
> ```
> or you can create a symbolic link in /usr/local/bin pointing to the actual binary:
> ```
> ln -s /opt/homebrew/bin/swiftlint /usr/local/bin/swiftlint
> ```

**Comment by kahest** [comment]
Hi @sebj, thanks for reporting this & the suggested solution!

**Comment by brustolin** [comment]
Thanks @sebj for the help!
This will be updated in the [docs](https://github.com/getsentry/sentry-docs/pull/11597) and in the [wizard](https://github.com/getsentry/sentry-wizard/pull/691).
