### ISSUE TITLE
Document how to set fingerprints in Rust SDK

### ISSUE THREAD

**Issue by rodolfoBee** [getsentry/sentry-docs#7611]
### Core or SDK?

Platform/SDK

### Which part? Which one?

https://docs.sentry.io/platforms/rust/usage/sdk-fingerprinting/

### Description

When navigating to Data Management -> Issue grouping -> SDK fingerprinting -> Rust, the user gets a 404 Page not found. 

### Suggested Solution

If it is supported: document how to with examples

If not, remove from the platform picker under SDK fingerprint.

**Comment by lizokm** [comment]
Looks like this has been updated.
