### ISSUE TITLE
SDK versions are outdated

### ISSUE THREAD

**Issue by romtsn** [getsentry/sentry-docs#7627]
### Core or SDK?

Platform/SDK

### Which part? Which one?

Android

### Description

Looks like release-registry pulling is not working recently, e.g. [Android docs](https://docs.sentry.io/platforms/android) are saying the latest gradle plugin version is 3.11.1, although 3.12.0 has been released a week ago. I'm not sure if it's a cache issue, or maybe this PR https://github.com/getsentry/sentry-docs/pull/6963 has introduced the regression.

### Suggested Solution

When I look at one of the open PR deployments, e.g. this one https://sentry-docs-git-feat-sagp-auto-install-backend.sentry.dev/platforms/android/, the version is correct there, so sounds like a caching issue on the main branch, there's probably no cache on a new deployment, that's why it's correct there.

**Comment by romtsn** [comment]
@shanamatthews or @evanpurkhiser perhaps you could take a look at this, I can also take a look but it will probably take me more time?

**Comment by shanamatthews** [comment]
Hey @romtsn - pretty sure you're right, Vercel uses its cache whenever possible. I don't think this was caused by Evan's PR. I fixed this by turning off caching for production builds in Vercel.
