### ISSUE TITLE
Document required scopes for iOS Debug Symbols upload auth token

### ISSUE THREAD

**Issue by ojii** [getsentry/sentry-docs#763]
The documentation at https://docs.sentry.io/clients/cocoa/dsym/ instructs you to use an auth token (by the way, for some reason only the "without bitcode" section tells you where to create one) to upload the debug symbols to sentry, but it does not say what scopes that auth token requires.

**Comment by apparition47** [comment]
After trial and error, I was able to use `sentry-cli upload-dsym` with a API token with `project:write`+`project:admin` scopes.

**Comment by eric** [comment]
Are these still the correct scopes?

**Comment by bdrelling** [comment]
I'm wondering this as well. I'd expect to see this in the [documentation](https://docs.sentry.io/clients/cocoa/dsym/#upload-symbols-with-sentry-cli) when it instructs what kind of token to create.

**Comment by jd-lacey** [comment]
The documentation here is woefully inadequate. Come on guys this issue was logged almost a year ago and still no guidance.
