### ISSUE TITLE
Update platform dropdown list and landing page

### ISSUE THREAD

**Issue by lizokm** [getsentry/sentry-docs#7641]
### Core or SDK?

Core Sentry product

### Which part? Which one?

Homepage and platforms page

### Description

The dropdown list is missing some frequently-used SDKs like React. (We only list React Native).
![Screenshot 2023-08-15 at 1 26 52 PM](https://github.com/getsentry/sentry-docs/assets/26800704/385b404f-bf79-4fff-80a9-487c3b905bd7)

And when you land on the page that is supposed to show all SDKs a lot of them are also missing here.
![Screenshot 2023-08-15 at 1 28 07 PM](https://github.com/getsentry/sentry-docs/assets/26800704/73b30d11-3821-4624-ad08-f37a45aa1e3f)

### Suggested Solution

Update the page to reflect the SDKs we support.

**Comment by shanamatthews** [comment]
@lizokm - FYI the historical reason React isn't on that list is because it's a framework within the Browser JavaScript SDK. We only list top-level SDKs in this list, so all frameworks within JS, Python, etc. aren't listed.

Not to say we can't change the approach, but it might take a tiny bit of work since they're pulled in automatically today :D

**Comment by lizokm** [comment]
Great point @shanamatthews, maybe we leave the dropdown as is, but I think we should re-look at this page: https://sentry-docs-git-armcknight-docsmain-thread-frame-drops.sentry.dev/platforms/?original_referrer=https%3A%2F%2Fgithub.com%2Fgetsentry%2Fsentry-docs%2Fpull%2F7625. It's really easy to miss frameworks other than the top-level ones :)

**Comment by natikgadzhi** [comment]
Another thing I noticed with the list of platforms is that most platforms are programming languages, while Swift and Objective-C are bundled into `Apple`.

The existing SDK is written in big part in Objective-C, so it assumes it's running on an actual Mac OS / iOS / you name it. I know we're working on adding Vision OS support and example now https://github.com/getsentry/sentry-cocoa/issues/3362.

Hypothetically, folks who are using Swift on Server (SSWG / Vapor / etc) could use Sentry, but they can't use `sentry-cocoa`, they would have to either use the unified API directly, or write their own wrapper like this one: https://github.com/swift-sentry/swift-sentry — I have no idea if that one is alive, but it looks like it only has partial support for errors, no tracing and profiling yet.

All of that to say, perhaps in the future, we should have **Swift** platform, with iOS / MacOS etc frameworks and recommend `sentry-cocoa` to them for now, and perhaps `sentry-swift` for clean Swift projects that only rely on stdlib and Foundation?

As of today, it could be useful to name SwiftUI as a separate framework, as it's gaining popularity, and could just make it easier for folks to find what they are looking for at the framework menu level?

**Comment by shanamatthews** [comment]
@natikgadzhi - your suggestion sounds reasonable to me. 

@getsentry/product-owners-sdks-mobile are the right folks to have that discussion with.

**Comment by kahest** [comment]
@natikgadzhi thanks for chiming in! Once we support Swift on server we will for sure add this as a separate entry in the platforms and frameworks listings. As our `SwiftUI` support requires `sentry-cocoa` and the use is limited to the listed platforms, I feel it's intuitive for people to look for it under Apple. I'd rather not add too many platforms in the dropdown.

**Comment by natikgadzhi** [comment]
@kahest I've been contributing to a few SSWG libraries for a little bit — there's a lot of fun work, and what looks like a small but active community <3 

If/when you consider adding Swift on server support, I would love to help out! I don't yet have enough context and experience to try and implement full Swift on server sentry client with errors, tracing, and profiling, but I was looking at tracing via otel, and perhaps I could start with an experimental `sentry-swift` client with just the tracing support?

I think I can get it in front of folks working on Swift server libraries, and write some documentation and manuals on wiring things up via `swift-otel` and `swift-distributed-tracing` and friends.

What would be the right place to continue that conversation? 👀

**Comment by kahest** [comment]
Hey @natikgadzhi - thanks so much for reaching out! While we don't have concrete plans to support server-side Swift at the moment, we'd appreciate your contributions on that in the future. In general, you can always reach us on our [Discord server](https://discord.gg/sentry) and of course ping us/me on Github if you start working on something.

cc @philipphofmann @brustolin and also @stephanie-anderson for backend Swift :)

**Comment by lizokm** [comment]
Woo hoo, it's done!
