### ISSUE TITLE
Sentry CLI: set-commits --commit options are not clear within Release Management docs

### ISSUE THREAD

**Issue by Prithvirajkumar** [getsentry/sentry-docs#7642]
### Core or SDK?

Core Sentry product

### Which part? Which one?

sentry-cli

### Description

Within the [Commit Integration](https://docs.sentry.io/product/cli/releases/#sentry-cli-commit-integration) section, the docs mention:
you can manually specify the commits instead. To do this, pass the --commit parameter to the set-commits command in the format REPO_NAME@REVISION. You can repeat this for as many repositories as you have:
`sentry-cli releases set-commits "$VERSION" --commit "my-repo@deadbeef"`

However, this is unclear to developers, resulting in the following error which is vague:
`error: Unknown repo 'my-repo' `

### Suggested Solution

REPO_NAME@REVISION should be replaced with REPO_ORG/REPO_NAME@COMMIT_SHA

**Comment by natikgadzhi** [comment]
@Prithvirajkumar, from the docs, right below the example: 
> The repository name `my-repo` should match the name you entered when linking the repo, and should be in the form `owner-name/repo-name`.

Perhaps using that format in the example CLI command would clarify things indeed.

Want me to put that in a PR? Seems like it's under 10 characters change 🤦

**Comment by shanamatthews** [comment]
I think the note @lobsterkatie added in https://github.com/getsentry/sentry-docs/pull/7646 was meant to address this issue, so I'll close it. It seems pretty clear as-is.
