### ISSUE TITLE
Sentry cron HTTP documentation use different endpoints

### ISSUE THREAD

**Issue by buckett** [getsentry/sentry-docs#7664]
### Core or SDK?

Core Sentry product

### Which part? Which one?

Crons

### Description

The HTTP documentation on sentry cron has 2 different styles of endpoints (https://docs.sentry.io/product/crons/getting-started/http/):

- https://something.ingest.sentry.io/ - with the DSN embedded into the URL (in parts).
- https://sentry.io/api/0/ - with the DSN sent in the Authorization header.

Which is the preferred?

### Suggested Solution

Provide guidance on the preferred endpoint.

**Comment by evanpurkhiser** [comment]
Thanks for opening this issue @buckett.

I believe there is only one piece of documentation right now that recommends using the `sentry.io/api` endpoint, ["Creating or Updating a Monitor Through a Check-In (Optional)"](https://docs.sentry.io/product/crons/getting-started/http/#creating-or-updating-a-monitor-through-a-check-in-optional).

We will be replacing this example with a "ingest" endpoint once we complete https://github.com/getsentry/relay/issues/2334. Unfortunately right now the "legacy" api is the only API that supports upserts.

From an enduser perspective you can use whichever endpoint makes sense for your use case. For normal check-ins you can simply use the ingest API endpoint as described in the docs. But if you would like to make use of the upserting functionality, use the `sentry.io/api` endpoint as described.

In the future we may deprecate the `sentry.io/api` endpoints before moving the Crons feature out of beat, but will provide guidance on switching over the URLs.

**Comment by evanpurkhiser** [comment]
I will go ahead and add a note to the docs though!
