### ISSUE TITLE
Add info for Server-rendered HTML > Browser SDK trace propagation to Node docs

### ISSUE THREAD

**Issue by mydea** [getsentry/sentry-docs#7671]
We have section on this in the laravel docs: https://docs.sentry.io/platforms/php/guides/laravel/performance/distributed-tracing/

But not really anything similar for e.g. node or other languages.

We should add docs for these for all server languages, probably.

ref https://github.com/getsentry/sentry-javascript/issues/8843

**Comment by Lms24** [comment]
Not yet merged 😅
