### ISSUE TITLE
Clarify 'List a Project's Events' endpoint documentation

### ISSUE THREAD

**Issue by kerenkhatiwada** [getsentry/sentry-docs#7688]
### Core or SDK?

Core Sentry product

### Which part? Which one?

https://docs.sentry.io/api/events/list-a-projects-events/

### Description

Currently, the documentation mentions 'Return a list of events bound to a project' for [this endpoint](https://docs.sentry.io/api/events/list-a-projects-events/) and is titled 'List a Project's Events'. A more accurate title and message would be helpful to make it clear that this endpoint returns error events, rather than all events including transaction events.

### Suggested Solution

Refining the 'List a Project's Events' Endpoint Documentation for better clarity

**Comment by Dhrumil-Sentry** [comment]
@schew2381 @shanamatthews Some useful feedback for API docs

**Comment by schew2381** [comment]
Updated to `List a Project's Error Events`
