### ISSUE TITLE
Typo in docs JS example

### ISSUE THREAD

**Issue by olyasazonava** [getsentry/sentry-docs#7697]
### Core or SDK?

Platform/SDK

### Which part? Which one?

NodeJS, Automatic Instrumentation

### Description

Noticed typo in example, here is the link ```https://docs.sentry.io/platforms/node/performance/instrumentation/automatic-instrumentation/?original_referrer=https%3A%2F%2Fwww.google.com%2F```

and where in code 
```


Sentry.init({
  dsn:DSN,
  integrations: [
    // enable HTTP calls tracing
    new Sentry.Integrations.Http({ tracing: true }),
    // Automatically instrument Node.js libraries and frameworks
    // (This function is slow because of file I/O, consider manually adding additional integrations instead)
    ...Sentry.autoDiscoverNodePerformanceMonitoringIntegrations(),
    // Or manually add integrations of your choice. For example:
    Sentry.Integrations.Apollo(),
    Sentry.Integraionts.Postgres(), // HERE TYPO
  ],

  // We recommend adjusting this value in production, or using tracesSampler
  // for finer control
  tracesSampleRate: 1.0,
});
```

### Suggested Solution

Change Sentry.**Integraionts**.Postgres() to Sentry.**Integrations**.Postgres()

**Comment by lizokm** [comment]
Thanks so much for letting us know. We've fixed the error. #7699
