### ISSUE TITLE
Missing Rust docs on how to upload debug information files

### ISSUE THREAD

**Issue by shanamatthews** [getsentry/sentry-docs#7710]
### Core or SDK?

Platform/SDK

### Which part? Which one?

Rust SDK

### Description

Need docs on how to upload debug information files.

Recently got this question on Reddit: https://www.reddit.com/r/rust/comments/161wrx5/how_do_i_upload_debug_information_files_to_sentry/

This started an internal discussion where we realized this info isn't in docs.

### Suggested Solution

Add this info to the "Install" section on the Getting Started page for Rust: https://docs.sentry.io/platforms/rust/

**Comment by antonpirker** [comment]
This is probably related (or a duplicate?) to this one: https://github.com/getsentry/sentry-docs/issues/9625

**Comment by szokeasaurusrex** [comment]
@antonpirker thanks for pointing this out. I am going to close this issue in favor of #9625, since that issue contains the information we should add to the docs
