### ISSUE TITLE
Default sample rates not documented

### ISSUE THREAD

**Issue by tsongas** [getsentry/sentry-docs#7764]
### Core or SDK?

Platform/SDK

### Which part? Which one?

Browser JavaScript

### Description

The `sampleRate` [documentation](https://docs.sentry.io/platforms/javascript/configuration/sampling/#sampling-error-events) fails to state the default sample rate if a sample rate is not specified.

### Suggested Solution

Please state the default sample rate.

**Comment by Lms24** [comment]
Hi, good point, we should add the defaults there. Fwiw, defaults are mentioned in the SDK [configuration](https://docs.sentry.io/platforms/javascript/configuration/options/#sample-rate) page
