### ISSUE TITLE
Not possible to use superuser with the API

### ISSUE THREAD

**Issue by max-wittig** [getsentry/sentry-docs#7778]
## Important Details

How are you running Sentry?

* [x] On-Premise docker [Version 10.0.0]
* [ ] Saas (sentry.io)
* [ ] Other [briefly describe your environment]

## Description

Some API endpoints require superuser permissions (e.g. https://sentry-instance.com/api/0/internal/stats/, but even when I create a superuser on the commandline and use the `Auth Token` from this user, I just get this message:

```json
{
  "detail": {
    "message": "You need to re-authenticate for superuser.",
    "code": "superuser-required",
    "extra": {}
  }
}
```

How do I re-authenticate? I've checked all the boxes in the API menu

![image](https://user-images.githubusercontent.com/6639323/73467034-0280e580-4383-11ea-8597-7e60b79190d1.png)

## Steps to Reproduce

1. Host sentry on premise
2. Create superuser
```sh
root@ec1c9b02cea0:/usr/src/sentry# sentry createuser
16:02:23 [WARNING] sentry.utils.geo: settings.GEOIP_PATH_MMDB not configured.
16:02:27 [INFO] sentry.plugins.github: apps-not-configured
Email: max@localhost
Password: 
Repeat for confirmation: 
Should this user be a superuser? [y/N]: y
User created: max@localhost
root@ec1c9b02cea0:/usr/src/sentry# 
```
3. Create token with superuser and try to call the `api/0/internal/stats/` endpoint

### What you expected to happen

I should work and grant the superuser permission to the endpoint

### Possible Solution

[If you have an idea on how this could be solved include that detail here.]

**Comment by chadwhitacre** [comment]
Moving to docs repo, I think this is a sentence or two on https://docs.sentry.io/api/auth/, yes?

> You will not be able to query any superuser endpoints via a non-session token. Superuser has escalated permissions, has an idle timeout, maximum session length, and requires re-auth to re-enable. This is entirely managed via the session and shouldn't be achievable via the API (though that's not a promise).

Something like that?

**Comment by vivianyentran** [comment]
@sentaur-athena What are your thoughts on this issue? Is this still relevant or can we close this?

**Comment by vivianyentran** [comment]
apis for self-hosted aren't documented in sentry-docs so we'll close for this for and bring this up with the owners for self-hosted sentry
