### ISSUE TITLE
Question: how to use EventHandler properly?

### ISSUE THREAD

**Issue by talal** [getsentry/sentry-docs#778]
_Disclaimer: I am new to Python therefore excuse the long post_ 😅 

I'm looking to integrate Sentry with [OpenStack Swift](https://docs.openstack.org/swift/latest/). 

#### Backgroud (in case you are not familiar with Swift):
Swift has different services (each service has its own system process) like `proxy-server`, `object-expirer`, `account-server`, etc. Each service has its loggers and some services spawn multiple processes.

<details>
 <summary>Example</summary>

 ```sh
docker exec -i -t onlyone /bin/bash
root@onlyone:$ ps aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.0  0.0   4452   856 pts/0    Ss+  17:40   0:00 /bin/sh -c /usr/local/bin/startmain.sh
root         7  0.0  0.1  17988  2940 pts/0    S+   17:40   0:00 /bin/bash /usr/local/bin/startmain.sh
root        20  0.0  0.6  51444 13448 ?        Ss   17:40   0:00 /usr/bin/python /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
swift       22  1.8  1.2  97128 26308 ?        S    17:40   0:14 /usr/bin/python /usr/bin/swift-container-server /etc/swift/container-server.conf
swift       23  0.0  1.1  84600 24036 ?        S    17:40   0:00 /usr/bin/python /usr/bin/swift-account-reaper /etc/swift/account-server.conf
swift       24  0.0  1.2  85056 25140 ?        S    17:40   0:00 /usr/bin/python /usr/bin/swift-object-replicator /etc/swift/object-server.conf
swift       25  0.0  1.1  84048 23316 ?        S    17:40   0:00 /usr/bin/python /usr/bin/swift-account-auditor /etc/swift/account-server.conf
swift       26  0.0  1.1  84452 24388 ?        S    17:40   0:00 /usr/bin/python /usr/bin/swift-object-auditor /etc/swift/object-server.conf
swift       27  0.0  1.2  89096 26544 ?        S    17:40   0:00 /usr/bin/python /usr/bin/swift-container-sync /etc/swift/container-server.conf
swift       28  0.0  1.2  84916 24920 ?        S    17:40   0:00 /usr/bin/python /usr/bin/swift-account-replicator /etc/swift/account-server.conf
swift       29  1.8  1.2  89900 25272 ?        S    17:40   0:14 /usr/bin/python /usr/bin/swift-account-server /etc/swift/account-server.conf
root        30  0.0  0.1  17972  2780 ?        S    17:40   0:00 /bin/bash -c source /etc/default/rsyslog && /usr/sbin/rsyslogd -n -c3
swift       31  1.8  1.2  84528 26604 ?        S    17:40   0:14 /usr/bin/python /usr/bin/swift-proxy-server /etc/swift/proxy-server.conf
swift       32  0.0  1.1  84484 24484 ?        S    17:40   0:00 /usr/bin/python /usr/bin/swift-object-updater /etc/swift/object-server.conf
syslog      33  0.0  0.1 182116  3132 ?        Sl   17:40   0:00 /usr/sbin/rsyslogd -n -c3
memcache    34  0.0  0.2 131872  5660 ?        Sl   17:40   0:00 /usr/bin/memcached -u memcache
swift       60  0.0  1.3 175760 27068 ?        Sl   17:40   0:00 /usr/bin/python /usr/bin/swift-container-server /etc/swift/container-server.conf
swift       61  0.0  1.2 168668 26552 ?        Sl   17:40   0:00 /usr/bin/python /usr/bin/swift-account-server /etc/swift/account-server.conf
swift       64  0.1  1.5 167288 31376 ?        Sl   17:40   0:00 /usr/bin/python /usr/bin/swift-proxy-server /etc/swift/proxy-server.conf
root        66  0.0  0.0   4392   672 pts/0    S+   17:40   0:00 tail -n 0 -f /var/log/syslog
root       148  1.5  0.1  18180  3348 pts/1    Ss   17:53   0:00 /bin/bash
root       163  0.0  0.1  15576  2156 pts/1    R+   17:53   0:00 ps aux
```
</details>
<br>

Swift [documentation](https://docs.openstack.org/swift/latest/admin_guide.html#custom-log-handlers) states support for custom log handler hooks and lists [an example](https://github.com/pandemicsyn/swift-sentry/blob/master/swift_sentry/__init__.py) for these handler hooks which implements Sentry integration.

Since the example listed ind the docs uses the old `python-raven` SDK and hasn't been updated in 6 years, I wanted to write something similar using the new SDK that I could use.

#### Problem

The problem is that I am seeing multiple events in the Sentry dashboard with the following implementation:

```python
import logging
from sentry_sdk import init
from sentry_sdk.integrations.logging import EventHandler

# dsn is specified through the SENTRY_DSN env variable
init()

# the parameters for the sentry_logger is standard boilerplate for swift customer log handler hooks
# from what I understand also for getLogger and LogAdapter object
def sentry_logger(conf, name, log_to_console, log_route, fmt, logger, adapted_logger):
    sentry_handler = EventHandler()
    sentry_handler.setLevel(logging.ERROR)
    logger.addHandler(sentry_handler)
```

Each service has a `.conf` file and the logger handler hook is loaded by adding the following to the `.conf` file:

```ini
log_custom_handlers = module_name.sentry_logger, other_custom_hooks, ...
```

I am seeing 6 log entries for some specific log message in the Swift's docker container log. For example, six log messages for the following entry:

```sh
Feb 17 18:20:32 onlyone proxy-server: Object HEAD returning 503 for [] (txn: tx8b127fa760de469984ac8-005c69a5f0) (client_ip: 172.17.0.1)
```
but in the Sentry dashboard I see 30 events of this log message. This pattern is repeated for other events so for each event 4 additional events are being sent.

The example listed in the Swift docs that uses the `raven` SDK has a similar setup:

```python
import eventlet
import logging


def sentry_logger(conf, name, log_to_console, log_route, fmt, logger, adapted_logger):
    # conf.get allows to read settings from the configuration dict (.conf file for the specific service)
    sentry_dsn = conf.get("log_sentry_dsn", None)
    sentry_log_level = getattr(
        logging, conf.get("log_sentry_level", "ERROR").upper(), logging.ERROR
    )
    if sentry_dsn:
        raven_logging = eventlet.import_patched("raven.handlers.logging")
        sentry = raven_logging.SentryHandler(sentry_dsn)
        sentry.setLevel(sentry_log_level)
        logger.addHandler(sentry)
```

With the old approach I also duplicate events, but the number of duplicates are different. Same test case was used as stated above, in the container log there are 6 log messages for some event but in the dashboard there are 21 events.

The problem is resolved if I just use `init()` without the `EventHandler`. I understand this much that multiple `EventHandler` are added to the `logger` inside the function which results in multiple events.

#### Question

My question is should I just use the `sentry_logger` function as a no-op so that I can specify it in the `.conf` file (`log_custom_handlers = my_module.sentry_logger`) and when the Swift service loads my module, the `init()` will do its work and initialise Sentry for the runtime of some services' some specific process. 

Or is there something that I am missing regarding the `EventHandler` that would help my achieve something more idiomatic with regards to Swift customer log handler hooks, having a no-op just for doing module level `init()` seems a bit weird.

Thank you in advance!

**Comment by untitaker** [comment]
If I understand you correctly, you're asking which of the two is better:

```python
def sentry_logger1(..., logger, ...):
    init(DSN, default_integrations=False)  # do not add eventhandler automatically
    logger.addHandler(EventHandler())

def sentry_logger2(..., logger, ...):
    init(DSN)  # add eventhandler automatically
```

I would argue that `sentry_logger2` is better even if it looks weird. The reason is that the `LoggingIntegration` (which is used in `sentry_logger1` but not in `sentry_logger2`) will also set up `BreadcrumbHandler` automatically, which adds the last `n` log entries to each event. This might give you useful context in events. Additionally the code in `sentry_logger2` will register the handlers for **all** loggers, not just whatever logger swift decides to give you control over. Of course you can set all of this up manually like in `sentry_logger2` (`addHandler(BreadcrumbHandler()`, and so on), but why? You'd be just duplicating code from the SDK itself.

A reason to choose `sentry_logger1` would be if the monkeypatching magic in `sentry_logger2` causes problems, but I don't think this is likely.

If you want to iterate on `sentry_logger1` to make it more idiomatic, I would suggest asking in the OpenStack Swift community for something like this:

>How can I run arbitrary Python code as early as possible on startup?

Because that's what you're basically (mis)using their custom logging handler feature for. Which is still fine IMO if there's no other way.

**Comment by talal** [comment]
First of all thank you for the swift response 😄 

You are right, that is exactly what I wanted to ask. I will ask the Swift community for suggestions on arbitrary code execution at startup but I believe in the end the approach that you suggested is the best and I will end up going with that.

Some follow-up questions in order to a get a better understanding of Sentry:

```python
def sentry_logger1(..., logger, ...):
    init(DSN, default_integrations=False)
    logger.addHandler(EventHandler())

def sentry_logger2(..., logger, ...):
    init(DSN)
    logger.addHandler(EventHandler())

def sentry_logger3(..., logger, ...):
    init(DSN)
```

1. `sentry_logger1` doesn't work for me, no events are sent to Sentry regardless of adding `EventHandler` explicitly.
2. Taking `sentry_logger2` as an example, the reason for seeing duplicate events in Sentry is because the `EventHandler` is added multiple times for the same `logger` since `sentry_logger` hook is called for each logging event. 
If we don't take into consideration the calling of logger hook by Swift and just proceed with the notion that the functions is called once but there are multiple `logger.addHandler(EventHandler())` for the same `logger`, this would result in multiple events?
3. Taking `sentry_logger3` as an example, is it better to call `init()` inside the function or at the module level in the `__init__.py` file?
This is similar to my question above so basically does calling `init()` multiple times for the same python process (runtime) poses an issue?
A simple test case shows that it doesn't have any effect on the number of events sent but I wanted to get your opinion on which is better.

**Comment by untitaker** [comment]
1.  This is a bug, I'll fix this in 0.7.3. I remembered this working differently.
2.  I am not sure about the question, but I think you understand what is happening.
3.  Import-level is better in theory, but calling `init` multiple times should not be an issue. The latest `init` will overwrite the previous one.

**Comment by talal** [comment]
@untitaker Thank you for taking the time to answer all my questions, it is much appreciated 😄

**Comment by untitaker** [comment]
cool, btw 0.7.3 is released which should fix that case where you use
`EventHandler` explicitly with `default_integrations=False`. :)

**Comment by talal** [comment]
Wow, that was fast :)
