### ISSUE TITLE
Wrong SDK version for Routing events to different projects in Micro Frontend Support

### ISSUE THREAD

**Issue by robinvdbroek** [getsentry/sentry-docs#7809]
### Core or SDK?

Platform/SDK

### Which part? Which one?

SDK

### Description

When trying to implement makeMultiplexedTransport the docs are specified on SDK versions > 7.50.0 or higher. However, the latest changes since 7.59.0 implement additional features to send events to specified releases. Between 7.50.0 and 7.59.0 there will be a build error if one tries to follow the docs. 

### Suggested Solution

Improve the docs to suggest that 7.59.0 or higher is required, or provide an example for 7.50.0 that will not result in a build error.

**Comment by lforst** [comment]
Thanks for raising!
