### ISSUE TITLE
Unclear wording for `attachStackTrace` configuration option

### ISSUE THREAD

**Issue by whitep4nth3r** [getsentry/sentry-docs#7815]
### Core or SDK?

Core Sentry product

### Which part? Which one?

Configuration options

### Description

The `attachStackTrace` configuration doesn't explicitly define the value type of the option (boolean, string, etc).

Whereas most other configuration options like this one are true/false, the documentation states that this option is `off` by default, which implies that this option value is a string type, of `off/on`. This is confusing as the wording doesn't specify how to turn this on, and I expected a boolean value here to match the others.

Do we turn this on using the `on` string, or by setting `attachStackTrace` to `true`?

[Link to relevant docs section](https://docs.sentry.io/platforms/node/guides/express/configuration/options/?original_referrer=https://www.google.com/#attach-stacktrace)

### Suggested Solution

If the configuration is `true/false`, specify that it is `false` by default. Otherwise, indicate that to enable this configuration option, you need to specify the `on` value.

As an aside, which is out of scope of this, it would be _super_ helpful to see all of the configuration options presented in code, to be able to reference the value types of the options, just like how some of the options (3) are shown in code at the top of the "Basic Options" page.

**Comment by lforst** [comment]
Thanks for raising this! We can't change this to `true` and `false` because these docs are shared between all sdks but we can at least not make it seem like on and off are keywords.

**Comment by whitep4nth3r** [comment]
Thank you!
