### ISSUE TITLE
Replay: Document examples where `replay.start` can be used to sample sessions

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-docs#7839]
We often receive requests to sample sessions based on some conditions other than the already offered 'on error' or just by rolling a dice on a new session.

Common examples are:

* I'd like to always capture a Replay for a specific user
* If a user browsers certain page, start recording
* When a user submits feedback/ticket

These can be achieved today by calling `replay.start` programatically.

It's isn't always clear to developer how it can be achieved, who ask us for examples or best practices.

**Comment by billyvg** [comment]
@bruno-garcia I added examples for the first 2 points, I don't think the third is very common
