### ISSUE TITLE
Docs should call out any differences on native errors captured by React Native SDK vs native iOS/Android SDKs

### ISSUE THREAD

**Issue by shanamatthews** [getsentry/sentry-docs#7865]
### Core or SDK?

Platform/SDK

### Which part? Which one?

React Native SDK

### Description

Feedback on the RN SDK from a new customer, Metamask (Consensys):

Call out any differences in docs on native errors captured by React Native SDK vs native iOS/Android SDKs

For example, if you want to know what the `ui.load` is for iOS and Android, the docs should have links for these on the React Native page here: https://docs.sentry.io/platforms/react-native/

### Suggested Solution

see description

**Comment by krystofwoldrich** [comment]
Do we have any more information about what is missing in the docs?

The native errors/crashes are the same both for RN and native apps, as the crash is always processed by the native SDK.
