### ISSUE TITLE
Mentioning of Rust SDK in Flutter platform is a mistake?

### ISSUE THREAD

**Issue by gd08xxx** [getsentry/sentry-docs#7877]
### Core or SDK?

Platform/SDK

### Which part? Which one?

Flutter

### Description

https://docs.sentry.io/platforms/flutter/configuration/releases/?original_referrer=https%3A%2F%2Fwww.google.com%2F#sessions

'To benefit from the health data, you must use at least version 0.4.0 of the Rust SDK'

Is this correct?

### Suggested Solution

Remove the sentence?

**Comment by souredoutlook** [comment]
@matejminar might be interested in this one @snigdhas - not replay related
