### ISSUE TITLE
Add examples in sentry docs

### ISSUE THREAD

**Issue by awbacker** [getsentry/sentry-docs#789]
Using: Python

I am migrating to the new sentry SDK, and its going fairly smoothly except for the lack of examples in the documenation.  The docs describe _what_ the thing is (e.g. send_default_pii) but not how to use it.  In the case of PII its pretty clear its a boolean.  

These things could use an example or two for each language:

*in_app_include* and *in_app_exclude*

What format should this string array take?  `mymodule` or `mymodule.`?  will one of them work or fail, should I included the dot to ensure only my exact module and descendants?

*before_send* and *before_breadcrumb*

What is the format of this function (just takes a single param? etc).  What are the object types the function receives so I can look them up and see what my options are.  A simple example function would be enough (with type annotations, perhaps).  

Some others are also unclear (like url black/white list) but not available in python. 

In general I feel the new docs site has led to less helpful content in general due to the big unification (though it is easier to find.)  It feels specific content has been reduced somewhat, and the examples & discussion of features is now a 3.5/5 down from 5/5 :)

**Comment by awbacker** [comment]
The `before_send` (python) event is also misdocumented, as it seems to take `(event,hint)` from the sentry source code.  

Also noticed that there isn't a lot of arg checking on options initialization, which just leads to errors at runtime rather than informative error messages.  For instance, a common convention is a dotted path to a function (e.g `before_send='proj.mod.my_func'`), which will just fail.

**Comment by untitaker** [comment]
* before-send: the option should link to https://docs.sentry.io/error-reporting/configuration/filtering/?platform=javascript#before-send
* in-app-include: we should do the same thing as before-send, have a separate page for explaining what we have it for
* arg checking in python in particular: yes, we should do this, will open issue on sentry-python
* I think there's a decent amount of examples, but inter-page linking is just not enough. There could be a lot more links on the configuration page in particular

**Comment by awbacker** [comment]
@untitaker Thanks for that link.  Agreed, its a little hard to discover now.  I'm guessing part of that is a common entry point is platforms/python (etc) rather than error reporting directly.  For

I also found an interesting breadcrumb case (that just crashed a request).  In at least one case I get an `AnnotatedValue` as the breadcrumb.message, and I was expecting a string.  The whole event looks like this:

```
{
    category: 'query', 
    message: <sentry_sdk.utils.AnnotatedValue object at 0x7fd6e7cf2048>, 
    timestamp: datetime.datetime(2019, 2, 26, 11, 36, 29, 800470), 
    type: 'default'
}
```

For now I just wrap up all my filters in an exception handler, because I now know I have _no idea_ what is going to come in some of the fields.  It would be good, though I am betting quite difficult, to document what might actually be in the event.

**Comment by untitaker** [comment]
@awbacker I am thinking of using Python's type hints for this and generating docs out of that. I'll bring this up.

**Comment by awbacker** [comment]
@untitaker Its not the parameters themselves (they are dics), but the values inside the event object itself.  Not sure how you could really do that even with type hints.  Only option I see would be a separate `BreadcrumbEvent` class in some fashion, which is not very flexible. 

I'm curious to see what you guys come up with though.  

I have to say that I really like the new SDK, the filters, and integrations model.  Its worked great for me so far.  My small struggles here don't represent the whole picture :)

**Comment by untitaker** [comment]
This thing here: https://mypy.readthedocs.io/en/latest/more_types.html#typeddict

I tried this yesterday in a different context (client options) and it seems that IDEs have poor support :(

**Comment by PeloWriter** [comment]
Closing as this issue is pretty dated (and we've completed many updates since the initial issue was opened). Glad to know things are working well for you, @awbacker
