### ISSUE TITLE
NullReferenceException on Dispose()

### ISSUE THREAD

**Issue by nicolaigj** [getsentry/sentry-docs#791]
Hi! 

We have a ASP.NET Framework API project using .NET Framework 4.6.2 and we are using Sentry SDK version 1.1.2. I struggled a bit finding documentation on how to use sentry in a project without a main method so I could wrap sentry SDK around the program, so I ended up using this documentation on [Entity framework](https://github.com/getsentry/sentry-docs/blob/master/src/collections/_documentation/platforms/dotnet/entityframework.md) and it works quite well when I configured Sentry in Global.asax. 

Today I received an error in Sentry dashboard that we got a NullReferenceException on sentrySDK.Dispose(). Is the documentation still valid? Should we call Dispose()? It reports other errors as normal, so it works, but the error was quite strange. 

Stack trace in Sentry
```
System.NullReferenceException: Object reference not set to an instance of an object.
  File "D:\a\1\s\ProductAPI\Global.asax.cs", line 57, col 13, in Dispose
    Void Dispose()
  Module "System.Web.HttpApplication", in DisposeInternal
```
The code that triggered the exception
```csharp
public override void Dispose()
{
    sentrySDK.Dispose(); //This is line 57 in the code
    base.Dispose();
}
```

The full configuration in Global.asax with unrelated code omitted. 
```csharp
public class WebApiApplication : System.Web.HttpApplication
{
    private IDisposable sentrySDK;
    protected void Application_Start()
    {
        // Omitted
        var appSettings = container.GetInstance<IConfigurationManager>();

        // Omitted

        sentrySDK = SentrySdk.Init(o =>
        {
            o.Dsn = new Dsn(appSettings.GetString("sentryDSN"));
            o.Environment = appSettings.GetString("sentryEnv");
        });
    }

    private Container RegisterDependencies()
    {
      // Omitted code
    }

    // Global error catcher
    protected void Application_Error()
    {
        var exception = Server.GetLastError();
        SentrySdk.CaptureException(exception);
    }

    public override void Dispose()
    {
        sentrySDK.Dispose();
        base.Dispose();
    }
}
```

**Comment by untitaker** [comment]
@nicolaigj this is really better reported at https://github.com/getsentry/sentry-dotnet rather than here

**Comment by nicolaigj** [comment]
Okay, I'll close this one.
