### ISSUE TITLE
Feedback report: The documentation around beforeSend seems wrong. It says it's part of transportOptions, but it is not. It also does not expect a string to be returned.

### ISSUE THREAD

**Issue by shanamatthews** [getsentry/sentry-docs#7920]
### Core or SDK?

Platform/SDK

### Which part? Which one?

JavaScript SDK

### Description

The documentation around beforeSend seems wrong. It says it's part of transportOptions, but it is not. It also does not expect a string to be returned.

Internal link to feedback report: https://sentry.sentry.io/feedback/docs:26ede80d9a0945e4a3ce11a622bfebeb/?project=1267915&referrer=feedback_list_page&statsPeriod=14d

### Suggested Solution

Review JavaScript `beforeSend` docs for accuracy

**Comment by lforst** [comment]
@shanamatthews The link in this issue is dead for me. Would you mind explaining which part of the docs this feedback is referencing? I searched a bit but couldn't find it. Thanks!

**Comment by shanamatthews** [comment]
the user was on the electron set up page when they sent in this feedback: https://docs.sentry.io/platforms/javascript/guides/electron/ so I think this is referencing the [offline support code sample](https://docs.sentry.io/platforms/javascript/guides/electron/#offline-support)

**Comment by lforst** [comment]
The docs are correct. My guess is the user is using an outdated SDK version that doesn't have this field yet. The version that introduced `beforeSend` was released over a year ago so I think it is fine as-is.

Another case for a version dropdown in the docs.
