### ISSUE TITLE
Simplify Integration / Language Docs

### ISSUE THREAD

**Issue by bazilio91** [getsentry/sentry-docs#8]
https://docs.getsentry.com/hosted/clients/php/
IMHO this page should be an anchors list, not separate page, so I continuously read whole php guide.

Or subpages [like this](https://docs.getsentry.com/hosted/clients/php/install/) should have a footer with link on next page in section (Installation => Usage => Configuration)

Another good idea is to sepparate section nav (php client) from whole docs nav and move it to the right.

Nice new docs tho! :+1:

**Comment by dcramer** [comment]
Having subpages be in a separate nav is an interesting idea. That might be slightly technically challenging.

@ckj thoughts on that from UX point of view?

Refs GH-7 for client doc spec

**Comment by bazilio91** [comment]
Take a look at newrelic docs https://docs.newrelic.com/docs/agents/php-agent

**Comment by mitsuhiko** [comment]
From looking at it newrelic basically just shows the headlines on the overview page which would be easy to accomplish.

**Comment by mitsuhiko** [comment]
We changed this heavily now.  Feedback appreciated.

**Comment by bazilio91** [comment]
Much better now. :+1:
