### ISSUE TITLE
Feedback report: "docs for comparison operators don't show an example.. all these things dont work:  'version>6.0.0' 'version>=6.0.0' 'version > 6.0.0' 'version >= 6.0.0'... how do I use this thing?"

### ISSUE THREAD

**Issue by shanamatthews** [getsentry/sentry-docs#8125]
### Core or SDK?

Core Sentry product

### Which part? Which one?

Search comparison operators

### Description

https://docs.sentry.io/product/sentry-basics/search/#comparison-operators

docs for comparison operators don't show an example.. all these things dont work:  'version>6.0.0' 'version>=6.0.0' 'version > 6.0.0' 'version >= 6.0.0'... how do I use this thing?

### Suggested Solution

Verify which syntax works and add an example

**Comment by chargome** [comment]
closing as comparison operators are documented with examples
