### ISSUE TITLE
Feedback report:     only pg-native and pg are supported for databases. I think there is a large userbase of the npm postgres library which is the fastest library for postgres in node

### ISSUE THREAD

**Issue by shanamatthews** [getsentry/sentry-docs#8126]
### Core or SDK?

Platform/SDK

### Which part? Which one?

Node SDK database integrations

### Description

https://docs.sentry.io/platforms/node/performance/database/

only pg-native and pg are supported for databases. I think there is a large userbase of the npm postgres library which is the fastest library for postgres in node

### Suggested Solution

Verify that the list of supported databases on this page (https://docs.sentry.io/platforms/node/performance/database/) is correct.

**Comment by lizokm** [comment]
@mydea would appreciate it if you could take a look!

**Comment by mydea** [comment]
Hello!

With the upcoming v8 release of the JavaScript SDKs, we will use a new auto instrumentation library for Node. I hope this will also extend support there, we can try to test this when we have a first v8 release.

**Comment by lizokm** [comment]
Sounds good! Will check back after v8

**Comment by mydea** [comment]
This is now hopefully supported in v8, so we can close this.
