### ISSUE TITLE
Feedback report: Incorrect in-product link to docs

### ISSUE THREAD

**Issue by shanamatthews** [getsentry/sentry-docs#8136]
### Core or SDK?

Core Sentry product

### Which part? Which one?

In-product link is incorrect

### Description

"I clicked a link in the performance tab for "add integrations" and it was trying to take me to - https://docs.sentry.io/platforms/php/configuration/integrations/ but got a page not found, it appears the correct url is something more based off of https://docs.sentry.io/platforms/php/integrations/"

### Suggested Solution

Find where this link is in-product and fix, or add appropriate redirects.

**Comment by stayallive** [comment]
I think this got fixed somewhere along the way, I can't find the broken link anymore!

If it's still there please let us know where exactly (in the product or in the docs itself or...)
