### ISSUE TITLE
Token permissions for Sentry CLI are unclear

### ISSUE THREAD

**Issue by nfeltrin-dkb** [getsentry/sentry-docs#8163]
### Core or SDK?

Platform/SDK

### Which part? Which one?

CLI or other tools to upload mappings

### Description

The documentation to upload mappings (e.g. [for the CLI](https://docs.sentry.io/platforms/javascript/sourcemaps/uploading/cli/?original_referrer=https%3A%2F%2Fwww.google.com%2F#2-configure-sentry-cli)) states that a token is needed, but there is no documentation (at least that I could find) explaining which permissions this token should have.

This lack of information might be minimal for a developer uploading from local, but it becomes relevant when we want to have a token available to our CI solution; when creating an internal integration one can select the permissions that will be granted to the token, and it would be ideal to provide only the least necessary privilege.

### Suggested Solution

Provide a link to a general page whit an detailed list of permissions required for each operation

**Comment by lizokm** [comment]
Hi there, we have the following docs for token permissions:
https://docs.sentry.io/product/accounts/auth-tokens/
https://docs.sentry.io/api/permissions/?original_referrer=https%3A%2F%2Fgithub.com%2Fgetsentry%2Fsentry-docs%2Fissues%2F8163

Are either of these sources helpful for you?

**Comment by shanamatthews** [comment]
Hey @nfeltrin-dkb - the token you create via docs or via the linked "Auth Tokens" page in Sentry is an **Organization Auth Token** and is created with the correct, least-necessary permissions for uploading source maps. 

You can learn more about this new type of token here: https://docs.sentry.io/product/accounts/auth-tokens/#organization-auth-tokens
