### ISSUE TITLE
Docs site is sometimes unresponsive on initial load

### ISSUE THREAD

**Issue by JoshFerge** [getsentry/sentry-docs#8178]
### Steps to Reproduce

See  e.g. https://sentry.sentry.io/replays/71d868eaa95c470ea0c46a9f513dc2d4

Believe this happens due to https://answers.netlify.com/t/performance-issue-with-gatsby-link-pre-fetching-functionality/43769/5

### Expected Result

Docs site should load and users should be able to navigate around

### Actual Result

The docs site appears unresponsive

### Additional Info

Just creating this issue to track

**Comment by Lymah123** [comment]
Hi, as anyone started working on this?

**Comment by shanamatthews** [comment]
Hey @Lymah123 - no one has started working on it yet! Feel free to take a look!

**Comment by Lymah123** [comment]
Alright @shanamatthews. Can you assign me to the issue. Also, if you can add Hactoberfest label.

**Comment by Lymah123** [comment]
![Screenshot (1311)](https://github.com/getsentry/sentry-docs/assets/109049037/b73562ec-1c1c-458d-9fbc-89d4f897e18b)

@shanamatthews, I couldn't signup. 

But I guess the slow of the webpage is probably browser. I tried different browsers and I could figure the the changes of website speed.

**Comment by shanamatthews** [comment]
Hey @Lymah123 - sorry, you won't be able to access the replay link (https://sentry.sentry.io/replays/71d868eaa95c470ea0c46a9f513dc2d4) since that's in our company's Sentry instance :/

**Comment by Lymah123** [comment]
> Hey @Lymah123 - sorry, you won't be able to access the replay link (https://sentry.sentry.io/replays/71d868eaa95c470ea0c46a9f513dc2d4) since that's in our company's Sentry instance :/

Okay, thanks for the quick response. @shanamatthews 

What would you suggest ?

**Comment by shanamatthews** [comment]
@Lymah123 - this may be a trickier issue to debug, depending on what your familiarity with Gatsby is! 
We don't have a ton of known bugs that look easy to fix right now. If you're a CSS whiz, this one might be good: https://github.com/getsentry/sentry-docs/issues/7437

However, we have plenty of content issues that would be easy Hacktoberfest contributions!

**Comment by Lymah123** [comment]
@shanamatthews - Alright. I will check. Thank you!

**Comment by a-hariti** [comment]
Does the issue persist after the migration @stephanie-anderson ?

**Comment by JoshFerge** [comment]
I'm gonna guess no, and will go ahead and close this out (we see a large drop in rage clicks)
