### ISSUE TITLE
I can't find documentation about setupIntegrations

### ISSUE THREAD

**Issue by Zero-ruan** [getsentry/sentry-docs#8185]
### Core or SDK?

Core Sentry product

### Which part? Which one?

documentation

### Description

    const client = Sentry.getCurrentHub().getClient();
    client?.setupIntegrations();
There is only one paragraph of instructions, which is confusing for newbies.
<img width="936" alt="image" src="https://github.com/getsentry/sentry-docs/assets/67668275/6b15f30e-031a-44d5-910c-6b27a5cab99d">

![image](https://github.com/getsentry/sentry-docs/assets/67668275/11c5fa3b-65fb-41ec-95ce-82019f107b7b)

### Suggested Solution

Please improve this part

**Comment by lizokm** [comment]
Hi there! Thanks for the feedback, which integration were you trying to add?

**Comment by Zero-ruan** [comment]
> Hi there! Thanks for the feedback, which integration were you trying to add?

client?.setupIntegrations();
I want to know the specific instructions for using `setupIntegrations`

**Comment by shanamatthews** [comment]
Hey @Zero-ruan - I'm gonna pass this one over to the JS SDK team. I don't think you're meant to have to call this function. Adding the integrations to your `Sentry.init` should be enough! The team can confirm :D
