### ISSUE TITLE
Document source map pull from github

### ISSUE THREAD

**Issue by dimaqq** [getsentry/sentry-docs#819]
> Release Artifacts
> JavaScript and iOS projects can utilize release artifacts to unminify or symbolicate error stack traces. To learn more, please check out our iOS and JavaScript docs.

Ref: https://docs.sentry.io/workflow/releases/?_ga=2.243728325.1150502112.1551921850-55094994.1551748953%3F_ga&platform=python#release-artifacts

Suggests that js source maps will be pulled from git/github (by commit? by release? am I even correct?)

However, https://docs.sentry.io/platforms/javascript/sourcemaps/availability/ doesn't mention git/github.

**Comment by PeloWriter** [comment]
Closing - we've updated the source maps content.
