### ISSUE TITLE
Expand Distributed Tracing docs for JavaScript

### ISSUE THREAD

**Issue by cleptric** [getsentry/sentry-docs#8277]
https://docs.sentry.io/platforms/javascript/usage/distributed-tracing/ is missing some details, mainly a Custom Instrumentation page for Distributed Tracing. See https://docs.sentry.io/platforms/python/usage/distributed-tracing/custom-instrumentation/ as an example.

Make sure to document the usage of:

- [ ] `Sentry::getBaggage()`
- [ ] `Sentry::getTraceparent()`
- [ ] `Sentry::continueTrace()`

**Comment by Anton-Plagemann** [comment]
I am highly interested in this as I haven't figured out how to exchange tracing information when using websocket communication instead of http 😢

**Comment by mydea** [comment]
We have improved these docs quite a bit, hopefully they cover everything we need now, so closing this for now.
