### ISSUE TITLE
Unclear how to filter when a value is present/not empty

### ISSUE THREAD

**Issue by stevebissett** [getsentry/sentry-docs#8325]
### Core or SDK?

Core Sentry product

### Which part? Which one?

Discover

### Description

I am trying to filter in the Discover page where `user.email` is present and not blank/empty/null. 
I can't find reference in the docs how to do this, and it feels like an obvious use case. 

Page in docs suggested in Dropdown:
https://docs.sentry.io/product/reference/search/

### Suggested Solution

Add documentation to show how to filter for a non-empty column. 
If someone is able to point out how to do this, I am more than happy to put in a pull request into the documentation.

**Comment by udameli** [comment]
Hi @stevebissett,

You could use `has` filter like `has:user.email`. You can find it [here in the docs](https://docs.sentry.io/product/reference/search/searchable-properties/events/#has). Hope this helps!
