### ISSUE TITLE
Document Angular SDK installation for standalone component Angular projects

### ISSUE THREAD

**Issue by Lms24** [getsentry/sentry-docs#8342]
### Core or SDK?

Platform/SDK

### Which part? Which one?

@sentry/angular-ivy

### Description

Since Angular 16 (I belive), entire Angular applications can created without declaring a single `NgModule`, by [only using standalone components](https://angular.io/guide/standalone-components#bootstrapping-an-application-using-a-standalone-component). 

We currently instruct users to declare our providers (`ErrorHandler`, `TraceService`) in `app.module.ts` which doesn't exist in this case. 

### Suggested Solution

Add instructions how to declare providers in `app.config.ts`. There are no big differences except for the used Angular API but we should nevertheless cover this in our docs.  

Kind of blocked on https://github.com/getsentry/sentry-javascript/issues/9376 since I first want to figure out the best course of action around using the SDK in SSR Angular 17 apps.

**Comment by zip-fa** [comment]
I suggest you to create dedicated `provideSentryErrorHandler()` function, which will do this under-the-hood:

```
import { createErrorHandler } from ‘@sentry/angular-ivy’;

export function provideSentryErrorHandler(opts: SomeOptsType = {}) {
return {
      provide: ErrorHandler,
      useValue: createErrorHandler(opts)
    }
}
```

and use it in standalone application just by calling this fn like this:

```
providers: [
provideSentryErrorHandler({ showDialog: true })
]
```

**Comment by Lms24** [comment]
Good idea! Would you be interested in opening a PR for this? No worries if not, I'll get to it next week.

**Comment by zip-fa** [comment]
PR for provider fn or for docs?:)

**Comment by Lms24** [comment]
@zip-fa I was thinking about the provider helper functions but any help is appreciated :) 

I wrote up an issue to track the provider functions in the SDK repo: https://github.com/getsentry/sentry-javascript/issues/9407.

**Comment by vadimcoder** [comment]
We need this

**Comment by OAuthority** [comment]
Is there any update for this, please?

**Comment by Lms24** [comment]
Hey, sorry, no updates. It works in NGModule-less angular apps. It's not ideal but for now, to set up the SDK you can refer to an example app we use to E2E test the Angular SDK:
- [`src/main.ts`](https://github.com/getsentry/sentry-javascript/blob/develop/dev-packages/e2e-tests/test-applications/angular-18/src/main.ts)
- [`src/app.config.ts`](https://github.com/getsentry/sentry-javascript/blob/develop/dev-packages/e2e-tests/test-applications/angular-18/src/app/app.config.ts)

**Comment by garytube** [comment]
@Lms24  thx for the example. Hope to see it soon in the docs
