### ISSUE TITLE
Is withSentry neccessary for the v2 error boundary

### ISSUE THREAD

**Issue by Kobby-Bawuah** [getsentry/sentry-docs#8400]
### Core or SDK?

Core Sentry product

### Which part? Which one?

Remix, Cofiguration

### Description

For this [page](https://docs.sentry.io/platforms/javascript/guides/remix/manual-setup/#configuration), a user reached out about it not being clear if he needs to use `withSentry`. He currently interprets the docs to mean that he doesn't, instead, he has to do the steps below for the v2 error boundary. 

### Suggested Solution

The configuration could be made clearer for users.

**Comment by Lms24** [comment]
Looking at our Remix v2 e2e test app, I belive, wrapping `App` in `withSentry` is also required for Remix v2. 

cc @onurtemizkan can you confirm this please? 
 
The way I understand the manual setup docs, everything that is in the top part (above the V2 features section) is necessary for both, Remix v1 and v2. Only the things mentioned in the V2 features section need to be added _in Addition_. Perhaps we can point this out more clearly in the docs. @onurtemizkan let's see how we can improve this after you're done with Hapi.

**Comment by onurtemizkan** [comment]
Users still need to use `withSentry` to get proper `pageload` / `navigation` transactions on Remix v2. I'll try to open a PR to make it clearer in the docs 👍
