### ISSUE TITLE
Cannot install sentry on Angular 16 app

### ISSUE THREAD

**Issue by Joroooo** [getsentry/sentry-docs#8468]
### Core or SDK?

Platform/SDK

### Which part? Which one?

@Sentry

### Description

Running npm install --save @sentry/angular-ivy
on Angular 16 App returns error that Sentry requires Angular 17.02
Cannot install older Versions of Sentry

### Suggested Solution

Sentry should be install on Angular 16

**Comment by lizokm** [comment]
Hi there! Were you able to contact our support team and get your question answered?

**Comment by Lms24** [comment]
Hi @Joroooo I'm very sorry that your issue slipped through the cracks! We'll try to do better next time. 

If you're still experiencing the issue, would you be able to provide some more background on your setup? Our package requires any stable Angular version between 12 and 17 as a peer dependency:

https://github.com/getsentry/sentry-javascript/blob/8879fd544aba8ed456360ed81d88f82f610d93d9/packages/angular-ivy/package.json#L18-L20
