### ISSUE TITLE
Elixir docs use LoggerBackend (outdated) instead of LoggerHandler

### ISSUE THREAD

**Issue by shanamatthews** [getsentry/sentry-docs#8501]
### Core or SDK?

Platform/SDK

### Which part? Which one?

Elixir

### Description

https://x.com/leosoto/status/1724818979808563594?s=20

We reference LoggerBackend all over in the Elixir docs, but according to ^^ that is outdated and the v9 version of the library uses LoggerHandler instead.

This issue also exists in the in-product setup docs.

### Suggested Solution

Update docs with LoggerHandler info

**Comment by sl0thentr0py** [comment]
also update sentry stuff
https://github.com/getsentry/sentry/blob/77baa9f03796f106e5070e5d07c955c894ca2eb4/static/app/gettingStartedDocs/elixir/elixir.tsx#L196

**Comment by sl0thentr0py** [comment]
closing in favor of
https://github.com/getsentry/sentry-docs/issues/9463

**Comment by sl0thentr0py** [comment]
onboarding cleaned up 
https://github.com/getsentry/sentry/pull/67051
