### ISSUE TITLE
[Design Support] New Shiny Images for Docs that Reflect New Layout Changes

### ISSUE THREAD

**Issue by jas-kas** [getsentry/sentry-docs#8514]
## Doc Pages Impacted

Page 1: [Replay Page and Filters](https://docs.sentry.io/product/session-replay/replay-page-and-filters/)

Image should be now  "Replay Index -- Filters Focus.png" from GDrive

- Keep purple label
- Replace the underlying image with this "Replay Index -- Filters Focus.png"
- Either hide IP addresses OR make it be "Anonymous User"
- Drop "new" label from Selectors tab and widgets because this will not continue to be new

Page 2: [Session Replay](https://docs.sentry.io/product/session-replay/)

Image 1 should be now "Replay Details View.png" from GDrive

- Either hide IP addresses OR make it be "Anonymous User"

Image 2 should be now "Replay Details -- DOM.png"

- Either hide IP addresses OR make it be "Anonymous User"
- Same "Snapshot of DOM state" label and highlighting as before

Page 3: [Replay Details](https://docs.sentry.io/product/session-replay/replay-details/?original_referrer=https%3A%2F%2Fgithub.com%2F)

Image 1 should be now "Replay Details View - SCRUBBED TO ERROR.png" from GDrive

- Either hide IP addresses OR make it be "Anonymous User"
- The labels should be "Timeline", "Replay Player" and "Additional Components"
- Can we make the URL be "https://pokemon-market.sentry.dev/cart"

Image 2 should be now  "Replay Details View - SCRUBBED TO ERROR.png" from GDrive

- Either hide IP addresses OR make it be "Anonymous User"
- "Page Actions" label
 - Can we make the URL be "https://pokemon-market.sentry.dev/cart"

Image 3 should be now "Replay Details - TAGS.png" from GDrive

- Either hide IP addresses OR make it be "Anonymous User"
- "Tags" label
 - Can we make the URL be "https://pokemon-market.sentry.dev/cart"

--------

Google Drive for all high-quality images for download: https://drive.google.com/drive/folders/1ujrYpxRgB551AQWFd0ytSNylUEuCvlG6?usp=sharing 

Sub-ticket of this: https://github.com/getsentry/team-replay/issues/280

**Comment by Jesse-Box** [comment]
Hey @jas-kas, here is the first draft.

Let me know if theres something you want changed :)

![Image](https://github.com/getsentry/sentry-docs/assets/6508377/b2f7e166-63ea-44ec-b4ff-061206e9ddca)



![Image](https://github.com/getsentry/sentry-docs/assets/6508377/6f4c808f-9fc9-4c37-bc00-b0d9f0f310a0)



![Image](https://github.com/getsentry/sentry-docs/assets/6508377/19905bba-cac8-4c8e-8195-325aec640e38)



![Image](https://github.com/getsentry/sentry-docs/assets/6508377/94bfd004-0297-4e75-a25c-6661ea739853)



![Image](https://github.com/getsentry/sentry-docs/assets/6508377/505fa364-a89e-4b81-8ddc-a5bdc471f993)



![Image](https://github.com/getsentry/sentry-docs/assets/6508377/7966500f-d4b5-4c55-b186-76b16fd62db0)

**Comment by jas-kas** [comment]
@Jesse-Box These look great!!

A couple thoughts
- the pixelating of the IP addresses is almost not blurry enough that I can read the IP address still. what about light grey bar to show that it's been redacted?
- Replay Player should "highlight" show somehow also encompass the actual replay video 
- Can we hide the Tags that start with "sdk."?

**Comment by Jesse-Box** [comment]
>the pixelating of some of the IP addresses is almost not blurry enough that I can read the IP address still. what about light grey bar to show that it's been redacted?

I've pixelated the screenshots further so you _really_ cant comprehend the ip addresses

> Replay Player should "highlight" should somehow also encompass the actual replay video

See Below

![Image](https://github.com/getsentry/sentry-docs/assets/6508377/26e1ef63-0145-46c1-aad5-8ba627b545ca)

> Can we hide the Tags that start with "sdk."? (aka all the ones at the bottom there)

See Below

![Image](https://github.com/getsentry/sentry-docs/assets/6508377/6d6d15da-9f4a-4f39-86d8-ce0378954156)


The remaining assets

![Image](https://github.com/getsentry/sentry-docs/assets/6508377/be6ab3d6-6ac9-4ba8-8a18-c2cfd1af1e99)
![Image](https://github.com/getsentry/sentry-docs/assets/6508377/638ad635-726c-4f76-b5dc-9be92c312390)
![Image](https://github.com/getsentry/sentry-docs/assets/6508377/219e6a6e-9eac-4be8-86af-29735ca21142)
![Image](https://github.com/getsentry/sentry-docs/assets/6508377/4874037f-822e-4b10-879b-75414b71a33b)

**Comment by jas-kas** [comment]
@Jesse-Box thank you jesse! these look great.

Do you think I can save these images from the GH issue & maintain the quality or should you upload them to the same GDrive I linked above to maintain quality?

**Comment by jas-kas** [comment]
Updated docs - https://github.com/getsentry/sentry-docs/pull/8575
