### ISSUE TITLE
Tree Shaking guide improvements

### ISSUE THREAD

**Issue by lforst** [getsentry/sentry-docs#8520]
@untitaker gave some feedback about the treeshaking docs. I'll write down some stuff here:

- We could maybe give the page a different title to optimize for people searching for "Sentry Bundlesize" or similar. Maybe we call it "Minimizing Sentry SDK Bundle Size".
- The page should read more like a step by step guide. Right now it uses too much passive language.
- The links to the bundler plugin docs are confusing, as we don't really highlight the options there.
- Add a link to the tree shaking docs from the troubleshooting section.

**Comment by untitaker** [comment]
i suggest having a section in Troubleshooting that tells people to look at the treeshaking page, and then yeah, some smaller improvements to treeshaking page that link the user to the right docs for esbuild etc

**Comment by mydea** [comment]
We've updated these docs quite a bit, so closing this for now.
