### ISSUE TITLE
[Design Support] User Feedback Product Doc Images

### ISSUE THREAD

**Issue by jas-kas** [getsentry/sentry-docs#8565]
## User Feedback Product Doc Assets

**[1] Image 1 - Widget on External Site**

Represents both steps an end-user would take *while* also having the context of a demo/user's site: 
- Clicking the Floating Button 
- And then Clicking Seeing Form/Filling it out

See both Pokemart images [here](https://drive.google.com/drive/folders/1SUwgaBYfB1T0H2iLDC3z7OGoehGHSxlM)

**[2] Image 2 - Crash-Report Modal**

Taken from this page -  https://docs.sentry.io/platforms/javascript/enriching-events/user-feedback/?original_referrer=https%3A%2F%2Fdocs.sentry.io%2F%3Foriginal_referrer%3Dhttps%253A%252F%252Fdocs.sentry.io%252F#embeddable-javascript-widget

No action required from Design. This is here for when we insert images on the docs site.

**[3] Image 3 - User Feedback in Sentry**

Highlight each section of the page --
1. Left-side - "User Feedback List"
2. Right-side "User Feedback Details"
3. Top [page filters + search bar] - "Filtering"

See image titled "User Feedback Page" from  [here](https://drive.google.com/drive/folders/1SUwgaBYfB1T0H2iLDC3z7OGoehGHSxlM)

**[4] Image 4 - User Feedback Page Actions**

- Magnify "Assign"/"Resolve"/"Mark Unread" as Page Actions on the User Feedback Details
- Redact Michelle's email address

See image titled "User Feedback ---Page Actions.png" from [here](https://drive.google.com/drive/folders/1SUwgaBYfB1T0H2iLDC3z7OGoehGHSxlM)

**Comment by Jesse-Box** [comment]
@jas-kas @bruno-garcia 

Heres [3,4] assets required. Let me know if you want any changes :)

![Image](https://github.com/getsentry/sentry-docs/assets/6508377/16195dcc-0767-4f00-b57c-a1a27cfef258)
![Image](https://github.com/getsentry/sentry-docs/assets/6508377/8c45bcdc-e728-4764-8808-ea615d4ad86c)

**Comment by jas-kas** [comment]
@Jesse-Box Looks good! Thanks Jesse~

**Comment by Jesse-Box** [comment]
Hey @jas-kas see below my latest draft which includes all the assets you need :)
![Image](https://github.com/getsentry/sentry-docs/assets/6508377/1519225c-e097-49bb-aef6-454197374387)
![Image](https://github.com/getsentry/sentry-docs/assets/6508377/e818a6e0-46a1-4360-baad-fa228424c9fa)
![Image](https://github.com/getsentry/sentry-docs/assets/6508377/79cc09f5-a696-483b-a428-b8d99b5bfcfa)

**Comment by jas-kas** [comment]
Feedback from @ryan953 

> https://docs.sentry.io/product/user-feedback/
idk if we need the colors in the first
and the second, with the User Actions… needs more spacing inside the purple, and maybe a rounded purple border instead of squared

> with User Actions, it’s not clear if we magnified part of the screen,…or what,
The dropdown that we’re highlighting, right next to the purple line on the left makes it look funny, no continuity when i look from left to right

**Comment by jas-kas** [comment]
This is done
