### ISSUE TITLE
Add Dockerfile information

### ISSUE THREAD

**Issue by cjoecker** [getsentry/sentry-docs#8567]
### Problem Statement

I'm using `@sentry/remix` with Remix and deploying it with a docker container to AWS.
I couldn't find in the documentation that I need to add the `ARG SENTRY_AUTH_TOKEN` during the docker build to make Sentry work during `npm run build`. 

### Solution Brainstorm

It would be nice to have a small example on how to run the `npm run build` inside of a docker file safely in order to build the app authenticating Sentry.

For example:
## Build on docker
If your are using docker to deploy your application, you will need to authenticate Sentry during `npm run build`. For that, you need to do the following: 
1. Add `ARG SENTRY_AUTH_TOKEN` at the beginning of your file `Dockerfile`
1. Add `ENV SENTRY_AUTH_TOKEN=${SENTRY_AUTH_TOKEN}` before the `RUN npm run build` command in your `Dockerfile`
1. Add your sentry token to your pipeline secrets and on the build step.

**Comment by lforst** [comment]
@yuvi-pc Correct. I would advise against using the any build arguments for auth tokens as that will bake the auth tokens into the image. Instead I recommend using build secrets: https://docs.docker.com/build/building/secrets/

**Comment by yuvi-pc** [comment]
Thank you for the reply on my previous question.

Here is my docker file which runs on Azure pipeline however I keep getting 401 when mounting the secret. If i hardcode the SENTRY_AUTH_TOKEN, it works okay. The SENTRY_AUTH_TOKEN is an organisation token.

```
# 1. Install dependencies only when needed
FROM node:20-alpine AS base

RUN --mount=type=secret,id=SENTRY_AUTH_TOKEN \
	SENTRY_AUTH_TOKEN=$(cat /run/secrets/SENTRY_AUTH_TOKEN)


# 2. Rebuild the source code only when needed
FROM base AS builder
WORKDIR /app
COPY . .
RUN yarn install --frozen-lockfile

ENV NODE_ENV=production
ENV NEXT_PUBLIC_SENTRY_DSN="{{NEXT_PUBLIC_SENTRY_DSN}}"
ENV NEXT_PUBLIC_SENTRY_LOGGING_ENABLED="{{NEXT_PUBLIC_SENTRY_LOGGING_ENABLED}}"
ENV SENTRY_LOG_LEVEL=debug
ENV SENTRY_AUTH_TOKEN="{{SENTRY_AUTH_TOKEN}}"

RUN yarn build

# 3. Production image, copy all the files and run next
FROM base AS runner

WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV USE_HTTPS=true

RUN addgroup -g 1001 -S nodejs
RUN adduser -S nextjs -u 1001

COPY --from=builder /app/public ./public
COPY --from=builder /app/package.json ./package.json

# Automatically leverage output traces to reduce image size
# https://nextjs.org/docs/advanced-features/output-file-tracing
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
COPY --from=builder --chown=nextjs:nodejs /app/entrypoint.sh ./entrypoint.sh
COPY --from=builder --chown=nextjs:nodejs /app/next.config.js ./next.config.js
COPY --from=builder --chown=nextjs:nodejs /app/next-i18next.config.js ./next-i18next.config.js

RUN ["chmod", "755", "/app/entrypoint.sh"]

USER nextjs

EXPOSE 3000

ENV PORT 3000

ENTRYPOINT ["/app/entrypoint.sh"]

CMD ["node", "server.js"]
```

Am i right here thinking it is ideal to upload source maps during the build process? If i remove the `SENTRY_AUTH_TOKEN`, i will get an error indicating no source maps was uploaded.

**Comment by yuvi-pc** [comment]
It was azure pipeline issue. Once that is resolved, my source map is being uploaded to the sentry release

**Comment by Lms24** [comment]
@yuvi-pc does this mean we can close the issue?

**Comment by yuvi-pc** [comment]
@Lms24 I am not the original author for this issue. But you can use my docker file example in your documentation or I can raise a PR if you could point where i need to set it.

**Comment by mydea** [comment]
I'll close this as I believe this has been answered - feel free to open a PR if you feel this should be added to the docs somewhere, or else this issue is always there as a reference 🙏
