### ISSUE TITLE
Performance data is not sent in Sentry with vanilla PHP setup

### ISSUE THREAD

**Issue by Pum-purum** [getsentry/sentry-docs#8622]
### How do you use Sentry?

Self-hosted / on-premises

### SDK version

3.22

### Steps to reproduce

1. Include Sentry profile script in top of the page:

```php
\Sentry\init(['dsn'                  => $_SERVER['SENTRY_DSN'],
                  'environment'          => $_SERVER['SENTRY_ENV'],
                  'traces_sample_rate'   => 0.1
    ]);
```

### Expected result

Data appears in Performance section

### Actual result

Nothing. 

Another method - set up with Symfony bundle - works fine.

**Comment by stayallive** [comment]
Without warnings everywhere I think we have this one covered with this page: https://docs.sentry.io/platforms/php/tracing/instrumentation/automatic-instrumentation/ which users are directed towards when setting up their tracing.
