### ISSUE TITLE
profile page in docs doesn't explain what this does

### ISSUE THREAD

**Issue by peter-bilt** [getsentry/sentry-docs#8629]
### Core or SDK?

Core Sentry product

### Which part? Which one?

sentry javascript sdk

### Description

can you add an explaination of what this is / does?  right now it doesn't try to explain that at all

https://docs.sentry.io/platforms/javascript/profiling/?original_referrer=https%3A%2F%2Fwww.google.com%2F

### Suggested Solution

thank you

**Comment by mydea** [comment]
We have tweaked this page quite a bit and do reference places where we explain these things now, so I'm going to close this issue!
