### ISSUE TITLE
In-text definitions are kind of overkill and mess up copying and pasting

### ISSUE THREAD

**Issue by lobsterkatie** [getsentry/sentry-docs#8667]
### Steps to Reproduce

Copy some text that has a hover definition in it, like this:

![image](https://github.com/getsentry/sentry-docs/assets/14812505/76456f26-3306-4d6a-b7eb-4925c833f849)

### Expected Result

The selected text is copied.

### Actual Result

The definition inserts itself into the text. In the example above, what you get when you copy it is:

> The per-projectRepresents your service in Sentry and allows you to scope events to a distinct application. allocation you set is the minimum not the maximum number of events each project will get.

It'd be easy for someone to miss that this had happened, and even if they notice, they then have to both figure out what the heck happened and figure out exactly which text to get rid of (both of which are made harder by the fact that they probably haven't hovered over the defined word and therefore have never seen the inserted text before).

### Additional Info

There may be (hopefully is) a software fix for the above problem, but an easier fix for many of the spots is to not make so many words hoverable. I get the intention, and it's a good one in principle, but I feel like we've taken it too far when we define project twice in two consecutive paragraphs:

![image](https://github.com/getsentry/sentry-docs/assets/14812505/5ebb0edf-9c7b-4627-b191-64b5476e0a70)

(We actually define it a third time, later in the page.)

I'd argue that once per page is probably enough, and that it really should be the _first_ mention of the term. (In the example above, the word "project" has already been used five times before we define it.)

**Comment by a-hariti** [comment]
It seems like this issue is not relevant anymore

**Comment by a-hariti** [comment]
I explored it a bit out of curiosity.

The solution to this problem would've been this CSS on the definition `span`: `user-select: none;`
