### ISSUE TITLE
Add examples to integrations

### ISSUE THREAD

**Issue by rodolfoBee** [getsentry/sentry-docs#8680]
### Core or SDK?

Platform/SDK

### Which part? Which one?

https://docs.sentry.io/platforms/node/guides/express/performance/database/auto-instrument/

### Description

The documentation only has example for Mongo, but not for the other integrations.

### Suggested Solution

Add code examples with all available options for them.

**Comment by mydea** [comment]
We have updated these quite a bit, so closing this issue.
