### ISSUE TITLE
Document how to propagate a trace that starts on a server-side rendered webpage to the JS SDK

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-docs#8715]
Basically what we have here for PHP but without the custom function possibly:

https://docs.sentry.io/platforms/php/guides/laravel/performance/distributed-tracing/

We can document in the Browser/JS docs the `meta` tags, and on BE SDKs we document what helper functions exist if any (as PHP did above) ^

Seems to only be documented for PHP and Svelte:

<img width="525" alt="image" src="https://github.com/getsentry/sentry-docs/assets/1633368/8e3db56e-118b-4aad-951a-f61e6a8ea002">

This is relevant for several backend SDKs, for example:
* ASP.NET
* ASP.NET Core
* Spring
* Spring Boot
* Express
* Flask
* Django
* Ruby on Rails
* etc

**Comment by chargome** [comment]
closing as this is documented in https://docs.sentry.io/platforms/javascript/tracing/trace-propagation/
