### ISSUE TITLE
[User Feedback] Document how to add your own widget using the JS SDK API

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-docs#8752]
It's documented on the internal package's README:

https://www.npmjs.com/package/@sentry-internal/feedback#bring-your-own-widget

But not on the SDK docs itself:

https://docs.sentry.io/platforms/javascript/guides/react/user-feedback/

Or "sort" of is under "User Feedback API" but this only references the one that takes "event_id" and not the new API in `Feedback` to easily capture through `sendFeedback`

**Comment by jas-kas** [comment]
@bruno-garcia I think we have this documented: https://docs.sentry.io/platforms/javascript/guides/react/user-feedback/configuration/?original_referrer=https%3A%2F%2Fgithub.com%2Fgetsentry%2Fsentry-docs%2Fissues%2F8752#bring-your-own-widget
