### ISSUE TITLE
Still seeing hidden environments in filter dropdown

### ISSUE THREAD

**Issue by ogrubes** [getsentry/sentry-docs#8758]
### Core or SDK?

Core Sentry product

### Which part? Which one?

Filter UX

### Description

I've followed the guidance to hide old environments via project settings.
However, I'm still seeing those hidden environments in the dropdown.
Is there a cache to clear / a delayed reset / other activity that needs to happen before those envs are removed from my dropdown filter?

I was expecting that any env in the list at
https://promise.sentry.io/settings/projects/myproject/environments/hidden/
would no longer appear in the env dropdown on the issue or project pages.

### Suggested Solution

Update documentation to give guidance on when (how long it will take for) hidden envs take effect.
Or fix this bug :)

**Comment by ogrubes** [comment]
It appears that by the time I followed through with this request, the Hidden Envs are now removed from my list 👍 
So now just updating the docs to suggest it might take some time / how long would be appreciated.

**Comment by MichaelSun48** [comment]
Closing due to >6 months of inactivity after @jangjodi's response suggesting that this is no longer an issue - feel free to reopen if you're still experiencing this.
