### ISSUE TITLE
Browser JavaScript docs don't mention `networkDetailDenyUrls`

### ISSUE THREAD

**Issue by p-himik** [getsentry/sentry-docs#8769]
### Core or SDK?

Platform/SDK

### Which part? Which one?

Browser JavaScript

### Description

In the context of [this issue](https://github.com/getsentry/sentry-javascript/issues/8435) a new option have been added - `networkDetailDenyUrls`. However, the page at https://docs.sentry.io/platforms/javascript/session-replay/configuration/ only mentions its counterpart, `networkDetailAllowUrls`.

### Suggested Solution

Document `networkDetailDenyUrls`. Not sure whether it can be automated (or maybe it is, and there simply hasn't been a new deploy since the fix for that issue).

**Comment by mydea** [comment]
Hey,

thanks for bringing this up. We'll add this to the docs, just didn't get around to doing so yet!
