### ISSUE TITLE
Performance Monitoring is not available for the Sentry Python SDK version == 1.9.10

### ISSUE THREAD

**Issue by EatARainbow** [getsentry/sentry-docs#8771]
### Core or SDK?

Platform/SDK

### Which part? Which one?

Debian/python3-sentry-sdk

### Description

In my Django project which run in Debian bookworm, when i add "enable_tracing=True" in sentry_sdk.init(), it will throw error "Unknown option 'enable_tracing'" when start.
In Document, it says "Performance Monitoring is available for the Sentry Python SDK version ≥ 0.11.2.". Is this wrong?
In version sentry-sdk 1.39.1, it's OK.

### Suggested Solution

Get the correct min version to use Performance Monitoring

**Comment by sentrivana** [comment]
Hey @EatARainbow, this is indeed an oversight. A [fix](https://github.com/getsentry/sentry-docs/pull/9307) is on the way. Thanks for pointing this out to us!
