### ISSUE TITLE
node.js user feedback docs incorrect

### ISSUE THREAD

**Issue by mrhappyma** [getsentry/sentry-docs#8781]
### Core or SDK?

Core Sentry product

### Which part? Which one?

node.js

### Description

The [node.js user feedback docs](https://docs.sentry.io/platforms/node/user-feedback/) show importing the `@sentry/browser` package, and a `Sentry.captureUserFeedback` method that as far as I can find does not exist in the node api. I'm uncertian if this is a typo/copied content that was missed, or am I really supposed to install the web SDK for this?

### Suggested Solution

none

**Comment by bruno-garcia** [comment]
Thanks for raising. Opened a PR to fix this #9039
