### ISSUE TITLE
Python with_scope example shows push_scope use

### ISSUE THREAD

**Issue by daveoconnor** [getsentry/sentry-docs#8823]
### Core or SDK?

Platform/SDK

### Which part? Which one?

Python

https://docs.sentry.io/platforms/python/enriching-events/scopes/?original_referrer=https%3A%2F%2Fsentry.io%2F#using-platformidentifier-namewith-scope-

### Description

I was reading the documentation on "Local Scopes" and the section "Using `with_scope`" has an example which uses `push_scope()`, not `with_scope()`

Something in this documentation isn't clear., either the section heading or the code sample.

Also possible that this is missing a `with_scope()` example and a `push_scope()` section description. 

### Suggested Solution

Update documentation to correct information

**Comment by szokeasaurusrex** [comment]
This problem was also reported in #8888, and it was fixed in #9294
