### ISSUE TITLE
Documentation is not very clear for Open telemetry support for python

### ISSUE THREAD

**Issue by shijo-keyvalue** [getsentry/sentry-docs#8846]
### Core or SDK?

Platform/SDK

### Which part? Which one?

Open telemetry support for python docs

### Description

The details provided in https://docs.sentry.io/platforms/python/performance/instrumentation/opentelemetry/ is not very clear.
Its not mentioning where we need to add the opentelemetry specific code snippets.
If you guys can provide an example of code to to add opentelemetry integration and in that code , where we need to add this , then this will be more easy for developers who are new to opentelemetry and sentry.
![Screenshot from 2024-01-10 13-51-16](https://github.com/getsentry/sentry-docs/assets/92438495/96d249ba-06f1-454f-a709-32e7e4c36cf7)

### Suggested Solution

If you guys can provide an example of code to to add opentelemetry integration and in that code , where we need to add this , then this will be more easy for developers who are new to opentelemetry and sentry.

**Comment by sentrivana** [comment]
Should be fixed by https://github.com/getsentry/sentry-docs/pull/8863 -- the example in the docs should now fully work by itself without having to do anything in the background.
