### ISSUE TITLE
JavaScript Integrations: outdated docs

### ISSUE THREAD

**Issue by OliverJAsh** [getsentry/sentry-docs#885]
The migration guide and the docs say two different things. Is this integration enabled by default? I suspect it's not anymore, and the docs need updating.

https://github.com/getsentry/sentry-javascript/blob/f412f7b0f55bf1d2e2f7e1de712b9f82847815df/MIGRATION.md#upgrading-from-4x-to-5x

> Integrations that are now opt-in and were default before:
>
> - Dedupe (responsible for sending the same error only once)

https://docs.sentry.io/platforms/javascript/pluggable-integrations/#dedupe

> This is enabled by default and should not be disabled except in rare circumstances.

**Comment by OliverJAsh** [comment]
Bump

**Comment by PeloWriter** [comment]
Fixed in https://github.com/getsentry/sentry-docs/pull/886
