### ISSUE TITLE
JS/RN Custom Instrumentation pages should note that timestamps are in seconds

### ISSUE THREAD

**Issue by krystofwoldrich** [getsentry/sentry-docs#8861]
### Core or SDK?

Platform/SDK

### Which part? Which one?

JS/RN

### Description

https://docs.sentry.io/platforms/react-native/performance/instrumentation/custom-instrumentation
https://docs.sentry.io/platforms/javascript/performance/instrumentation/custom-instrumentation

- Context https://github.com/getsentry/sentry-react-native/issues/3517

### Suggested Solution

Adding a note about `startTimestamp` and `endTimestamp` being expected in seconds. Note: timestamps are currently not mentioned on the whole page so would also need to explain what they are, what they are used for, and how.

**Comment by mydea** [comment]
In v8, this will be updated in the process of aligning with OpenTelemetry Spans. We will accept second _and_ millisecond timestamps then, and convert internally where needed. We'll also accept a `Date`. So hopefully this will become "solved" there, pretty much. (We should still document this then, obviously!)

**Comment by mydea** [comment]
With v8, can we close this? You can now use both seconds or ms and stuff should generally work!
