### ISSUE TITLE
The Sentry.setUser function is poorly documented

### ISSUE THREAD

**Issue by boxed** [getsentry/sentry-docs#8880]
### Core or SDK?

Core Sentry product

### Which part? Which one?

browser SDK

### Description

User Sentry.setUser as the docs said. But if you do that, you get an error because setUser doesn't exist yet. I think it should.

See also https://stackoverflow.com/questions/71699244/where-to-set-sentrys-setuser-in-next-js-app for others with this problem

### Suggested Solution

Make setUser available at the very start. Ideally even before Sentry.init is called.

**Comment by mydea** [comment]
Hey,

I'm not sure I fully understand - `Sentry.setUser()` should always be available in recent versions of the SDK. Are you saying that this:

```js
import * as Sentry from '@sentry/browser';

Sentry.setUser(...);
```

is failing for you? If so, which package & version are you using? I'd ask you to open an issue here https://github.com/getsentry/sentry-javascript with more details, so we can debug this!

Or is it working, but not actually being set properly?

One potential reason is that you may be setting the user inside of a forked execution context - with `Sentry.setUser()`, this will set the user on the current scope, so it is only valid in there. If this is the case, you can use the new (and not yet documented very well) `getIsolationScope().setUser()` to set a user for the whole request. Or you can use `getGlobalScope().setUser()` to set a user globally (if you're using this in the client/browser environment, setting on the global scope is probably what you want).

**Comment by boxed** [comment]
I had this code:

```js
Sentry.init(....)
Sentry.setUser()
```

which fails with "

If I change it to:

```js
Sentry.init(...);
Sentry.configureScope(scope => scope.setUser({email: '{{ user.email }}'}));
```

then that works.

**Comment by boxed** [comment]
I copy pasted the url from the setup docs. I would assume that's the latest version you link to with the CDN.

**Comment by mydea** [comment]
Which URL, from which docs? In order to be able to help you, I need a bit more specific information. Are you using the Loader Script? If so, the docs explain here:

https://docs.sentry.io/platforms/javascript/install/loader/#guarding-sdk-function-calls

that since the loader is lazy-loaded, you can only use a limited set of global methods on it. You need to guard any other calls - in your case, what you should do is:

```js
 window.sentryOnLoad = function () {
   // in here, Sentry is ensured to be loaded & fully available
    Sentry.init(...);
    Sentry.setUser(...);
  };
```

as outlined here: https://docs.sentry.io/platforms/javascript/install/loader/#custom-configuration

**Comment by boxed** [comment]
No, I'm just doing what I understood from https://docs.sentry.io/platforms/javascript/ and doing Sentry.init() in a script block. Which works fine, except for this. I am starting to get the feeling this "getting started" part lead me astray :P

**Comment by mydea** [comment]
Hmm yeah, I see what you mean - this is mentioned below, but not sufficiently, that if you use this script tag, you need to configure your SDK differently 🤔 I'll see if we can clarify this a bit! Anyhow, if you follow what I mentioned above, it should work!

**Comment by mydea** [comment]
I opened a PR to clarify this here: https://github.com/getsentry/sentry-docs/pull/8890
