### ISSUE TITLE
Update mentions to `with_scope` from Python docs

### ISSUE THREAD

**Issue by szokeasaurusrex** [getsentry/sentry-docs#8888]
[This page](https://docs.sentry.io/platforms/python/enriching-events/scopes/#using-platformidentifier-namewith-scope-) in the Python Docs mentions a `with_scope` function, which does not exist anywhere in the Python SDK codebase. We should probably update references to `with_scope`, and replace them with the function users should use instead (likely `push_scope` per the code sample on the page).

@antonpirker and @sentrivana – if either of you have more historical context about what `with_scope` was or why it was changed, please update the issue

**Comment by sentrivana** [comment]
Likely an artifact caused by sharing docs across platforms. Looks very much like `push_scope` is what was meant; the docs even say:
```
This is typically called with_scope, push_scope or implemented as a function parameter on the capture methods, depending on the SDK. 
```
So we should substitute `with_scope` with `push_scope` and we should be good.
