### ISSUE TITLE
Can't upload source maps after running EAS Update => sentry-expo-upload-sourcemaps removed from npmjs

### ISSUE THREAD

**Issue by obasille** [getsentry/sentry-docs#8907]
### Steps to Reproduce

`npx sentry-expo-upload-sourcemaps dist`
From the [doc](https://docs.sentry.io/platforms/react-native/sourcemaps/uploading/expo/#manual-upload-for-eas-updates]).

### Expected Result

Installation and execution of the package

### Actual Result

E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/sentry-expo-upload-sourcemaps - Not found
npm ERR! 404
npm ERR! 404  'sentry-expo-upload-sourcemaps@latest' is not in this registry.

### Additional Info

Hi there, the "npx sentry-expo-upload-sourcemaps dist" returns E404.
Indeed the sentry-expo-upload-sourcemaps package is not listed anymore on npmjs.com
How should I proceed to upload source maps after running EAS Update?

**Comment by Lms24** [comment]
Hey @obasille sorry for the late reply. Something seems to have gone wrong with our internal routing of this isssue. Since this is about Expo I guess this is ReactNative/Mobile related. Gonna ask @krystofwoldrich to take a look, thanks!

**Comment by obasille** [comment]
Hi! I was using Expo 49 at the time, so may be that's issue. I'm about to update to Expo 50.

**Comment by kahest** [comment]
@obasille Hey, yes the guide you used expects a recent SDK version (5.19.0+) and Expo 50. Please report back when you had a chance to try with Expo 50.

Also, there is another issue reporting the same error with Expo 50, which includes a [workaround](https://github.com/getsentry/sentry-react-native/issues/3627#issuecomment-1978360943).
