### ISSUE TITLE
Docs Reference using Deprecated API

### ISSUE THREAD

**Issue by Silvenga** [getsentry/sentry-docs#8908]
### Core or SDK?

Platform/SDK

### Which part? Which one?

@sentry/integrations

### Description

The docs located [here](https://docs.sentry.io/platforms/javascript/guides/react/configuration/integrations/httpclient/) reference using a deprecated API `new HttpClient()`.

![image](https://github.com/getsentry/sentry-docs/assets/2753330/e66be33d-4d64-440b-bd2d-be5293c174f5)

### Suggested Solution

Use the new (?) API.

```
httpClientIntegration()
```

**Comment by mydea** [comment]
Hey, I'm going to close this in favor of https://github.com/getsentry/sentry-docs/issues/8982, where we are tracking this. We're working to update the docs as soon as possible!
