### ISSUE TITLE
With Sentry Python SDK version==1.9.10, I can't use "enable_tracing=True" when sentry_sdk.init()

### ISSUE THREAD

**Issue by EatARainbow** [getsentry/sentry-docs#8928]
### Core or SDK?

Platform/SDK

### Which part? Which one?

sentry-sdk for python

### Description

In https://docs.sentry.io/platforms/python/performance, it said, "Activate performance monitoring by setting enable_tracing to True. Performance Monitoring is available for the Sentry Python SDK version ≥ 0.11.2.".
But I can't set "enable_tracing=True" in version 1.9.10.

### Suggested Solution

Change to the correct version

**Comment by aamsur-933** [comment]
it seems duplicate with https://github.com/getsentry/sentry-docs/issues/8771

**Comment by sentrivana** [comment]
Closing this in favor of https://github.com/getsentry/sentry-docs/issues/8771 -- PR coming soon
