### ISSUE TITLE
Outdated documentation for Python's Flask web framework

### ISSUE THREAD

**Issue by jake-low** [getsentry/sentry-docs#895]
The page at https://sentry.io/for/flask/ shows a brief example of how to use the new unified SDK in Python to integrate with the Flask web framework. Below this example is a prominent link which reads [Flask integration](https://docs.sentry.io/clients/python/integrations/flask/) but this link points to documentation for the deprecated raven SDK. At a glance, it's not clear how to use the new unified SDK to accomplish the tasks documented on this page (e.g. "Getting The Last Event ID", "Dealing With Proxies", etc.). Updated documentation would be greatly appreciated.

**Comment by jake-low** [comment]
I've just discovered this page: https://docs.sentry.io/platforms/python/flask/ which addresses some of my questions. Perhaps the homepage link should point here?

**Comment by untitaker** [comment]
thanks for the report, I will fix this tomorrow

**Comment by untitaker** [comment]
The link in particular is fixed now, feel free to ask questions on https://github.com/getsentry/sentry-python's bugtracker if anything is unclear.
