### ISSUE TITLE
Setting per-request context in node/express

### ISSUE THREAD

**Issue by lorensr** [getsentry/sentry-docs#898]
What I'm finding is:

https://docs.sentry.io/enriching-error-data/context/?platform=node#capturing-the-user

But it looks global, so I imagine that this is only for the browser? I don't see a `Node.js` dropdown example—just "JavaScript".

I also can't find the API docs for `@sentry/node` (a listing of `foo`s for `Sentry.foo`). I'm looking here:

https://docs.sentry.io/platforms/node/

**Comment by ilaif** [comment]
Also looking on how to do this in an arbitrary node.js server framework.
