### ISSUE TITLE
On "page not found" you can't select a platform

### ISSUE THREAD

**Issue by vivianyentran** [getsentry/sentry-docs#9000]
If you end up on a page that doesn't exist, you can't select a platform from the dropdown.

for example, on https://docs.sentry.io/product/alerts-notifications/
you get:

<img width="1143" alt="image" src="https://github.com/getsentry/sentry-docs/assets/20403606/7eba55bd-0b18-435c-a697-083e909efdc6">

**Comment by Shubhdeep12** [comment]
Is this still valid? @stephanie-anderson @mjq-sentry 
 I think we removed everything except the logo of sentry on not found page.
