### ISSUE TITLE
Performance tour link redirecting to missing docs page

### ISSUE THREAD

**Issue by rachrwang** [getsentry/sentry-docs#9003]
### Core or SDK?

Core Sentry product

### Which part? Which one?

Performance

### Description

As a user taking a tour on an empty performance page, the last page links to a "page not found" on docs.

In-product entry point:
![image](https://github.com/getsentry/sentry-docs/assets/82916311/ac749bb5-4dac-4102-b794-aaa70bdfe087)

Destination:
![image](https://github.com/getsentry/sentry-docs/assets/82916311/0db10899-dcf0-40fd-93e2-05410fd1f648)

### Suggested Solution

We should either 1) fix the redirect so that this original URL redirects to the correct page, or 2) update this product feature to a new link

**Comment by mjq-sentry** [comment]
Thanks for reporting this - it was fixed in #9027 🙏
