### ISSUE TITLE
Speed up Next.js build

### ISSUE THREAD

**Issue by mjq-sentry** [getsentry/sentry-docs#9020]
The full site Next.js build currently takes ~38 minutes in Vercel, which is annoyingly slow. I previously got it down to ~18 minutes in Vercel but it regressed to over 35 minutes in c8d5391dad419b21fb85d5b1c2deca45ca483257. Look into want happened and see how much time we can get back.

**Comment by stephanie-anderson** [comment]
Optimisations are done for now, closing issue
