### ISSUE TITLE
Browser Javascript Framework docs list `before-send` instead of `beforeSend`

### ISSUE THREAD

**Issue by Fwang36** [getsentry/sentry-docs#9051]
### Core or SDK?

Platform/SDK

### Which part? Which one?

Browser Javascript Frameworks

### Description

The browser javascript framework's Filtering page (such as Angular or React), `beforeSend` is listed incorrectly as `before-send`.  The main browser javascript docs page does not have this issue.

[Docs Link](https://docs.sentry.io/platforms/javascript/guides/nextjs/configuration/filtering/#using-)

<img width="429" alt="Screenshot 2024-02-05 at 9 38 27 AM" src="https://github.com/getsentry/sentry-docs/assets/96670625/5eb19717-fc4d-4643-95e2-7369ea1a5288">

### Suggested Solution

`before-send` should be changed to `beforeSend` like how it is on the main [browser javascript page](https://docs.sentry.io/platforms/javascript/configuration/filtering/#filtering-error-events)

**Comment by aparajita** [comment]
It isn't just `before-send`, it's *every* option under any of the [browser Javascript pages](https://docs.sentry.io/platforms/javascript/configuration/options/).

**Comment by mjq-sentry** [comment]
Double-check guide inheritance - works on platform but not its guides
