### ISSUE TITLE
Missing a code snippet/pic of the Distributed Tracing - Basic Example

### ISSUE THREAD

**Issue by KateKatze** [getsentry/sentry-docs#9064]
### Core or SDK?

Platform/SDK

### Which part? Which one?

Home-Platforms-Java-Usage-Distributed Tracing

### Description

On this page code snippet/pic in the Basic Example went missing:

![Screenshot from 2024-02-06 12-45-05](https://github.com/getsentry/sentry-docs/assets/97441714/b9b4edb7-d084-451a-862e-76ab53a791e9)

### Suggested Solution

Just add a code snippet/pic and fix the link for it please :)

**Comment by mjq-sentry** [comment]
This was fixed in #9066 ([link to doc](https://docs.sentry.io/platforms/java/usage/distributed-tracing/)). Thanks for reporting the issue! 🙏
