### ISSUE TITLE
Right sidebar anchors broken

### ISSUE THREAD

**Issue by cleptric** [getsentry/sentry-docs#9115]
https://docs.sentry.io/platforms/php/configuration/options/#max_breadcrumbs

Clicking the links in the sidebar no longer scrolls to the content. Same issue on page load.

**Comment by kahest** [comment]
this is true for multi-word config options - the anchors are created with dashes to separate words (e.g. `max_breadcrumbs` or `maxBreadcrumbs` becomes `max-breadcrumbs`)

**Comment by Shubhdeep12** [comment]
looks like this is the same issue - https://github.com/getsentry/sentry-docs/issues/9068

hi @mjq-sentry I guess this is causing the issue - https://github.com/getsentry/sentry-docs/blob/6c0b7651e4ecd441d99f5487a1b64b5a9250d796/src/components/tableOfContents.tsx#L81

we should not depend on content of the headings. 
instead the `name` attribute which is passed in `ConfigKey` 
and looks like `ConfigKey` component is setting  `name` in both href and in id
So I think we can simply make the useEffect like this 

```javascript

useEffect(() => {
    if (typeof document !== 'undefined') {
      const main = document.getElementById('main');
      const elements = main?.querySelectorAll('h2, h3');
      const tocItems: TocItem[] = [];
      elements?.forEach(e => {
        const title = e.textContent?.trim();
        const id = e.id;
        if (title && id) {
          tocItems.push({
            depth: e.tagName === 'H2' ? 2 : 3,
            url: `#${id}`,
            value: title,
          });
        }
      });
      setHeadings(tocItems);
    }
  }, []);

```

let me know if you want me to create a PR

thanks

**Comment by mjq-sentry** [comment]
Hi @Shubhdeep12, thanks for your time looking into this! Your fix looks great to me - if you don't mind, please submit it as a PR and I'd be happy to approve + merge. Thanks again!

**Comment by Shubhdeep12** [comment]
Raised the PR @mjq-sentry
