### ISSUE TITLE
Mention that Performance Issues don't use quota

### ISSUE THREAD

**Issue by sdzhong** [getsentry/sentry-docs#9136]
### Core or SDK?

Core Sentry product

### Which part? Which one?

https://docs.sentry.io/product/accounts/quotas/

### Description

There's no mention about how Performance Issues interact with quota consumption.

### Suggested Solution

Sentry users should know that Performance Issues don't use their quota--they are complimentary Issues that come from the Transactions sent to Sentry & processed by Sentry servers.

This information should be in https://docs.sentry.io/product/accounts/quotas/ or https://docs.sentry.io/product/issues/issue-details/performance-issues/

**Comment by lizokm** [comment]
Not sure I'm following, do you mean something like this: https://docs.sentry.io/product/accounts/quotas/manage-transaction-quota/ and this: https://docs.sentry.io/product/accounts/pricing/?

**Comment by sdzhong** [comment]
@lizokm Something like that. Maybe it can be similar to the callout in https://docs.sentry.io/product/issues/:
![image](https://github.com/getsentry/sentry-docs/assets/89550162/311205b0-143c-4c4b-a26b-701d96860592)

But for the https://docs.sentry.io/product/issues/issue-details/performance-issues/ page, say _Performance Issue events_ are derived from Performance Transaction events and they themselves do not consume quota (but the Performance Transaction events do)? I'm not sure how to present this clearly in all areas where quota is described, but it should be made clear since there is confusion from Sentry users.
