### ISSUE TITLE
Improve 'Allowing the Compiler to Link Libraries' page for C++ native projects and CMake

### ISSUE THREAD

**Issue by glennra** [getsentry/sentry-docs#9176]
### Core or SDK?

Platform/SDK

### Which part? Which one?

sentry-native

### Description

https://docs.sentry.io/platforms/android/configuration/using-ndk/#allowing-the-compiler-to-link-libraries

`Then update the CmakeLists.txt configuration to link the Sentry NDK libraries:`

```# include paths generated by androidNativeBundle
include (${ANDROID_GRADLE_NATIVE_BUNDLE_PLUGIN_MK})
# change native-lib to your native lib's name
target_link_libraries(native-lib ${ANDROID_GRADLE_NATIVE_MODULES})
```

This is very confusing. As far as I can tell the variables mentioned are not CMake variables but are referenced from ```Android.mk```. If they are actually CMake variables then what CMake package needs to be ```include()```'d to access them?

### Suggested Solution

n/a

**Comment by mjq-sentry** [comment]
@stephanie-anderson Removed this from the Docs Platform project (and tags, etc) since, as far as I can tell, this is an issue with the content of a particular page.

**Comment by kahest** [comment]
@mjq-sentry You're right, this issue is about the content of this page, we'll take a look

**Comment by glennra** [comment]
I have figured out the build issue I had. The instructions here are gradle-centric and it would have been very helpful to have had some guidance on what is required for the integration at a lower level. For a C++ native app built using CMake + NDK and packaged for Android using gradle this would be which libraries need to be linked and which .aar packages and .jars need to be included in the package and where these are located in the sentry-java build tree.
