### ISSUE TITLE
"On this page" links don't work for multiword config items

### ISSUE THREAD

**Issue by vaind** [getsentry/sentry-docs#9197]
### Steps to Reproduce

sidebar links to: https://docs.sentry.io/platforms/javascript/configuration/options/#samplerate

vs the actual anchor: https://docs.sentry.io/platforms/javascript/configuration/options/#sample-rate

### Expected Result

.

### Actual Result

.

**Comment by Shubhdeep12** [comment]
Similar issue is tracked here. https://github.com/getsentry/sentry-docs/issues/9115

**Comment by a-hariti** [comment]
Looks like this is fixed in #9277
