### ISSUE TITLE
Security Policy Reporting - Content-Security-Policy has incorrect report-to info

### ISSUE THREAD

**Issue by dan-goswag** [getsentry/sentry-docs#9199]
### Core or SDK?

Platform/SDK

### Which part? Which one?

Web - Security Headers

### Description

Following the instructions at https://docs.sentry.io/product/security-policy-reporting/#content-security-policy I configured the report-to field in my CSP to send to Sentry.

However this did not work - as per https://github.com/getsentry/sentry/issues/52794 report-to does not support the use of querystring parameters which are used in the examples. Report-uri continues to work as expected.

### Suggested Solution

The documentation should not show using the report-to field in a way which does not currently work, so this documentation should be removed or updated.

**Comment by rodolfoBee** [comment]
@vivianyentran this is a question for the engineering team responsible for the feature.

**Comment by vivianyentran** [comment]
@olksdr @jan-auer Can either of you help us with this?

**Comment by olksdr** [comment]
Hi @vivianyentran,  
it's on my todo list, will update the issue once I know more.

**Comment by olksdr** [comment]
proposed some doc changes in https://github.com/getsentry/sentry-docs/pull/9440

@dan-goswag  could you, please, check if the config from the above PR works for you?

**Comment by olksdr** [comment]
The docs will be updated in the linked PR and the followup work will be done in https://github.com/getsentry/sentry/issues/38940 and https://github.com/getsentry/relay/issues/2645

**Comment by dan-goswag** [comment]
> proposed some doc changes in #9440
> 
> @dan-goswag could you, please, check if the config from the above PR works for you?

@olksdr Gave it a try, seems to work for me. Many thanks for the fix.
