### ISSUE TITLE
[Remix docs] captureRemixServerException snippet is not valid typescript

### ISSUE THREAD

**Issue by souredoutlook** [getsentry/sentry-docs#9210]
Please find where the error was introduced into the docs code here. 

This should be an if else statement not a function followed by an else block.

https://github.com/getsentry/sentry-docs/pull/8681/commits/9572a2cb3e2a721b6ba833b9fd9600a21c76b9b3#diff-2841ea14d67b70df5fa331ae9178a58cbb0cce5f4ba715cb1a4a9474bde74a25L177

**Comment by Lms24** [comment]
Opened #9242 to fix. 

As a side note to the community or to anyone following this issue: This is literally a one-line change - there's no need to wait for an SDK engineer to fix this. Let's please all approach docs as a joint effort. If you see something like this that needs fixing - go for it and open a PR :) (bumps your GH stats and alleviates some triaging overhead on our end). In cases like this, you can even just directly edit this file on GH - no need to even clone the repo ;) 

![image](https://github.com/getsentry/sentry-docs/assets/8420481/2ef9f9e9-e102-4f69-80a0-aae699e6f297)
