### ISSUE TITLE
Anchors for headings

### ISSUE THREAD

**Issue by stephanie-anderson** [getsentry/sentry-docs#9218]
Currently, the icon for the anchor link is always visible, but was previously only visible on hover, and the link only wraps the icon, not the whole headline anymore.

now:
![Image](https://github.com/getsentry/sentry-docs/assets/7096858/fe054d85-4dbe-4a69-acd2-735992d9c4ef)

before (default state):
![Image](https://github.com/getsentry/sentry-docs/assets/7096858/14361764-36ba-4a72-abd1-be45747d668a)

before (on hover):
![Image](https://github.com/getsentry/sentry-docs/assets/7096858/3de58966-01b9-4f84-9a65-f1f5762328e2)

**Comment by a-hariti** [comment]
In the old docs, the links wrap the icons only.

Should the headers keep the body color when wrapped in links?
