### ISSUE TITLE
Header isn't fully responsive at smaller browser widths

### ISSUE THREAD

**Issue by stephanie-anderson** [getsentry/sentry-docs#9220]
Everything fits at wide widths:
![Image](https://github.com/getsentry/sentry-docs/assets/82916311/ae77a94b-6ed1-4303-b61d-dd0c897b2e76)

For a narrower width, the links render a bit strangely:

![Image](https://github.com/getsentry/sentry-docs/assets/82916311/a7c56dba-0f53-4638-a289-a03ac89d7002)

![Image](https://github.com/getsentry/sentry-docs/assets/82916311/d8bb1ecd-afce-41c7-bf17-b72ab8d7eb2e)

**Comment by Shubhdeep12** [comment]
Yes, need some limits defined here for the content on different breakpoints.

Let me know if i can take this up?
And also, if there is any design inputs here.

**Comment by a-hariti** [comment]
Steal the double nav UX from wikipedia, example: https://en.wikipedia.org/wiki/Oxygen
