### ISSUE TITLE
Sidebar scrolls up on item selection

### ISSUE THREAD

**Issue by stephanie-anderson** [getsentry/sentry-docs#9222]
If the sidebar is very long (like here: https://sentry-docs-next.sentry.dev/platforms/python/integrations/tornado/) and you scroll down the sidebar and select an item, the sidebar scrolls back up. It should not change the scroll position when selecting elements.

**Comment by Shubhdeep12** [comment]
yes @stephanie-anderson , how about this approach:

there will be any 1 active element in the sidebar,
if we get one, we'll run .scrollIntoView() browser API which scrolls the sidebar to the active element.


let me know if this sounds good, I'll push a PR.

Thanks
