### ISSUE TITLE
The Next.js site can save the users's desired SDK in state as they navigate back and forth between SDK-specific docs and generic product docs

### ISSUE THREAD

**Issue by stephanie-anderson** [getsentry/sentry-docs#9223]

**Comment by Shubhdeep12** [comment]
hi @stephanie-anderson 

how about this approach

When the user clicks any platform from the navbar -> we will check for any last visited URL -> if yes, then redirect to it otherwise redirect to the main path

we can store the last visited URL in react context or we can also store it in session storage.

**Comment by Shubhdeep12** [comment]
Let me know if this sounds good.
I'll be happy to put a PR for this.

**Comment by stephanie-anderson** [comment]
Hey @Shubhdeep12, thanks for the suggestion - I think storing it in session storage would be great. But before we tackle this issue, we will need to talk about the bigger UX changes when switching between product and platform docs. But I'll respond here once we have more details on it 🙏

If you're looking for ways to contribute to the docs platform, feel free to have a look at this board:
https://github.com/orgs/getsentry/projects/207

What would be most impactful is working on fixing some bugs:
https://github.com/orgs/getsentry/projects/207/views/8

And especially bugs that sneaked in through the Gatsby to Next.js migration:
https://github.com/orgs/getsentry/projects/207/views/2

Let me know if you need any more details

**Comment by Shubhdeep12** [comment]
Great!
Thanks for the info. 
I'll check these issues there. 👍🏻

**Comment by a-hariti** [comment]
How would this look in light of the Platforms + Product sidebar merge @stephanie-anderson ?
