### ISSUE TITLE
Hidden pages return HTTP 404, but instead, they should simply be hidden from the navigation

### ISSUE THREAD

**Issue by stephanie-anderson** [getsentry/sentry-docs#9224]
An example of this would be the legacy SDKs, which are often linked from the landingpage of a specific SDK, e.g. the JS SDK:
https://docs.sentry.io/platforms/javascript/legacy-sdk/

**Comment by Shubhdeep12** [comment]
Hi @stephanie-anderson what is the issue here

With having 404 pages for legacysdk pages ?

OR

Having the links in cotent to the page?

**Comment by stephanie-anderson** [comment]
Hey @Shubhdeep12, thank you for asking! The issue is that "hidden" pages should simply be missing from the navigation, and must not be index by search engines. But other than that, they should display their contents, like all the other non-hidden pages. We also link to that legacy SDK documentation page from the JS SDK landingpage: https://docs.sentry.io/platforms/javascript/ so users with older versions can still use it's documentation.

![Image](https://github.com/getsentry/sentry-docs/assets/7096858/c565e4db-2bf7-48a7-b4da-7faf40b6c157)

**Comment by Shubhdeep12** [comment]
Oh, now i get it. 
It's hidden from indexing and navigation, but it should be visible when the user clicks on these anchors.

I can see in parsing mdx file that we are parsing legacy-sdk folder in src/mdx.ts which is  i think causing this redirection to not-found page.

If no one is working on it. Should i resolve this?

**Comment by hubertdeng123** [comment]
What do you think @stephanie-anderson? Looks like @a-hariti has linked a pull request here related to this too.
