### ISSUE TITLE
Add code examples for adding custom data as structured context with ruby/rails

### ISSUE THREAD

**Issue by amo13** [getsentry/sentry-docs#9262]
### Core or SDK?

Platform/SDK

### Which part? Which one?

Ruby / Rails

### Description

I am looking [here](https://docs.sentry.io/platforms/ruby/guides/rails/enriching-events/context/) for code examples. The only example shown does not say where that exemplary code would go inside a rails project.

### Suggested Solution

I'd like to see how to add context to an exception raised with a `raise StandardError` statement.

**Comment by sl0thentr0py** [comment]
hey @amo13 i'll add some clarification to the docs but the quick answer for you is that a `before_action` should work.

**Comment by amo13** [comment]
Thank you very much. This unfortunately does not answer my question just yet:
In my rails project, I define exception classes and use `raise MyError, "Some text telling what happened"` in the code (not only controller, also model, modules, jobs, etc.). What I'd like to achieve is to submit additional context *from there*, where I `raise MyError`, maybe to catch arguments given to the method raising MyError, or to add the state of some linked object.

I was hoping for something like
```ruby
def method_anywhere_in_project
  ...
  raise MyError.new(context1: "something", context2: 42)
  ...
end
```

...and maybe magically when sentry catches that error, it would submit context1 and context2 as part of the Exception.

**Comment by sl0thentr0py** [comment]
you can't add those to the exception instance but you can do the following even in your model method and when sentry captures that exception it will pick up this data.

```ruby
Sentry.configure_scope do |scope|
  scope.set_context(
    'character',
    {
      name: 'Mighty Fighter',
      age: 19,
      attack_type: 'melee'
    }
  )
end
```
