### ISSUE TITLE
Usage of `captureMessage` unclear

### ISSUE THREAD

**Issue by johanbook** [getsentry/sentry-docs#9284]
### Steps to Reproduce

On page https://docs.sentry.io/platforms/javascript/usage/ the API of `captureMessage` is documented, but however, I cannot find the docs of what the method actually does and where these messages show up in Sentry.

### Expected Result

There to be docs on what method does.

### Actual Result

There is no docs on it (as far as I can find)

**Comment by lforst** [comment]
@lizokm This is fair feedback but it is the same for all SDKs. Can we track this more globally?

**Comment by lizokm** [comment]
@lforst  Yup! I'll add this to my backlog.
