### ISSUE TITLE
[Feature Request] Respect historic anchor links

### ISSUE THREAD

**Issue by leeandher** [getsentry/sentry-docs#9293]
### Steps to Reproduce

1. Rename heading (e.g. `# Something` -> `# Something Else`
2. All historic links no longer work (e.g. `docs.sentry.io/page#something` doesn't scroll to view)

### Expected Result

- When I rename a heading I'd like to be able to provide it's previous value so saved anchor links continue to work (since they can live anywhere from other site's documentation, blog posts, promotional material, etc.)

### Actual Result

- The links fail and leave users to find the appropriate section themselves

### Additional Info

We have configuration for [permanent page redirects](https://github.com/getsentry/sentry-docs/blob/master/next.config.js#L27) which does that for pages, but not anchor links.

**Comment by a-hariti** [comment]
The current fragments are generated from the `slug`s of the headers themselves

The way to go about this is to force authors who change headers to add a redirect entry for it

Is there a way to enforce the current page redirects? @lizokm @stephanie-anderson @mjq-sentry

**Comment by stephanie-anderson** [comment]
Hey @a-hariti, not that I'm aware of, no. I'd be interested in how much effort it would take to make this possible though. The value provided by such an improvement is nice, but not super impactful, I'd argue.

So for me it's really about how easy we can build something and if it really is worth the effort. Do you have ideas how to solve that?

**Comment by a-hariti** [comment]
Upon further digging, I think using redirects will not solve this as the `#part` of the URL is not sent to the server

Writing HTML headers directly with an `id` attribute freezes the id, but takes it out of the normal generation flow (icons ...)

So the short answer is there's no "obvious" way to do it, unless we can justify adding complexity specifically for this feature
@stephanie-anderson

**Comment by lizokm** [comment]
I'm not convinced that this is worth the effort. I don't think a lot of our users will be saving this kind of link.
