### ISSUE TITLE
DSN should be project specific

### ISSUE THREAD

**Issue by Shubhdeep12** [getsentry/sentry-docs#9302]
### Steps to Reproduce

Its a very minor thing, but thought of adding an issue on this :sweat
In docs, we show the DSN of a project created by the user otherwise a dummy dsn url

### Expected Result

If a user has created a next.js project(s), we should only show the nextjs project's DSN there.
for all other docs, we should show the example DSN.

### Actual Result

We show the DSN and also give users flexibility to change the DSN if they want.the 

### Additional Info

i think showing only the relevant dsn url and also informing the user about configured project will help the end user.

**Comment by chargome** [comment]
We have added a search bar for DSNs in https://github.com/getsentry/sentry-docs/pull/11393, which should facilitate finding the right project. Also sometimes there is a need to add DSNs from projects that are based on different frameworks, this would not be possible then.
