### ISSUE TITLE
deprecated documentation for nodejs, ProfilingIntegration is deprecated

### ISSUE THREAD

**Issue by lucas-zimerman** [getsentry/sentry-docs#9309]
### Core or SDK?

Core Sentry product

### Which part? Which one?

Configure Node.js SDK

### Description

snippet from the website contains a deprecated reference on `ProfilingIntegration`
```
// You can also use ESM `import * as Sentry from "@sentry/node"` instead of `require`
const Sentry = require("@sentry/node");
import { ProfilingIntegration } from "@sentry/profiling-node";

Sentry.init({
  dsn: ",,,",
  integrations: [
    new ProfilingIntegration(),
  ],
  // Performance Monitoring
  tracesSampleRate: 1.0, //  Capture 100% of the transactions
  // Set sampling rate for profiling - this is relative to tracesSampleRate
  profilesSampleRate: 1.0,
});
```

### Suggested Solution

replace `ProfilingIntegration` by the recommended `nodeProfilingIntegration` so users don't get deprecation warninngs/errors on their first interaction with a nodejs project.

**Comment by mydea** [comment]
I think this should be fixed already - if you find a place that still references the old style, feel free to reopen this! thank you!

**Comment by aaly00** [comment]
<img width="444" alt="image" src="https://github.com/getsentry/sentry-docs/assets/11652379/cf8ddba4-68ee-4297-87e6-b0379512836c">

I still find this mentioned in the NextJS documentation
