### ISSUE TITLE
RewriteFrames is not a constructor

### ISSUE THREAD

**Issue by megmut** [getsentry/sentry-docs#931]
As per the docs on integrating TypeScript sourcemaps into Sentry, I have added the following code.

--index.ts-- 
declare global {
    namespace NodeJS {
        interface Global {
            __rootdir__: string;
        }
    }
}

--sentryLogger.ts--

SentryLogger._sentryClient = new Sentry.NodeClient({
     dsn: Config.sentry.dsn,
     integrations: [new Sentry.Integrations.RewriteFrames({
         root: global.__rootdir__
     })]
});

However, it's giving me an error: "Sentry.Integrations.RewriteFrames is not a constructor". TypeScript is also confirming this error with the folliwing:

[ts] Property 'RewriteFrames' does not exist on type '{ Console: typeof Console; Http: typeof Http; OnUncaughtException: typeof OnUncaughtException; OnUnhandledRejection: typeof OnUnhandledRejection; LinkedErrors: typeof LinkedErrors; Modules: typeof Modules; FunctionToString: typeof FunctionToString; InboundFilters: typeof InboundFilters; }'. [2339]

I can't find any more up-to-date docs so not sure where to go from here.

**Comment by jvandenaardweg** [comment]
I've noticed the same when I upgraded from `^4.6.4` to the latest `5.1.0`. 

When scrolling through the Github docs of the package I noticed there's a change: https://github.com/getsentry/sentry-javascript/blob/38ea918309bd0621a052555d2aed14cd3fdef17e/MIGRATION.md#how-to-use-sentryintegrations

Doing this fixed it for me:

```
npm install @sentry/integrations --save
```

Then

```
import * as Integrations from '@sentry/integrations';

Sentry.init({
      integrations: [
        new Integrations.RewriteFrames({ })
      ]
    });
```

So yeah, the docs should be updated :-)
