### ISSUE TITLE
Add platform to the HTML `<title>`.

### ISSUE THREAD

**Issue by antonpirker** [getsentry/sentry-docs#9311]
In search results it is not clear if the page that was found is about a specific platform or about Sentry in general. 

See this search result:
![Capto_Capture 2024-03-04_03-15-57_PM](https://github.com/getsentry/sentry-docs/assets/202325/e833c590-e06b-4c68-8bc7-15eb11fd9120)

The last entry is about Sentry for .NET.

The HTML `<title>` of all platform pages (everything that is under the URL https://docs.sentry.io/platforms/ should add a suffix to the title that is ` | Sentry for XXX` where XXX is the name of the platform. 

In the example from the screenshot, this page:
https://docs.sentry.io/platforms/dotnet/metrics/

Should have a title `Set Up Metrics | Sentry for .NET` instead of just `Set Up Metrics`.

**Comment by a-hariti** [comment]
Where should the source of truth for this live @antonpirker ?

I think it makes sense to keep it as the responsibility of SDK authors, otherwise we need to add some kind of flag to the files where the title should be changed dynamically to reflect this change
