### ISSUE TITLE
Doc tree generation bug (shows in PageGrid component)

### ISSUE THREAD

**Issue by stephanie-anderson** [getsentry/sentry-docs#9324]
There’s an empty listed item in <https://docs.sentry.io/platforms/javascript/data-management/>. (I don’t know what should be there or if it should be removed)

[Slack Message](https://sentry.slack.com/archives/C8H0BQRDJ/p1709575127794999)

**Comment by a-hariti** [comment]
This is a weird bug!

**Comment by a-hariti** [comment]
Pinging @mjq-sentry. Any idea why a node might have a `path` and no front matter?
