### ISSUE TITLE
Listed Items with Embedded URL Have Wrong Font Color

### ISSUE THREAD

**Issue by sdzhong** [getsentry/sentry-docs#9330]
### Core or SDK?

Core Sentry product

### Which part? Which one?

Docs pages with Listed Items

### Description

Docs pages with Listed Items are dark purple font instead of pink to indicate there's an embedded URL.

E.g.:
https://docs.sentry.io/platforms/javascript/enriching-events/, https://docs.sentry.io/product/data-management-settings/scrubbing/
![image](https://github.com/getsentry/sentry-docs/assets/89550162/c50de02c-bd7b-4024-bb8f-9ea880691808)

### Suggested Solution

Use pink font like before, e.g. Scrubbing Sensitive Data is correctly the pink font:
![image](https://github.com/getsentry/sentry-docs/assets/89550162/a493d9cf-57aa-4eac-95d8-04deb00661c5)

Note, this is the corresponding current page where Scrubbing Sensitive Data is incorrectly the dark purple font:
![image](https://github.com/getsentry/sentry-docs/assets/89550162/f4a9d746-3f82-437f-9c35-f0f4d35ec586)

**Comment by Shubhdeep12** [comment]
yes, this happens across all pages I guess, 
I was about to raise this issue. 

is this intended?
