### ISSUE TITLE
Crashpad_handler doesn't generate minidump if app is not started by admin

### ISSUE THREAD

**Issue by stephanie-anderson** [getsentry/sentry-docs#9331]
### Discussed in https://github.com/getsentry/sentry-docs/discussions/7715

<div type='discussions-op-text'>

<sup>Originally posted by **martirosyanH** August 31, 2023</sup>
Hi,
 I have integrated sentry-native to my application. everything seems to work when I start my exe with admin.
 But when I do regular start of my application it generates all the folder strcture, creates reports folder, but mini dump file is not generated.
 
 I tried to set sentry_options_set_database_pathw to some other directory, where admin acess is not needed, but same issue persist.
 
 Any help would be appreciated.

Thank you.</div>

**Comment by supervacuus** [comment]
Thanks, @stephanie-anderson, for adding this to the issues (I would not have seen the discussion). The user posed the same question in the sentry-native discussions, and I did not yet get a response from him. 

I think we can close this on sentry-docs (both the issue and the discussion). This is a question/issue that should be solved in the Native SDK repo, IMO.

cc: @kahest

**Comment by kahest** [comment]
Closing this in favor of https://github.com/getsentry/sentry-native/discussions/878
