### ISSUE TITLE
Apply Highlighting to Replay Code Snippets in Docs

### ISSUE THREAD

**Issue by jas-kas** [getsentry/sentry-docs#9340]
Update any docs to use this new feature: <https://vanguard.getsentry.net/p/cltd2gded0000s60q671bjal5>
- Highlighting of lines
- New way to show diffs

## Tasklist of Where We Can Update Docs for Highlighting

- [x] Highlight Replay sample rates and new Replay integration block on [this code snippet](https://docs.sentry.io/platforms/javascript/session-replay/#set-up)
- [x] Highlight `Sentry.replayCanvasIntegration()` on [this code snippet](https://docs.sentry.io/platforms/javascript/session-replay/#canvas-recording)
- [x] Highlight ` networkRequestHeaders: ["Cache-Control"],
  networkResponseHeaders: ["Referrer-Policy"],` on this [code snippet](https://docs.sentry.io/platforms/javascript/session-replay/configuration/#network-details)
  
 Note that these changes should be reflected for all applicable platforms.

[Slack Message for Context](https://sentry.slack.com/archives/C04RDSY3ML1/p1709587154375279?thread_ts=1709587154.375279&cid=C04RDSY3ML1)

**Comment by a-hariti** [comment]
Could you please clarify what you mean exactly by "new Replay integration block" @jas-kas ?

**Comment by jas-kas** [comment]
![Screenshot 2024-03-14 at 3 51 09 PM](https://github.com/getsentry/sentry-docs/assets/77064737/84b24108-e0b1-4c80-a329-e7be1d4735f2)

This part! @a-hariti

**Comment by a-hariti** [comment]
Should the highlighting happen every time there's a call to `replayIntegration` or following set up context (when the docs are talking specifically about it) @jas-kas ?

**Comment by jas-kas** [comment]
@a-hariti not everywhere, just in the specific code snippet i'm referring to!

**Comment by a-hariti** [comment]
oh, I misunderstood that last statement then!

**Comment by jas-kas** [comment]
@a-hariti By that I mean it shouldn't be in just the Vanilla JS page, but also the React, Vue, NextJS, etc... 😅

**Comment by a-hariti** [comment]
I'm confused 😬 

That's what I did for the `replayCanvasIntegration()`, but I'm not sure about the integration block.

Could you please specify what files will be affected by the replay integration block?

(I added you to a draft PR to keep an eye on changes) #9454

**Comment by a-hariti** [comment]
I think I understood the requirement. PR is up @jas-kas!

**Comment by jas-kas** [comment]
Thank you!!! @a-hariti 🙏
