### ISSUE TITLE
Issue with Sentry.Integrations.Console

### ISSUE THREAD

**Issue by nishant-lbb** [getsentry/sentry-docs#935]
The documentation leaves out the options available for Sentry.Integrations.Console integration. Are there no options available for the same?

**Comment by kumar303** [comment]
Maybe this is fixed?

I see the `levels` option: https://docs.sentry.io/platforms/javascript/?platform=browsernpm#captureconsole

**Comment by nishant-lbb** [comment]
The link you mentioned is for Sentry.Integrations.CaptureConsole. Do the same options apply for Sentry.Integrations.Console ?

**Comment by kumar303** [comment]
oh, I thought they were the same thing. Maybe not.
