### ISSUE TITLE
JS - Is Sentry.withScope synchronous?

### ISSUE THREAD

**Issue by graue** [getsentry/sentry-docs#939]
Hi, this documentation does not state whether `Sentry.withScope` calls its callback synchronously or asynchronously:

https://docs.sentry.io/enriching-error-data/scopes/?platform=javascript

It appears to be synchronous, but can you state explicitly if this is guaranteed? Thanks!

**Comment by untitaker** [comment]
It's synchronous. If this comes up more often we should update the docs or even standardize the behavior across SDKs.

**Comment by graue** [comment]
Thank you. Yes, please add this to the JS docs. Since JS has idioms where callbacks are called both synchronously (`array.forEach()`) and asynchronously (`setTimeout`), I didn't feel safe assuming.

**Comment by andycmaj** [comment]
hey! is there a recommended way to actually push and pop scopes around async actions?
