### ISSUE TITLE
Menu items are incorrect in Sentry for Elixir/Usage

### ISSUE THREAD

**Issue by simonmcconnell** [getsentry/sentry-docs#9406]
### Steps to Reproduce

The menu items on the left under **Usage** are wrong and don't match what is on the right hand side.

### Expected Result

correct menu items

### Actual Result

![image](https://github.com/getsentry/sentry-docs/assets/22566656/59a64dc5-fa12-4d30-87e6-77408d81c189)

**Comment by a-hariti** [comment]
The links on the right are the page TOC, the links on the left are subpages of usage.

it works as expected
