### ISSUE TITLE
Add beforeScreenshotCallback documentation to flutter SDK docs

### ISSUE THREAD

**Issue by rodolfoBee** [getsentry/sentry-docs#9408]
### Core or SDK?

Platform/SDK

### Which part? Which one?

Flutter SDK

### Description

beforeScreenshotCapture was added in v7.15.0 but there is no code example for it: https://github.com/getsentry/sentry-dart/pull/1805

### Suggested Solution

Add code example and explanation in the documentation: https://docs.sentry.io/platforms/flutter/enriching-events/screenshots/

**Comment by kahest** [comment]
@buenaflor we missed that - can @denrase take care of this?
