### ISSUE TITLE
[Changelog] Add hash/anchor to url when clicking Categories/Dates/Search on the Changelog

### ISSUE THREAD

**Issue by HazAT** [getsentry/sentry-docs#9410]
^ title

It's nice for sharing urls.

**Comment by a-hariti** [comment]
a hash makes sense for dates, but probably not for categories (more than one) or search,
maybe saving state to query params would be better? (but uglier) @HazAT

**Comment by Shubhdeep12** [comment]
yes, ideally we should add params for both dates and categories(comma separated ids of categories) in the URL.

**Comment by HazAT** [comment]
this is done
