### ISSUE TITLE
[Changelog] Same Header Nav (+Content) as sentry.io

### ISSUE THREAD

**Issue by HazAT** [getsentry/sentry-docs#9413]
^ title

We want to look and feel to be consistent across all sub pages of sentry.io

**Comment by Shubhdeep12** [comment]
Hi @HazAT @vivianyentran do we need this?
what I understood from this GH issue, we have to make the navbar and content look and feel consistent as sentry.io and blog.sentry.io and other sentry pages.
correct?

**Comment by HazAT** [comment]
@Shubhdeep12 yes, same header as here
https://sentry.io/for/mobile/ for example

**Comment by Shubhdeep12** [comment]
Ok great. Lets do this.

**Comment by Shubhdeep12** [comment]
Ok great. Lets do this.

**Comment by Shubhdeep12** [comment]
Hey @HazAT sorry I was super busy last week. starting this now.

Let me make the navbar same as what we have on other screens. like sentry blog and Sentry for mobile which you shared above.

**Comment by HazAT** [comment]
this is done
