### ISSUE TITLE
Track React Components 

### ISSUE THREAD

**Issue by smeubank** [getsentry/sentry-docs#9419]
### Core or SDK?

Platform/SDK

### Which part? Which one?

React

### Description

There is a special feature for react apps to [track react components](https://github.com/getsentry/sentry-docs/edit/master/docs/platforms/javascript/guides/react/features/component-tracking.mdx)

This page is rather large, and I belive difficult to discern the precise steps to get it setup, then it is not easy to cofirm, and we don't really indicate what they should expect to see in the product

### Suggested Solution

Consoliodate the page and cut it down in a way that the headers indicate that first part is required for the 2nd. 

Also, a nice to have to indicate what the expected outcome should be in product

1. install
2. setup
3. validate

**Comment by lizokm** [comment]
@smeubank would love to work with you on this improvement

**Comment by chargome** [comment]
@smeubank is this still relevant? Page has moved [here](https://docs.sentry.io/platforms/javascript/guides/react/features/component-monitoring/)

**Comment by chargome** [comment]
Actually closing this since https://github.com/getsentry/sentry-docs/issues/7240 is already well refined
