### ISSUE TITLE
API Documentation Error: /api/events/get-group-events/

### ISSUE THREAD

**Issue by LoveAndCoding** [getsentry/sentry-docs#942]
The output data for this endpoint does not seem to match what is documented here.

Most notably for our use case, there is no file or stacktrace information in it's current form.

Previously the data was in `entries[].data.frames[]` (where type is `stacktrace` or sometimes `exception`?). Last week, there was a shortcut using `metadata.filename`. But now, both seem to have disappeared and there seems to be no way to get that data, and the data itself does not seem to take the same shape as that in the doucmentation

Request URL: `[GET] https://sentry.io/api/0/issues/<ID>/events/?limit=50&query=&statsPeriod=1d`

Expected:
![Screen Shot 2019-04-29 at 12 19 29 PM](https://user-images.githubusercontent.com/205630/56920815-15276080-6a79-11e9-8454-f22d575a9513.png)

Actual:
![Screen Shot 2019-04-29 at 12 18 09 PM](https://user-images.githubusercontent.com/205630/56920752-e7dab280-6a78-11e9-884a-545f4fe1b4bf.png)

**Comment by quinnleong** [comment]
+1 on this – we're not getting any of the `context`, `_meta`, etc fields shown in the example response. They come through when fetching the single latest event for the issue (`/events/latest/`), but not on the list (`/events/`) endpoint.

**Comment by cedricpim** [comment]
The same is happening here. Is it possible to get any more information if this is being addressed?

**Comment by boblail** [comment]
+1 Same —  https://github.com/getsentry/sentry-docs/issues/1057

**Comment by quinnleong** [comment]
@markstory Any follow-up here?

**Comment by cedricpim** [comment]
boblail linked MR points to a solution but it takes way longer to get the details, since you need to do a request per event.

**Comment by saveman71** [comment]
Same here, it used to send all the data in a previous version. I'm also in the position where before I'd do 3 requests to paginate all the events of an issue, now I would need to do 300 requests to get the info of each event.
