### ISSUE TITLE
Platform change doesn't remember the URL path

### ISSUE THREAD

**Issue by iker-barriocanal** [getsentry/sentry-docs#9423]
### Steps to Reproduce

1. Go to the JS SDK [custom instrumentation page](https://docs.sentry.io/platforms/javascript/performance/instrumentation/custom-instrumentation/).
2. Change the platform to e.g. Python.

### Expected Result

Get redirected to the Python SDK [custom instrumentation page](https://docs.sentry.io/platforms/python/performance/instrumentation/custom-instrumentation/).

### Actual Result

Get redirected to the Python SDK [getting started page](https://docs.sentry.io/platforms/python/).

### Additional Info

Switching the platform back to JS keeps me on the getting started page.

**Comment by Shubhdeep12** [comment]
In that case, we should store the previous visit url in session storage ideally - plaform wise. 
If we found the url or page, otherwise the default page.
