### ISSUE TITLE
Next.js Basic Options - Missing Information Regarding "NEXT_PUBLIC_" prefix

### ISSUE THREAD

**Issue by jeffinnes** [getsentry/sentry-docs#9441]
### Core or SDK?

Platform/SDK

### Which part? Which one?

Next.js Configuration > Basic Options

### Description

On the [Next.js > Configuration > Basic Options](https://docs.sentry.io/platforms/javascript/guides/nextjs/configuration/options/) page, under "Common Options",  it says:

> Options that can be read from an environment variable (SENTRY_DSN, SENTRY_ENVIRONMENT, SENTRY_RELEASE) are read automatically.

However, because Next.js requires the `NEXT_PUBLIC_` prefix on any environmental variables, the client side initialization does not pick this value up so it defaults the client-side environment to "production" while errors on the server side are logged to the expected environment.

I haven't tested it, but I assume the same is true for all of the supported common options.

### Suggested Solution

I think the easiest would be to add to the "Common Options" paragraph calling out this potential gotcha. Otherwise, I suppose the SDK could look for the prefixed `NEXT_PUBLIC_SENTRY_ENVIRONMENT`.

**Comment by jeffinnes** [comment]
Thanks @AbhiPrasad!

I wasn't sure how you all would prefer to handle it, but I'd be happy to submit a PR for the docs change.

**Comment by lizokm** [comment]
@jeffinnes a PR submitted to the docs repo would be much appreciated, thank you!
