### ISSUE TITLE
Add notes about Replay inside of Feedback docs

### ISSUE THREAD

**Issue by billyvg** [getsentry/sentry-docs#9478]
There is currently NO mentions of Replay inside of our [Feedback docs](https://docs.sentry.io/platforms/javascript/user-feedback/) - let's add some.

We should disclose the behavior of capturing replays when your `onErrorSampleRate is > 0` only. We will have a future change where we also capture replays if `sessionSampleRate > 0` (and onError is 0).

**Comment by lizokm** [comment]
@billyvg would love to work with you on this!
