### ISSUE TITLE
Add Zendesk widget to footer

### ISSUE THREAD

**Issue by souredoutlook** [getsentry/sentry-docs#9483]
### Problem Statement

The only place where we currently direct folks to support is on our landing page for docs.

When we experimented with the User Feedback feature from Sentry we noticed many folks were interacting with the widget like it was a Support widget which leads us to believe it could be a really big enhancement to add more avenues for contacting support from docs.

### Solution Brainstorm

We'd like to propose adding a CTA to contact support in the footer of every docs page. Like so: 
<img width="1512" alt="image" src="https://github.com/getsentry/sentry-docs/assets/76002357/9cc2bf91-c12d-41e5-9687-2f4ab71ef6d1">

This link when clicked should open our web widget - similar to how it works with Sentry's app:

<img width="1037" alt="image" src="https://github.com/getsentry/sentry-docs/assets/76002357/8669e7a5-ee9e-4764-bd35-59d7e67ab607">

This will help us know what page the individual wrote in from - which should add some context to their support request.

This widget can be added to the docs site as a script. I can supply the script when it's ready to go ahead. One caveat is that in certain browser security configurations this script will be blocked from loading the required config to display the correct forms and fields (this is due to tracker blocking).

We have a remedy for this where we make a request for a resource we know is blocked by tracking - then if it it fails we  render a fallback, or if it succeeds render a button that will open the widget (by default the widget should be non-visible to Docs users - unless they click the button that will call `zE.show()`

Finally, we should consider add the feedback widget back to the docs site but disambiguate whether we want folks to report bugs through github or to give feedback on the page with the widget.

We do this on our help center now and in order to prevent the widgets from clashing (if both are simultaneously open) we have our widget open in the center of the page, like so: 

<img width="1342" alt="image" src="https://github.com/getsentry/sentry-docs/assets/76002357/9874c4c9-677a-419c-bdee-427a390972cc">

**Comment by a-hariti** [comment]
We might be able to work around the tracker blocking by proxying the script through our domain?

**Comment by souredoutlook** [comment]
The issue with proxying the script through our domain is that the script itself is making requests for additional resources at the blocked domain

**Comment by a-hariti** [comment]
We can install a service worker to intercept the requests and proxy them

Not sure if it would kick in before the ad blocker though

**Comment by souredoutlook** [comment]
@a-hariti Here's how it shows up in Firefox:

<img width="913" alt="image" src="https://github.com/getsentry/sentry-docs/assets/76002357/a2e3c47a-b0c1-43df-8cd0-d829015d1b0d">

AFAICT our application wouldn't have access to this request for a few reasons:
- it's being made from an iframe
- PerformanceObserver doesn't register this event either

I'm in talks with Zendesk about either getting themselves removed from the tracker list (unlikely) or modifying their widget to use the hostmapped URL - which would not be blocked (the same resource is available at support.sentry.io for example)

We've been experimenting with the following:
- make a request for the resource and observe if it fails
- if it fails render a link or alter the behaviour of the click event to open a new tab with the request submission form

Seems to be an alright UX.

Happy to chat through this live some time! would be nice to meet :)

**Comment by a-hariti** [comment]
I think opening a new tab could work as an alternative if it's not subject to blocking itself

The first two options both take control away from us and would probably delay the implementation indefinitely

**Comment by souredoutlook** [comment]
@lizokm as a stop gap I think adding the content to the footer and opening help.sentry.io in a new tab would be a great first step.

If we get the go ahead from Security to use the widget - it can be run cookie-less here by using the config setting outlined here: https://developer.zendesk.com/api-reference/widget/settings/#cookies

**Comment by lizokm** [comment]
@a-hariti - This has been approved by our legal team so we can go ahead and add it after we're done implementing the new UI. Their only stipulation was to add a script that ensures that no cookies are being dropped. Here's what they said:

If we have the following script loaded before the widget script it will prevent trackers from being dropped:

<script type="text/javascript">
    window.zESettings = {
        cookies: false
    };
</script>

**Comment by stephanie-anderson** [comment]
Would be great if we could create GH issues automatically for all incoming user feedback, and set the feedback in Sentry to done

**Comment by jas-kas** [comment]
@souredoutlook @stephanie-anderson @lizokm 

Given that **we already have experimented with adding the User Feedback widget** to the docs site and saw that most of the 'feedbacks' coming in **were support inquiries**, I would recommend against adding the Feedback widget back. 

> Finally, we should consider add the feedback widget back to the docs site but disambiguate whether we want folks to report bugs through github or to give feedback on the page with the widget.

> We do this on our help center now and in order to prevent the widgets from clashing (if both are simultaneously open) we have our widget open in the center of the page, like so:

This suggestion creates unnecessary confusion for the user where we are passing off the decision to them as to whether their message is 'feedback' or a 'support inquiry', which may not be obvious. I also don't expect users to think too hard about where is the "right" place to send a message and will likely just submit a message on the first widget they come across.

If anything, we should simply embed the Zendesk widget so all inquiries can be routed to the appropriate place & we reduce the friction of manually routing these feedbacks to Support, or ask users to report bugs in our docs repo.

**Comment by a-hariti** [comment]
this is blocked for now due to cookies
