### ISSUE TITLE
Add an opengraph image to docs repo

### ISSUE THREAD

**Issue by lizokm** [getsentry/sentry-docs#9485]
### Problem Statement

Right now if you post the docs URL on social media no image is generated.

<img width="730" alt="Screenshot 2024-03-18 at 3 21 02 PM" src="https://github.com/getsentry/sentry-docs/assets/26800704/941116c2-81b7-43df-84bf-827e165cce78">

### Solution Brainstorm

Add the below open graph image in docs so that when we post a docs URL on social media it looks more eye-catching.

<img width="673" alt="Screenshot 2024-03-18 at 3 25 22 PM" src="https://github.com/getsentry/sentry-docs/assets/26800704/466d104f-9af9-4bcd-abd0-3624db478eec">

(This is what it looks like for the Sentry url, which does have an open graph image)

<img width="490" alt="Screenshot 2024-03-18 at 3 23 55 PM" src="https://github.com/getsentry/sentry-docs/assets/26800704/892ef2d0-a65e-41b7-bea2-6331b5d80ecb">

Here's an article about [open graph](https://www.semrush.com/blog/open-graph/).

**Comment by a-hariti** [comment]
what should go in the title and description @lizokm ?
