### ISSUE TITLE
Wrong tab selector label per command on install page for react sdk

### ISSUE THREAD

**Issue by arnoproblems** [getsentry/sentry-docs#9486]
### Core or SDK?

Platform/SDK

### Which part? Which one?

react sdk

### Description

The tab label doesn't match with the command.

here: https://docs.sentry.io/platforms/javascript/guides/react/

<img width="799" alt="image" src="https://github.com/getsentry/sentry-docs/assets/54511008/7bbbfec0-b7f4-4f84-b3d6-ddf02c5acd2f">

### Suggested Solution

switch labels or switch commands

**Comment by Shubhdeep12** [comment]
It is happening across the app. Looks like some issue is there while rendering tabs using remark or something

**Comment by Shubhdeep12** [comment]
Looks like this has impacted the app, and this is the impact of https://github.com/getsentry/sentry-docs/pull/9367
I've raised a PR for the fix and removed the sorting of tab names while creating key names for localstorage

**Comment by Shubhdeep12** [comment]
Sorry i missed checking the opened PRs
the PR for the fix is already opened here - https://github.com/getsentry/sentry-docs/pull/9481

closing this one.
