### ISSUE TITLE
Add supported units to metrics documentation. 

### ISSUE THREAD

**Issue by rodolfoBee** [getsentry/sentry-docs#9509]
### Core or SDK?

Platform/SDK

### Which part? Which one?

All SDKs that support metrics

### Description

Currently only JS based SDKs have a section called [Supported Performance Metric Units](https://docs.sentry.io/platforms/javascript/metrics/#supported-performance-metric-units) with the units supported by Sentry backend. 

### Suggested Solution

Expand it to the other supported SDKs: .NET, Android, Java, PHP, Python, Unity and Ruby.

**Comment by stephanie-anderson** [comment]
Java/Android: https://github.com/getsentry/sentry-java/blob/main/sentry/src/main/java/io/sentry/MeasurementUnit.java

**Comment by stephanie-anderson** [comment]
.NET: 

- https://github.com/getsentry/sentry-dotnet/blob/main/src/Sentry/MeasurementUnit.Duration.cs
- https://github.com/getsentry/sentry-dotnet/blob/main/src/Sentry/MeasurementUnit.Fraction.cs
- https://github.com/getsentry/sentry-dotnet/blob/main/src/Sentry/MeasurementUnit.Information.cs

**Comment by stephanie-anderson** [comment]
Apple / Cocoa: no metrics support yet

**Comment by stephanie-anderson** [comment]
JS: 
- https://github.com/getsentry/sentry-javascript/blob/develop/packages/types/src/measurement.ts

**Comment by stephanie-anderson** [comment]
Dart / Flutter: no metrics support yet

**Comment by stephanie-anderson** [comment]
PHP: 
- https://github.com/getsentry/sentry-php/blob/master/src/Metrics/MetricsUnit.php

**Comment by stephanie-anderson** [comment]
Python:
- https://github.com/getsentry/sentry-python/blob/05d1e5ca94cc4fffcd01c46ceda6713459308404/sentry_sdk/_types.py#L122

**Comment by chargome** [comment]
@rodolfoBee can this be closed?

**Comment by rodolfoBee** [comment]
metrics is deprecated, yes it can be closed.
