### ISSUE TITLE
[Session Replay] Document request size limits for req bodies

### ISSUE THREAD

**Issue by jas-kas** [getsentry/sentry-docs#9516]
Request size calc found here: https://github.com/getsentry/sentry-javascript/blob/4ba3e405b01c1f37a64bb3c78b96be0a6cfa2571/packages/replay/src/coreHandlers/util/networkUtils.ts#L219

**Comment by mydea** [comment]
actually this is already done! "Captured bodies will be truncated to 150k characters max."
