### ISSUE TITLE
Replay pricing table can be amended for clarity

### ISSUE THREAD

**Issue by jas-kas** [getsentry/sentry-docs#9517]
https://docs.sentry.io/product/accounts/pricing/#replays-pricing

Instead of just `n/a`, clarify that minimum purchase of replays is 10k.

![Image](https://github.com/getsentry/sentry-docs/assets/77064737/fec8c844-4a38-4b41-b570-15f8aa49b252)

**Comment by lizokm** [comment]
n/a - minimum purchase of prepaid replays 10k

**Comment by lizokm** [comment]
done: https://github.com/getsentry/sentry-docs/pull/9591
