### ISSUE TITLE
Unclear what access token permissions are required for uploading source maps

### ISSUE THREAD

**Issue by tjhorner** [getsentry/sentry-docs#9524]
### Core or SDK?

Core Sentry product

### Which part? Which one?

Source map uploading

### Description

On [this page](https://docs.sentry.io/platforms/javascript/sourcemaps/uploading/webpack/) it is unclear what permissions a token needs to be given for source maps uploads to work. Ideally I would want to give the token the least permissions possible.

### Suggested Solution

n/a

**Comment by tjhorner** [comment]
Ah I see there is the concept of an org-associated auth token. I now see it's linked with the text "manually create an Auth Token" but I had assumed it would just take me to the user auth token page that I was already at. Maybe being more clear about the difference between an org auth token vs a user auth token would be beneficial.

**Comment by mydea** [comment]
Hey, we'll clarify this more on that page that you should set up an org auth token!
