### ISSUE TITLE
User-Feedback Integration outdated

### ISSUE THREAD

**Issue by nachtfunke** [getsentry/sentry-docs#9583]
### Core or SDK?

Platform/SDK

### Which part? Which one?

User Feedback

### Description

I was looking through the docs for implementing the User Feedback Integration from sentry (https://docs.sentry.io/platforms/javascript/user-feedback/configuration/#bring-your-own-button). When attempting to implement, I was immediately prompted by the IDE that the code was outdated:

![image](https://github.com/getsentry/sentry-docs/assets/4201323/28bc4ec1-0e6a-4116-afda-004de366c504)

The IDE's hints:

![Screenshot 2024-03-29 at 13 20 19](https://github.com/getsentry/sentry-docs/assets/4201323/f4b210d5-f1d5-4361-8b46-d7fce673f747)
![Screenshot 2024-03-29 at 13 20 28](https://github.com/getsentry/sentry-docs/assets/4201323/69198b05-9c00-4d41-8ac1-e4c9f22a50b6)

### Suggested Solution

Update the docs so that they don't reference deprecated parts of the codebase.

**Comment by mydea** [comment]
Hey, we have since updated the docs here, so everything should be up-to-date!
