### ISSUE TITLE
Unable to set alert for new issues that's seen more than X times 

### ISSUE THREAD

**Issue by rrosenshain-sc** [getsentry/sentry-docs#9621]
### Core or SDK?

Core Sentry product

### Which part? Which one?

Alerts

### Description

Following the instructions in https://www.youtube.com/watch?v=GXmYTOOQ_5A it seems impossible to create an alert when a new issue was created and has more than 10 events:

<img width="939" alt="image" src="https://github.com/getsentry/sentry-docs/assets/140540945/64d3af16-1d8f-4cec-889e-8e84785c9278">

Is that a bug with Sentry? Docs are missing? The alert is wrong?

Thanks!

### Suggested Solution

Not sure

**Comment by ceorourke** [comment]
@rrosenshain-sc an issue can't be both new and have been seen more than 10 times. Being new means it hasn't been seen before, so logically this can never fire. I'll reach out to the team that made the video for clarification, thanks for pointing this out!
