### ISSUE TITLE
Update Changelog 

### ISSUE THREAD

**Issue by pevensentry** [getsentry/sentry-docs#9649]
### Problem Statement

To improve readability and direct visitors to the signup page, please make the changes below:

- The sub-header yellow text at the top is crowded. Please add a small line space between the header and sub-header copy.
- Update the sub-header copy to “Follow [@SentryChangelog](https://twitter.com/SentryChangelog) to stay up to date on everything from product updates to SDK changes.”
- Update the post template to include our standard CTA at the bottom (see attached). 
<img width="763" alt="image" src="https://github.com/getsentry/sentry-docs/assets/101372341/1c56c7ac-c8ea-426c-b008-6a53825a3bab">

### Solution Brainstorm

see above

**Comment by Shubhdeep12** [comment]
How about having a minimal cta like we have in sentry blog - 
![image](https://github.com/getsentry/sentry-docs/assets/43654389/9ee9408d-51da-4f6a-8729-3406d839a2b6)

**Comment by pevensentry** [comment]
@Shubhdeep12 that works great!

**Comment by Shubhdeep12** [comment]
Ok i'll update the PR then.

**Comment by Shubhdeep12** [comment]
updated the footer. 
![image](https://github.com/getsentry/sentry-docs/assets/43654389/8ae9e442-4f37-41dd-b9a6-86695c3e3e03)

**Comment by pevensentry** [comment]
@Shubhdeep12 please note I edited the sub-header copy to link to the Sentry Changelog twitter

**Comment by Shubhdeep12** [comment]
ok thanks for the update @pevensentry 
updated the copy in PR 
![Uploading image.png…]()

**Comment by pevensentry** [comment]
Thank you!

**Comment by stephanie-anderson** [comment]
Was fixed by https://github.com/getsentry/sentry-docs/pull/9702
