### ISSUE TITLE
Feedback: Additional Micro Frontend Context

### ISSUE THREAD

**Issue by kpujjigit** [getsentry/sentry-docs#9667]
### Core or SDK?

Platform/SDK

### Which part? Which one?

@sentry/browser

### Description

Looking for:

1. Prerequisite information when leveraging bundler plugins.

2. A Deeper dive into the "undefined behaviors" mentioned by our Docs when using more than one init()

### Suggested Solution

Identify exact prerequisites when using bundler plugins, and share more context on why only one init() should be initialized, with some examples of the "undefined behavior" our docs mention. 

I apologize I don't have the exact context/details to share and add.

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-2157) by [Unito](https://www.unito.io)

**Comment by lforst** [comment]
> Prerequisite information when leveraging bundler plugins.

What exactly is missing?

> A Deeper dive into the "undefined behaviors" mentioned by our Docs when using more than one init()

Right now we will probably not give examples of undefined behaviour. The mentality should be “If you call init multiple times the SDK will not work and may send garbage. Don’t do it.”

**Comment by realkosty** [comment]
Capturing internal conversation in the linked Jira ticket

**Comment by lforst** [comment]
Closing to clean up a bit. Lmk if there is still anything to do here.
