### ISSUE TITLE
sentry/capacitor replay set-up references unknown replayIntegration function

### ISSUE THREAD

**Issue by ChrisHSandN** [getsentry/sentry-docs#9678]
### Core or SDK?

Platform/SDK

### Which part? Which one?

sentry/capacitor replay

### Description

https://docs.sentry.io/platforms/javascript/guides/capacitor/session-replay/#set-up

```js
Sentry.init({
 ...
  integrations: [
    replayIntegration({
      // Additional SDK configuration goes in here, for example:
      maskAllText: true,
      blockAllMedia: true,
    }),
  ],
});
```

### Suggested Solution

Should be:

```js
Sentry.init({
 ...
  integrations: [
    new Replay({
      // Additional SDK configuration goes in here, for example:
      maskAllText: true,
      blockAllMedia: true,
    }),
  ],
});
```

There is no function called `replayIntegration()` so I am pretty sure it is meant to be `new Replay()`

**Comment by s1gr1d** [comment]
Which SDK and version are you using to import `Replay`? 

Since v8, the class-based integrations are deprecated: https://docs.sentry.io/platforms/javascript/migration/v7-to-v8/#removal-of-class-based-integrations
