### ISSUE TITLE
To add commonly asked questions under every platform guides.

### ISSUE THREAD

**Issue by Shubhdeep12** [getsentry/sentry-docs#9701]
### Problem Statement

There are some common questions that devs working in different SDKs answer on discord.

### Solution Brainstorm

It would be great to have "Commonly asked questions" under every Platform guide which will have questions and answers to that, all added by devs.

**Comment by AbhiPrasad** [comment]
@Shubhdeep12 every sdk docs have a troubleshooting section attached to them: https://docs.sentry.io/platforms/python/troubleshooting/

Is that sufficient for the things you are looking at?

**Comment by Shubhdeep12** [comment]
Yes @AbhiPrasad 
It would be helpful if we could compile commonly asked questions by developers, which are commonly answered by the Sentry team in Discord here in troubleshooting page

**Comment by Shubhdeep12** [comment]
i think there is an issue already created for this - https://github.com/getsentry/sentry-docs/issues/9664

my bad, closing this one.
