### ISSUE TITLE
"What are Artifact Bundles" is no longer accessible from Javascript's docs page

### ISSUE THREAD

**Issue by viddo** [getsentry/sentry-docs#9726]
### Core or SDK?

Platform/SDK

### Which part? Which one?

Javascript

### Description

When present at https://docs.sentry.io/platforms/javascript/guides/react/sourcemaps/troubleshooting_js/ and clicking _"What are Artifact Bundles"_ in the sidebar should show me the page for https://github.com/getsentry/sentry-docs/blob/master/platform-includes/sourcemaps/artifact-bundles/javascript.mdx

<img width="400" alt="Screenshot 2024-04-17 at 13 38 48" src="https://github.com/getsentry/sentry-docs/assets/978461/2f002d81-6550-49e9-8128-f9fe52257094">

Instead it redirects me back to https://docs.sentry.io/platforms/javascript/guides/react/sourcemaps/troubleshooting_js/ 

Changing to some other "platform", e.g. _Node.js_ the equivalent/same(?) content is accessible, e.g. https://docs.sentry.io/platforms/node/sourcemaps/troubleshooting_js/artifact-bundles/

### Suggested Solution

Fix broken link/redirect

**Comment by Shubhdeep12** [comment]
i think it is because of this redirection defined for artifact-bundles page for javascript guides -
 https://github.com/getsentry/sentry-docs/blob/807b2ee97e15b0261960da67763f4614e1aee4e5/vercel.json#L501C5-L504C7

**Comment by mydea** [comment]
Hey, sorry about the late response, but this was fixed in the meanwhile!
