### ISSUE TITLE
Import instructions for expressIntegration are missing from the Express getting started page

### ISSUE THREAD

**Issue by michael-ravelhq** [getsentry/sentry-docs#9767]
### Core or SDK?

Platform/SDK

### Which part? Which one?

Express - Getting started

### Description

The docs indicate I should init the SDK with 
```
  integrations: [expressIntegration({ app })],
```

But there is no function exported with the name `expressIntegration` in `@sentry/node` or in `@sentry/integrations`.
The docs also don't say where to import the function from.

### Suggested Solution

Update docs to how express integration should be done.

**Comment by januardsoterana** [comment]
Thank you, @michael-ravelhq 
Waiting for solution.

**Comment by RahulLanjewar93** [comment]
Hi, even i am confused about the same. 
Any updates ? 
Thanks in advance.

**Comment by alexgoto** [comment]
Hello. Have same issue. 8.0.0-beta1 and above contains export of expressIntegration from root of @sentry/node, but without app as an argument

**Comment by mydea** [comment]
In v8, you do not need to define this anymore. Docs have been updated in the meanwhile - sorry that this issue fell off our radar for so long!
