### ISSUE TITLE
Migrate from sentry-expo code sample errors

### ISSUE THREAD

**Issue by iotashan** [getsentry/sentry-docs#9782]
### Core or SDK?

Platform/SDK

### Which part? Which one?

@sentry/react-native

### Description

Migration Guide > Migrate from sentry-expo > [Changes to Default Tags](https://docs.sentry.io/platforms/react-native/migration/sentry-expo/#changes-to-default-tags)

There's two code errors... first line 8 `manifest` is undefined, I'm guessing it should be Updates.manifest. Second, line 20 should be `Sentry.setTag`

### Suggested Solution

There's two code errors... first line 8 `manifest` is undefined, I'm guessing it should be Updates.manifest. Second, line 20 should be `Sentry.setTag`

**Comment by kahest** [comment]
fixed in https://github.com/getsentry/sentry-docs/pull/10199
