### ISSUE TITLE
RewriteFrames documentation out of date

### ISSUE THREAD

**Issue by Kadajett** [getsentry/sentry-docs#9804]
### Core or SDK?

Platform/SDK

### Which part? Which one?

RewriteFrames Documentation

### Description

https://docs.sentry.io/platforms/javascript/configuration/integrations/rewriteframes/ references the new `rewriteFramesIntegration` but then shows usage examples for `RewriteFrames`. I am seeing a persistent error around this `rewriteFramesIntegration` is not a function, even without importing this into my project. It seems that Sentry@7.112.1 is calling this improperly, or some variation of our sentry versions post-upgrade are incorrect. 

### Suggested Solution

Updating the docs to show usage information for `rewriteFramesIntegration`. 

Documenting how `rewriteFramesIntegration` is used by Sentry.init() by default.

**Comment by mydea** [comment]
Hey, we have since improved our docs for this and aligned this with the up-to-date state. sorry about the confusion!
