### ISSUE TITLE
Correct Remix+Vite usage instructions

### ISSUE THREAD

**Issue by elledienne** [getsentry/sentry-docs#9815]
### Core or SDK?

Platform/SDK

### Which part? Which one?

Remix SDK

### Description

Currently, the docs are recommending users on the SDK < 7.106.0 to `await` the call to `viteDevServer.ssrLoadModule`. That unfortunately is not really viable as it breaks HDR

![GL8Nm3MW4AAVdAN](https://github.com/getsentry/sentry-docs/assets/3903093/34946c5c-cc88-4494-8650-d07936634824)

### Suggested Solution

While it's true that the documentation recommends upgrading to the latest version, I believe it should also mention that awaiting the build loader will break HDR as that might cause quite some confusion

**Comment by mydea** [comment]
Hey,

we have since updated our Remix docs for the new SDK versions accordingly. Hopefully, it is less confusing now! I'm going to close this, if you believe there is still something to be done please feel free to reopen this issue.
