### ISSUE TITLE
Missing explanation in docs: "The trace for this event cannot be found. Read the docs to understand why."

### ISSUE THREAD

**Issue by Arkkimaagi** [getsentry/sentry-docs#9844]
### Core or SDK?

Core Sentry product

### Which part? Which one?

Stack trace?

### Description

I was trying to check out a stack trace of an JS error I see multiple events for. The trace can not be seen for some reason and it guides me to read the documentation why. The documentation page it links to however does not mention this issue at all.
![image](https://github.com/getsentry/sentry-docs/assets/1191667/643815e7-40c3-477a-a0f0-4139caf47b5e)

The link points to https://docs.sentry.io/product/sentry-basics/tracing/trace-view/#troubleshooting but on that page there's no #troubleshooting anchor.

### Suggested Solution

Update link or documentation to match. (And maybe help me understand what reasons could be there why I'm not seeing a trace)

**Comment by AbhiPrasad** [comment]
This should be fixed now.
