### ISSUE TITLE
`/product/*` 404s on `ui-redesign` compared to production

### ISSUE THREAD

**Issue by a-hariti** [getsentry/sentry-docs#9848]
### Steps to Reproduce

1. I scraped the prod `/sitemap.xml` into a text file replacing the host with `localhost:3000`
2. Did a local production build
3. loop over the sitemap keeping track of broken urls

### Expected Result

Links from prod should redirect properly to their new location

### Actual Result

404

### Additional Info

Actual list

[broken_urls.txt](https://github.com/getsentry/sentry-docs/files/15149026/broken_urls.txt)

**Comment by a-hariti** [comment]
update: not all of them are broken. Sigh!!

this is the list of actually broken links:

- [ ] https://sentry-docs-git-ui-redesign.sentry.dev/product/accounts/auth-tokens/
- [ ] https://sentry-docs-git-ui-redesign.sentry.dev/product/accounts/
- [ ] https://sentry-docs-git-ui-redesign.sentry.dev/product/accounts/user-settings/
- [ ] https://sentry-docs-git-ui-redesign.sentry.dev/product/crons/getting-started/cli/

I got fooled by the `vercel.json` redirects not working on localhost

**Comment by stephanie-anderson** [comment]
Then just the redirects aren't working... /product/accounts should no longer exist. Maybe a merge created some troubles?

**Comment by a-hariti** [comment]
Solved finally 🎉
@stephanie-anderson @lizokm
