### ISSUE TITLE
Search not indexed/working?

### ISSUE THREAD

**Issue by mydea** [getsentry/sentry-docs#9869]
### Core or SDK?

Platform/SDK

### Which part? Which one?

Try to search for `fastify`

### Description

Searching for `fastify`, a new guide I added last week, shows nothing about the new guide.

### Suggested Solution

Search should show fastify docs.

**Comment by stephanie-anderson** [comment]
@a-hariti please have a look if this stopped working by the time we migrated to Next.js. I think we somehow stopped updating the Algolia index

**Comment by lizokm** [comment]
This is where rules for Algolia global search live: https://github.com/getsentry/sentry-global-search?tab=readme-ov-file
