### ISSUE TITLE
Integrations missing and need @sentry/integrations

### ISSUE THREAD

**Issue by phiz118** [getsentry/sentry-docs#9883]
### Core or SDK?

Platform/SDK

### Which part? Which one?

@sentry/serverless

### Description

The captureConsoleIntegration is not automatically installed with autoDiscoverNodePerformanceMonitoringIntegrations and does not exist under @sentry/node. 

### Suggested Solution

Update the imports for all the integrations from @sentry/node to @sentry/integrations

**Comment by mydea** [comment]
Hey, we've updated the integrations quite a bit, and also the docs for it. You do not need `autoDiscoverNodePerformanceMonitoringIntegrations` anymore in v8 at all. You can import all integrations directly from your SDK package, `@sentry/integrations` no longer exists.
