### ISSUE TITLE
Click on right sidebar do not work

### ISSUE THREAD

**Issue by antonpirker** [getsentry/sentry-docs#9951]
### Steps to Reproduce

- Got to this page: https://docs.sentry.io/platforms/python/configuration/options/
- Click any link on the right sidebar.
- Nothing happens.

### Expected Result

The main are should scroll to the clicked headline in the right sidebar. 

### Actual Result

Nothing is happening.

### Additional Info

Screen recording of the problem:
https://github.com/getsentry/sentry-docs/assets/202325/556e2a14-5225-4ca1-b9c2-1f60f14f39ad

**Comment by a-hariti** [comment]
it works fine on my end, with different browsers 🤔 @antonpirker

**Comment by a-hariti** [comment]
Do you have a consistent way to repro this @antonpirker ?

**Comment by a-hariti** [comment]
Do you have a consistent way to repro this @antonpirker ?

**Comment by lizokm** [comment]
This has been fixed :)
