### ISSUE TITLE
Make updating the Sentry copyright year automatic

### ISSUE THREAD

**Issue by lizokm** [getsentry/sentry-docs#9957]
### Problem Statement

Our copyright year is wrong.

<img width="512" alt="Screenshot 2024-05-08 at 8 15 14 AM" src="https://github.com/getsentry/sentry-docs/assets/26800704/36a0202a-a231-402f-8fcc-9aa92f60a4c0">

### Solution Brainstorm

Would like it to be updated and to make it update automatically every year without us having to change it manually.

**Comment by a-hariti** [comment]
How fast do you want it @lizokm? 😂
