### ISSUE TITLE
"Follow along with the gif below to see how to hide and unhide environments". Git block not working

### ISSUE THREAD

**Issue by PWMKHANUKAYEV** [getsentry/sentry-docs#9960]
### Core or SDK?

Core Sentry product

### Which part? Which one?

Follow along with the gif below to see how to hide and unhide environments.

### Description

"Follow along with the gif below to see how to hide and unhide environments". Git block not working
Git imbedding not working.  
![sentryerr](https://github.com/getsentry/sentry-docs/assets/79668541/b8b9a1ec-83b0-409d-a525-aeed3e7202f7)

### Suggested Solution

Fix Git Window please
![sentryerr](https://github.com/getsentry/sentry-docs/assets/79668541/21f4b82b-cd5a-4bee-8fc8-4a49e660179a)

**Comment by a-hariti** [comment]
seems to be [working fine](https://docs.sentry.io/concepts/key-terms/environments/#hidden-environments)
