### ISSUE TITLE
Add redirects for all integrations coming from Sentry website

### ISSUE THREAD

**Issue by lizokm** [getsentry/sentry-docs#9969]
### URL

https://docs.sentry.io/organization/integrations/github/
https://docs.sentry.io/organization/integrations/gitlab/
https://docs.sentry.io/organization/integrations/pagerduty/
https://docs.sentry.io/organization/integrations/clickup/
https://docs.sentry.io/organization/integrations/rookout/
https://docs.sentry.io/organization/integrations/split/
https://docs.sentry.io/organization/integrations/teamwork/
https://docs.sentry.io/organization/integrations/jira/
https://docs.sentry.io/organization/integrations/linear/
https://docs.sentry.io/organization/integrations/bitbucket/
https://docs.sentry.io/organization/integrations/notification-incidents/amixr/
https://docs.sentry.io/organization/integrations/project-mgmt/shortcut/
https://docs.sentry.io/organization/integrations/slack/
https://docs.sentry.io/organization/integrations/vanta/
https://docs.sentry.io/organization/integrations/jam/

### Additional Info

This is where the errors are coming from.

https://sentry.io/integrations/

**Comment by a-hariti** [comment]
Looks like Amixr is [discontinued](https://amixr.io/), we don't have anything about it (or its successor) in the docs anyway.

It should probably be removed from the marketing website @lizokm
