### ISSUE TITLE
SessionStack integration has broken docs

### ISSUE THREAD

**Issue by mrlubos** [getsentry/sentry-docs#997]
See https://docs.sentry.io/workflow/integrations/sessionstack/

Source: https://sentry.io/integrations/sessionstack/

**Comment by untitaker** [comment]
Apparently intentionally removed by https://github.com/getsentry/sentry-docs/pull/709

I lack context here, @mikellykels?

**Comment by mikellykels** [comment]
@untitaker the actual decision to remove it from the docs was done in Slack, but this is the Jira ticket that started the whole discussion on supporting SessionStack https://getsentry.atlassian.net/browse/ISSUE-135. 

A little more context here https://getsentry.atlassian.net/browse/FEEDBACK-261, but basically the integration had been broken for 6+ months and SessionStack were the ones maintaining it.

**Comment by mrlubos** [comment]
@mikellykels I had a conversation with them earlier today, tested the integration, and it works. Their docs aren't up-to-date either, so a small modification was required, but other than that, nothing seems amiss.

**Comment by untitaker** [comment]
@mikellykels We fixed the integration a few months ago because we broke it. I think if we want to remove it from our docs we should also remove it from marketing pages. Who made the call on removing it?

**Comment by mikellykels** [comment]
Fixed the broken link on https://sentry.io/integrations/sessionstack/ to redirect to SessionStack's docs
