### ISSUE TITLE
"Coose Your SDK" card items have cursor style inconsistencies

### ISSUE THREAD

**Issue by Lms24** [getsentry/sentry-docs#9990]
### Steps to Reproduce

1. Go to landing page
2. Hover over "Choose your SDK" link cards

### Expected Result

The cursor becomes a pointer on the entire card

### Actual Result

The cursor style is inconsistent (see screenshot):
- Items with sub items/guides (e.g. JavaScript): Cursor only becomes pointer when hovering over text or arrow
- Items without sub items/guides (e.g. Kotlin): Cursor becomes pointer over the entire card

### Additional Info

![image](https://github.com/getsentry/sentry-docs/assets/8420481/28a0c84c-0a16-4bf3-be09-6c7a913d6c10)

**Comment by a-hariti** [comment]
This was intentional, the rationale behind it is that platforms with nothing to expand take you directly to the page,
others link there when clicking the text, and expand elsewhere

Do you think it would be better to have all links limited to visible text @Lms24 ?

**Comment by Lms24** [comment]
I see, I kinda suspected something like this. I dont wanna dwell on this too much but to me it seems weird that there's so much dead space where a click doesn't do anything. If we can somehow solve that I think it'd be great but it doesn't necessarily have to be identical to the simple links

**Comment by a-hariti** [comment]
The cursor style gives a hint (the hand) when you're about to click on a link, that was the compromise I came up.

The alternative was to not have links on expandable headers and nest the platform link along with its guides, which looks weird
```
Javascript
  Javascript
  [other guides]
```

**Comment by adinauer** [comment]
Hey, It took me a while to figure out this behaviour of opening the generic "Java" docs via the text.
Maybe we could simply add the generic link to the list instead and open the dropdown regardless of where you click?

**Comment by mydea** [comment]
related to this, imho the arrows here are "wrong" - I would expect, when collapsed, that the arrow is `v` (down), and when expanded, it is `^`? does that make sense?

**Comment by a-hariti** [comment]
currently it kinda mirrors the standard [`<details>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details) element @mydea

**Comment by a-hariti** [comment]
I meant in terms of caret direction @mydea

**Comment by a-hariti** [comment]
wyt @stephanie-anderson ?
